force-app/main/default/objects/Campaign/fields/msf_FinalCampaign__c.field-meta.xml
<CustomField>
    <fullName>msf_FinalCampaign__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Campaña final</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Associative.recordType-meta.xml
<RecordType>
    <fullName>Associative</fullName>
    <active>true</active>
    <label>Asociativo</label>
</RecordType>

force-app/main/default/objects/Contact/fields/msf_IsAssosiative__c.field-meta.xml
<CustomField>
    <fullName>msf_IsAssosiative__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es asociado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_MainEmail__c.field-meta.xml
<CustomField>
    <fullName>msf_MainEmail__c</fullName>
    <label>Email principal</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_NIF__c.field-meta.xml
<CustomField>
    <fullName>msf_NIF__c</fullName>
    <label>NIF/NIE/CIF</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/cpm__Payment_Method__c/fields/cpm__IsActive__c.field-meta.xml
<CustomField>
    <fullName>cpm__IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Method__c/fields/cpm__IsDefault__c.field-meta.xml
<CustomField>
    <fullName>cpm__IsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Method__c/fields/cpm__Method_Default__c.field-meta.xml
<CustomField>
    <fullName>cpm__Method_Default__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates the default method. extremely usefull when having multiple of the same payment method for different PSP&apos;s</description>
    <label>Method Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Method__c/fields/cpm__Requires_Payment_Profile__c.field-meta.xml
<CustomField>
    <fullName>cpm__Requires_Payment_Profile__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Become true if this payment method required a Payment Profile object.</description>
    <label>Requires Payment Profile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/cpm__Payment_Profile__c.object-meta.xml
<CustomObject>
    <description>captures the payment profiles per contact/account.
such as IBAN, legacy bank account, Credit Card etc.</description>
    <label>Payment Profile</label>
    <nameField>
        <displayFormat>PP-{0}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/msf_NIF__c.field-meta.xml
<CustomField>
    <fullName>msf_NIF__c</fullName>
    <label>NIF del titular</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__PaymentHub_Settings__c/fields/cpm__Auto_Create_Mandate_Recurring_Payment_DD__c.field-meta.xml
<CustomField>
    <fullName>cpm__Auto_Create_Mandate_Recurring_Payment_DD__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When true a mandate will be created when an Recurring or Single Payment is created of type Direct Debit which doesn&apos;t already has a relationship to a Mandate</description>
    <inlineHelpText>Wanneer aangevinkt zal er een mandaat aangemaakt worden wanneer een terugkerende betaling van het type automatische incasso gemaakt wordt en deze nog geen relatie met een mandaat heeft</inlineHelpText>
    <label>Autocreate mandate for Direct Debits</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cpm__PaymentHub_Settings__c/fields/cpm__Re_use_existing_mandate__c.field-meta.xml
<CustomField>
    <fullName>cpm__Re_use_existing_mandate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>re-use existing mandate if available</description>
    <label>Reuse existing mandate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cpm__PaymentHub_Settings__c/fields/cpm__Store_Informal_Logs__c.field-meta.xml
<CustomField>
    <fullName>cpm__Store_Informal_Logs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Store Informal Logs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_acceptDataProtectionPolicy__c.field-meta.xml
<CustomField>
    <fullName>msf_acceptDataProtectionPolicy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Política protección de datos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_AcceptStatutes__c.field-meta.xml
<CustomField>
    <fullName>msf_AcceptStatutes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Conozco y acepto mis obligaciones</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_AssociativePhone__c.field-meta.xml
<CustomField>
    <fullName>msf_AssociativePhone__c</fullName>
    <label>Teléfono de asociativo</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_EndorsedByOne__c.field-meta.xml
<CustomField>
    <fullName>msf_EndorsedByOne__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Avalado por (1)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.msf_IsAssosiative__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Avalado1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_EndorsedByTwo__c.field-meta.xml
<CustomField>
    <fullName>msf_EndorsedByTwo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Avalado por (2)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.msf_IsAssosiative__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidatos (Avalado por)</relationshipLabel>
    <relationshipName>Avalado2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_ExemptOfPayment__c.field-meta.xml
<CustomField>
    <fullName>msf_ExemptOfPayment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exento de pago</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANAccountNumber__c</fullName>
    <label>Número de cuenta</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANCode__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANCode__c</fullName>
    <label>Código IBAN</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANDC__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANDC__c</fullName>
    <label>Dígito de control</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANEntity__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANEntity__c</fullName>
    <label>Entidad</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANOffice__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANOffice__c</fullName>
    <label>Oficina</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IsAssosiative__c.field-meta.xml
<CustomField>
    <fullName>msf_IsAssosiative__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es de asociativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_MoreInfo__c.field-meta.xml
<CustomField>
    <fullName>msf_MoreInfo__c</fullName>
    <label>Más información</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_NIF__c.field-meta.xml
<CustomField>
    <fullName>msf_NIF__c</fullName>
    <description>VAT Number</description>
    <label>NIF/NIE/CIF</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_noCriminalRecord__c.field-meta.xml
<CustomField>
    <fullName>msf_noCriminalRecord__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No antecedentes penales</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Associative.recordType-meta.xml
<RecordType>
    <fullName>Associative</fullName>
    <active>true</active>
    <businessProcess>Associative Lead</businessProcess>
    <label>Associative</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <businessProcess>Individual Lead</businessProcess>
    <label>Individual</label>
</RecordType>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_LeadId__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidato</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MSF_ConvertAssociativeLead_TEST.cls
@isTest
public class MSF_ConvertAssociativeLead_TEST {
    
    @testSetup static void setup(){
        
        npsp__Trigger_Handler__c thCon = new npsp__Trigger_Handler__c(
            Name = 'TriggerTestOpportunitiesFieldsLogic',
            npsp__Class__c = 'MSF_OpportunitiesFieldsLogic_TDTM',
            npsp__Object__c = 'Opportunity',
            npsp__Trigger_Action__c = 'BeforeInsert;BeforeUpdate;AfterInsert;AfterUpdate;AfterDelete',
            npsp__Active__c = true,
            npsp__Load_Order__c = 3,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );        
        upsert thCon;         
        
        Campaign camp = new Campaign(Name='MSFConvertAssociativeLeadTESTcamp1',msf_FinalCampaign__c = false);
        insert camp;
        
        Contact c = new Contact(
            FirstName='FirstName1',
            LastName= 'LastName1',
            msf_MainEmail__c = 'm@m.com',
            msf_NIF__c='43578879C',
            msf_IsAssosiative__c = true
        );
        insert c;
        
        Contact c2 = new Contact(
            FirstName='FirstName2',
            LastName= 'LastName2',
            msf_MainEmail__c = 'm@mm.com',
            msf_NIF__c='82970393D',
            msf_IsAssosiative__c = true
        );
        insert c2;
        
        Lead lead = new Lead(RecordTypeId=Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('Individual').getRecordTypeId(), 
                             Company='Company1',
                             FirstName='FirstName1',
                             LastName='LastName1',
                             Suffix = 'Suffix1',
                             msf_NIF__c = '94939216T',
                             Email='a@a.com',   
                             msf_AssociativePhone__c = '911111111',
                             Phone = '911111111',
                             MobilePhone='611111111',
                             LeadSource='SMS',
                             msf_ExemptOfPayment__c=false,
                             msf_IBANCode__c = 'ES21',
                             msf_IBANEntity__c = '2059',
                             msf_IBANOffice__c = '7074',
                             msf_IBANDC__c = '08',
                             msf_IBANAccountNumber__c = '0558221500',
                             msf_noCriminalRecord__c = true,
                             msf_AcceptStatutes__c = true,
                             msf_acceptDataProtectionPolicy__c = true,   
                             msf_MoreInfo__c = 'test', 
                             msf_EndorsedByOne__c = c.Id,
                             msf_EndorsedByTwo__c = c2.Id);        
        insert lead;
        
        //Contentlink lead1
        ContentVersion content = new ContentVersion(); 
        content.Title = 'Header_Picture1'; 
        content.PathOnClient = '/' + content.Title + '.jpg'; 
        Blob bodyBlob = Blob.valueOf('Unit Test ContentVersion Body'); 
        content.VersionData = bodyBlob; 
        content.origin = 'H';
        insert content;
        
        ContentVersion cv = [SELECT ContentDocumentId FROM ContentVersion WHERE id =:content.Id];
        
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId = lead.id;
        contentlink.ContentDocumentId = cv.ContentDocumentId;
        contentlink.ShareType = 'V';
        insert contentlink; 
        //End contentlink Contentlink lead1
        
        Lead lead2 = new Lead(RecordTypeId=Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('Associative').getRecordTypeId(),
                              Company='Company2',
                              FirstName='FirstName2',
                              LastName='LastName2',
                              Suffix = 'Suffix2',
                              msf_NIF__c = '59115913W',
                              Email='a@a2.com',   
                              msf_AssociativePhone__c = '911111112',
                              Phone = '911111112',
                              MobilePhone='611111112',
                              LeadSource='SMS',
                              msf_ExemptOfPayment__c=false,
                              msf_IBANCode__c = 'ES27',
                              msf_IBANEntity__c = '0013',
                              msf_IBANOffice__c = '1494',
                              msf_IBANDC__c = '95',
                              msf_IBANAccountNumber__c = '8887610140',     
                              msf_noCriminalRecord__c = true,
                              msf_AcceptStatutes__c = true,
                              msf_acceptDataProtectionPolicy__c = true,                             
                              msf_EndorsedByOne__c = c.Id,
                              msf_EndorsedByTwo__c = c2.Id);  
        insert lead2;
        
        Lead lead3 = new Lead(RecordTypeId=Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('Individual').getRecordTypeId(),
                              Company='Company3',
                              FirstName='FirstName3',
                              LastName='LastName3',
                              Suffix = 'Suffix3',
                              msf_NIF__c = '53617806E',
                              Email='a@a3.com',   
                              msf_AssociativePhone__c = '911111113',
                              Phone = '911111113',
                              MobilePhone='611111113',
                              LeadSource='SMS',
                              msf_ExemptOfPayment__c=false,
                              msf_IBANCode__c = 'ES28',
                              msf_IBANEntity__c = '2022',
                              msf_IBANOffice__c = '1321',
                              msf_IBANDC__c = '87',
                              msf_IBANAccountNumber__c = '8568946703',     
                              msf_noCriminalRecord__c = true,
                              msf_AcceptStatutes__c = true,
                              msf_acceptDataProtectionPolicy__c = true,                             
                              msf_EndorsedByOne__c = c.Id,
                              msf_EndorsedByTwo__c = c2.Id);      
        insert lead3;
        
        Lead lead4 = new Lead(RecordTypeId=Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('Individual').getRecordTypeId(),
                              Company='Company4',
                              FirstName='FirstName4',
                              LastName='LastName4',
                              Suffix = 'Suffix4',
                              msf_NIF__c = '43578879C',
                              Email='a@a4.com',   
                              msf_AssociativePhone__c = '911111114',
                              Phone = '911111114',
                              MobilePhone='611111114',
                              LeadSource='SMS',
                              msf_ExemptOfPayment__c=false,
                              msf_IBANCode__c = 'ES91',
                              msf_IBANEntity__c = '1004',
                              msf_IBANOffice__c = '6063',
                              msf_IBANDC__c = '91',
                              msf_IBANAccountNumber__c = '9233907664',     
                              msf_noCriminalRecord__c = true,
                              msf_AcceptStatutes__c = true,
                              msf_acceptDataProtectionPolicy__c = true,                             
                              msf_EndorsedByOne__c = c.Id,
                              msf_EndorsedByTwo__c = c2.Id); 
        insert lead4;

        CampaignMember campMem = new CampaignMember(CampaignId=camp.Id, LeadId = lead2.Id);
        insert campMem;
        
        Opportunity opp = new Opportunity(msf_LeadId__c=lead2.Id, Name='MSFConvertAssociativeLeadTESTopp1', StageName='SMS Donor', Amount=5, CloseDate=date.today(), CampaignId = camp.Id);
        insert opp;
                       
        cpm__IbanValidation__c ibanValidation = new cpm__IbanValidation__c(
            Name = 'ES',
            cpm__RegEx__c = '^(?=[0-9A-Z]{24}$)ES\\d{22}$' ,
            SetupOwnerId = UserInfo.getOrganizationId()
        );
        insert ibanValidation;
        
        npsp4hub.NPSPSetup base = new npsp4hub.NPSPSetup();
        cpm.SetupService.install(base);
        cpm.TestService.activateSourceExtension(base);
        cpm.TestService.createIbanRegex();
        cpm.TestService.initTestPSPExtension();
        cpm.TestService.initTestSourceExtension();
        
        cpm__PaymentHub_Settings__c ps = new cpm__PaymentHub_Settings__c (
            cpm__Auto_Create_Mandate_Recurring_Payment_DD__c = false,	
            cpm__Re_use_existing_mandate__c	= false,
            cpm__Store_Informal_Logs__c	= true,
            Name = 'main',
            SetupOwnerId = UserInfo.getOrganizationId()
        );
        insert ps;
        
        cpm__Payment_Method__c pm = new cpm__Payment_Method__c(
            cpm__IsActive__c = true,
            cpm__IsDefault__c = false,
            cpm__Method_Default__c = true,
            cpm__Payment_Method__c = 'Direct Debit',
            cpm__Payment_Service_Provider__c = null,
            cpm__Provided_By__c = 'PaymentHub-SEPA',
            cpm__Requires_Payment_Profile__c = true,
            cpm__Support_Bulk__c = true,
            cpm__Support_Online__c = true,
            cpm__Support_Recurring__c = false,
            Name = 'PaymentHub-SEPA-Direct Debit',
            SetupOwnerId = UserInfo.getOrganizationId()
        );
        insert pm;      
        
        String sIBAN = lead3.msf_IBANCode__c + lead3.msf_IBANEntity__c + lead3.msf_IBANOffice__c + lead3.msf_IBANDC__c + lead3.msf_IBANAccountNumber__c;
        cpm__Payment_Profile__c payment = new cpm__Payment_Profile__c(cpm__Contact__c=c.Id, 
                                                                      cpm__IBAN__c=sIBAN, 
                                                                      msf_NIF__c=lead3.msf_NIF__c, 
                                                                      cpm__Active__c=true,
                                                                      RecordTypeId = Schema.SObjectType.cpm__Payment_Profile__c.getRecordTypeInfosByDeveloperName().get('IBAN').getRecordTypeId()
                                                                     );
        insert payment;
    }
    
    @isTest static void getLeadInformationTest(){
        Lead ld = [SELECT Id FROM lead WHERE LastName='LastName1' LIMIT 1];
        Map<String, Object> LeadList = (Map<String, Object> )MSF_ConvertAssociativeLead_CTRL.getLeadInformation(ld.Id);
        Lead returnedLead = (Lead)LeadList.get('lead');
        System.assertEquals(ld.Id,returnedLead.Id);
        System.assertEquals(((List<Object>)LeadList.get('contacts')).size(),0);
    }
    
    @isTest static void setNewAssociativePersonTestSuccess(){
        Lead ld = [SELECT Id,LastName FROM Lead WHERE LastName='LastName2' LIMIT 1];
        Map<String,Object> data = (Map<String,Object>)MSF_ConvertAssociativeLead_CTRL.setNewAssociativePerson(ld.Id);
        Id contactId = (ID)data.get('goToSobject');
        System.assertNotEquals(contactId,ld.Id);
    }
    
    @isTest static void setNewAssociativePersonTestError(){
        Lead ld = [SELECT Id,LastName FROM Lead WHERE LastName='LastName1' LIMIT 1];
        Map<String,Object> data = (Map<String,Object>)MSF_ConvertAssociativeLead_CTRL.setNewAssociativePerson(ld.Id);
        Id contactId = (ID)data.get('goToSobject');
        System.assertEquals(contactId,ld.Id);
    }
    
    @isTest static void setMemberAsAssociativePersonTestSuccess(){
        Lead ld = [SELECT Id,LastName FROM Lead WHERE LastName='LastName2' LIMIT 1];
        Contact cont = [SELECT Id FROM Contact WHERE LastName='LastName1' LIMIT 1];
        Map<String,Object> returnData = (Map<String,Object>)MSF_ConvertAssociativeLead_CTRL.setMemberAsAssociativePerson(ld.Id,cont.Id);
        System.assertNotEquals(ld.Id,returnData.get('goToSobject'));
    }
    
    @isTest static void setMemberAsAssociativePersonTestError(){
        Lead ld = [SELECT Id,LastName FROM Lead WHERE LastName='LastName1' LIMIT 1];
        Contact cont = [SELECT Id FROM Contact WHERE LastName='LastName1' LIMIT 1];
        Map<String,Object> returnData = (Map<String,Object>)MSF_ConvertAssociativeLead_CTRL.setMemberAsAssociativePerson(ld.Id,cont.Id);
        System.assertEquals(ld.Id,returnData.get('goToSobject'));
    }
    
    @isTest static void setMemberAsAssociativePersonTestErrorWithPaymentProfile(){
        Lead ld = [SELECT Id,LastName FROM Lead WHERE LastName='LastName3' LIMIT 1];
        Contact cont = [SELECT Id FROM Contact WHERE LastName='LastName1' LIMIT 1];
        Map<String,Object> returnData = (Map<String,Object>)MSF_ConvertAssociativeLead_CTRL.setMemberAsAssociativePerson(ld.Id,cont.Id);
        System.assertEquals(ld.Id,returnData.get('goToSobject'));
    }
}