force-app/main/default/objects/Campaign/fields/msf_CRMExternalId__c.field-meta.xml
<CustomField>
    <fullName>msf_CRMExternalId__c</fullName>
    <displayFormat>C{0}</displayFormat>
    <externalId>true</externalId>
    <label>Id campaña</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/msf_FinalCampaign__c.field-meta.xml
<CustomField>
    <fullName>msf_FinalCampaign__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Campaña final</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/msf_PromoterIndividual__c.field-meta.xml
<CustomField>
    <fullName>msf_PromoterIndividual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campañas de promotor</relationshipLabel>
    <relationshipName>Campanas_promotor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_ContactInformationSummary__c.field-meta.xml
<CustomField>
    <fullName>msf_ContactInformationSummary__c</fullName>
    <label>Resumen de los datos de contacto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_CRMExternalId__c.field-meta.xml
<CustomField>
    <fullName>msf_CRMExternalId__c</fullName>
    <description>WebSAS Member ID</description>
    <displayFormat>{0}</displayFormat>
    <externalId>true</externalId>
    <label>ID Miembro</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_IsAssosiative__c.field-meta.xml
<CustomField>
    <fullName>msf_IsAssosiative__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es asociado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_IsPublicPerson__c.field-meta.xml
<CustomField>
    <fullName>msf_IsPublicPerson__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Implica exclusión programa de prospectos.</inlineHelpText>
    <label>Es persona pública</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_MemberType__c.field-meta.xml
<CustomField>
    <fullName>msf_MemberType__c</fullName>
    <defaultValue>&apos;Nada&apos;</defaultValue>
    <label>Tipo de miembro</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_NIF__c.field-meta.xml
<CustomField>
    <fullName>msf_NIF__c</fullName>
    <label>NIF/NIE/CIF</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_Organization__c.field-meta.xml
<CustomField>
    <fullName>msf_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organización</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contactos de organización</relationshipLabel>
    <relationshipName>Organization</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_OrganizationType__c.field-meta.xml
<CustomField>
    <fullName>msf_OrganizationType__c</fullName>
    <label>Tipo de organización</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Company</fullName>
                <default>true</default>
                <label>Company</label>
            </value>
            <value>
                <fullName>Public Entity</fullName>
            </value>
            <value>
                <fullName>Collective</fullName>
            </value>
            <value>
                <fullName>Foundation</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
                <isActive>false</isActive>
                <label>Anonymous</label>
            </value>
            <value>
                <fullName>Channel Partner / Reseller</fullName>
                <isActive>false</isActive>
                <label>Channel Partner / Reseller</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <isActive>false</isActive>
                <label>Corporate</label>
            </value>
            <value>
                <fullName>Customer - Channel</fullName>
                <isActive>false</isActive>
                <label>Customer - Channel</label>
            </value>
            <value>
                <fullName>Customer - Direct</fullName>
                <isActive>false</isActive>
                <label>Customer - Direct</label>
            </value>
            <value>
                <fullName>Government</fullName>
                <isActive>false</isActive>
                <label>Government</label>
            </value>
            <value>
                <fullName>Household</fullName>
                <isActive>false</isActive>
                <label>Household</label>
            </value>
            <value>
                <fullName>Individual</fullName>
                <isActive>false</isActive>
                <label>Individual</label>
            </value>
            <value>
                <fullName>Installation Partner</fullName>
                <isActive>false</isActive>
                <label>Installation Partner</label>
            </value>
            <value>
                <fullName>Nonprofit</fullName>
                <isActive>false</isActive>
                <label>Nonprofit</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
                <isActive>false</isActive>
                <label>Technology Partner</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_PercomsSummary__c.field-meta.xml
<CustomField>
    <fullName>msf_PercomsSummary__c</fullName>
    <label>Resumen percoms</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_RelationshipLevel__c.field-meta.xml
<CustomField>
    <fullName>msf_RelationshipLevel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level de relación</label>
    <referenceTo>npsp__Level__c</referenceTo>
    <relationshipLabel>Contactos (Level de relación)</relationshipLabel>
    <relationshipName>Contactos2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/npe01__HomeEmail__c.field-meta.xml
<CustomField>
    <fullName>npe01__HomeEmail__c</fullName>
    <description>See Preferred Email field.</description>
    <inlineHelpText>Ver Correo electrónico elegido.</inlineHelpText>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/npsp__Primary_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Account marked as Primary in this Contact&apos;s list of Organization Affiliations.</description>
    <inlineHelpText>Cuenta de la afiliación seleccionada como Principal</inlineHelpText>
    <label>Primary Affiliation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Do Not Use.  Use Organization Affiliations.</relationshipLabel>
    <relationshipName>PrimaryAffiliatedContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <description>Indicates if this Contact is designated as the Primary Contact on their Account (read only).</description>
    <formula>Account.npe01__One2OneContact__c = Id</formula>
    <inlineHelpText>Este campo esta seleccionado si es el contacto principal en la cuenta. El contacto principal puede editarse en la cuenta.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Organization_Contact.recordType-meta.xml
<RecordType>
    <fullName>Organization_Contact</fullName>
    <active>true</active>
    <label>Organization Contact</label>
</RecordType>

force-app/main/default/objects/npe4__Relationship__c/npe4__Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/npe4__Relationship__c/fields/npe4__Contact__c.field-meta.xml
<CustomField>
    <fullName>npe4__Contact__c</fullName>
    <description>Related Contact is this Contact&apos;s ______.</description>
    <inlineHelpText>El contracto relacionad es el _______ de este contacto.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/npe4__Relationship__c/fields/npe4__Type__c.field-meta.xml
<CustomField>
    <fullName>npe4__Type__c</fullName>
    <description>Field that describes how the Related Contact is connected to the Contact.</description>
    <inlineHelpText>Campo que describe como el contacto relacionado esta conectado a este contacto.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aunt</fullName>
            </value>
            <value>
                <fullName>Brother</fullName>
            </value>
            <value>
                <fullName>Brother-in-law</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Cousin</fullName>
            </value>
            <value>
                <fullName>Coworker</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>Grandchild</fullName>
            </value>
            <value>
                <fullName>Granddaughter</fullName>
            </value>
            <value>
                <fullName>Grandfather</fullName>
            </value>
            <value>
                <fullName>Grandmother</fullName>
            </value>
            <value>
                <fullName>Gran Donante</fullName>
            </value>
            <value>
                <fullName>Grandparent</fullName>
            </value>
            <value>
                <fullName>Grandson</fullName>
            </value>
            <value>
                <fullName>Husband</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Other Relationships</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Siblings</fullName>
            </value>
            <value>
                <fullName>Siblings-in-law</fullName>
            </value>
            <value>
                <fullName>Sister</fullName>
            </value>
            <value>
                <fullName>Sister-in-law</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_CRMExternalId__c.field-meta.xml
<CustomField>
    <fullName>msf_CRMExternalId__c</fullName>
    <displayFormat>{0}</displayFormat>
    <externalId>true</externalId>
    <label>Id aportación</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_DonationVehicleContact__c.field-meta.xml
<CustomField>
    <fullName>msf_DonationVehicleContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Donante por vehículo de donación</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El valor no existe o no coinciden los criterios de filtro. Contacto VD</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Individual Contact, Organization, Anonymous</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades vehículo de donación</relationshipLabel>
    <relationshipName>DonationVehicleContact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Contact for this Opportunity. If this is an individual Donation, NPSP attributes the Donation to the Primary Contact. If this is an organizational Donation, NPSP attributes a soft credit to the Primary Contact.</description>
    <inlineHelpText>El contacto principal para esta oportunidad. La función del contacto principal se mantiene sincronizada con este campo. Para donantes individuales, esto significa atribuciones por esta oportunidad.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <businessProcess>Grant</businessProcess>
    <description>Grant Received</description>
    <label>Grant</label>
</RecordType>

force-app/main/default/classes/MSF_SummarySection_TEST.cls
/**
* @author       Deloitte
* @date         01-2019
* @group        Contact
* @description  test class for the MSF_SummarySection_CONTROLLER class.
*/
@isTest
private class MSF_SummarySection_TEST {
    static Integer s_num = 1;
    @testSetup static void setup(){
        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().Get('Organization').getRecordTypeId();
        Id RecordTypeIdOrg = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization').getRecordTypeId();
        Id RecordTypeIdContOrg = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization_Contact').getRecordTypeId();
        List<Opportunity> listOpportunityTest1 = new List<Opportunity>(); 
        
        Account a = new Account();
        a.name='Silver&Gold';
        a.RecordTypeId=RecordTypeIdAccount;
        //a.msf_CRMExternalId__c='0120O000000kNMEQA2';
        insert a;
        
        Contact co = new Contact();
        co.LastName= 'Medina';
        co.RecordTypeId = RecordTypeIdOrg;
        co.npe01__HomeEmail__c = 'm@m.com';
        co.msf_NIF__c='B52296126';
        co.msf_IsAssosiative__c =true;
        co.msf_IsPublicPerson__c = true;
        co.npsp__Primary_Affiliation__c= a.Id;
        co.msf_MemberType__c ='Nada';
        co.msf_ContactInformationSummary__c = 'Nada';
        co.msf_PercomsSummary__c = 'Varios';
        insert co;
        
        Contact co2 = new Contact();
        co2.LastName= 'Medina S.L.';
        co2.RecordTypeId = RecordTypeIdOrg;
        co2.npe01__HomeEmail__c = 'm@org.com';
        co2.msf_NIF__c='12345678D';
        co2.msf_IsAssosiative__c =true;
        co2.msf_IsPublicPerson__c = true;
        co2.npsp__Primary_Affiliation__c= a.Id;
        co2.msf_MemberType__c ='Nada';
        co2.msf_ContactInformationSummary__c = 'Nada';
        co2.msf_PercomsSummary__c = 'Varios';
        insert co2;
        
        Contact orgCont = new Contact();
        orgCont.FirstName= 'Manolo';
        orgCont.LastName= 'Medina';
        orgCont.RecordTypeId = RecordTypeIdContOrg;
        orgCont.npe01__HomeEmail__c = 'm@morg.com';
        orgCont.msf_NIF__c='12345678Z';
        orgCont.msf_IsAssosiative__c =true;
        orgCont.msf_IsPublicPerson__c = true;
        orgCont.npsp__Primary_Affiliation__c= a.Id;
        orgCont.msf_MemberType__c ='Nada';
        orgCont.msf_ContactInformationSummary__c = 'Nada';
        orgCont.msf_PercomsSummary__c = 'Varios';
        insert orgCont;
        
        Contact c2 = new Contact();
        c2.RecordTypeId = RecordTypeIdOrg;
        c2.LastName= 'Medina';
        c2.npe01__HomeEmail__c = null;
        c2.msf_NIF__c='12345678P';
        c2.msf_IsAssosiative__c =false;
        c2.msf_IsPublicPerson__c = false;
        c2.npsp__Primary_Affiliation__c= null;
        c2.msf_MemberType__c ='Nada';
        c2.msf_ContactInformationSummary__c = 'Nada';
        c2.msf_PercomsSummary__c = 'Varios';
        insert c2;
        
        Contact c3 = new Contact();
        c3.RecordTypeId = RecordTypeIdOrg;
        c3.LastName= 'Medina';
        c3.npe01__HomeEmail__c = null;
        c3.msf_NIF__c='12345678R';
        c3.msf_IsAssosiative__c =false;
        c3.msf_IsPublicPerson__c = false;
        c3.npsp__Primary_Affiliation__c= null;
        c3.msf_MemberType__c ='Nada';
        c3.msf_ContactInformationSummary__c = 'Nada';
        c3.msf_PercomsSummary__c = 'Varios';

        insert c3;
        
        Campaign camp = new Campaign();
        camp.msf_PromoterIndividual__c = co.Id;
        camp.Name = 'MSFSummarySectionTestName1';
        camp.msf_FinalCampaign__c = false;
        insert camp;
        
        Opportunity o = new Opportunity();
        o.name='Donacion puntual';
        o.type='Solidarity Wedding';
        o.npsp__Primary_Contact__c=co.Id;
        o.AccountId = a.Id;
        o.StageName = 'Propuesta';
        o.CloseDate = date.newInstance(2019, 10, 15);
        listOpportunityTest1.add(o);
        
        Opportunity o2 = new Opportunity();
        o2.name='Donacion puntual';
        o2.type='Herencia';
        o2.npsp__Primary_Contact__c=c2.Id;
        o2.AccountId = a.Id;
        o2.StageName = 'Propuesta';
        o2.CloseDate = date.newInstance(2019, 10, 15);
        listOpportunityTest1.add(o2);
        
        Opportunity o3 = new Opportunity();
        o3.name='Donacion puntual';
        o3.type='Grant';
        o3.npsp__Primary_Contact__c=c3.Id;
        o3.AccountId = a.Id;
        o3.StageName = 'Propuesta';
        o3.CloseDate = date.newInstance(2019, 10, 15);
        listOpportunityTest1.add(o3);
         
        
        Opportunity o4 = new Opportunity();
        o4.name='Donacion puntual';
        o4.type='Grant';
        o4.npsp__Primary_Contact__c=co2.Id;
        o4.AccountId = a.Id;
        o4.StageName = 'Propuesta';
        o4.CloseDate = date.newInstance(2019, 10, 15);
        o4.msf_DonationVehicleContact__c = c2.Id;
        listOpportunityTest1.add(o4);
        
        Opportunity o5 = new Opportunity();
        o5.name='Donacion puntual';
        o5.type='Grant';
        o5.npsp__Primary_Contact__c=c3.Id;
        o5.AccountId = a.Id;
        o5.StageName = 'Impagada';
        o5.CloseDate = date.today();
        listOpportunityTest1.add(o5);

        
        insert listOpportunityTest1;
        
        npe4__Relationship__c dup = new npe4__Relationship__c(npe4__Type__c = 'Duplicate', npe4__Contact__c = c2.Id, npe4__RelatedContact__c = co.Id);
        insert dup;
        
        
        Case caso = new Case(ContactId = c2.Id,
                             RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('MSF_Doubts').getRecordTypeId());
        insert caso;
    }
    
    @isTest static void msfContactError(){
        Contact co = new Contact(Id=getFAkeId(Contact.SObjectType));
        Map<String,Object> out = new Map<String,Object>();
        System.assertEquals(out,MSF_SummarySection_CONTROLLER.getContact(co.Id));        
    }
    @isTest static void existsOneOrMorePromotionsFromContact(){
        Contact c = [SELECT Id FROM Contact WHERE msf_NIF__c='B52296126' LIMIT 1];
        System.assert(MSF_SummarySection_CONTROLLER.getProm(c.Id,null));
    }
    
    @isTest static void notExistsOneOrMorePromotionsFromContact(){
        Contact c = [SELECT Id FROM Contact WHERE msf_NIF__c='12345678P' LIMIT 1];
        System.assert(!MSF_SummarySection_CONTROLLER.getProm(c.Id,null));
    }
    @isTest static void checkNotExistsOportunityDonationVehicle(){
        Contact c = [SELECT Id FROM Contact WHERE msf_NIF__c='12345678P' LIMIT 1];
        System.assert(!MSF_SummarySection_CONTROLLER.getVd(c.Id));
    }
    
    @isTest static void testGetContact(){
        Contact co = [SELECT RecordType.DeveloperName, toLabel(RecordType.Name),  toLabel(msf_OrganizationType__c), msf_Organization__r.Name, msf_Organization__r.msf_RelationshipLevel__r.Name, msf_OrgContactType__c, msf_RelationshipLevel__r.Name, msf_Level__r.Name, msf_PrimaryContact__c,
                      msf_Program__c, msf_MainEmail__c, msf_NIF__c, msf_IsPrimary__c,  msf_MemberType__c,
                      msf_ContactInformationSummary__c, msf_PercomsSummary__c, msf_Seniority__c, msf_IsAssosiative__c, msf_IsPublicPerson__c,
                      AccountId
                      FROM Contact
                      WHERE msf_NIF__c = 'B52296126'
                      LIMIT 1];
        Map<String,Object> out = (Map<String,Object>) MSF_SummarySection_CONTROLLER.getContact(co.Id);
        System.assertEquals(co, out.get('c'), 'Contact is not the same');
        System.assertEquals(co.msf_Organization__r.msf_RelationshipLevel__r.Name, out.get('lvl'),'Relationship Level is not the same');
        System.assertEquals([SELECT Name, msf_IsOrganizationGroup__c FROM Account WHERE id=:co.AccountId LIMIT 1], out.get('acc'), 'Organization Group is not the same');
    }
    
    @isTest static void testGetOrgContact(){
        Contact co = [SELECT RecordType.DeveloperName, toLabel(RecordType.Name),  toLabel(msf_OrganizationType__c), msf_Organization__r.Name, msf_Organization__r.msf_RelationshipLevel__r.Name, msf_OrgContactType__c, msf_RelationshipLevel__r.Name, msf_Level__r.Name, msf_PrimaryContact__c,
                      msf_Program__c, msf_MainEmail__c, msf_NIF__c, msf_IsPrimary__c,  msf_MemberType__c,
                      msf_ContactInformationSummary__c, msf_PercomsSummary__c, msf_Seniority__c, msf_IsAssosiative__c, msf_IsPublicPerson__c,
                      AccountId
                      FROM Contact
                      WHERE msf_NIF__c = '12345678Z'
                      LIMIT 1];
        Map<String,Object> out = (Map<String,Object>) MSF_SummarySection_CONTROLLER.getContact(co.Id);
        System.assertEquals(co, out.get('c'), 'Contact is not the same');
        System.assertEquals([SELECT Name, msf_IsOrganizationGroup__c FROM Account WHERE id=:co.AccountId LIMIT 1], out.get('acc'), 'Organization Group is not the same');
    }
    
    @isTest static void checkgetCasoHasOut(){
        Contact co = [SELECT Id FROM Contact WHERE msf_NIF__c = '12345678P' LIMIT 1];
        Map<String,Object> out = (Map<String,Object>)MSF_SummarySection_CONTROLLER.getCaso(co.Id);
        System.assert(((Integer)out.get('case')) > 0);
    }
    
    @isTest static void checkgetCasoHasNotOut(){
        Contact co = [SELECT Id FROM Contact WHERE msf_NIF__c = '12345678D' LIMIT 1];
        Map<String,Object> out = (Map<String,Object>)MSF_SummarySection_CONTROLLER.getCaso(co.Id);
        System.assert(((Integer)out.get('case')) == 0);
    }
    
    @isTest static void checkExistsOportunityDonationVehicle(){
        Contact c = [SELECT Id FROM Contact WHERE msf_NIF__c='12345678D' LIMIT 1];
        System.assert(MSF_SummarySection_CONTROLLER.getVd(c.Id));
    }
    
    @isTest static void checkCanNotGetDuplicate(){
        Contact c = [SELECT Id FROM Contact WHERE msf_NIF__c='12345678R' LIMIT 1];
        System.assert(!MSF_SummarySection_CONTROLLER.getDuplicate(c.Id));
    }
    
    @isTest static void checkCanGetDuplicate(){
        Contact c = [SELECT Id FROM Contact WHERE msf_NIF__c='12345678P' LIMIT 1];
        System.assert(MSF_SummarySection_CONTROLLER.getDuplicate(c.Id));
    }
    
    @isTest static void checkGetOporSolitaryWedding(){
        Contact c = [SELECT Id FROM Contact WHERE msf_NIF__c='B52296126' LIMIT 1];        
        Map<String,Object> out = (Map<String,Object>) MSF_SummarySection_CONTROLLER.getOpor(c.Id);
        System.assert((Boolean)out.get('boda'));
    }
    
    @isTest static void checkGetOporOther(){
        Contact c = [SELECT Id FROM Contact WHERE msf_NIF__c='12345678R' LIMIT 1];
        Test.setCreatedDate(c.Id, Date.today().addYears(-1));
        Test.startTest();
        update c;
        Map<String,Object> out = (Map<String,Object>) MSF_SummarySection_CONTROLLER.getOpor(c.Id);
        System.assert((Boolean)out.get('apor'));
        Test.stopTest();
    }
    
    @isTest static void checkGetOporInheritance(){
        Contact c = [SELECT Id FROM Contact WHERE msf_NIF__c='12345678P' LIMIT 1];
        Map<String,Object> out = (Map<String,Object>) MSF_SummarySection_CONTROLLER.getOpor(c.Id);
        System.assert((Boolean)out.get('her'));
    }    
    
    private static String getFakeId(Schema.SObjectType sot){
        String result = String.valueOf(s_num++);
        return sot.getDescribe().getKeyPrefix() + 
            '0'.repeat(12-result.length()) + result;
    }
}