force-app/main/default/objects/Campaign/fields/msf_FinalCampaign__c.field-meta.xml
<CustomField>
    <fullName>msf_FinalCampaign__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Campaña final</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_DateReturnedMail3Backup__c.field-meta.xml
<CustomField>
    <fullName>msf_DateReturnedMail3Backup__c</fullName>
    <label>Fecha correo devuelto 3 (Backup)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_EntryCampaign__c.field-meta.xml
<CustomField>
    <fullName>msf_EntryCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaña de entrada inicial</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Contactos (Campaña de entrada)</relationshipLabel>
    <relationshipName>Contactos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_MainEmail__c.field-meta.xml
<CustomField>
    <fullName>msf_MainEmail__c</fullName>
    <label>Email principal</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_NIF__c.field-meta.xml
<CustomField>
    <fullName>msf_NIF__c</fullName>
    <label>NIF/NIE/CIF</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_NoEmail__c.field-meta.xml
<CustomField>
    <fullName>msf_NoEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_NoRecibirNada__c.field-meta.xml
<CustomField>
    <fullName>msf_NoRecibirNada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No desea recibir nada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_Organization__c.field-meta.xml
<CustomField>
    <fullName>msf_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organización</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contactos de organización</relationshipLabel>
    <relationshipName>Organization</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <description>Indicates if this Contact is designated as the Primary Contact on their Account (read only).</description>
    <formula>Account.npe01__One2OneContact__c = Id</formula>
    <inlineHelpText>Este campo esta seleccionado si es el contacto principal en la cuenta. El contacto principal puede editarse en la cuenta.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Organization_Contact.recordType-meta.xml
<RecordType>
    <fullName>Organization_Contact</fullName>
    <active>true</active>
    <label>Organization Contact</label>
</RecordType>

force-app/main/default/objects/cpm__Payment_Profile__c/cpm__Payment_Profile__c.object-meta.xml
<CustomObject>
    <description>captures the payment profiles per contact/account.
such as IBAN, legacy bank account, Credit Card etc.</description>
    <label>Payment Profile</label>
    <nameField>
        <displayFormat>PP-{0}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/cpm__Contact__c.field-meta.xml
<CustomField>
    <fullName>cpm__Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The debitor.</description>
    <inlineHelpText>El deudor</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Payment_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/cpm__Holder_Name__c.field-meta.xml
<CustomField>
    <fullName>cpm__Holder_Name__c</fullName>
    <description>Name of the account/credit card holder.</description>
    <inlineHelpText>Nombre del titular de la cuenta / tarjeta de crédito.</inlineHelpText>
    <label>Holder Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/cpm__IBAN__c.field-meta.xml
<CustomField>
    <fullName>cpm__IBAN__c</fullName>
    <description>The bank account number in IBAN format.</description>
    <inlineHelpText>El número de cuenta bancaria en formato IBAN.</inlineHelpText>
    <label>IBAN</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/msf_HolderFirstName__c.field-meta.xml
<CustomField>
    <fullName>msf_HolderFirstName__c</fullName>
    <label>Nombre titular de la cuenta</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/msf_HolderLastName1__c.field-meta.xml
<CustomField>
    <fullName>msf_HolderLastName1__c</fullName>
    <label>Apellido 1 titular de la cuenta</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/msf_HolderLastName2__c.field-meta.xml
<CustomField>
    <fullName>msf_HolderLastName2__c</fullName>
    <label>Apellido 2 titular de la cuenta</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/msf_NIF__c.field-meta.xml
<CustomField>
    <fullName>msf_NIF__c</fullName>
    <label>NIF del titular</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/msf_Associative__c.object-meta.xml
<CustomObject>
    <label>Asociativo</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Número asociado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asociativos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_Associative__c/fields/msf_ContactId__c.field-meta.xml
<CustomField>
    <fullName>msf_ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre del contacto</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Asociativos</relationshipLabel>
    <relationshipName>Asociativos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/msf_Endorsement__c/msf_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Aval</label>
    <nameField>
        <displayFormat>AV-{000000}</displayFormat>
        <label>Código aval</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_Endorsement__c/fields/msf_IsEndorsed__c.field-meta.xml
<CustomField>
    <fullName>msf_IsEndorsed__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Avalado</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Avalado por</relationshipLabel>
    <relationshipName>AvaladoPor</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/msf_Endorsement__c/fields/msf_isEndorsing__c.field-meta.xml
<CustomField>
    <fullName>msf_isEndorsing__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Aval</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Aval de</relationshipLabel>
    <relationshipName>Avales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/msf_GDPRLog__c/msf_GDPRLog__c.object-meta.xml
<CustomObject>
    <label>Registro RGPD</label>
    <nameField>
        <displayFormat>RGPD_LOG_{0000000000}</displayFormat>
        <label>Nombre de Registro RGPD</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registros RGPD</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_GDPRLog__c/fields/msf_Contact__c.field-meta.xml
<CustomField>
    <fullName>msf_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contacto</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Registros_GDPR</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Contact for this Opportunity. If this is an individual Donation, NPSP attributes the Donation to the Primary Contact. If this is an organizational Donation, NPSP attributes a soft credit to the Primary Contact.</description>
    <inlineHelpText>El contacto principal para esta oportunidad. La función del contacto principal se mantiene sincronizada con este campo. Para donantes individuales, esto significa atribuciones por esta oportunidad.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MSF_AnonymizationProcess_TEST.cls
/**
* @author       Deloitte
* @date         05-2019
* @group        Contact
* @description  test class for the MSF_AnonymizationProcess_CTRL class.
*/
@isTest
private class MSF_AnonymizationProcess_TEST {

    @testSetup 
    static void setup(){
        
        Map<String,Schema.RecordTypeInfo> mConRtInfo = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName(); 
        Map<String,Schema.RecordTypeInfo> mPPRtInfo = Schema.SObjectType.cpm__Payment_Profile__c.getRecordTypeInfosByDeveloperName(); 
        
        Campaign camp = new Campaign(Name='MSF Entry Campaign',msf_FinalCampaign__c = false);
        insert camp;  
        
        npsp__Trigger_Handler__c thCon = new npsp__Trigger_Handler__c(
            Name = 'TriggerTestContactFieldsLogic',
            npsp__Class__c = 'MSF_ContactFieldsLogic_TDTM',
            npsp__Object__c = 'Contact',
            npsp__Trigger_Action__c = 'BeforeInsert;BeforeUpdate;AfterUpdate',
            npsp__Active__c = true,
            npsp__Load_Order__c = 3,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );        
        upsert thCon; 
        
        
    	Contact c = new Contact(
            RecordtypeId = mConRtInfo.get('Organization').getRecordTypeId(),            
            LastName= 'LastName1',
            msf_MainEmail__c = 'm@m.com',
            msf_NIF__c='00000000T',            
            MailingCity = 'Barcelona',
            MailingCountry = 'España',
            MailingPostalCode = '08013',
            MailingState = 'Barcelona',
            MailingStreet = 'C/ Gran via',
            msf_DateReturnedMail3Backup__c = date.today(),
            msf_NoRecibirNada__c = false,
            msf_EntryCampaign__c = camp.Id
        );
        insert c;
        
        msf_GDPRLog__c log = new msf_GDPRLog__c();
        log.msf_Contact__c = c.Id; 
        insert log;
        
        msf_Associative__c ass = new msf_Associative__c();
        ass.msf_ContactId__c = c.Id; 
        insert ass; 
        
        msf_Endorsement__c endorsement = new msf_Endorsement__c();
        endorsement.msf_isEndorsing__c = c.Id;
        endorsement.msf_IsEndorsed__c = c.Id; 
        insert endorsement;
        
        /*Contact c2 = new Contact(
            RecordtypeId = mConRtInfo.get('Organization_Contact').getRecordTypeId(),
			msf_Organization__c = c.Id,            
            FirstName='FirstName1',
            LastName= 'LastName1',
            Suffix = 'LastName2',
            msf_MainEmail__c = 'm@m.com',
            msf_NIF__c='43578879C',            
            MailingCity = 'Barcelona',
            MailingCountry = 'España',
            MailingPostalCode = '08013',
            MailingState = 'Barcelona',
            MailingStreet = 'C/ Gran via',
            msf_DateReturnedMail3Backup__c = date.today(),
            msf_NoRecibirNada__c = false,
            msf_EntryCampaign__c = camp.Id
        );
        insert c2;*/
        
        Contact c3 = new Contact();
        c3.FirstName='Manuel';
        c3.LastName= 'Medina';
        c3.Suffix = 'Herrera';
        c3.msf_NIF__c='15573648A';
        c3.MobilePhone='665310426';
        c3.msf_NoEmail__c=false;
       	insert c3;
        
        //Opportunity
        Opportunity opp = new Opportunity();
        opp.Name = 'TESTOPP';
        opp.npe03__Recurring_Donation__c = null;
        opp.npsp__Primary_Contact__c = c3.id;
        opp.StageName = 'Propuesta';
        opp.CloseDate = Date.today();
        opp.AccountId = c3.AccountId; 
        insert opp;
        
                       
        cpm__IbanValidation__c ibanValidation = new cpm__IbanValidation__c(
            Name = 'ES',
            cpm__RegEx__c = '^(?=[0-9A-Z]{24}$)ES\\d{22}$' ,
            SetupOwnerId = UserInfo.getOrganizationId()
        );
        insert ibanValidation;
        
        npsp4hub.NPSPSetup base = new npsp4hub.NPSPSetup();
        cpm.SetupService.install(base);
        cpm.TestService.activateSourceExtension(base);
        cpm.TestService.createIbanRegex();
        cpm.TestService.initTestPSPExtension();
        cpm.TestService.initTestSourceExtension(); 
        
        cpm__Payment_Profile__c newPaymentProfile = new cpm__Payment_Profile__c(
            cpm__Contact__c = c.Id,
            recordtypeId = mPPRtInfo.get('IBAN').getRecordTypeId(),
            cpm__IBAN__c = 'ES4714577504091166875044',
            msf_HolderFirstName__c = c.FirstName,
            msf_HolderLastName1__c = c.LastName,
            msf_HolderLastName2__c = c.Suffix,
            msf_NIF__c = c.msf_NIF__c,
            cpm__Holder_Name__c = c.FirstName + ' ' + c.LastName + ' ' + c.Suffix,
            cpm__Active__c = true
        );        
        insert newPaymentProfile;   
    }
    
    
    @isTest 
    static void anonymizationProcess(){
    	Contact c = [SELECT Id FROM Contact WHERE msf_NIF__c = '00000000T' LIMIT 1];
        MSF_AnonymizationProcess_CTRL.anonymizationRecord(c.Id);
        
        Contact c2 = [SELECT ID FROM Contact WHERE msf_NIF__c = '15573648A' LIMIT 1];
        MSF_AnonymizationProcess_CTRL.anonymizationRecord(c2.Id);
        
        /*Contact con = [SELECT Id, LastName, msf_MainEmail__c, msf_NoRecibirNada__c, msf_DateReturnedMail3Backup__c, AccountId FROM Contact WHERE Id =: c.Id LIMIT 1];
        //Contact orgCon = [SELECT Id, FirstName, LastName, msf_MainEmail__c, msf_NoRecibirNada__c, msf_DateReturnedMail3Backup__c FROM Contact WHERE msf_Organization__c =: con.Id LIMIT 1];
        Account ac = [SELECT Name, BillingCountry FROM Account WHERE Id =: con.AccountId ];
        cpm__Payment_Profile__c pp = [SELECT cpm__IBAN__c, cpm__Holder_Name__c, cpm__Active__c FROM cpm__Payment_Profile__c WHERE cpm__Contact__c =: con.Id LIMIT 1];
        */
        /*System.assertEquals('Miembro eliminado ' + date.today().day() + '-' + date.today().month() + '-' + date.today().year() + ' .', con.LastName);        
        System.assertEquals(null, con.msf_MainEmail__c);
        System.assertEquals(true, con.msf_NoRecibirNada__c);
        System.assertEquals(null, con.msf_DateReturnedMail3Backup__c);  
        
        System.assertEquals('Miembro eliminado ' + date.today().day() + '-' + date.today().month() + '-' + date.today().year(), orgCon.FirstName); 
        System.assertEquals('.' , orgCon.LastName);   
        System.assertEquals(null, orgCon.msf_MainEmail__c);
        System.assertEquals(true, orgCon.msf_NoRecibirNada__c);
        System.assertEquals(null, orgCon.msf_DateReturnedMail3Backup__c); 
        
        System.assertEquals('ES8200000000000000000000', pp.cpm__IBAN__c);
        System.assertEquals(null, pp.cpm__Holder_Name__c);
        System.assertEquals(false, pp.cpm__Active__c);
        
        System.assertEquals('Miembro eliminado ' + date.today().day() + '-' + date.today().month() + '-' + date.today().year(), ac.Name);
        System.assertEquals(null, ac.BillingCountry);*/
    }
    
}