force-app/main/default/objects/Campaign/fields/msf_IsOnline__c.field-meta.xml
<CustomField>
    <fullName>msf_IsOnline__c</fullName>
    <label>Es online</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/msf_Objective__c.field-meta.xml
<CustomField>
    <fullName>msf_Objective__c</fullName>
    <label>Objetivo principal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Captación de leads</fullName>
            </value>
            <value>
                <fullName>Captación de socios o donantes</fullName>
            </value>
            <value>
                <fullName>Conversión (de lead o donante a asociado)</fullName>
            </value>
            <value>
                <fullName>Conversión (de lead o donante a socio)</fullName>
            </value>
            <value>
                <fullName>Cultivación</fullName>
            </value>
            <value>
                <fullName>Desconocido</fullName>
            </value>
            <value>
                <fullName>Informativo</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Petición difusión</fullName>
            </value>
            <value>
                <fullName>Recuperación</fullName>
            </value>
            <value>
                <fullName>Rendición de cuentas</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/msf_OwnBy__c.field-meta.xml
<CustomField>
    <fullName>msf_OwnBy__c</fullName>
    <label>Propiedad de</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Colaboraciones Estratégicas</fullName>
            </value>
            <value>
                <fullName>Desconocido</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Fidelización</fullName>
            </value>
            <value>
                <fullName>Captación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/msf_Segment__c.field-meta.xml
<CustomField>
    <fullName>msf_Segment__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One to One</fullName>
            </value>
            <value>
                <fullName>Frio individuos</fullName>
            </value>
            <value>
                <fullName>Organizaciones</fullName>
            </value>
            <value>
                <fullName>Celebraciones</fullName>
            </value>
            <value>
                <fullName>Mass donors</fullName>
            </value>
            <value>
                <fullName>Mid donors</fullName>
            </value>
            <value>
                <fullName>Desconocido</fullName>
            </value>
            <value>
                <fullName>Leads</fullName>
            </value>
            <value>
                <fullName>OCBA All</fullName>
            </value>
            <value>
                <fullName>Asociados</fullName>
            </value>
            <value>
                <fullName>Asociados España</fullName>
            </value>
            <value>
                <fullName>Sanitarios</fullName>
            </value>
            <value>
                <fullName>Terreno</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Testamentarios</fullName>
            </value>
            <value>
                <fullName>Mid+ donors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Level__c/npsp__Level__c.object-meta.xml
<CustomObject>
    <description>Tracks the definition of levels, for any object.</description>
    <label>Level</label>
    <nameField>
        <label>Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Level__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Level is currently in use.</description>
    <inlineHelpText>Si este nivel esta en uso actualmente.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Level__c/fields/npsp__Level_Field__c.field-meta.xml
<CustomField>
    <fullName>npsp__Level_Field__c</fullName>
    <description>Indicates which field to use on the target object to store the current Level.</description>
    <inlineHelpText>El campo (nombre de la Api) en el objecto destino donde se guarda la búsqueda al nivel actual. Tenga en cuenta que este campo implícitamente define la &quot;escalera&quot; de la que este nivel es parte.</inlineHelpText>
    <label>Level Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Level__c/fields/npsp__Source_Field__c.field-meta.xml
<CustomField>
    <fullName>npsp__Source_Field__c</fullName>
    <description>The target object&apos;s field (developer name) that defines the amount and timeframe to base this Level on.</description>
    <inlineHelpText>El campo del objeto destino (nombre de la API) que define la cantidad y el período de tiempo en la que se basa este nivel.</inlineHelpText>
    <label>Source Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Level__c/fields/npsp__Target__c.field-meta.xml
<CustomField>
    <fullName>npsp__Target__c</fullName>
    <description>The object that this Level applies to.</description>
    <inlineHelpText>El objeto al que se le aplica este nivel.</inlineHelpText>
    <label>Target</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MSF_CopyLevelAndProgramContact_TEST.cls
/**
* @author 		Omega CRM
* @date 		11-2021
* @group 		Contacts
* @description	test class for the MSF_CopyLevelAndProgramContact_TDTM class.
*/
@isTest
public class MSF_CopyLevelAndProgramContact_TEST {
    @TestSetup
    static void testSetup(){
        //Create Trigger
        npsp__Trigger_Handler__c thCon = new npsp__Trigger_Handler__c(
            Name = 'TriggerTestLevelFieldChanges',
            npsp__Class__c = 'MSF_CopyLevelAndProgramContact_TDTM',
            npsp__Object__c = 'Contact',
            npsp__Trigger_Action__c = 'BeforeUpdate, BeforeInsert, AfterUpdate',
            npsp__Active__c = true,
            npsp__Load_Order__c = 3,
            npsp__User_Managed__c = false,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );        
        upsert thCon; 

        List<npsp__Level__c> listLevel = new List<npsp__Level__c>();
        listLevel.add(new npsp__Level__c(
        	Name='MSF_LevelFieldsChanges_TEST_Contact_Level_Name',
            npsp__Target__c	= 'Contact',
            npsp__Level_Field__c='MSF_LevelFieldsChanges_TEST_Contact_Level_Field',
            npsp__Source_Field__c='MSF_LevelFieldsChanges_TEST_Contact_Level_Source_Field'
        ));
        insert listLevel;

        Campaign c = new Campaign(Name = 'Captación 2018', msf_IsOnline__c = 'Si', msf_Objective__c = 'Desconocido', msf_OwnBy__c = 'Digital',
        msf_Segment__c = 'Organizaciones', msf_Thematic__c = '91');
        insert c;

        Contact Organization = new Contact();
        Organization.LastName = 'Test Organization 1';
        Organization.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization').getRecordTypeId();
        Organization.msf_OrganizationType__c = 'Company';
        Organization.LeadSource = 'Cupón';
        Organization.msf_EntryCampaign__c = c.Id;
        Organization.msf_RelationshipLevel__c = listLevel[0].Id;
        Organization.msf_Program__c = 'Vehículo donación de Gran Donante = YES';
        insert Organization;

        Contact Organization2 = new Contact();
        Organization2.LastName = 'Test Organization 2';
        Organization2.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization').getRecordTypeId();
        Organization2.msf_OrganizationType__c = 'Company';
        Organization2.LeadSource = 'Cupón';
        Organization2.msf_EntryCampaign__c = c.Id;
        Organization2.msf_RelationshipLevel__c = listLevel[0].Id;
        Organization2.msf_Program__c = 'Prospectos Empresas & Colectivos Mass';
        insert Organization2;

    }

    @isTest 
    static void copyLevelAndProgramContactTest1 (){
        Contact organization = [SELECT id FROM Contact WHERE LastName = 'Test Organization 1' LIMIT 1];
        Campaign campanha = [SELECT id FROM Campaign WHERE name = 'Captación 2018'];
        Contact OrganizationContact = new Contact();
        OrganizationContact.LastName = 'Test OrganizationContact 2';
        OrganizationContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization_Contact').getRecordTypeId();
        OrganizationContact.msf_OrganizationType__c = 'Company';
        OrganizationContact.LeadSource = 'Cupón';
        OrganizationContact.msf_EntryCampaign__c = campanha.Id;
        OrganizationContact.msf_Organization__c = organization.Id;

        test.startTest();
        insert OrganizationContact;
        test.stopTest();

        Contact OrganizationContacto = [SELECT id, msf_Program__c FROM Contact WHERE LastName = 'Test OrganizationContact 2' LIMIT 1];
        system.assertEquals('Vehículo donación de Gran Donante = YES', OrganizationContacto.msf_Program__c);
    }

    @isTest 
    static void copyLevelAndProgramContactTest2 (){
        Contact organization = [SELECT id FROM Contact WHERE LastName = 'Test Organization 1' LIMIT 1];
        Campaign campanha = [SELECT id FROM Campaign WHERE name = 'Captación 2018'];
        Contact OrganizationContact = new Contact();
        OrganizationContact.LastName = 'Test OrganizationContact 2';
        OrganizationContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization_Contact').getRecordTypeId();
        OrganizationContact.msf_OrganizationType__c = 'Company';
        OrganizationContact.LeadSource = 'Cupón';
        OrganizationContact.msf_EntryCampaign__c = campanha.Id;
        OrganizationContact.msf_Organization__c = organization.Id;
        insert OrganizationContact;

        Contact organization2 = [SELECT id FROM Contact WHERE LastName = 'Test Organization 2' LIMIT 1];
        OrganizationContact.msf_Organization__c = organization2.Id;

        test.startTest();
        update OrganizationContact;
        test.stopTest();

        Contact OrganizationContacto = [SELECT id, msf_Program__c FROM Contact WHERE LastName = 'Test OrganizationContact 2' LIMIT 1];
        system.assertEquals('Prospectos Empresas & Colectivos Mass', OrganizationContacto.msf_Program__c);
    }

    @isTest 
    static void copyLevelAndProgramContactTest3 (){
        Contact organization = [SELECT id FROM Contact WHERE LastName = 'Test Organization 1' LIMIT 1];
        Campaign campanha = [SELECT id FROM Campaign WHERE name = 'Captación 2018'];
        Contact OrganizationContact = new Contact();
        OrganizationContact.LastName = 'Test OrganizationContact 2';
        OrganizationContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization_Contact').getRecordTypeId();
        OrganizationContact.msf_OrganizationType__c = 'Company';
        OrganizationContact.LeadSource = 'Cupón';
        OrganizationContact.msf_EntryCampaign__c = campanha.Id;
        OrganizationContact.msf_Organization__c = organization.Id;
        insert OrganizationContact;

        Contact organizationTest1 = [SELECT id, msf_Program__c FROM Contact WHERE LastName = 'Test Organization 1' LIMIT 1];
        organizationTest1.msf_Program__c = 'Prospectos Empresas & Colectivos Mass';

        test.startTest();
        update organizationTest1;
        test.stopTest();

        Contact OrganizationContacto = [SELECT id, msf_Program__c FROM Contact WHERE LastName = 'Test OrganizationContact 2' LIMIT 1];
        system.assertEquals('Prospectos Empresas & Colectivos Mass', OrganizationContacto.msf_Program__c);
    }

    @isTest 
    static void copyLevelAndProgramContactTestBulk (){
        List<Contact> listContact =  new List<Contact>();
        Contact organization = [SELECT id FROM Contact WHERE LastName = 'Test Organization 1' LIMIT 1];
        Contact organization2 = [SELECT id FROM Contact WHERE LastName = 'Test Organization 2' LIMIT 1];
        Campaign campanha = [SELECT id FROM Campaign WHERE name = 'Captación 2018'];
        Contact OrganizationContact = new Contact();
        OrganizationContact.LastName = 'Test OrganizationContact 1';
        OrganizationContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization_Contact').getRecordTypeId();
        OrganizationContact.msf_OrganizationType__c = 'Company';
        OrganizationContact.LeadSource = 'Cupón';
        OrganizationContact.msf_EntryCampaign__c = campanha.Id;
        OrganizationContact.msf_Organization__c = organization.Id;

        Contact OrganizationContact2 = new Contact();
        OrganizationContact2.LastName = 'Test OrganizationContact 2';
        OrganizationContact2.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization_Contact').getRecordTypeId();
        OrganizationContact2.msf_OrganizationType__c = 'Company';
        OrganizationContact2.LeadSource = 'Cupón';
        OrganizationContact2.msf_EntryCampaign__c = campanha.Id;
        OrganizationContact2.msf_Organization__c = organization2.Id;

        Contact OrganizationContact3 = new Contact();
        OrganizationContact3.LastName = 'Test OrganizationContact 3';
        OrganizationContact3.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization_Contact').getRecordTypeId();
        OrganizationContact3.msf_OrganizationType__c = 'Company';
        OrganizationContact3.LeadSource = 'Cupón';
        OrganizationContact3.msf_EntryCampaign__c = campanha.Id;
        OrganizationContact3.msf_Organization__c = organization.Id;

        listContact.add(OrganizationContact);
        listContact.add(OrganizationContact2);
        listContact.add(OrganizationContact3);

        test.startTest();
        insert listContact;
        test.stopTest();

        Contact OrganizationContacto = [SELECT id, msf_Program__c FROM Contact WHERE LastName = 'Test OrganizationContact 1' LIMIT 1];
        Contact OrganizationContacto2 = [SELECT id, msf_Program__c FROM Contact WHERE LastName = 'Test OrganizationContact 2' LIMIT 1];
        Contact OrganizationContacto3 = [SELECT id, msf_Program__c FROM Contact WHERE LastName = 'Test OrganizationContact 3' LIMIT 1];
        system.assertEquals('Vehículo donación de Gran Donante = YES', OrganizationContacto.msf_Program__c);
        system.assertEquals('Prospectos Empresas & Colectivos Mass', OrganizationContacto2.msf_Program__c);
        system.assertEquals('Vehículo donación de Gran Donante = YES', OrganizationContacto3.msf_Program__c);
    }

}