force-app/main/default/objects/Campaign/fields/msf_FinalCampaign__c.field-meta.xml
<CustomField>
    <fullName>msf_FinalCampaign__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Campaña final</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Associative.recordType-meta.xml
<RecordType>
    <fullName>Associative</fullName>
    <active>true</active>
    <label>Asociativo</label>
</RecordType>

force-app/main/default/objects/Contact/fields/msf_FirstEntryDateRecurringDonor__c.field-meta.xml
<CustomField>
    <fullName>msf_FirstEntryDateRecurringDonor__c</fullName>
    <label>Fecha de primera alta de socio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_IsAssosiative__c.field-meta.xml
<CustomField>
    <fullName>msf_IsAssosiative__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es asociado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_MainEmail__c.field-meta.xml
<CustomField>
    <fullName>msf_MainEmail__c</fullName>
    <label>Email principal</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_NIF__c.field-meta.xml
<CustomField>
    <fullName>msf_NIF__c</fullName>
    <label>NIF/NIE/CIF</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Individual_Contact.recordType-meta.xml
<RecordType>
    <fullName>Individual_Contact</fullName>
    <active>true</active>
    <label>Individual Contact</label>
</RecordType>

force-app/main/default/objects/cpm__Payment_Profile__c/cpm__Payment_Profile__c.object-meta.xml
<CustomObject>
    <description>captures the payment profiles per contact/account.
such as IBAN, legacy bank account, Credit Card etc.</description>
    <label>Payment Profile</label>
    <nameField>
        <displayFormat>PP-{0}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/cpm__Active__c.field-meta.xml
<CustomField>
    <fullName>cpm__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this payment profile is active and available for use.</description>
    <inlineHelpText>Indica si este perfil de pago está activo y disponible para su uso.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/cpm__Contact__c.field-meta.xml
<CustomField>
    <fullName>cpm__Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The debitor.</description>
    <inlineHelpText>El deudor</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Payment_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/cpm__Holder_Name__c.field-meta.xml
<CustomField>
    <fullName>cpm__Holder_Name__c</fullName>
    <description>Name of the account/credit card holder.</description>
    <inlineHelpText>Nombre del titular de la cuenta / tarjeta de crédito.</inlineHelpText>
    <label>Holder Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/cpm__IBAN__c.field-meta.xml
<CustomField>
    <fullName>cpm__IBAN__c</fullName>
    <description>The bank account number in IBAN format.</description>
    <inlineHelpText>El número de cuenta bancaria en formato IBAN.</inlineHelpText>
    <label>IBAN</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/msf_NIF__c.field-meta.xml
<CustomField>
    <fullName>msf_NIF__c</fullName>
    <label>NIF del titular</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__PaymentHub_Settings__c/fields/cpm__Auto_Create_Mandate_Recurring_Payment_DD__c.field-meta.xml
<CustomField>
    <fullName>cpm__Auto_Create_Mandate_Recurring_Payment_DD__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When true a mandate will be created when an Recurring or Single Payment is created of type Direct Debit which doesn&apos;t already has a relationship to a Mandate</description>
    <inlineHelpText>Wanneer aangevinkt zal er een mandaat aangemaakt worden wanneer een terugkerende betaling van het type automatische incasso gemaakt wordt en deze nog geen relatie met een mandaat heeft</inlineHelpText>
    <label>Autocreate mandate for Direct Debits</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cpm__PaymentHub_Settings__c/fields/cpm__Re_use_existing_mandate__c.field-meta.xml
<CustomField>
    <fullName>cpm__Re_use_existing_mandate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>re-use existing mandate if available</description>
    <label>Reuse existing mandate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cpm__PaymentHub_Settings__c/fields/cpm__Store_Informal_Logs__c.field-meta.xml
<CustomField>
    <fullName>cpm__Store_Informal_Logs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Store Informal Logs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_acceptDataProtectionPolicy__c.field-meta.xml
<CustomField>
    <fullName>msf_acceptDataProtectionPolicy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Política protección de datos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_AcceptStatutes__c.field-meta.xml
<CustomField>
    <fullName>msf_AcceptStatutes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Conozco y acepto mis obligaciones</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_AssociativePhone__c.field-meta.xml
<CustomField>
    <fullName>msf_AssociativePhone__c</fullName>
    <label>Teléfono de asociativo</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_ExemptOfPayment__c.field-meta.xml
<CustomField>
    <fullName>msf_ExemptOfPayment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exento de pago</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANAccountNumber__c</fullName>
    <label>Número de cuenta</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANCode__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANCode__c</fullName>
    <label>Código IBAN</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANDC__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANDC__c</fullName>
    <label>Dígito de control</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANEntity__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANEntity__c</fullName>
    <label>Entidad</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANOffice__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANOffice__c</fullName>
    <label>Oficina</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IsAssosiative__c.field-meta.xml
<CustomField>
    <fullName>msf_IsAssosiative__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es de asociativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_NIF__c.field-meta.xml
<CustomField>
    <fullName>msf_NIF__c</fullName>
    <description>VAT Number</description>
    <label>NIF/NIE/CIF</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_noCriminalRecord__c.field-meta.xml
<CustomField>
    <fullName>msf_noCriminalRecord__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No antecedentes penales</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Associative.recordType-meta.xml
<RecordType>
    <fullName>Associative</fullName>
    <active>true</active>
    <businessProcess>Associative Lead</businessProcess>
    <label>Associative</label>
</RecordType>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/User/fields/msf_City__c.field-meta.xml
<CustomField>
    <fullName>msf_City__c</fullName>
    <label>Ciudad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Barcelona</fullName>
            </value>
            <value>
                <fullName>Madrid</fullName>
            </value>
            <value>
                <fullName>Málaga</fullName>
            </value>
            <value>
                <fullName>Cordoba</fullName>
                <isActive>false</isActive>
                <label>Cordoba</label>
            </value>
            <value>
                <fullName>Las Palmas</fullName>
                <isActive>false</isActive>
                <label>Las Palmas</label>
            </value>
            <value>
                <fullName>Sevilla</fullName>
                <isActive>false</isActive>
                <label>Sevilla</label>
            </value>
            <value>
                <fullName>Valencia</fullName>
                <isActive>false</isActive>
                <label>Valencia</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestMSF_SharedMethods_Util.cls
/**
 * @description       : 
 * @author            : arubio@omegacrmconsulting.com
 * @group             : 
 * @last modified on  : 06-04-2022
 * @last modified by  : arubio@omegacrmconsulting.com
**/
@isTest
private class TestMSF_SharedMethods_UTIL{

	@testSetup static void setup(){

        Id recordPF = Schema.SObjectType.cpm__Payment_Profile__c.getRecordTypeInfosByName().get('Credit Card').getRecordTypeId();
        Id IDContactRT = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Individual_Contact').getRecordTypeId();
		Id recordRD = Schema.SObjectType.npe03__Recurring_Donation__c.getRecordTypeInfosByDeveloperName().get('Recurring_donation').getRecordTypeId();
        Id recordTypeOppDonation = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Donation').getRecordTypeId();
        Id recordTypeLead = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('Associative').getRecordTypeId();

		npsp__Trigger_Handler__c thCon = new npsp__Trigger_Handler__c(
            Name = 'TriggerTestOpportunitiesFieldsLogic',
            npsp__Class__c = 'MSF_OpportunitiesFieldsLogic_TDTM',
            npsp__Object__c = 'Opportunity',
            npsp__Trigger_Action__c = 'BeforeInsert;BeforeUpdate;AfterInsert;AfterUpdate',
            npsp__Active__c = true,
            npsp__Load_Order__c = 6,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );        
        upsert thCon;  
		Profile prof = [SELECT Id FROM Profile WHERE Name = 'Service Center'];
		User u = new User();
        u.msf_City__c = 'Barcelona';
        u.Email = 'user@ac.testcom';
        u.Username = 'user@ac.testcom';
        u.LastName = 'user1';
        u.Alias = 'cc';
        u.CommunityNickname = '';
        u.TimeZoneSidKey = 'Europe/Paris';
        u.LocaleSidKey = 'es_ES';
        u.EmailEncodingKey = 'ISO-8859-1';
        u.ProfileId=prof.Id;
        u.LanguageLocaleKey='es';
        insert u;
		cpm__IbanValidation__c ibanValidation = new cpm__IbanValidation__c(
            Name = 'ES',
            cpm__RegEx__c = '^(?=[0-9A-Z]{24}$)ES\\d{22}$' 
        );
        insert ibanValidation;
		npsp4hub.NPSPSetup base = new npsp4hub.NPSPSetup();
        cpm.SetupService.install(base);
        cpm.TestService.activateSourceExtension(base);
        cpm.TestService.createIbanRegex();
        cpm.TestService.initTestPSPExtension();
        cpm.TestService.initTestSourceExtension();
		cpm__PaymentHub_Settings__c ps = new cpm__PaymentHub_Settings__c (
            cpm__Auto_Create_Mandate_Recurring_Payment_DD__c = false,	
            cpm__Re_use_existing_mandate__c	= false,
            cpm__Store_Informal_Logs__c	= true,
            Name = 'main'        
        );
        insert ps;
		
		
		Campaign camp = new Campaign(Name='MSFConvertAssociativeLeadTESTcamp1',msf_FinalCampaign__c = false);
        insert camp;


		Lead lead2 = new Lead(RecordTypeId=recordTypeLead,
                              Company='Company2',
                              FirstName='FirstName2',
                              LastName='LastName2',
                              Suffix = 'Suffix2',
                              msf_NIF__c = '59115913W',
                              Email='a@a2.com',   
                              msf_AssociativePhone__c = '911111112',
                              Phone = '911111112',
                              MobilePhone='611111112',
                              LeadSource='SMS',
                              msf_ExemptOfPayment__c=false,
                              msf_IBANCode__c = 'ES76',
                              msf_IBANEntity__c = '3183',
                              msf_IBANOffice__c = '5763',
                              msf_IBANDC__c = '08',
                              msf_IBANAccountNumber__c = '4530503821',     
                              msf_noCriminalRecord__c = true,
                              msf_AcceptStatutes__c = true,
                              msf_acceptDataProtectionPolicy__c = true                             
                              );  
        insert lead2;
		CampaignMember campMem = new CampaignMember(CampaignId=camp.Id, LeadId = lead2.Id);
        insert campMem;
		/**************************************************************************************************************** */
        Contact cont2 = new Contact(LastName='MSF_AccountFieldsLogic_TEST_LastName12',RecordTypeId=IDContactRT);
        insert cont2;

        
        
        Account acc = new Account(Name='MSF_AccountFieldsLogic_TEST_Name');
        
        insert acc;        
        Contact contactPrueba  = new Contact(
                FirstName='NombrePrueba',
                LastName= 'ApellidoPrueba',
                msf_MainEmail__c = 'm@m.com',
                msf_NIF__c='43578812C',
                msf_IsAssosiative__c = true,
                RecordTypeId=IDContactRT,
                AccountId = acc.Id,
                msf_FirstEntryDateRecurringDonor__c = Date.newInstance(2020, 3, 7)
            );
        
        
        insert contactPrueba;
        
        cpm__Payment_Profile__c p1 = new cpm__Payment_Profile__c(
                cpm__Contact__c = contactPrueba.Id,
                recordtypeId = recordPF,
                cpm__IBAN__c = 'ES7900830842484269389890',
                msf_NIF__c =  contactPrueba.msf_NIF__c,
                cpm__Holder_Name__c =  contactPrueba.FirstName + ' ' +  contactPrueba.LastName + ' ' +  contactPrueba.Suffix,
                cpm__Active__c = true
            ); 
        
        
        insert p1;

        
        npe03__Recurring_Donation__c don = new npe03__Recurring_Donation__c();
        don.npe03__Contact__c =  contactPrueba.Id;
        don.Name = 'test2';
        don.npe03__Open_Ended_Status__c = 'Open';
        don.npsp4hub__Payment_Method__c = 'CreditCard';
        don.npsp4hub__Payment_Processor__c  = 'PaymentHub-SEPA';
        don.npsp4hub__Target__c  = 'LA CAIXA CCC OPERATIVA';
        don.RecordTypeId = recordRD;
        don.npe03__Paid_Amount__c = 0;
        don.npe03__Total_Paid_Installments__c = 0;
        don.npe03__Amount__c = 1234;
        don.npe03__Installment_Period__c ='Monthly';
        don.msf_CurrentLeadSource1__c ='Correo postal sin cupón';
        don.msf_CurrentCampaign__c = camp.ID;
        don.npsp4hub__Payment_Profile__c = p1.Id;
        don.npe03__Date_Established__c = Date.newInstance(2022, 3, 11);

        insert don;
    
        Opportunity newOpp = new Opportunity(
			Name = 'Opportunity Test', 
            RecordTypeId = recordTypeOppDonation,
			Type = 'Recovered Quota',
            CloseDate = Date.newInstance(2022, 3, 9),
            npsp__Primary_Contact__c = contactPrueba.Id,
            StageName='Cobrada',
			Amount = 1000,
            npsp4hub__Payment_Method__c = 'CreditCard',
            npsp4hub__Payment_Processor__c = 'PaymentHub-SEPA',
            npsp4hub__Target__c = 'LA CAIXA CCC OPERATIVA',
			CampaignId = camp.Id,
			npsp4hub__Payment_Profile__c=  p1.Id,
			npe03__Recurring_Donation__c = don.Id
            );
		insert newOpp;

        OpportunityContactRole opportunityContactRole = new OpportunityContactRole();
        opportunityContactRole.OpportunityId = newOpp.Id;
        opportunityContactRole.ContactId = contactPrueba.Id;
        opportunityContactRole.IsPrimary = true;
        insert opportunityContactRole;

	}

	@isTest static void SocioConExtraActiva() {

        Contact contactPrueba = [SELECT msf_MemberType__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        npe03__Recurring_Donation__c testRd = [SELECT ID,npe03__Open_Ended_Status__c,npe03__Paid_Amount__c,npe03__Total_Paid_Installments__c FROM npe03__Recurring_Donation__c WHERE npe03__Contact__c =: contactPrueba.Id];
        Opportunity opp = [SELECT StageName FROM Opportunity WHERE npsp__Primary_Contact__c=:contactPrueba.Id LIMIT 1];
        Test.startTest();
        opp.type ='Solidarity Wedding';
        update opp;
        Contact contactPrueba1 = [SELECT msf_MemberType__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        System.assertEquals('Socio con extra activa', contactPrueba1.msf_MemberType__c);

        Test.stopTest();
    }
    @isTest static void SocioConExtraInactiva() {

        Contact contactPrueba = [SELECT msf_MemberType__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        npe03__Recurring_Donation__c testRd = [SELECT ID,npe03__Open_Ended_Status__c,npe03__Date_Established__c,npe03__Paid_Amount__c,npe03__Total_Paid_Installments__c FROM npe03__Recurring_Donation__c WHERE npe03__Contact__c =: contactPrueba.Id];
        Opportunity opp = [SELECT StageName FROM Opportunity WHERE npsp__Primary_Contact__c=:contactPrueba.Id LIMIT 1];
        Test.startTest();
        testRd.npe03__Date_Established__c = Date.newInstance(2020, 3, 8);
        update testRd;
        opp.type ='Solidarity Wedding';
        opp.CloseDate = Date.newInstance(2020, 3, 9);
        update opp;
        Contact contactPrueba1 = [SELECT msf_MemberType__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        System.assertEquals('Socio con extra inactiva', contactPrueba1.msf_MemberType__c);

        Test.stopTest();
    }
    @isTest static void Socio() {

        Contact contactPrueba = [SELECT msf_MemberType__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        npe03__Recurring_Donation__c testRd = [SELECT ID,npe03__Open_Ended_Status__c,npe03__Date_Established__c,npe03__Paid_Amount__c,npe03__Total_Paid_Installments__c FROM npe03__Recurring_Donation__c WHERE npe03__Contact__c =: contactPrueba.Id];
        Opportunity opp = [SELECT StageName FROM Opportunity WHERE npsp__Primary_Contact__c=:contactPrueba.Id LIMIT 1];
        Test.startTest();
        System.assertEquals('Socio', contactPrueba.msf_MemberType__c);

        Test.stopTest();
    }

    @isTest static void DonanteConBajaPrevia() {

        Contact contactPrueba = [SELECT msf_MemberType__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        npe03__Recurring_Donation__c testRd = [SELECT ID,npe03__Open_Ended_Status__c,npe03__Paid_Amount__c,npe03__Total_Paid_Installments__c FROM npe03__Recurring_Donation__c WHERE npe03__Contact__c =: contactPrueba.Id];
        Opportunity opp = [SELECT StageName FROM Opportunity WHERE npsp__Primary_Contact__c=:contactPrueba.Id LIMIT 1];
        Test.startTest();
        testRd.npe03__Open_Ended_Status__c = 'Closed';
        testRd.npe03__Paid_Amount__c = 1;
        testRd.msf_CancelationReason__c = '2 TCS devueltas';

        update testRd;
        opp.type ='Solidarity Wedding';
        update opp;
        Contact contactPrueba1 = [SELECT msf_MemberType__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        System.assertEquals('Donante con Baja previa', contactPrueba1.msf_MemberType__c);

        Test.stopTest();
    }
    @isTest static void ExdonanteConBajaPrevia() {

        Contact contactPrueba = [SELECT msf_MemberType__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        npe03__Recurring_Donation__c testRd = [SELECT ID,npe03__Date_Established__c,npe03__Open_Ended_Status__c,npe03__Paid_Amount__c,npe03__Total_Paid_Installments__c FROM npe03__Recurring_Donation__c WHERE npe03__Contact__c =: contactPrueba.Id];
        Opportunity opp = [SELECT StageName,type,CloseDate FROM Opportunity WHERE npsp__Primary_Contact__c=:contactPrueba.Id LIMIT 1];
        Test.startTest();
        testRd.npe03__Open_Ended_Status__c = 'Closed';
        testRd.npe03__Paid_Amount__c = 1;
        testRd.msf_CancelationReason__c = '2 TCS devueltas';
        testRd.npe03__Date_Established__c =  Date.newInstance(2020, 3, 5);

        update testRd;
        opp.type ='Solidarity Wedding';
        opp.CloseDate = Date.newInstance(2020, 3, 9);
        update opp;
        Contact contactPrueba1 = [SELECT msf_MemberType__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        System.assertEquals('Exdonante con baja previa', contactPrueba1.msf_MemberType__c);

        Test.stopTest();
    }
    @isTest static void BajaConExtra() {

        Contact contactPrueba = [SELECT msf_MemberType__c,msf_FirstEntryDateRecurringDonor__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        npe03__Recurring_Donation__c testRd = [SELECT ID,npe03__Open_Ended_Status__c,npe03__Date_Established__c,npe03__Paid_Amount__c,npe03__Total_Paid_Installments__c FROM npe03__Recurring_Donation__c WHERE npe03__Contact__c =: contactPrueba.Id];
        Opportunity opp = [SELECT StageName,type,CloseDate FROM Opportunity WHERE npsp__Primary_Contact__c=:contactPrueba.Id LIMIT 1];
        Test.startTest();
        contactPrueba.msf_FirstEntryDateRecurringDonor__c =  Date.newInstance(2020, 3, 8);
        update contactPrueba;
        testRd.npe03__Open_Ended_Status__c = 'Closed';
        testRd.msf_CancelationReason__c = '2 TCS devueltas';
        testRd.npe03__Date_Established__c =  Date.newInstance(2020, 3, 5);
        update testRd;
        update opp;
        opp.type ='Solidarity Wedding';
        opp.CloseDate = Date.newInstance(2020, 3, 9);
        update opp;

        Test.stopTest();
        Contact contactPrueba1 = [SELECT msf_MemberType__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        System.assertEquals('Baja con extra', contactPrueba1.msf_MemberType__c);
    }
    @isTest static void Baja() {

        Contact contactPrueba = [SELECT msf_MemberType__c,msf_FirstEntryDateRecurringDonor__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        npe03__Recurring_Donation__c testRd = [SELECT ID,npe03__Open_Ended_Status__c,npe03__Paid_Amount__c,npe03__Total_Paid_Installments__c FROM npe03__Recurring_Donation__c WHERE npe03__Contact__c =: contactPrueba.Id];
        Opportunity opp = [SELECT StageName FROM Opportunity WHERE npsp__Primary_Contact__c=:contactPrueba.Id LIMIT 1];
        Test.startTest();
        testRd.npe03__Open_Ended_Status__c = 'Closed';
        testRd.msf_CancelationReason__c = '2 TCS devueltas';
        update testRd;
        update opp;
        Test.stopTest();
        Contact contactPrueba1 = [SELECT msf_MemberType__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        System.assertEquals('Baja', contactPrueba1.msf_MemberType__c);
        }

    @isTest static void Donante() {

        Contact contactPrueba = [SELECT msf_MemberType__c,msf_FirstEntryDateRecurringDonor__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        npe03__Recurring_Donation__c testRd = [SELECT  npe03__Contact__c FROM npe03__Recurring_Donation__c WHERE npe03__Contact__c =: contactPrueba.Id];
        Opportunity opp = [SELECT StageName FROM Opportunity WHERE npsp__Primary_Contact__c=:contactPrueba.Id LIMIT 1];
        Test.startTest();
        testRd.npe03__Contact__c = null;
        
        update testRd;

        opp.type ='Solidarity Wedding';
        update opp;
        Test.stopTest();
        Contact contactPrueba1 = [SELECT msf_MemberType__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        System.assertEquals('Donante', contactPrueba1.msf_MemberType__c);
    }
    @isTest static void Exdonante() {

        Contact contactPrueba = [SELECT msf_MemberType__c,msf_FirstEntryDateRecurringDonor__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        npe03__Recurring_Donation__c testRd = [SELECT  npe03__Contact__c FROM npe03__Recurring_Donation__c WHERE npe03__Contact__c =: contactPrueba.Id];
        Opportunity opp = [SELECT StageName FROM Opportunity WHERE npsp__Primary_Contact__c=:contactPrueba.Id LIMIT 1];
        Test.startTest();
        testRd.npe03__Contact__c = null;
        
        update testRd;
        opp.type ='Solidarity Wedding';
        opp.CloseDate = Date.newInstance(2020, 3, 9);
        update opp;
        Test.stopTest();
        Contact contactPrueba1 = [SELECT msf_MemberType__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        System.assertEquals('Exdonante', contactPrueba1.msf_MemberType__c);
    }
    @isTest static void NadaDonanteSMS() {

        Contact contactPrueba = [SELECT msf_MemberType__c,msf_FirstEntryDateRecurringDonor__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        npe03__Recurring_Donation__c testRd = [SELECT  npe03__Contact__c FROM npe03__Recurring_Donation__c WHERE npe03__Contact__c =: contactPrueba.Id];
        Opportunity opp = [SELECT StageName FROM Opportunity WHERE npsp__Primary_Contact__c=:contactPrueba.Id LIMIT 1];
        Test.startTest();
        testRd.npe03__Contact__c = null;
        
        update testRd;
        opp.type ='SMS Operator';
        update opp;
        Test.stopTest();
        Contact contactPrueba1 = [SELECT msf_MemberType__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        System.assertEquals('Nada (Donante SMS)', contactPrueba1.msf_MemberType__c);
    }
    @isTest static void Nada() {

        Contact contactPrueba = [SELECT msf_MemberType__c,msf_FirstEntryDateRecurringDonor__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        npe03__Recurring_Donation__c testRd = [SELECT  npe03__Contact__c FROM npe03__Recurring_Donation__c WHERE npe03__Contact__c =: contactPrueba.Id];
        Opportunity opp = [SELECT StageName FROM Opportunity WHERE npsp__Primary_Contact__c=:contactPrueba.Id LIMIT 1];
        Test.startTest();
        testRd.npe03__Contact__c = null;
        update testRd;
        update opp;
        Test.stopTest();
        Contact contactPrueba1 = [SELECT msf_MemberType__c FROM CONTACT WHERE LASTNAME = 'ApellidoPrueba' LIMIT 1];
        System.assertEquals('Nada', contactPrueba1.msf_MemberType__c);
    }
}