force-app/main/default/objects/Campaign/fields/msf_FinalCampaign__c.field-meta.xml
<CustomField>
    <fullName>msf_FinalCampaign__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Campaña final</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_BeginDateMSF__c.field-meta.xml
<CustomField>
    <fullName>msf_BeginDateMSF__c</fullName>
    <description>This field is to register the first time in MSF</description>
    <label>Fecha alta MSF</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_NIF__c.field-meta.xml
<CustomField>
    <fullName>msf_NIF__c</fullName>
    <label>NIF/NIE/CIF</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_RecalculateMemberType__c.field-meta.xml
<CustomField>
    <fullName>msf_RecalculateMemberType__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Recalcular tipo de miembro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Individual_Contact.recordType-meta.xml
<RecordType>
    <fullName>Individual_Contact</fullName>
    <active>true</active>
    <label>Individual Contact</label>
</RecordType>

force-app/main/default/objects/cpm__Payment_Profile__c/cpm__Payment_Profile__c.object-meta.xml
<CustomObject>
    <description>captures the payment profiles per contact/account.
such as IBAN, legacy bank account, Credit Card etc.</description>
    <label>Payment Profile</label>
    <nameField>
        <displayFormat>PP-{0}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/cpm__Active__c.field-meta.xml
<CustomField>
    <fullName>cpm__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this payment profile is active and available for use.</description>
    <inlineHelpText>Indica si este perfil de pago está activo y disponible para su uso.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/cpm__Contact__c.field-meta.xml
<CustomField>
    <fullName>cpm__Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The debitor.</description>
    <inlineHelpText>El deudor</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Payment_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/cpm__Holder_Name__c.field-meta.xml
<CustomField>
    <fullName>cpm__Holder_Name__c</fullName>
    <description>Name of the account/credit card holder.</description>
    <inlineHelpText>Nombre del titular de la cuenta / tarjeta de crédito.</inlineHelpText>
    <label>Holder Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/cpm__IBAN__c.field-meta.xml
<CustomField>
    <fullName>cpm__IBAN__c</fullName>
    <description>The bank account number in IBAN format.</description>
    <inlineHelpText>El número de cuenta bancaria en formato IBAN.</inlineHelpText>
    <label>IBAN</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/msf_HolderFirstName__c.field-meta.xml
<CustomField>
    <fullName>msf_HolderFirstName__c</fullName>
    <label>Nombre titular de la cuenta</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/msf_HolderLastName1__c.field-meta.xml
<CustomField>
    <fullName>msf_HolderLastName1__c</fullName>
    <label>Apellido 1 titular de la cuenta</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/msf_NIF__c.field-meta.xml
<CustomField>
    <fullName>msf_NIF__c</fullName>
    <label>NIF del titular</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__PaymentHub_Settings__c/fields/cpm__Auto_Create_Mandate_Recurring_Payment_DD__c.field-meta.xml
<CustomField>
    <fullName>cpm__Auto_Create_Mandate_Recurring_Payment_DD__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When true a mandate will be created when an Recurring or Single Payment is created of type Direct Debit which doesn&apos;t already has a relationship to a Mandate</description>
    <inlineHelpText>Wanneer aangevinkt zal er een mandaat aangemaakt worden wanneer een terugkerende betaling van het type automatische incasso gemaakt wordt en deze nog geen relatie met een mandaat heeft</inlineHelpText>
    <label>Autocreate mandate for Direct Debits</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cpm__PaymentHub_Settings__c/fields/cpm__Re_use_existing_mandate__c.field-meta.xml
<CustomField>
    <fullName>cpm__Re_use_existing_mandate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>re-use existing mandate if available</description>
    <label>Reuse existing mandate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cpm__PaymentHub_Settings__c/fields/cpm__Store_Informal_Logs__c.field-meta.xml
<CustomField>
    <fullName>cpm__Store_Informal_Logs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Store Informal Logs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/npe03__Recurring_Donation__c.object-meta.xml
<CustomObject>
    <description>Recurring Donations track charitable giving where a donor specifies an amount of money to be given on a regular basis.</description>
    <label>Recurring Donation</label>
    <nameField>
        <label>Recurring Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npe03__Amount__c.field-meta.xml
<CustomField>
    <fullName>npe03__Amount__c</fullName>
    <description>The amount for each installment Opportunity.</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npe03__Contact__c.field-meta.xml
<CustomField>
    <fullName>npe03__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>R00N80000002bOmREAU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npe03__Date_Established__c.field-meta.xml
<CustomField>
    <fullName>npe03__Date_Established__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>The initial inception date for this Recurring Donation. The default is the current date.</description>
    <label>Date Established</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npe03__Installment_Period__c.field-meta.xml
<CustomField>
    <fullName>npe03__Installment_Period__c</fullName>
    <description>How often you’ll receive the donations. NOTE: Changing the installment period for an existing Fixed-Length Recurring Donation may result in the loss and re-creation of open opportunities. Any data associated with those opportunities may be lost.</description>
    <inlineHelpText>Con que frecuencia se va a recibir las donaciones. Nota: Modificar la frecuencia en donaciones recurrentes sin final abierto puede resultar en la perdida o re-creación de las op. abiertas relacionadas. Información relacionada a estas op. puede perderse.</inlineHelpText>
    <label>Installment Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Bimensual</fullName>
            </value>
            <value>
                <fullName>Semestral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npe03__Installments__c.field-meta.xml
<CustomField>
    <fullName>npe03__Installments__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Number of installments (donations) you expect to receive. For Fixed-Length Recurring Donations only.</description>
    <inlineHelpText>Cantidad de cuotas (donaciones) que se esperan recibir. Para donaciones recurrentes con duración fija solamente.</inlineHelpText>
    <label>Number of Planned Installments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npe03__Open_Ended_Status__c.field-meta.xml
<CustomField>
    <fullName>npe03__Open_Ended_Status__c</fullName>
    <label>Open Ended Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/recordTypes/Recurring_donation.recordType-meta.xml
<RecordType>
    <fullName>Recurring_donation</fullName>
    <active>true</active>
    <label>Recurring donation</label>
</RecordType>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MSF_MemberType_TEST.cls
/**
* @author       Deloitte
* @date         01-2019
* @group        Accounts
* @description  test class for the MSF_MemberType_01_BATCH, MSF_MemberType_02_BATCH and MSF_MemberType_03_BATCH classes.
*/
@isTest
private class MSF_MemberType_TEST {

    @testSetup static void setup(){
        
        List<Contact> lConInsert = new List<Contact>();
        List<npe03__Recurring_Donation__c> lRDInsert = new List<npe03__Recurring_Donation__c>();
        List<Opportunity> lOppInsert = new List<Opportunity>();  
        List<cpm__Payment_Profile__c> lppInsert = new List<cpm__Payment_Profile__c>();  
        
        Map<String,Schema.RecordTypeInfo> mRtPaymentProfileInfo = Schema.SObjectType.cpm__Payment_Profile__c.getRecordTypeInfosByDeveloperName();
        Id RTIdHH = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('HH_Account').getRecordTypeId();    
        Id RTIdIndividuals = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Individual_Contact').getRecordTypeId();        
        Id RTIdDonation = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Donation').getRecordTypeId();
        Id RTIdRecurrentDonation = Schema.SObjectType.npe03__Recurring_Donation__c.getRecordTypeInfosByDeveloperName().get('Recurring_donation').getRecordTypeId();
        

        //Opportunities RecordType assigment
        List<npsp__Trigger_Handler__c> triggerHandlers = npsp.TDTM_Config_API.getCachedRecords();
        npsp__Trigger_Handler__c thCon = new npsp__Trigger_Handler__c(
            Name = 'TriggerTestMemberType',
            npsp__Class__c = 'MSF_OpportunitiesFieldsLogic_TDTM',
            npsp__Object__c = 'Opportunity',
            npsp__Trigger_Action__c = 'BeforeInsert;BeforeUpdate;AfterInsert;AfterUpdate;AfterDelete',
            npsp__Active__c = true,
            npsp__Load_Order__c = 6,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );
        triggerHandlers.add(thCon);
        upsert triggerHandlers;
        
        //Create account
        Account acc = new Account(
            Name = 'HH Account Test',
            RecordTypeId = RTIdHH
        );
        insert acc;
		//Create campaign
		Campaign camp = new Campaign(
            Name='MSFMemberTypeTESTCampName1', 
            msf_FinalCampaign__c = false
        );
        insert camp;
        
        //Create contact
        Integer numCon = 10;
        for (Integer x=0;x<numCon;x++){
            Contact c = new Contact(
                FirstName = 'FN'+x,
                LastName = 'LN'+x,
                RecordTypeId = RTIdIndividuals,
                AccountId = acc.Id,
                msf_RecalculateMemberType__c = FALSE,
                msf_BeginDateMSF__c=date.today()
            );
            lConInsert.add(c);
       
        }
        insert lConInsert;
        
        cpm.TestService.createIbanRegex();
        cpm.TestService.initTestPSPExtension();
        cpm.TestService.initTestSourceExtension();

        cpm__IbanValidation__c ibanValidation = new cpm__IbanValidation__c(
            Name = 'ES',
            cpm__RegEx__c = '^(?=[0-9A-Z]{24}$)ES\\d{22}$' 
        );
        insert ibanValidation;
        
       cpm__PaymentHub_Settings__c ps = new cpm__PaymentHub_Settings__c (
            cpm__Auto_Create_Mandate_Recurring_Payment_DD__c = false,	
            cpm__Re_use_existing_mandate__c	= false,
            cpm__Store_Informal_Logs__c	= true,
            Name = 'main'        
        );
        insert ps;
        
        //Payment profile
        Integer numPp = 10;
        for (Integer x=0;x<numPp;x++){
            cpm__Payment_Profile__c p = new cpm__Payment_Profile__c(
                cpm__IBAN__c ='ES8920631786117012691524',
                msf_HolderFirstName__c = 'contact1',
                msf_HolderLastName1__c = 'contact1',
                cpm__Holder_Name__c = 'contact1 contact1',
                msf_NIF__c = '12707968P',
                cpm__Active__c = true,
                cpm__Contact__c = lConInsert[x].Id,
                RecordTypeId = mRtPaymentProfileInfo.get('IBAN').getRecordTypeId()     
            );
            lppInsert.add(p);
        }
        insert lppInsert;
        
        //Create recurring donation
        Integer numRD = 3;
        for (Integer x=0;x<numRD;x++){
            npe03__Recurring_Donation__c rd = new npe03__Recurring_Donation__c (
                Name = 'DR'+x,
                recordTypeId = RTIdRecurrentDonation,
                npe03__Open_Ended_Status__c = 'Open',
                npe03__Installment_Period__c = 'Yearly',
                npe03__Contact__c = lConInsert[x].Id,
                npe03__Date_Established__c = date.today().addDays(1),
                npe03__Amount__c = 50,
                npe03__Installments__c = null,
                npsp4hub__Payment_Method__c = 'Direct Debit',
                npsp4hub__Payment_Processor__c  = 'PaymentHub-SEPA',
                npsp4hub__Target__c  = 'LA CAIXA CCC OPERATIVA'
            );
            lRDInsert.add(rd);
        }
        
        for (Integer x=0;x<numRD;x++){
            npe03__Recurring_Donation__c rd = new npe03__Recurring_Donation__c (
                Name = 'DR'+(x+numRD),
                recordTypeId = RTIdRecurrentDonation,
                npe03__Open_Ended_Status__c = 'Closed',
                npe03__Installment_Period__c = 'Yearly',
                npe03__Contact__c = lConInsert[x+numRD].Id,
                npe03__Date_Established__c = date.today(),
                npe03__Amount__c = 50,
                npe03__Installments__c = null,
                msf_CancelationReason__c = 'Unpaid',
                npsp4hub__Payment_Method__c = 'Direct Debit',
                npsp4hub__Payment_Processor__c  = 'PaymentHub-SEPA',
                npsp4hub__Target__c  = 'LA CAIXA CCC OPERATIVA'
            );
            lRDInsert.add(rd);
        }
        insert lRDInsert;
        
        //Create opportunities
        Integer numOpp = 3;
        for (Integer x=0;x<numOpp;x++){
            Opportunity opp = new Opportunity(
                Name = 'Opp'+(x*3),
                recordTypeId = RTIdDonation,
                AccountId = acc.Id,
                npsp__Primary_Contact__c = lConInsert[(x*3)].Id,
                CloseDate = date.today().addDays(-7),
                StageName = 'Cobrada',
	        	Amount = 10.0,
                CampaignId = camp.Id,
                npsp4hub__Payment_Method__c = 'TRANSFERENCIA BANCARIA',
                npsp4hub__Payment_Processor__c = 'PaymentHub-SEPA',
                npsp4hub__Target__c = 'BBVA',
                npsp4hub__Payment_Profile__c = lppInsert[(x*3)].Id,
                Type = 'One off Donation'           
            );
            lOppInsert.add(opp);
        }
        for (Integer x=0;x<numOpp;x++){
            Opportunity opp = new Opportunity(
                Name = 'Opp'+(x*3+1),
                recordTypeId = RTIdDonation,
                AccountId = acc.Id,
                npsp__Primary_Contact__c = lConInsert[(x*3+1)].Id,
                CloseDate = date.today().addYears(-7),
                StageName = 'Cobrada',
	        	Amount = 10.0,
                CampaignId = camp.Id,
                npsp4hub__Payment_Method__c = 'TRANSFERENCIA BANCARIA',
                npsp4hub__Payment_Processor__c = 'PaymentHub-SEPA',
                npsp4hub__Target__c = 'BBVA',
                npsp4hub__Payment_Profile__c = lppInsert[(x*3+1)].id,
                Type = 'One off Donation'           
            );
            lOppInsert.add(opp);
        }
        Opportunity oppSMS = new Opportunity(
            Name = 'OppSMS',
            recordTypeId = RTIdDonation,
            AccountId = acc.Id,
            npsp__Primary_Contact__c = lConInsert[9].Id,
            CloseDate = date.today().addYears(1),
            StageName = 'SMS Donor cerrada',
	        Amount = 10.0,
            CampaignId = camp.Id,
            npsp4hub__Payment_Method__c = 'TRANSFERENCIA BANCARIA',
            npsp4hub__Payment_Processor__c = 'PaymentHub-SEPA',
            npsp4hub__Target__c = 'LA CAIXA CCC OPERATIVA',
            npsp4hub__Payment_Profile__c = lppInsert[9].id,
            Type = 'SMS Donor'
        );
        lOppInsert.add(oppSMS);
        insert lOppInsert;
    }
    
    @isTest static void MemberType_BatchTest (){
        Test.startTest();
            MSF_MemberType_01_BATCH mta = new MSF_MemberType_01_BATCH();
            Id batchId = Database.executeBatch(mta);
        Test.stopTest();
        
        List<Contact> lCon = [SELECT Id, Name, msf_MemberType__c, 
                              (SELECT Id, CloseDate, msf_TypeFundraisingContribution__c, StageName 
                               FROM Opportunities 
                               ORDER BY CloseDate DESC
                               LIMIT 1) 
                              FROM Contact ORDER BY Name ASC];
        
        
        System.assertEquals('Socio + Donante', lCon[0].msf_MemberType__c);
        System.assertEquals('Socio + Exdonante', lCon[1].msf_MemberType__c);
        System.assertEquals('Socio', lCon[2].msf_MemberType__c);        
        System.assertEquals('Baja + Donante', lCon[3].msf_MemberType__c);
        System.assertEquals('Baja + Exdonante', lCon[4].msf_MemberType__c);
        System.assertEquals('Baja', lCon[5].msf_MemberType__c);
        System.assertEquals('Donante',lCon[6].msf_MemberType__c);
        System.assertEquals('Exdonante',lCon[7].msf_MemberType__c);
        System.assertEquals('Nada', lCon[8].msf_MemberType__c);
        System.assertEquals('Nada (Donante SMS)', lCon[9].msf_MemberType__c);
    }
    
    @isTest static void MemberType_01_SchedulerTest (){
        Test.startTest();           
            String CRON_EXP = '0 0 0 * * ? *';
            String jobId = System.schedule('MSF - MemberTypeTest',CRON_EXP, new MSF_MemberType_01_BATCH());  
        Test.stopTest();
        
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];       
        System.assert(ct != null, 'Job is not exist.');
        System.assert(ct.NextFireTime != null, 'Job is not schedule.');
    }
}