force-app/main/default/objects/Campaign/fields/msf_BetterNowExternalId__c.field-meta.xml
<CustomField>
    <fullName>msf_BetterNowExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Id externo BetterNow</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign/fields/msf_FinalCampaign__c.field-meta.xml
<CustomField>
    <fullName>msf_FinalCampaign__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Campaña final</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_CustomExternalId__c.field-meta.xml
<CustomField>
    <fullName>msf_CustomExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Id externo personalizado</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/npe03__Recurring_Donation__c.object-meta.xml
<CustomObject>
    <description>Recurring Donations track charitable giving where a donor specifies an amount of money to be given on a regular basis.</description>
    <label>Recurring Donation</label>
    <nameField>
        <label>Recurring Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npsp4hub__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>npsp4hub__Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>CreditCard</fullName>
            </value>
            <value>
                <fullName>PAGARÉS</fullName>
            </value>
            <value>
                <fullName>HERENCIAS Y LEGADOS</fullName>
            </value>
            <value>
                <fullName>FACEBOOK</fullName>
            </value>
            <value>
                <fullName>GIRO POSTAL RECEPCIÓN</fullName>
            </value>
            <value>
                <fullName>EFECTIVO ASOCIATIVO</fullName>
            </value>
            <value>
                <fullName>CUENTA ABOGADO/CUENTA PUENTE</fullName>
            </value>
            <value>
                <fullName>EN ESPECIE-SERVICIOS</fullName>
            </value>
            <value>
                <fullName>TALÓN BANCARIO ESTÁNDAR</fullName>
            </value>
            <value>
                <fullName>INICIATIVA SOLIDARIA ONLINE</fullName>
            </value>
            <value>
                <fullName>GIRO POSTAL</fullName>
            </value>
            <value>
                <fullName>EFECTIVO S.C.</fullName>
            </value>
            <value>
                <fullName>GRANT</fullName>
            </value>
            <value>
                <fullName>TALÓN NO ESTÁNDAR EXTRANJERO</fullName>
            </value>
            <value>
                <fullName>TALÓN NO ESTÁNDAR EN EUROS</fullName>
            </value>
            <value>
                <fullName>TC ONLINE</fullName>
            </value>
            <value>
                <fullName>EFECTIVO RECEPCIÓN</fullName>
            </value>
            <value>
                <fullName>PAYPAL</fullName>
            </value>
            <value>
                <fullName>TRUSTLY - TR ONLINE</fullName>
            </value>
            <value>
                <fullName>ACMA</fullName>
            </value>
            <value>
                <fullName>TRANSFERENCIA BANCARIA</fullName>
            </value>
            <value>
                <fullName>EN ESPECIE-INMOVILIZADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npsp4hub__Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>npsp4hub__Payment_Processor__c</fullName>
    <label>Payment Processor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>npsp4hub__Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PaymentHub-SEPA</fullName>
            </value>
            <value>
                <fullName>PaymentHub-Redsys</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/recordTypes/Associate.recordType-meta.xml
<RecordType>
    <fullName>Associate</fullName>
    <active>true</active>
    <label>Associate</label>
</RecordType>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_BetterNowExternalId__c.field-meta.xml
<CustomField>
    <fullName>msf_BetterNowExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Id externo BetterNow</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_CustomExternalId__c.field-meta.xml
<CustomField>
    <fullName>msf_CustomExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Id externo personalizado</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp4hub__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>npsp4hub__Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>CreditCard</fullName>
            </value>
            <value>
                <fullName>PAGARÉS</fullName>
            </value>
            <value>
                <fullName>HERENCIAS Y LEGADOS</fullName>
            </value>
            <value>
                <fullName>FACEBOOK</fullName>
            </value>
            <value>
                <fullName>GIRO POSTAL RECEPCIÓN</fullName>
            </value>
            <value>
                <fullName>EFECTIVO ASOCIATIVO</fullName>
            </value>
            <value>
                <fullName>CUENTA ABOGADO/CUENTA PUENTE</fullName>
            </value>
            <value>
                <fullName>EN ESPECIE-SERVICIOS</fullName>
            </value>
            <value>
                <fullName>TALÓN BANCARIO ESTÁNDAR</fullName>
            </value>
            <value>
                <fullName>INICIATIVA SOLIDARIA ONLINE</fullName>
            </value>
            <value>
                <fullName>GIRO POSTAL</fullName>
            </value>
            <value>
                <fullName>EFECTIVO S.C.</fullName>
            </value>
            <value>
                <fullName>GRANT</fullName>
            </value>
            <value>
                <fullName>TALÓN NO ESTÁNDAR EXTRANJERO</fullName>
            </value>
            <value>
                <fullName>TALÓN NO ESTÁNDAR EN EUROS</fullName>
            </value>
            <value>
                <fullName>TC ONLINE</fullName>
            </value>
            <value>
                <fullName>EFECTIVO RECEPCIÓN</fullName>
            </value>
            <value>
                <fullName>PAYPAL</fullName>
            </value>
            <value>
                <fullName>TRUSTLY - TR ONLINE</fullName>
            </value>
            <value>
                <fullName>ACMA</fullName>
            </value>
            <value>
                <fullName>TRANSFERENCIA BANCARIA</fullName>
            </value>
            <value>
                <fullName>EN ESPECIE-INMOVILIZADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp4hub__Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>npsp4hub__Payment_Processor__c</fullName>
    <label>Payment Processor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>npsp4hub__Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PaymentHub-SEPA</fullName>
            </value>
            <value>
                <fullName>PaymentHub-Redsys</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Donation.recordType-meta.xml
<RecordType>
    <fullName>Donation</fullName>
    <active>true</active>
    <businessProcess>Donation</businessProcess>
    <description>Donation Received</description>
    <label>Donation</label>
</RecordType>

force-app/main/default/classes/MSF_CloseRecurringDonations_Batches_Test.cls
/**
 * @description       : 
 * @author            : sheredia@omegacrmconsulting.com
 * @group             : 
 * @last modified on  : 03-22-2022
 * @last modified by  : sheredia@omegacrmconsulting.com
**/
@isTest
public with sharing class MSF_CloseRecurringDonations_Batches_Test {

    @TestSetup
    static void makeData(){
        npsp__Trigger_Handler__c thCon = new npsp__Trigger_Handler__c(
            Name = 'TriggerTestOpportunitiesFieldsLogic',
            npsp__Class__c = 'MSF_OpportunitiesFieldsLogic_TDTM',
            npsp__Object__c = 'Opportunity',
            npsp__Trigger_Action__c = 'BeforeInsert;BeforeUpdate;AfterInsert;AfterUpdate;AfterDelete',
            npsp__Active__c = true,
            npsp__Load_Order__c = 6,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );        
        upsert thCon; 
               
        Id idRDAssc = Schema.SObjectType.npe03__Recurring_Donation__c.getRecordTypeInfosByDeveloperName().get('Associate').getRecordTypeId();
        Id IdRecType = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Donation').getRecordTypeId();
        List<npe03__Recurring_Donation__c> lRecDon = new List<npe03__Recurring_Donation__c>();
        List<Contact> lcon = new List<Contact>();
        List<cpm__Payment_Profile__c> lppInsert = new List<cpm__Payment_Profile__c>();
        Map<String,Schema.RecordTypeInfo> mRtPaymentProfileInfo = Schema.SObjectType.cpm__Payment_Profile__c.getRecordTypeInfosByDeveloperName();
        
        //Campaign
        Campaign c = new Campaign(Name='MSFOpportunitiesFieldsLogicTESTName1', msf_FinalCampaign__c = false, msf_BetterNowExternalId__c = 'TEST01OFL', msf_CustomExternalId__c = 'TEST02OFL');
        insert c;
        Campaign camp1 = new Campaign(Name='CampaignRatingOppTemplado',msf_FinalCampaign__c = false, msf_BetterNowExternalId__c = 'TEST01Rating', msf_CustomExternalId__c = 'TEST02Rating');
        insert camp1;
        
        //Recurring Donation
        npe03__Recurring_Donation__c recDon = new npe03__Recurring_Donation__c(
            Name='MSF_OpportunitiesFieldsLogic_TEST_Name1',
            npsp4hub__Payment_Method__c = 'Direct Debit',
            npsp4hub__Payment_Processor__c  = 'PaymentHub-SEPA',
            npsp4hub__Target__c  = 'LA CAIXA CCC OPERATIVA'
        );
        lRecDon.add(recDon);
        
        npe03__Recurring_Donation__c recDon2 = new npe03__Recurring_Donation__c(
            Name='MSF_OpportunitiesFieldsLogic_TEST_Name2',
            RecordTypeId=idRDAssc,
            npsp4hub__Payment_Method__c = 'Direct Debit',
            npsp4hub__Payment_Processor__c  = 'PaymentHub-SEPA',
            npsp4hub__Target__c  = 'LA CAIXA CCC OPERATIVA'
        );
        lRecDon.add(recDon2);        
        insert lRecDon;
        
        //Contacts
        lcon.add(new Contact(LastName='MSF_OpportunitiesFieldsLogic_TEST_LastName1', msf_BeginDateMSF__c=date.today()));
        lcon.add(new Contact(LastName='MSF_OpportunitiesFieldsLogic_TEST_LastName2',msf_BeginDateMSF__c=date.today()));
        lcon.add(new Contact(LastName='contact1',msf_BeginDateMSF__c=date.today().addMonths(-2)));
        insert lcon;                   

    }

    @isTest static void testBatch01AsBatch() {
        ID donationID = [SELECT ID FROM npe03__Recurring_Donation__c LIMIT 1].ID;

        try{
            Test.startTest();
            Id batchJobId = Database.executeBatch(new MSF_CloseRecurringDonations_01_BATCH(new Set<ID>{donationID}), 10);
            Test.stopTest();
        }catch(Exception e){
            System.assert(false, 'Error: ' + e);
        }
    }

    @isTest static void testBatch01AsSchedule() {
        ID donationID = [SELECT ID FROM npe03__Recurring_Donation__c LIMIT 1].ID;
        MSF_CloseRecurringDonations_01_BATCH schedule = new MSF_CloseRecurringDonations_01_BATCH(new Set<ID>{donationID});
        String sch = '0 0 8 13 2 ?';

        try {
            Test.startTest();
            System.schedule('Schedule Test', sch, schedule);
            Test.stopTest();
        }catch (Exception e) {
            System.assert(false, 'Error: ' + e);
        }

    }

}