force-app/main/default/objects/Campaign/fields/msf_IsOnline__c.field-meta.xml
<CustomField>
    <fullName>msf_IsOnline__c</fullName>
    <label>Es online</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/msf_Objective__c.field-meta.xml
<CustomField>
    <fullName>msf_Objective__c</fullName>
    <label>Objetivo principal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Captación de leads</fullName>
            </value>
            <value>
                <fullName>Captación de socios o donantes</fullName>
            </value>
            <value>
                <fullName>Conversión (de lead o donante a asociado)</fullName>
            </value>
            <value>
                <fullName>Conversión (de lead o donante a socio)</fullName>
            </value>
            <value>
                <fullName>Cultivación</fullName>
            </value>
            <value>
                <fullName>Desconocido</fullName>
            </value>
            <value>
                <fullName>Informativo</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Petición difusión</fullName>
            </value>
            <value>
                <fullName>Recuperación</fullName>
            </value>
            <value>
                <fullName>Rendición de cuentas</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/msf_OutboundChannel1__c.field-meta.xml
<CustomField>
    <fullName>msf_OutboundChannel1__c</fullName>
    <label>Canal de salida 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afiliación</fullName>
            </value>
            <value>
                <fullName>Banners</fullName>
            </value>
            <value>
                <fullName>Banners web</fullName>
                <isActive>false</isActive>
                <label>Banners web</label>
            </value>
            <value>
                <fullName>Celebraciones</fullName>
            </value>
            <value>
                <fullName>D2D</fullName>
            </value>
            <value>
                <fullName>Desconocido</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Dipticos</fullName>
            </value>
            <value>
                <fullName>Display</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Emailings</fullName>
            </value>
            <value>
                <fullName>Encarte</fullName>
            </value>
            <value>
                <fullName>Espontaneos</fullName>
                <isActive>false</isActive>
                <label>Espontaneos</label>
            </value>
            <value>
                <fullName>Eventos</fullName>
            </value>
            <value>
                <fullName>Exposiciones</fullName>
            </value>
            <value>
                <fullName>F2F</fullName>
            </value>
            <value>
                <fullName>Impreso</fullName>
            </value>
            <value>
                <fullName>Iniciativa Solidaria</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Mensajería Instantánea</fullName>
            </value>
            <value>
                <fullName>Officers</fullName>
            </value>
            <value>
                <fullName>Orgánico</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Paid Search</fullName>
            </value>
            <value>
                <fullName>Pendiente digital</fullName>
            </value>
            <value>
                <fullName>Prensa o cupón</fullName>
            </value>
            <value>
                <fullName>Publicidad digital</fullName>
            </value>
            <value>
                <fullName>Publi Ext</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Redes Sociales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/msf_OwnBy__c.field-meta.xml
<CustomField>
    <fullName>msf_OwnBy__c</fullName>
    <label>Propiedad de</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Colaboraciones Estratégicas</fullName>
            </value>
            <value>
                <fullName>Desconocido</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Fidelización</fullName>
            </value>
            <value>
                <fullName>Captación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/msf_Segment__c.field-meta.xml
<CustomField>
    <fullName>msf_Segment__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One to One</fullName>
            </value>
            <value>
                <fullName>Frio individuos</fullName>
            </value>
            <value>
                <fullName>Organizaciones</fullName>
            </value>
            <value>
                <fullName>Celebraciones</fullName>
            </value>
            <value>
                <fullName>Mass donors</fullName>
            </value>
            <value>
                <fullName>Mid donors</fullName>
            </value>
            <value>
                <fullName>Desconocido</fullName>
            </value>
            <value>
                <fullName>Leads</fullName>
            </value>
            <value>
                <fullName>OCBA All</fullName>
            </value>
            <value>
                <fullName>Asociados</fullName>
            </value>
            <value>
                <fullName>Asociados España</fullName>
            </value>
            <value>
                <fullName>Sanitarios</fullName>
            </value>
            <value>
                <fullName>Terreno</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Testamentarios</fullName>
            </value>
            <value>
                <fullName>Mid+ donors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/msf_Segment__c.field-meta.xml
<CustomField>
    <fullName>msf_Segment__c</fullName>
    <label>Segmento 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MSF_CampaignMemberStatus_TEST.cls
@isTest public class MSF_CampaignMemberStatus_TEST {
    @testSetup static void setup(){
        
        //Create Trigger
        npsp__Trigger_Handler__c thCam = new npsp__Trigger_Handler__c(
            Name = 'TriggerTestCam',
            npsp__Class__c = 'MSF_CampaignLogic_TDTM',
            npsp__Object__c = 'Campaign',
            npsp__Trigger_Action__c = 'AfterInsert',
            npsp__Active__c = true,
            npsp__Load_Order__c = 1,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );
        upsert thCam;
        
        npsp__Trigger_Handler__c thCm = new npsp__Trigger_Handler__c(
                Name = 'TriggerTestCm',
                npsp__Class__c = 'MSF_CampaignMemberStatus_TDTM',
                npsp__Object__c = 'CampaignMember',
                npsp__Trigger_Action__c = 'BeforeUpdate',
                npsp__Active__c = true,
                npsp__Load_Order__c = 1,
                npsp__User_Managed__c = true,
                npsp__Asynchronous__c = false,
                npsp__Usernames_to_Exclude__c = ''
            );
        upsert thCm;
    }
    
    @isTest static void test() {
        Campaign camp = new Campaign(Name = 'Test', msf_OwnBy__c='Otros', msf_IsOnline__c='Si',
                                     msf_Objective__c='Cultivación', msf_OutboundChannel1__c='F2F', msf_Segment__c = 'Frio individuos',
                                    msf_Thematic__c='02');
        insert camp;
        
        Contact c = new Contact(FirstName = 'Test', LastName='Testa');
        insert c; 
        
        CampaignMember cm = new CampaignMember(ContactId = c.id, CampaignId = camp.id);
        insert cm; 
        
        cm.Status = 'Respondida (op abierta)';
        update cm; 
        
        cm.Status = 'Respondida (cerrada)';
        update cm;
        
        cm.Status = 'Impactado';
        update cm; 
    }
}