force-app/main/default/objects/Campaign/fields/msf_BetterNowExternalId__c.field-meta.xml
<CustomField>
    <fullName>msf_BetterNowExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Id externo BetterNow</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign/fields/msf_FinalCampaign__c.field-meta.xml
<CustomField>
    <fullName>msf_FinalCampaign__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Campaña final</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_BeginDateMSF__c.field-meta.xml
<CustomField>
    <fullName>msf_BeginDateMSF__c</fullName>
    <description>This field is to register the first time in MSF</description>
    <label>Fecha alta MSF</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_CustomExternalId__c.field-meta.xml
<CustomField>
    <fullName>msf_CustomExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Id externo personalizado</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <description>Indicates if this Contact is designated as the Primary Contact on their Account (read only).</description>
    <formula>Account.npe01__One2OneContact__c = Id</formula>
    <inlineHelpText>Este campo esta seleccionado si es el contacto principal en la cuenta. El contacto principal puede editarse en la cuenta.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_BetterNowExternalId__c.field-meta.xml
<CustomField>
    <fullName>msf_BetterNowExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Id externo BetterNow</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_CustomExternalId__c.field-meta.xml
<CustomField>
    <fullName>msf_CustomExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Id externo personalizado</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp4hub__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>npsp4hub__Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>CreditCard</fullName>
            </value>
            <value>
                <fullName>PAGARÉS</fullName>
            </value>
            <value>
                <fullName>HERENCIAS Y LEGADOS</fullName>
            </value>
            <value>
                <fullName>FACEBOOK</fullName>
            </value>
            <value>
                <fullName>GIRO POSTAL RECEPCIÓN</fullName>
            </value>
            <value>
                <fullName>EFECTIVO ASOCIATIVO</fullName>
            </value>
            <value>
                <fullName>CUENTA ABOGADO/CUENTA PUENTE</fullName>
            </value>
            <value>
                <fullName>EN ESPECIE-SERVICIOS</fullName>
            </value>
            <value>
                <fullName>TALÓN BANCARIO ESTÁNDAR</fullName>
            </value>
            <value>
                <fullName>INICIATIVA SOLIDARIA ONLINE</fullName>
            </value>
            <value>
                <fullName>GIRO POSTAL</fullName>
            </value>
            <value>
                <fullName>EFECTIVO S.C.</fullName>
            </value>
            <value>
                <fullName>GRANT</fullName>
            </value>
            <value>
                <fullName>TALÓN NO ESTÁNDAR EXTRANJERO</fullName>
            </value>
            <value>
                <fullName>TALÓN NO ESTÁNDAR EN EUROS</fullName>
            </value>
            <value>
                <fullName>TC ONLINE</fullName>
            </value>
            <value>
                <fullName>EFECTIVO RECEPCIÓN</fullName>
            </value>
            <value>
                <fullName>PAYPAL</fullName>
            </value>
            <value>
                <fullName>TRUSTLY - TR ONLINE</fullName>
            </value>
            <value>
                <fullName>ACMA</fullName>
            </value>
            <value>
                <fullName>TRANSFERENCIA BANCARIA</fullName>
            </value>
            <value>
                <fullName>EN ESPECIE-INMOVILIZADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp4hub__Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>npsp4hub__Payment_Processor__c</fullName>
    <label>Payment Processor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>npsp4hub__Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PaymentHub-SEPA</fullName>
            </value>
            <value>
                <fullName>PaymentHub-Redsys</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp4hub__Target__c.field-meta.xml
<CustomField>
    <fullName>npsp4hub__Target__c</fullName>
    <label>Target</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>npsp4hub__Payment_Processor__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>LIBERBANK (CAJASTUR)</fullName>
            </value>
            <value>
                <fullName>TRIODOS BANK</fullName>
            </value>
            <value>
                <fullName>CAIXABANK DONATIVOS</fullName>
            </value>
            <value>
                <fullName>BANKIA</fullName>
            </value>
            <value>
                <fullName>CAIXABANK INTERNA</fullName>
            </value>
            <value>
                <fullName>BANC SABADELL</fullName>
            </value>
            <value>
                <fullName>BANCO SANTANDER BIZUM</fullName>
            </value>
            <value>
                <fullName>CUENTA DOLARES</fullName>
            </value>
            <value>
                <fullName>CUENTA CUADRE-PROVISIONES</fullName>
            </value>
            <value>
                <fullName>LA CAIXA CCC OPERATIVA</fullName>
            </value>
            <value>
                <fullName>KUTXABANK</fullName>
            </value>
            <value>
                <fullName>ABANCA</fullName>
            </value>
            <value>
                <fullName>CAIXABANK FUSION BANKIA</fullName>
            </value>
            <value>
                <fullName>UNICAJA</fullName>
            </value>
            <value>
                <fullName>BBVA BCN GENERAL</fullName>
            </value>
            <value>
                <fullName>BANCO SANTANDER EMERGENCIAS</fullName>
            </value>
            <value>
                <fullName>BANCO SANTANDER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Contact for this Opportunity. If this is an individual Donation, NPSP attributes the Donation to the Primary Contact. If this is an organizational Donation, NPSP attributes a soft credit to the Primary Contact.</description>
    <inlineHelpText>El contacto principal para esta oportunidad. La función del contacto principal se mantiene sincronizada con este campo. Para donantes individuales, esto significa atribuciones por esta oportunidad.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Donation.recordType-meta.xml
<RecordType>
    <fullName>Donation</fullName>
    <active>true</active>
    <businessProcess>Donation</businessProcess>
    <description>Donation Received</description>
    <label>Donation</label>
</RecordType>

force-app/main/default/classes/MSF_UpdateRollUps_TEST.cls
@isTest
private class MSF_UpdateRollUps_TEST {

    @testSetup static void setup(){
        
        Contact c = new Contact(LastName='MSF_OpportunitiesFieldsLogic_TEST_LastName1', msf_BeginDateMSF__c=date.today());
        insert c; 
        
        Campaign camp1 = new Campaign(Name='CampaignRatingOppTemplado',msf_FinalCampaign__c = false, msf_BetterNowExternalId__c = 'TEST01Rating', msf_CustomExternalId__c = 'TEST02Rating');
        insert camp1;
        
        Id oppRT = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Donation').getRecordTypeId();
        
        //Opportunities
        Opportunity o = new Opportunity (
            Name ='RatingOpportunity1',
            RecordTypeId = oppRT,
            CampaignId = camp1.Id,
            LeadSource = 'Cupón',
            CloseDate = date.today(),
            Type= 'One off Donation',
            npsp__Primary_Contact__c = c.Id,
            Amount = 10,
            StageName='Cobrada',
            npsp4hub__Payment_Method__c = 'EFECTIVO S.C.',
            npsp4hub__Payment_Processor__c = 'PaymentHub-SEPA',
            npsp4hub__Target__c = 'LA CAIXA CCC OPERATIVA'
        );
        insert o; 
        
    }
    
    
    @isTest static void testRollUpsContact() {
        Test.startTest();
        MSF_UpdateRollUpsContact_BATCH mta = new MSF_UpdateRollUpsContact_BATCH();
        Id batchId = Database.executeBatch(mta);
        Test.stopTest();
    }
    
    @isTest static void testRollUpsAccount() {
        Test.startTest();
        MSF_UpdateRollUpsAccount_BATCH mta = new MSF_UpdateRollUpsAccount_BATCH();
        Id batchId = Database.executeBatch(mta);
        Test.stopTest();
    }
}