force-app/main/default/objects/Campaign/fields/msf_FinalCampaign__c.field-meta.xml
<CustomField>
    <fullName>msf_FinalCampaign__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Campaña final</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_BeginDateMSF__c.field-meta.xml
<CustomField>
    <fullName>msf_BeginDateMSF__c</fullName>
    <description>This field is to register the first time in MSF</description>
    <label>Fecha alta MSF</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <description>Indicates if this Contact is designated as the Primary Contact on their Account (read only).</description>
    <formula>Account.npe01__One2OneContact__c = Id</formula>
    <inlineHelpText>Este campo esta seleccionado si es el contacto principal en la cuenta. El contacto principal puede editarse en la cuenta.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_CurrentCampaign__c.field-meta.xml
<CustomField>
    <fullName>msf_CurrentCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaña actual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Campaign.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Volunteers_Campaign</value>
        </filterItems>
        <infoMessage>No es posible seleccionar una campaña de Voluntarios</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_ModificationCampaign__c.field-meta.xml
<CustomField>
    <fullName>msf_ModificationCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaña de modificación</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No es posible seleccionar una campaña de Voluntarios</errorMessage>
        <filterItems>
            <field>Campaign.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Volunteers_Campaign</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Oportunidades (Campaña de modificación)</relationshipLabel>
    <relationshipName>Oportunidades1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp4hub__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>npsp4hub__Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>CreditCard</fullName>
            </value>
            <value>
                <fullName>PAGARÉS</fullName>
            </value>
            <value>
                <fullName>HERENCIAS Y LEGADOS</fullName>
            </value>
            <value>
                <fullName>FACEBOOK</fullName>
            </value>
            <value>
                <fullName>GIRO POSTAL RECEPCIÓN</fullName>
            </value>
            <value>
                <fullName>EFECTIVO ASOCIATIVO</fullName>
            </value>
            <value>
                <fullName>CUENTA ABOGADO/CUENTA PUENTE</fullName>
            </value>
            <value>
                <fullName>EN ESPECIE-SERVICIOS</fullName>
            </value>
            <value>
                <fullName>TALÓN BANCARIO ESTÁNDAR</fullName>
            </value>
            <value>
                <fullName>INICIATIVA SOLIDARIA ONLINE</fullName>
            </value>
            <value>
                <fullName>GIRO POSTAL</fullName>
            </value>
            <value>
                <fullName>EFECTIVO S.C.</fullName>
            </value>
            <value>
                <fullName>GRANT</fullName>
            </value>
            <value>
                <fullName>TALÓN NO ESTÁNDAR EXTRANJERO</fullName>
            </value>
            <value>
                <fullName>TALÓN NO ESTÁNDAR EN EUROS</fullName>
            </value>
            <value>
                <fullName>TC ONLINE</fullName>
            </value>
            <value>
                <fullName>EFECTIVO RECEPCIÓN</fullName>
            </value>
            <value>
                <fullName>PAYPAL</fullName>
            </value>
            <value>
                <fullName>TRUSTLY - TR ONLINE</fullName>
            </value>
            <value>
                <fullName>ACMA</fullName>
            </value>
            <value>
                <fullName>TRANSFERENCIA BANCARIA</fullName>
            </value>
            <value>
                <fullName>EN ESPECIE-INMOVILIZADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp4hub__Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>npsp4hub__Payment_Processor__c</fullName>
    <label>Payment Processor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>npsp4hub__Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PaymentHub-SEPA</fullName>
            </value>
            <value>
                <fullName>PaymentHub-Redsys</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp4hub__Target__c.field-meta.xml
<CustomField>
    <fullName>npsp4hub__Target__c</fullName>
    <label>Target</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>npsp4hub__Payment_Processor__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>LIBERBANK (CAJASTUR)</fullName>
            </value>
            <value>
                <fullName>TRIODOS BANK</fullName>
            </value>
            <value>
                <fullName>CAIXABANK DONATIVOS</fullName>
            </value>
            <value>
                <fullName>BANKIA</fullName>
            </value>
            <value>
                <fullName>CAIXABANK INTERNA</fullName>
            </value>
            <value>
                <fullName>BANC SABADELL</fullName>
            </value>
            <value>
                <fullName>BANCO SANTANDER BIZUM</fullName>
            </value>
            <value>
                <fullName>CUENTA DOLARES</fullName>
            </value>
            <value>
                <fullName>CUENTA CUADRE-PROVISIONES</fullName>
            </value>
            <value>
                <fullName>LA CAIXA CCC OPERATIVA</fullName>
            </value>
            <value>
                <fullName>KUTXABANK</fullName>
            </value>
            <value>
                <fullName>ABANCA</fullName>
            </value>
            <value>
                <fullName>CAIXABANK FUSION BANKIA</fullName>
            </value>
            <value>
                <fullName>UNICAJA</fullName>
            </value>
            <value>
                <fullName>BBVA BCN GENERAL</fullName>
            </value>
            <value>
                <fullName>BANCO SANTANDER EMERGENCIAS</fullName>
            </value>
            <value>
                <fullName>BANCO SANTANDER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Contact for this Opportunity. If this is an individual Donation, NPSP attributes the Donation to the Primary Contact. If this is an organizational Donation, NPSP attributes a soft credit to the Primary Contact.</description>
    <inlineHelpText>El contacto principal para esta oportunidad. La función del contacto principal se mantiene sincronizada con este campo. Para donantes individuales, esto significa atribuciones por esta oportunidad.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp__Primary_Contact_Campaign_Member_Status__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact_Campaign_Member_Status__c</fullName>
    <description>The status NPSP uses when it creates a Campaign Member for this Opportunity&apos;s Primary Contact and Primary Campaign Source. Leave blank to default to a responded status for Closed/Won Opportunities, and a non-responded status for other Opportunities.</description>
    <inlineHelpText>El estado a usar al crear un miembro de campaña para el contacto principal y el origen de campaña de esta oportunidad. Deje en blanco para ir por defecto a un estado respondido para una op. cerrada ganada, y un estado no respondido para otras op.</inlineHelpText>
    <label>Primary Contact Campaign Member Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Donation.recordType-meta.xml
<RecordType>
    <fullName>Donation</fullName>
    <active>true</active>
    <businessProcess>Donation</businessProcess>
    <description>Donation Received</description>
    <label>Donation</label>
</RecordType>

force-app/main/default/classes/MSF_AddCampaignMember_TEST.cls
/**
* @author 		Deloitte
* @date 		05-2019
* @group 		Opportunity
* @description	test class for the MSF_OpportunitiesFieldsLogic_TDTM class.
*/
@isTest
private class MSF_AddCampaignMember_TEST {
	@testSetup static void setup(){
        npsp__Trigger_Handler__c thCon = new npsp__Trigger_Handler__c(
            Name = 'TriggerTestOpportunitiesFieldsLogic',
            npsp__Class__c = 'MSF_AddCampaignMember_TDTM',
            npsp__Object__c = 'Opportunity',
            npsp__Trigger_Action__c = 'BeforeInsert;BeforeUpdate;AfterInsert;AfterUpdate;AfterDelete',
            npsp__Active__c = true,
            npsp__Load_Order__c = 3,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );        
        upsert thCon; 
        
        //Contacts
        List<Contact> lCon = new List<Contact>(); 
        lcon.add(new Contact(LastName='MSF_AddCampaignMember_TEST_LastName1', msf_BeginDateMSF__c=date.today()));
        lcon.add(new Contact(LastName='MSF_AddCampaignMember_TEST_LastName2',msf_BeginDateMSF__c=date.today()));
        lcon.add(new Contact(LastName='contact1',msf_BeginDateMSF__c=date.today().addMonths(-2)));
        system.debug('lCon: ' + lCon);
        insert lcon;
        
        //Campaign
        List<Campaign> lCampaign = new List<Campaign>();
        lCampaign.add(new Campaign(Name='MSFAddCampaignMemberTESTCampaign1',msf_FinalCampaign__c = false));
        lCampaign.add(new Campaign(Name='MSFAddCampaignMemberTESTCampaign2',msf_FinalCampaign__c = false));
        lCampaign.add(new Campaign(Name='MSFAddCampaignMemberTESTCampaign3',msf_FinalCampaign__c = false));
        lCampaign.add(new Campaign(Name='MSFAddCampaignMemberTESTCampaign4',msf_FinalCampaign__c = false));
        lCampaign.add(new Campaign(Name='MSFAddCampaignMemberTESTCampaign5',msf_FinalCampaign__c = false));
        system.debug('lCampaign: ' + lCampaign);
        insert lCampaign;
        
        //CampaignMember
        CampaignMember cM = new CampaignMember();
        cM.ContactId 	= lCon.get(0).Id;
        cM.CampaignId 	= lCampaign.get(1).Id; 
        system.debug('cM: ' + cM);
        insert cM;
        
        //CampaignMemberStatus
        CampaignMemberStatus cMS = new CampaignMemberStatus();
        cMS.CampaignId = lCampaign.get(1).Id; 
        cMS.Label = Label.npsp.campaignMemberStatusNonResponded;
        cMS.SortOrder = 4;
        system.debug('cMS: ' + cMS);
        insert cMS; 
    }
    
    @isTest static void testAfterInsertAndAfterUpdate() {
         Opportunity o = new Opportunity (
            Name ='RatingOpportunity1',
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Donation').getRecordTypeId(),
            CloseDate = date.today(),
            Type= 'One off Donation',
            Amount = 10,
            StageName='Cobrada',
            npsp4hub__Payment_Method__c = 'EFECTIVO S.C.',
            npsp4hub__Payment_Processor__c = 'PaymentHub-SEPA',
            npsp4hub__Target__c = 'LA CAIXA CCC OPERATIVA'
        );
        o.npsp__Primary_Contact__c 	= [SELECT Id FROM Contact WHERE LastName = 'MSF_AddCampaignMember_TEST_LastName1' LIMIT 1].Id;
        o.CampaignId 				= [SELECT Id FROM Campaign WHERE Name = 'MSFAddCampaignMemberTESTCampaign1' LIMIT 1].Id;
        o.msf_CurrentCampaign__c 	= [SELECT Id FROM Campaign WHERE Name = 'MSFAddCampaignMemberTESTCampaign2' LIMIT 1].Id;
        o.msf_ModificationCampaign__c = [SELECT Id FROM Campaign WHERE Name = 'MSFAddCampaignMemberTESTCampaign3' LIMIT 1].Id;
        insert o;
        
        o.npsp__Primary_Contact_Campaign_Member_Status__c = 'TEST';
        o.msf_CurrentCampaign__c 		= [SELECT Id FROM Campaign WHERE Name = 'MSFAddCampaignMemberTESTCampaign4' LIMIT 1].Id;
        o.msf_ModificationCampaign__c 	= [SELECT Id FROM Campaign WHERE Name = 'MSFAddCampaignMemberTESTCampaign5' LIMIT 1].Id;
        update o; 
    }
}