force-app/main/default/objects/Lead/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <businessProcess>Individual Lead</businessProcess>
    <label>Individual</label>
</RecordType>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/msf_AutomatedProcessErrors__c.object-meta.xml
<CustomObject>
    <label>Automated Process Error</label>
    <nameField>
        <displayFormat>ERROR_{YYYY}-{MM}-{DD}_{0000000000}</displayFormat>
        <label>Identificador de error</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automated Process Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>msf_ErrorMessage__c</fullName>
    <label>Mensaje de error</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_FieldsErrors__c.field-meta.xml
<CustomField>
    <fullName>msf_FieldsErrors__c</fullName>
    <label>Campos con errores</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_Process__c.field-meta.xml
<CustomField>
    <fullName>msf_Process__c</fullName>
    <label>Proceso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_RecordId__c.field-meta.xml
<CustomField>
    <fullName>msf_RecordId__c</fullName>
    <label>Id registro</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_StatusCode__c.field-meta.xml
<CustomField>
    <fullName>msf_StatusCode__c</fullName>
    <label>Código de error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MSF_IncompleteLeadManagement_BATCH.cls
/**
* @author 		Deloitte
* @date 		11-2018
* @group 		Contact
* @description	Lead management. Delete leads that have been created 30 days before
* 				and there isn't from assosiative 
*/
global without sharing class MSF_IncompleteLeadManagement_BATCH implements Database.Batchable<sObject>, Schedulable{

    global final String query; 
    
    global MSF_IncompleteLeadManagement_BATCH (){
         
        String queryStep = '';
        queryStep  = 'SELECT Id ';												
        queryStep += 'FROM Lead ';
        queryStep += 'WHERE RecordType.DeveloperName = \'Individual\' ';
        queryStep += 'AND LeadSource != \'SMS\' ';
        if(Test.IsRunningTest()){
            queryStep += 'AND CreatedDate <= TODAY';    
        }else{
            queryStep += 'AND CreatedDate < LAST_N_DAYS:30 ';
        }      
        
        query = queryStep;         
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(SchedulableContext SC){ 
    	MSF_IncompleteLeadManagement_BATCH myBatch = new MSF_IncompleteLeadManagement_BATCH();
        Id batchJobId = Database.executeBatch(myBatch, 500);
    }
	
    global void execute(Database.BatchableContext BC, List<Lead> scope){
        
        // DML statements        
        if(!scope.isEmpty()){        	
            Database.DeleteResult[] drList = Database.delete(scope, false);
            
            //*
            List<msf_AutomatedProcessErrors__c> lAPE = new List<msf_AutomatedProcessErrors__c>(); 
            
            for (Database.DeleteResult dr : drList) { // Iterate through each returned result
                if (!dr.isSuccess()) {  // Operation failed, so get all errors                                   
                    for(Database.Error err : dr.getErrors()) {
                        msf_AutomatedProcessErrors__c tempAPE = new msf_AutomatedProcessErrors__c(msf_Process__c = 'MSF_IncompleteLeadManagement', msf_RecordId__c = scope.get(drList.indexOf(dr)).Id, msf_StatusCode__c = String.valueOf(err.getStatusCode()), msf_FieldsErrors__c = String.valueOf(err.getFields()), msf_ErrorMessage__c = err.getMessage());
                        lAPE.add(tempAPE);
                    }
                }            
            }  
            
            if(!lAPE.isEmpty()){
                insert lAPE;
            }//*/   
        }
    }
    
    global void finish(Database.BatchableContext BC){
        System.debug('END BATCH - MSF_IncompleteLeadManagement_BATCH');
    }  
}