force-app/main/default/objects/cpm__Payment_Schedule__c/cpm__Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>Object is used to schedule Payment Runs in the future</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{000000000}</displayFormat>
        <label>Payment Schedule Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>cpm__Collection_Date__c</fullName>
    <description>Date when the payments should be collected by the bank. This is only used for direct debit methods with FinDock as processor (PaymentHub-BACS, PaymentHub-SEPA, etc.)</description>
    <label>Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>cpm__PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>CreditCard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Run_Date__c.field-meta.xml
<CustomField>
    <fullName>cpm__Run_Date__c</fullName>
    <description>Date when payment schedule is run.</description>
    <inlineHelpText>¿Cuándo debe ejecutarse este pago?</inlineHelpText>
    <label>Run Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Status__c.field-meta.xml
<CustomField>
    <fullName>cpm__Status__c</fullName>
    <description>Set status to &apos;Scheduled&apos; unless otherwise instructed.</description>
    <inlineHelpText>El estado actual de este elemento programado</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Generating</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/msf_IntegrationsControl__c.object-meta.xml
<CustomObject>
    <label>Importaciones e integraciones</label>
    <nameField>
        <displayFormat>CI-{0}</displayFormat>
        <label>Control Integraciones Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Importaciones e integraciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_IntegrationsControl__c/fields/msf_EndDatePeriod__c.field-meta.xml
<CustomField>
    <fullName>msf_EndDatePeriod__c</fullName>
    <label>Fecha fin periodo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/fields/msf_ProcessType__c.field-meta.xml
<CustomField>
    <fullName>msf_ProcessType__c</fullName>
    <label>Tipo de proceso</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAP Finance</fullName>
            </value>
            <value>
                <fullName>SAP HR</fullName>
            </value>
            <value>
                <fullName>Altiria</fullName>
            </value>
            <value>
                <fullName>Talones</fullName>
            </value>
            <value>
                <fullName>Fichero entrada único</fullName>
            </value>
            <value>
                <fullName>SAP ITR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/fields/msf_StartDatePeriod__c.field-meta.xml
<CustomField>
    <fullName>msf_StartDatePeriod__c</fullName>
    <label>Fecha inicio periodo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/fields/msf_Status__c.field-meta.xml
<CustomField>
    <fullName>msf_Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>En progreso</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Finalización correcta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/fields/msf_TypologyPaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>msf_TypologyPaymentMethod__c</fullName>
    <label>Tipologia forma de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <label>Orden Bancaria</label>
            </value>
            <value>
                <fullName>01</fullName>
                <label>Tarjeta Crédito</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Talones standard</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Transferencias</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Varios</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>TC On line</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Cheques varios</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Devolución OB</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>En especie - Servicio</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>En especie - inmovilizado</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Sellos Correo</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Trustly On line</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>PayPal</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Iniciativa solidaria On line</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Efectivo asociativo</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>ACMA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/recordTypes/SAPFinance.recordType-meta.xml
<RecordType>
    <fullName>SAPFinance</fullName>
    <active>true</active>
    <label>SAP Finanzas</label>
</RecordType>

force-app/main/default/classes/MSF_PaymentScheduleLogic_TDTM.cls
/**
* @author       Deloitte
* @date         10-2019
* @group        PaymentSchedule.
* @description  Logic of some fields and processes.
*/
global without sharing class MSF_PaymentScheduleLogic_TDTM extends npsp.TDTM_Runnable {

    /*******************************************************************************************************
    * @description  Trigger Handler on PaymentSchedule that handles the logic of some fields and deletions. 
    * @param        listNew the list of PaymentSchedule from trigger new. 
    * @param        listOld the list of PaymentSchedule from trigger old. 
    * @param        triggerAction which trigger event (BeforeInsert, AfterInsert, etc.). 
    * @param        objResult the describe for PaymentSchedule
    * @return       dmlWrapper. 
    ********************************************************************************************************/
    global override npsp.TDTM_Runnable.DmlWrapper run(List<SObject> newlist, List<SObject> oldlist, npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {    
        
        List<cpm__Payment_Schedule__c> lNewPS = (List<cpm__Payment_Schedule__c>) newlist;
        List<cpm__Payment_Schedule__c> lOldPS = (List<cpm__Payment_Schedule__c>) oldlist;
        
        List<msf_IntegrationsControl__c> icToInsert = new List<sObject>(); 
        
        //After Update
        if(triggerAction == npsp.TDTM_Runnable.Action.AfterUpdate){
            Id recordTypeIdSAPFinance = Schema.SObjectType.msf_IntegrationsControl__c.getRecordTypeInfosByDeveloperName().get('SAPFinance').getRecordTypeId();
            
            for (cpm__Payment_Schedule__c ps : lNewPS) {
                if (ps.cpm__Status__c == 'Done') {
               		if (ps.cpm__PaymentMethod__c == 'Direct Debit') {
                    	msf_IntegrationsControl__c ic = new msf_IntegrationsControl__c(); 
                        ic.msf_ProcessType__c = 'SAP Finance'; 
                        ic.msf_StartDatePeriod__c = ps.cpm__Collection_Date__c;
                        ic.msf_EndDatePeriod__c = ps.cpm__Collection_Date__c; 
                        ic.msf_TypologyPaymentMethod__c = '00'; 
                        ic.msf_Status__c = 'Nuevo'; 
                        ic.RecordTypeId = recordTypeIdSAPFinance;
                        
                        icToInsert.add(ic);

                    }
                    else if (ps.cpm__PaymentMethod__c == 'CreditCard') {
                        msf_IntegrationsControl__c ic = new msf_IntegrationsControl__c(); 
                        ic.msf_ProcessType__c = 'SAP Finance'; 
                        ic.msf_StartDatePeriod__c = ps.cpm__Run_Date__c;
                        ic.msf_EndDatePeriod__c = ps.cpm__Run_Date__c; 
                        ic.msf_TypologyPaymentMethod__c = '01'; 
                        ic.msf_Status__c = 'Nuevo'; 
                        ic.RecordTypeId = recordTypeIdSAPFinance;
                        
                        icToInsert.add(ic); 
                    }     
                }
            }
            
        }
        
        if (icToInsert.isEmpty()) {
         	return null;    
        }
		
		//DML Operations
        npsp.TDTM_Runnable.dmlWrapper dmlWrapper = new npsp.TDTM_Runnable.DmlWrapper();
        dmlWrapper.objectsToInsert.addAll((List<msf_IntegrationsControl__c>) icToInsert);
        
        return dmlWrapper; 
    }
    
}