force-app/main/default/objects/cpm__Payment_Schedule__c/cpm__Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>Object is used to schedule Payment Runs in the future</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{000000000}</displayFormat>
        <label>Payment Schedule Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>cpm__Collection_Date__c</fullName>
    <description>Date when the payments should be collected by the bank. This is only used for direct debit methods with FinDock as processor (PaymentHub-BACS, PaymentHub-SEPA, etc.)</description>
    <label>Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>cpm__Payment_Processor__c</fullName>
    <label>Payment Processor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>cpm__PaymentMethod__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PaymentHub-SEPA</fullName>
            </value>
            <value>
                <fullName>PaymentHub-Redsys</fullName>
            </value>
            <value>
                <fullName>PaymentHub-MT940</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>cpm__PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>CreditCard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Run_Date__c.field-meta.xml
<CustomField>
    <fullName>cpm__Run_Date__c</fullName>
    <description>Date when payment schedule is run.</description>
    <inlineHelpText>¿Cuándo debe ejecutarse este pago?</inlineHelpText>
    <label>Run Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Selection_Date__c.field-meta.xml
<CustomField>
    <fullName>cpm__Selection_Date__c</fullName>
    <description>Installments with a due date on or before the selection date are collected if all other processing details match.</description>
    <inlineHelpText>La fecha en que se seleccionan los Pagos recurrentes dentro de esta ejecución del proceso de cobros</inlineHelpText>
    <label>Selection Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Source__c.field-meta.xml
<CustomField>
    <fullName>cpm__Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PaymentHub</fullName>
            </value>
            <value>
                <fullName>PaymentHub-for-NPSP</fullName>
                <default>true</default>
                <label>PaymentHub-for-NPSP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Status__c.field-meta.xml
<CustomField>
    <fullName>cpm__Status__c</fullName>
    <description>Set status to &apos;Scheduled&apos; unless otherwise instructed.</description>
    <inlineHelpText>El estado actual de este elemento programado</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Generating</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/msf_IntegrationsControl__c.object-meta.xml
<CustomObject>
    <label>Importaciones e integraciones</label>
    <nameField>
        <displayFormat>CI-{0}</displayFormat>
        <label>Control Integraciones Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Importaciones e integraciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_IntegrationsControl__c/fields/msf_EndDatePeriod__c.field-meta.xml
<CustomField>
    <fullName>msf_EndDatePeriod__c</fullName>
    <label>Fecha fin periodo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/fields/msf_ProcessType__c.field-meta.xml
<CustomField>
    <fullName>msf_ProcessType__c</fullName>
    <label>Tipo de proceso</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAP Finance</fullName>
            </value>
            <value>
                <fullName>SAP HR</fullName>
            </value>
            <value>
                <fullName>Altiria</fullName>
            </value>
            <value>
                <fullName>Talones</fullName>
            </value>
            <value>
                <fullName>Fichero entrada único</fullName>
            </value>
            <value>
                <fullName>SAP ITR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/fields/msf_StartDatePeriod__c.field-meta.xml
<CustomField>
    <fullName>msf_StartDatePeriod__c</fullName>
    <label>Fecha inicio periodo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/fields/msf_Status__c.field-meta.xml
<CustomField>
    <fullName>msf_Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>En progreso</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Finalización correcta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/recordTypes/SingleEntryFile.recordType-meta.xml
<RecordType>
    <fullName>SingleEntryFile</fullName>
    <active>true</active>
    <description>Económico + Cappta + Prospectos</description>
    <label>Fichero de entrada único</label>
</RecordType>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MSF_IntegrationsControl_TEST.cls
/**
* @author       Deloitte
* @date         01-2019
* @group        Campaign
* @description  test class for the MSF_IntegrationsControl_SCHED, MSF_IntegrationsControl_SCHED_02 class.
*/
@isTest
private class MSF_IntegrationsControl_TEST {
    
    @testSetup static void setup(){
        npsp__Trigger_Handler__c thCon = new npsp__Trigger_Handler__c(
            Name = 'TriggerT',
            npsp__Class__c = 'MSF_IntegrationsControl_TDTM',
            npsp__Object__c = 'msf_IntegrationsControl__c',
            npsp__Trigger_Action__c = 'BeforeInsert;BeforeUpdate;AfterInsert;AfterUpdate;AfterDelete',
            npsp__Active__c = true,
            npsp__Load_Order__c = 1,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );       
        upsert thCon; 
    }
    
    public static String CRON_EXP = '0 0 0 L * ? *';
    
   @isTest public static void test() {
        Test.startTest();        	
        String jobId = System.schedule('ScheduledApexTest',CRON_EXP, new MSF_IntegrationsControl_SCHED());  
        
        String jobId2 = System.schedule('ScheduledApexTest-2',CRON_EXP, new MSF_IntegrationsControl_SCHED_02());        
        Test.stopTest();
    }
    
    @isTest public static void test_2() {        
        cpm__Payment_Schedule__c ps = new cpm__Payment_Schedule__c(); 
        ps.cpm__Status__c = 'Verified';
        ps.cpm__PaymentMethod__c = 'CreditCard'; 
        ps.cpm__Run_Date__c = Date.today(); 
        ps.cpm__Selection_Date__c = Date.today(); 
        ps.cpm__Target__c = 'none'; 
        ps.cpm__Collection_Date__c = Date.today();
        ps.cpm__Payment_Processor__c = 'PaymentHub-MT940'; 
        ps.cpm__Source__c = 'PaymentHub'; 
        insert ps; 
        
        msf_IntegrationsControl__c ic = new msf_IntegrationsControl__c(); 
        ic.RecordTypeId = Schema.SObjectType.msf_IntegrationsControl__c.getRecordTypeInfosByDeveloperName().get('SingleEntryFile').getRecordTypeId();
        ic.msf_Status__c = 'Nuevo';
        ic.msf_StartDatePeriod__c = Date.today();
        ic.msf_EndDatePeriod__c = Date.today().addDays(1);
        ic.msf_ProcessType__c = 'Fichero entrada único'; 
        insert ic; 
    }
    
    @isTest public static void test_3() {        
        
        msf_IntegrationsControl__c ic = new msf_IntegrationsControl__c(); 
        ic.RecordTypeId = Schema.SObjectType.msf_IntegrationsControl__c.getRecordTypeInfosByName().get('Talones').getRecordTypeId();
        ic.msf_Status__c = 'Nuevo';
        ic.msf_StartDatePeriod__c = Date.today();
        ic.msf_EndDatePeriod__c = Date.today().addDays(1);
        ic.msf_ProcessType__c = 'Talones'; 
        insert ic; 
        
        List<msf_IntegrationsControl__c> icList = [SELECT Id FROM msf_IntegrationsControl__c WHERE msf_ProcessType__c = 'SAP Finance'];
        
        System.assertEquals(1, icList.size());
    }
}