force-app/main/default/objects/cpm__Payment_Schedule__c/cpm__Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>Object is used to schedule Payment Runs in the future</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{000000000}</displayFormat>
        <label>Payment Schedule Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>cpm__Collection_Date__c</fullName>
    <description>Date when the payments should be collected by the bank. This is only used for direct debit methods with FinDock as processor (PaymentHub-BACS, PaymentHub-SEPA, etc.)</description>
    <label>Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>cpm__Payment_Processor__c</fullName>
    <label>Payment Processor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>cpm__PaymentMethod__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PaymentHub-SEPA</fullName>
            </value>
            <value>
                <fullName>PaymentHub-Redsys</fullName>
            </value>
            <value>
                <fullName>PaymentHub-MT940</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>cpm__PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>CreditCard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Run_Date__c.field-meta.xml
<CustomField>
    <fullName>cpm__Run_Date__c</fullName>
    <description>Date when payment schedule is run.</description>
    <inlineHelpText>¿Cuándo debe ejecutarse este pago?</inlineHelpText>
    <label>Run Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Selection_Date__c.field-meta.xml
<CustomField>
    <fullName>cpm__Selection_Date__c</fullName>
    <description>Installments with a due date on or before the selection date are collected if all other processing details match.</description>
    <inlineHelpText>La fecha en que se seleccionan los Pagos recurrentes dentro de esta ejecución del proceso de cobros</inlineHelpText>
    <label>Selection Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Source__c.field-meta.xml
<CustomField>
    <fullName>cpm__Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PaymentHub</fullName>
            </value>
            <value>
                <fullName>PaymentHub-for-NPSP</fullName>
                <default>true</default>
                <label>PaymentHub-for-NPSP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Status__c.field-meta.xml
<CustomField>
    <fullName>cpm__Status__c</fullName>
    <description>Set status to &apos;Scheduled&apos; unless otherwise instructed.</description>
    <inlineHelpText>El estado actual de este elemento programado</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Generating</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MSF_PaymentScheduleLogic_TEST.cls
/**
* @author       Deloitte
* @date         01-2019
* @group        Campaign
* @description  test class for the MSF_PaymentScheduleLogic_TDTM class.
*/
@isTest
private class MSF_PaymentScheduleLogic_TEST {
	
    @testSetup static void setup(){
        //Create Trigger
        npsp__Trigger_Handler__c thCon = new npsp__Trigger_Handler__c(
            Name = 'test',
            npsp__Class__c = 'MSF_PaymentScheduleLogic_TDTM',
            npsp__Object__c = 'cpm__Payment_Schedule__c',
            npsp__Trigger_Action__c = 'AfterUpdate',
            npsp__Active__c = true,
            npsp__Load_Order__c = 1,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );        
        insert thCon; 
    }
    
    @isTest static void test() {
        cpm__Payment_Schedule__c ps = new cpm__Payment_Schedule__c(); 
        ps.cpm__PaymentMethod__c = 'Direct Debit'; 
        ps.cpm__Payment_Processor__c = 'PaymentHub-SEPA'; 
        ps.cpm__Source__c = 'PaymentHub'; 
        ps.cpm__Target__c = 'None';
        ps.cpm__Run_Date__c = Date.today();
        ps.cpm__Selection_Date__c = Date.today();
        ps.cpm__Collection_Date__c = Date.today().addMonths(3);
        insert ps; 
        
        test.startTest();
        
        ps.cpm__Status__c = 'Done'; 
        ps.cpm__PaymentMethod__c = 'Direct Debit'; 
        update ps; 
        
        ps.cpm__Status__c = 'Done'; 
        ps.cpm__PaymentMethod__c = 'CreditCard'; 
        update ps; 
        
        test.stopTest();
        
    }
    
}