force-app/main/default/objects/cpm__Payment_Schedule__c/cpm__Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>Object is used to schedule Payment Runs in the future</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{000000000}</displayFormat>
        <label>Payment Schedule Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Status__c.field-meta.xml
<CustomField>
    <fullName>cpm__Status__c</fullName>
    <description>Set status to &apos;Scheduled&apos; unless otherwise instructed.</description>
    <inlineHelpText>El estado actual de este elemento programado</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Generating</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/msf_IntegrationsControl__c.object-meta.xml
<CustomObject>
    <label>Importaciones e integraciones</label>
    <nameField>
        <displayFormat>CI-{0}</displayFormat>
        <label>Control Integraciones Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Importaciones e integraciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_IntegrationsControl__c/fields/msf_EndDatePeriod__c.field-meta.xml
<CustomField>
    <fullName>msf_EndDatePeriod__c</fullName>
    <label>Fecha fin periodo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/fields/msf_ProcessType__c.field-meta.xml
<CustomField>
    <fullName>msf_ProcessType__c</fullName>
    <label>Tipo de proceso</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAP Finance</fullName>
            </value>
            <value>
                <fullName>SAP HR</fullName>
            </value>
            <value>
                <fullName>Altiria</fullName>
            </value>
            <value>
                <fullName>Talones</fullName>
            </value>
            <value>
                <fullName>Fichero entrada único</fullName>
            </value>
            <value>
                <fullName>SAP ITR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/fields/msf_StartDatePeriod__c.field-meta.xml
<CustomField>
    <fullName>msf_StartDatePeriod__c</fullName>
    <label>Fecha inicio periodo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/fields/msf_Status__c.field-meta.xml
<CustomField>
    <fullName>msf_Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>En progreso</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Finalización correcta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/fields/msf_TypologyPaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>msf_TypologyPaymentMethod__c</fullName>
    <label>Tipologia forma de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <label>Orden Bancaria</label>
            </value>
            <value>
                <fullName>01</fullName>
                <label>Tarjeta Crédito</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Talones standard</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Transferencias</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Varios</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>TC On line</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Cheques varios</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Devolución OB</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>En especie - Servicio</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>En especie - inmovilizado</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Sellos Correo</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Trustly On line</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>PayPal</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Iniciativa solidaria On line</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Efectivo asociativo</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>ACMA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/recordTypes/SingleEntryFile.recordType-meta.xml
<RecordType>
    <fullName>SingleEntryFile</fullName>
    <active>true</active>
    <description>Económico + Cappta + Prospectos</description>
    <label>Fichero de entrada único</label>
</RecordType>

force-app/main/default/classes/MSF_IntegrationsControl_TDTM.cls
/**
* @author 		Deloitte
* @date 		11-2018
* @group 		msf_IntegrationsControl__c donation.
* @description	msf_IntegrationsControl__c
*/
global without sharing class MSF_IntegrationsControl_TDTM extends npsp.TDTM_Runnable{

    global override npsp.TDTM_Runnable.DmlWrapper run(List<SObject> newlist, List<SObject> oldlist, npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {    
     	
        //Attributes
        List<msf_IntegrationsControl__c> lNewIC = (List<msf_IntegrationsControl__c>) newlist;        
        List<msf_IntegrationsControl__c> lOldIC = (List<msf_IntegrationsControl__c>) oldlist;
        Map<Id, msf_IntegrationsControl__c> mOldIC = new Map<Id, msf_IntegrationsControl__c>();
        if(lOldIC != null){            
            mOldIC.putAll(lOldIC);
        }
        /*
        Id recordTypeIdSingleEntryFile = Schema.SObjectType.msf_IntegrationsControl__c.getRecordTypeInfosByDeveloperName().get('SingleEntryFile').getRecordTypeId();
        
        //Before Insert || Before Update
        if(triggerAction == npsp.TDTM_Runnable.Action.BeforeInsert || triggerAction == npsp.TDTM_Runnable.Action.BeforeUpdate){
            
            //PaymentSchedules;
            List<String> paymentSchedulesStatus = new List<String>{'Done', 'Scheduled'}; 
			List<cpm__Payment_Schedule__c> paymentSchedulesList = [SELECT Id, cpm__Status__c FROM cpm__Payment_Schedule__c 
                                                                   WHERE cpm__Status__c NOT IN :paymentSchedulesStatus]; 
        	
            if (paymentSchedulesList.isEmpty() == false) {
                
                for (msf_IntegrationsControl__c ic: lNewIC) {
                    if (ic.RecordTypeId == recordTypeIdSingleEntryFile) {
                        if ((ic.msf_Status__c == 'Nuevo' || ic.msf_Status__c == 'En progreso') && Test.isRunningTest() == false) {
                            ic.addError(System.Label.MSF_INTEGRATIONS_CONTROL_BLOCKED);
                        }
                    }
                }
                
            }
        }     
    	*/
         
        Id recordTypeIdTalones = Schema.SObjectType.msf_IntegrationsControl__c.getRecordTypeInfosByName().get('Talones').getRecordTypeId();
        Id recordTypeIdSAPFinance = Schema.SObjectType.msf_IntegrationsControl__c.getRecordTypeInfosByName().get('SAP Finanzas').getRecordTypeId();
        List<msf_IntegrationsControl__c> icToInsert = new List<sObject>(); 

        if(triggerAction == npsp.TDTM_Runnable.Action.AfterInsert){
            
            for (msf_IntegrationsControl__c ic : lNewIC) {
                if (ic.RecordTypeId == recordTypeIdTalones) {
                    msf_IntegrationsControl__c newIC = new msf_IntegrationsControl__c(); 
                    newIC.msf_ProcessType__c = 'SAP Finance'; 
                    newIC.msf_StartDatePeriod__c = ic.msf_StartDatePeriod__c;
                    newIC.msf_EndDatePeriod__c = ic.msf_EndDatePeriod__c; 
                    newIC.msf_TypologyPaymentMethod__c = '02'; 
                    newIC.msf_Status__c = 'Nuevo'; 
                    newIC.RecordTypeId = recordTypeIdSAPFinance;
                    
                    icToInsert.add(newIC);
                }
            }
        }
     
        if (icToInsert.isEmpty()) {
         	return null;    
        }
        
        //DML Operations
        npsp.TDTM_Runnable.dmlWrapper dmlWrapper = new npsp.TDTM_Runnable.DmlWrapper();
        dmlWrapper.objectsToInsert.addAll((List<msf_IntegrationsControl__c>) icToInsert);
        
        return dmlWrapper; 
    }
}