force-app/main/default/objects/cpm__Payment_Profile__c/cpm__Payment_Profile__c.object-meta.xml
<CustomObject>
    <description>captures the payment profiles per contact/account.
such as IBAN, legacy bank account, Credit Card etc.</description>
    <label>Payment Profile</label>
    <nameField>
        <displayFormat>PP-{0}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/cpm__Contact__c.field-meta.xml
<CustomField>
    <fullName>cpm__Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The debitor.</description>
    <inlineHelpText>El deudor</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Payment_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/cpm__Holder_Name__c.field-meta.xml
<CustomField>
    <fullName>cpm__Holder_Name__c</fullName>
    <description>Name of the account/credit card holder.</description>
    <inlineHelpText>Nombre del titular de la cuenta / tarjeta de crédito.</inlineHelpText>
    <label>Holder Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/cpm__IBAN__c.field-meta.xml
<CustomField>
    <fullName>cpm__IBAN__c</fullName>
    <description>The bank account number in IBAN format.</description>
    <inlineHelpText>El número de cuenta bancaria en formato IBAN.</inlineHelpText>
    <label>IBAN</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/msf_LastModificationChannel__c.field-meta.xml
<CustomField>
    <fullName>msf_LastModificationChannel__c</fullName>
    <label>Último canal de modificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_ModificationChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/msf_ModificationChannel__c.field-meta.xml
<CustomField>
    <fullName>msf_ModificationChannel__c</fullName>
    <inlineHelpText>Es obligatorio informar este campo cada vez que modifique el registro. Tras guardar los cambios el campo queda vacío para la próxima modificación.</inlineHelpText>
    <label>Canal de modificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_ModificationChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_GDPRLog__c/msf_GDPRLog__c.object-meta.xml
<CustomObject>
    <label>Registro RGPD</label>
    <nameField>
        <displayFormat>RGPD_LOG_{0000000000}</displayFormat>
        <label>Nombre de Registro RGPD</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registros RGPD</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_GDPRLog__c/fields/msf_ModificationChannel__c.field-meta.xml
<CustomField>
    <fullName>msf_ModificationChannel__c</fullName>
    <label>Canal de modificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_ModificationChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/msf_EconomicProcessUser__c.field-meta.xml
<CustomField>
    <fullName>msf_EconomicProcessUser__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check only for economic.process@barcelona.msf.org</inlineHelpText>
    <label>Economic process user</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/MSF_ModificationChannel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Teléfonos At. Socio</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Asociativo</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono One-to-One</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Telemarketing</fullName>
    </customValue>
    <customValue>
        <fullName>Centro de Preferencias</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud Page</fullName>
    </customValue>
    <customValue>
        <fullName>Correo Postal</fullName>
    </customValue>
    <customValue>
        <fullName>E-mail Asociativo</fullName>
    </customValue>
    <customValue>
        <fullName>E-mails At. Socio</fullName>
    </customValue>
    <customValue>
        <fullName>E-mails One-to-One</fullName>
    </customValue>
    <customValue>
        <fullName>F2F</fullName>
        <label>F2F Tablet</label>
    </customValue>
    <customValue>
        <fullName>Fax</fullName>
    </customValue>
    <customValue>
        <fullName>Fichero Bancario</fullName>
    </customValue>
    <customValue>
        <fullName>Single entry file</fullName>
        <label>Fichero de importación</label>
    </customValue>
    <customValue>
        <fullName>Formularios Web</fullName>
    </customValue>
    <customValue>
        <fullName>Generación Aplicación</fullName>
    </customValue>
    <customValue>
        <fullName>Mensajería Instantánea</fullName>
    </customValue>
    <customValue>
        <fullName>Mi Perfil</fullName>
    </customValue>
    <customValue>
        <fullName>n/a</fullName>
    </customValue>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>Nuevo</label>
    </customValue>
    <customValue>
        <fullName>Presencial</fullName>
    </customValue>
    <customValue>
        <fullName>RRHH</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
        <isActive>false</isActive>
        <label>Email</label>
    </customValue>
    <customValue>
        <fullName>Teléfono SAS</fullName>
        <isActive>false</isActive>
        <label>Teléfono SAS</label>
    </customValue>
    <masterLabel>Canal de modificación</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MSF_PaymentProfileGDPRLog_TDTM.cls
/**
* @author 		Deloitte
* @date 		05-2019
* @group 		Payment Profile
* @description	Trigger Handler that create GDPR logs
*/

global without sharing class MSF_PaymentProfileGDPRLog_TDTM extends npsp.TDTM_Runnable{

    /*******************************************************************************************************
    * @description	Trigger Handler on Payment profile that manage the changes that must be registered by the GDPR rules.
    * @param 		listNew the list of Payment Profiles from trigger new.  
    * @param 		listOld the list of Payment Profiles from trigger old. 
    * @param 		triggerAction which trigger event (BeforeInsert, AfterInsert, etc.). 
    * @param 		objResult the describe for Payment Profiles.
    * @return 		dmlWrapper. 
    ********************************************************************************************************/
    global override npsp.TDTM_Runnable.DmlWrapper run(List<SObject> newlist, List<SObject> oldlist, npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {    
    	
        //Current User
        Boolean bEcoUser = [SELECT Id, msf_EconomicProcessUser__c FROM User WHERE Id =: UserInfo.getUserId()].msf_EconomicProcessUser__c;
        
        //Attributes
        List<cpm__Payment_Profile__c> lNewPP = (List<cpm__Payment_Profile__c>) newlist;      
		List<cpm__Payment_Profile__c> lOldPP = (List<cpm__Payment_Profile__c>) oldlist;
        Map<Id, cpm__Payment_Profile__c> mOldPP = new Map<Id, cpm__Payment_Profile__c>();
        if(lOldPP != null){            
            mOldPP.putAll(lOldPP);
        }    
        
        MSF_SharedMethods_UTIL sm = new MSF_SharedMethods_UTIL();
   		
        List<msf_GDPRLog__c> lLogsToInsert = new List<msf_GDPRLog__c>();
        
        Map<String,Schema.sObjectField> mObjectFields = cpm__Payment_Profile__c.sObjectType.getDescribe().fields.getMap();
        
        Set<String> sfields = new Set<String>{'cpm__Holder_Name__c','cpm__IBAN__c','cpm__Token__c'};

            
        //Actions
                        
        /*** BEFORE INSERT & BEFORE UPDATE ***/
        if(triggerAction == npsp.TDTM_Runnable.Action.BeforeInsert || triggerAction == npsp.TDTM_Runnable.Action.BeforeUpdate) {	
            for(cpm__Payment_Profile__c pp : lNewPP){       
                if(pp.msf_ModificationChannel__c != null){
                    if(bEcoUser){
                        pp.msf_ModificationChannel__c = 'Fichero Bancario';
                    }
                    pp.msf_LastModificationChannel__c = pp.msf_ModificationChannel__c;
                    pp.msf_ModificationChannel__c = null;    
                }				
            }   
        }    
        
        /*** AFTER INSERT ***/
        if(triggerAction == npsp.TDTM_Runnable.Action.AfterInsert) {	
            for(cpm__Payment_Profile__c pp : lNewPP){            	 
            	msf_GDPRLog__c l = sm.createLog(pp, null, UserInfo.getUserId(), pp.cpm__Contact__c, pp.Id, true, false, sfields, mObjectFields);  
                if (l != null){
                	lLogsToInsert.add(l);     
                }
            }   
        }
        /*** AFTER UPDATE ***/
        if(triggerAction == npsp.TDTM_Runnable.Action.AfterUpdate) {	
        	for(cpm__Payment_Profile__c pp : lNewPP){
            	msf_GDPRLog__c l = sm.createLog(pp, mOldPP.get(pp.Id), UserInfo.getUserId(), pp.cpm__Contact__c, pp.Id, false, false, sfields, mObjectFields);  
                if (l != null){
                	lLogsToInsert.add(l);     
                }
            } 	   
        } 
        /*** AFTER DELETE ***/
        if(triggerAction == npsp.TDTM_Runnable.Action.AfterDelete) {	
        	for(cpm__Payment_Profile__c pp : lOldPP){
            	msf_GDPRLog__c l = sm.createLog(pp, null, UserInfo.getUserId(), pp.cpm__Contact__c, pp.Id, false, true, null, null);  
                if (l != null){
                	lLogsToInsert.add(l);     
                }
            } 
        }
        
        /*** DML OPERATIONS ***/
        if(lLogsToInsert.isEmpty()){
            return null;
        }
        
        npsp.TDTM_Runnable.dmlWrapper dmlWrapper = new npsp.TDTM_Runnable.DmlWrapper();
        dmlWrapper.objectsToInsert.addAll((List<msf_GDPRLog__c>) lLogsToInsert);        
        
        return dmlWrapper; 
    } 

}