force-app/main/default/objects/Case/recordTypes/MSF_IS_Celebrations.recordType-meta.xml
<RecordType>
    <fullName>MSF_IS_Celebrations</fullName>
    <active>true</active>
    <businessProcess>MSF_Celebrations</businessProcess>
    <label>IS - Celebraciones</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/MSF_IS_Solidarity_Initiative.recordType-meta.xml
<RecordType>
    <fullName>MSF_IS_Solidarity_Initiative</fullName>
    <active>true</active>
    <businessProcess>MSF_SolidarityInitiative</businessProcess>
    <label>IS - Iniciativa Solidaria</label>
</RecordType>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MSF_CaseLogic_TEST.cls
/**
* @author 		Deloitte
* @date 		10-2018
* @group 		Case
* @description	test class for the MSF_CaseLogic_TDTM clases.
*/
@isTest
private class MSF_CaseLogic_TEST {
    @testSetup static void setup(){  
        
        ID CaseCelebrationsRT = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('MSF_IS_Celebrations').getRecordTypeId();
        ID CaseSolidarityInitiative_RT = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('MSF_IS_Solidarity_Initiative').getRecordTypeId();

        List<Case> listCaseTest1 = new List<Case>();
        List<String> listStatusCase = new List<String>{'Pendiente envio Info','Enviar info extra', 'Enviar prespuesto', 'Pendiente info para diseño',
            'Enviar diseño', 'Enviar datos de pago', 'Enviar a Imprenta', 'Enviar email agradecimiento', 
            'Petición IS Recibida', 'Pendiente respuesta', 'Llamada Programada', 'Pendiente OK  presupuesto', 
            'Pendiente aprobación diseño', 'Pendiente justificante', 'Rechazada'
            };
                
        npsp__Trigger_Handler__c thCase = new npsp__Trigger_Handler__c(
            Name = 'TriggerTestCaseLogic',
            npsp__Class__c = 'MSF_CaseLogic_TDTM',
            npsp__Object__c = 'Case',
            npsp__Trigger_Action__c = 'AfterInsert;AfterUpdate',
            npsp__Active__c = true,
            npsp__Load_Order__c = 3,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );        
        upsert thCase; 
        
        for(Integer i = 0; i <= listStatusCase.size()-1; i++){
            Case c = new Case(
                Status = listStatusCase[i],
                Origin = 'BETTERNOW',
                RecordTypeId = (i == listStatusCase.size() ? CaseSolidarityInitiative_RT : CaseCelebrationsRT)
            );
            listCaseTest1.add(c);
        }
        
        Insert listCaseTest1;
       
    }
    
    @isTest static void createTaskForOwnerCase(){
        List<Task> ts = [SELECT Id FROM Task];
        System.assertEquals(14, ts.size());
    } 
    
}