force-app/main/default/objects/msf_AutomatedProcessErrors__c/msf_AutomatedProcessErrors__c.object-meta.xml
<CustomObject>
    <label>Automated Process Error</label>
    <nameField>
        <displayFormat>ERROR_{YYYY}-{MM}-{DD}_{0000000000}</displayFormat>
        <label>Identificador de error</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automated Process Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>msf_ErrorMessage__c</fullName>
    <label>Mensaje de error</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_FieldsErrors__c.field-meta.xml
<CustomField>
    <fullName>msf_FieldsErrors__c</fullName>
    <label>Campos con errores</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_Process__c.field-meta.xml
<CustomField>
    <fullName>msf_Process__c</fullName>
    <label>Proceso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_RecordId__c.field-meta.xml
<CustomField>
    <fullName>msf_RecordId__c</fullName>
    <label>Id registro</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_StatusCode__c.field-meta.xml
<CustomField>
    <fullName>msf_StatusCode__c</fullName>
    <label>Código de error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MSF_DisableCampaigns_BATCH.cls
/**
* @author       Deloitte
* @date         04-2019
* @group        Campaign
* @description  Disable campaigns based on their end date
*/
global without sharing class MSF_DisableCampaigns_BATCH implements Database.Batchable<sObject>, Schedulable{
    
    global final String query; 
    global static final Integer BATCH_SIZE = 200;
    
    global MSF_DisableCampaigns_BATCH (){
        String queryStep = '';
        queryStep = 'SELECT Id, IsActive ';
        queryStep += 'FROM Campaign ';
        queryStep += 'WHERE (IsActive = true AND EndDate != null AND EndDate <= TODAY) OR '; 
        queryStep += '(IsActive = false AND StartDate != null AND (StartDate = TODAY OR StartDate = TOMORROW) AND EndDate != TOMORROW)';
        query = queryStep; 
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(SchedulableContext SC){ 
        MSF_DisableCampaigns_BATCH myBatch = new MSF_DisableCampaigns_BATCH();
        Id batchJobId = Database.executeBatch(myBatch, BATCH_SIZE);
    }

    global void execute(Database.BatchableContext BC, List<Campaign> scope){

        for(Campaign s : scope){   
            if (s.IsActive == true) {
                s.Status = 'Completed';
            }
            else {
                s.Status = 'In Progress';
            }
            s.IsActive = !s.IsActive; 
        }       
    
        // DML statements
        Database.SaveResult[] srList = Database.update(scope, false); 
        
        //*
        List<msf_AutomatedProcessErrors__c> lAPE = new List<msf_AutomatedProcessErrors__c>(); 
        
        for (Database.SaveResult sr : srList) { // Iterate through each returned result
            if (!sr.isSuccess()) {  // Operation failed, so get all errors                                   
                for(Database.Error err : sr.getErrors()) {
                    msf_AutomatedProcessErrors__c tempAPE = new msf_AutomatedProcessErrors__c(msf_Process__c = 'MSF_DisableCampaigns_BATCH', msf_RecordId__c = scope.get(srList.indexOf(sr)).Id, msf_StatusCode__c = String.valueOf(err.getStatusCode()), msf_FieldsErrors__c = String.valueOf(err.getFields()), msf_ErrorMessage__c = err.getMessage());
                    lAPE.add(tempAPE);
                }
            } 
        }  
        
        if(!lAPE.isEmpty()){
            insert lAPE;
        }//*/ 
    }
    
    global void finish(Database.BatchableContext BC){
        System.debug('END BATCH - MSF_DisableCampaigns_BATCH');
    }   
    
}