force-app/main/default/objects/msf_AutomatedProcessErrors__c/msf_AutomatedProcessErrors__c.object-meta.xml
<CustomObject>
    <label>Automated Process Error</label>
    <nameField>
        <displayFormat>ERROR_{YYYY}-{MM}-{DD}_{0000000000}</displayFormat>
        <label>Identificador de error</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automated Process Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>msf_ErrorMessage__c</fullName>
    <label>Mensaje de error</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_FieldsErrors__c.field-meta.xml
<CustomField>
    <fullName>msf_FieldsErrors__c</fullName>
    <label>Campos con errores</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_Process__c.field-meta.xml
<CustomField>
    <fullName>msf_Process__c</fullName>
    <label>Proceso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_RecordId__c.field-meta.xml
<CustomField>
    <fullName>msf_RecordId__c</fullName>
    <label>Id registro</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_StatusCode__c.field-meta.xml
<CustomField>
    <fullName>msf_StatusCode__c</fullName>
    <label>Código de error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Donation.recordType-meta.xml
<RecordType>
    <fullName>Donation</fullName>
    <active>true</active>
    <businessProcess>Donation</businessProcess>
    <description>Donation Received</description>
    <label>Donation</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <businessProcess>Grant</businessProcess>
    <description>Grant Received</description>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Historical.recordType-meta.xml
<RecordType>
    <fullName>Historical</fullName>
    <active>true</active>
    <businessProcess>Donation</businessProcess>
    <label>Historical</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/In_Kind_Gift.recordType-meta.xml
<RecordType>
    <fullName>In_Kind_Gift</fullName>
    <active>true</active>
    <businessProcess>In-Kind Gift</businessProcess>
    <description>Goods or Services received as In-Kind</description>
    <label>In-Kind Gift</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Legacy.recordType-meta.xml
<RecordType>
    <fullName>Legacy</fullName>
    <active>true</active>
    <businessProcess>Testamentos%26Herencias</businessProcess>
    <description>Opportunity committed without Payment</description>
    <label>Legacy</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Matching_Gift.recordType-meta.xml
<RecordType>
    <fullName>Matching_Gift</fullName>
    <active>true</active>
    <businessProcess>Matching Gift</businessProcess>
    <description>Matching Donation from an Donor&apos;s Employer or other Organization</description>
    <label>Matching Gift</label>
</RecordType>

force-app/main/default/classes/MSF_UpdateRollUpsAccount_BATCH.cls
global without sharing class MSF_UpdateRollUpsAccount_BATCH implements Database.Batchable<sObject>{

    global final String query; 
    
    global MSF_UpdateRollUpsAccount_BATCH (){
         
        String queryStep = '';
        queryStep  = 'SELECT Id ';
        queryStep += 'FROM Account ';
        query = queryStep;         
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
	
    global void execute(Database.BatchableContext BC, List<Account> scope){
		
        
        List<Account> lUpdateAccounts = new List<Account>();
        Set<ID> sAccIds = new Map<ID,Account>(scope).keyset();
        
        for(AggregateResult ar : [SELECT AccountId account, COUNT(Id) NumberOfClosedOpps 
                                  FROM Opportunity 
                                  WHERE AccountId IN: sAccIds
                                  AND RecordType.DeveloperName IN ('Donation','Grant','Historical','In_Kind_Gift','Legacy','Matching_Gift') 
                                  AND IsWon = TRUE 
                                  AND Amount > 0 
                                  GROUP BY AccountId])
        {
        	Account tempAcc = new Account(
                Id = (Id)ar.get('account'),
                npo02__NumberOfClosedOpps__c = (Double)ar.get('NumberOfClosedOpps')
            );	
            lUpdateAccounts.add(tempAcc);  
        }
        
        // DML statement
        Database.SaveResult[] srList = Database.update(lUpdateAccounts, false);
        
        
        //*
        List<msf_AutomatedProcessErrors__c> lAPE = new List<msf_AutomatedProcessErrors__c>(); 
        
        for (Database.SaveResult sr : srList) { // Iterate through each returned result
            if (!sr.isSuccess()) {  // Operation failed, so get all errors                                   
                for(Database.Error err : sr.getErrors()) {
                    msf_AutomatedProcessErrors__c tempAPE = new msf_AutomatedProcessErrors__c(msf_Process__c = 'MSF_UpdateRollUpsAccount_BATCH', msf_RecordId__c = scope.get(srList.indexOf(sr)).Id, msf_StatusCode__c = String.valueOf(err.getStatusCode()), msf_FieldsErrors__c = String.valueOf(err.getFields()), msf_ErrorMessage__c = String.valueOf(err.getMessage()).abbreviate(255));
                    lAPE.add(tempAPE);
                }
            }            
        }  
        
        if(!lAPE.isEmpty()){
            insert lAPE;
        }//*/
    }
    
    global void finish(Database.BatchableContext BC){
        System.debug('END BATCH - MSF_UpdateRollUpsAccount_BATCH');
    }
}