force-app/main/default/objects/msf_AutomatedProcessErrors__c/msf_AutomatedProcessErrors__c.object-meta.xml
<CustomObject>
    <label>Automated Process Error</label>
    <nameField>
        <displayFormat>ERROR_{YYYY}-{MM}-{DD}_{0000000000}</displayFormat>
        <label>Identificador de error</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automated Process Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>msf_ErrorMessage__c</fullName>
    <label>Mensaje de error</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_FieldsErrors__c.field-meta.xml
<CustomField>
    <fullName>msf_FieldsErrors__c</fullName>
    <label>Campos con errores</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_Process__c.field-meta.xml
<CustomField>
    <fullName>msf_Process__c</fullName>
    <label>Proceso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_RecordId__c.field-meta.xml
<CustomField>
    <fullName>msf_RecordId__c</fullName>
    <label>Id registro</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_StatusCode__c.field-meta.xml
<CustomField>
    <fullName>msf_StatusCode__c</fullName>
    <label>Código de error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/npe03__Recurring_Donation__c.object-meta.xml
<CustomObject>
    <description>Recurring Donations track charitable giving where a donor specifies an amount of money to be given on a regular basis.</description>
    <label>Recurring Donation</label>
    <nameField>
        <label>Recurring Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/msf_CancelationReason__c.field-meta.xml
<CustomField>
    <fullName>msf_CancelationReason__c</fullName>
    <label>Motivo de cancelación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1 OBS/TCS devueltas con otras aportaciones impagadas en los últimos 2 años</fullName>
            </value>
            <value>
                <fullName>2 OBS devueltas es la primera de su historia</fullName>
            </value>
            <value>
                <fullName>2 TCS devueltas</fullName>
            </value>
            <value>
                <fullName>3 Obs/Tcs Devueltas</fullName>
            </value>
            <value>
                <fullName>Baja argumentada</fullName>
            </value>
            <value>
                <fullName>Baja asociativo</fullName>
                <isActive>false</isActive>
                <label>Baja asociativo</label>
            </value>
            <value>
                <fullName>Baja económica argumentada</fullName>
            </value>
            <value>
                <fullName>Baja e llamada de Bienvenida</fullName>
            </value>
            <value>
                <fullName>Baja en llamada de aumentos</fullName>
            </value>
            <value>
                <fullName>Baja en llamada de gestión de devoluciones</fullName>
            </value>
            <value>
                <fullName>Baja por cambio de titular</fullName>
            </value>
            <value>
                <fullName>Baja por impago orden Socio</fullName>
            </value>
            <value>
                <fullName>Baja proactiva Coronavirus</fullName>
            </value>
            <value>
                <fullName>Baja reactiva Coronavirus</fullName>
            </value>
            <value>
                <fullName>Baja socio temporal</fullName>
            </value>
            <value>
                <fullName>Voluntary withdrawal</fullName>
                <label>Baja voluntaria</label>
            </value>
            <value>
                <fullName>Cambio de domicilio</fullName>
            </value>
            <value>
                <fullName>Captador F2F-TLMK me informó mal</fullName>
            </value>
            <value>
                <fullName>Cierre/Cambio cuenta bancaria</fullName>
            </value>
            <value>
                <fullName>Colabora con otra ONG</fullName>
            </value>
            <value>
                <fullName>Decepcionado</fullName>
            </value>
            <value>
                <fullName>Desacuerdo aborto</fullName>
            </value>
            <value>
                <fullName>Desacuerdo colaboración  con Empresas</fullName>
            </value>
            <value>
                <fullName>Desacuerdo destino ayuda</fullName>
            </value>
            <value>
                <fullName>Desacuerdo gestión financiera</fullName>
            </value>
            <value>
                <fullName>Desacuerdo operaciones mediterraneo</fullName>
            </value>
            <value>
                <fullName>Desacuerdo política captacion de fondos</fullName>
            </value>
            <value>
                <fullName>Desacuerdo política intervención</fullName>
            </value>
            <value>
                <fullName>Duplicado</fullName>
            </value>
            <value>
                <fullName>Económico</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
                <label>Impago</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/msf_PendingCloseRecurring__c.field-meta.xml
<CustomField>
    <fullName>msf_PendingCloseRecurring__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pendiente baja</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npe03__Open_Ended_Status__c.field-meta.xml
<CustomField>
    <fullName>npe03__Open_Ended_Status__c</fullName>
    <label>Open Ended Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MSF_CloseRecurringDonations_02_BATCH.cls
/**
* @author 		Deloitte
* @date 		02-2020
* @group 		Recurring Donations
* @description	Close Recurring Donations in batch mode
*/
global without sharing class MSF_CloseRecurringDonations_02_BATCH implements Database.Batchable<sObject>{

    global final String query;
    global Set<ID> lIdsRecurringDonations;
    
    global MSF_CloseRecurringDonations_02_BATCH (){
            String queryStep = 'SELECT Id ';
            queryStep += 'FROM npe03__Recurring_Donation__c ';
        	queryStep += 'WHERE msf_PendingCloseRecurring__c = TRUE';
            query = queryStep;

    }    

	global MSF_CloseRecurringDonations_02_BATCH (Set<ID> lIds){
         
        lIdsRecurringDonations = lIds;         
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        Database.QueryLocator dbQuery;
        
        if(lIdsRecurringDonations!=null && lIdsRecurringDonations.isEmpty()==FALSE)
        {
        	//Batch called from trigger MSF_OpportunitiesFieldsLogic_TDTM
            dbQuery = Database.getQueryLocator([SELECT Id, msf_PendingCloseRecurring__c 
                                               FROM npe03__Recurring_Donation__c WHERE Id IN :lIdsRecurringDonations]);
        }
        else
        {
            //Batch called from Scheduled
            dbQuery = Database.getQueryLocator(query);
        }
        return dbQuery;
        
    }
	

    global void execute(Database.BatchableContext BC, List<npe03__Recurring_Donation__c> scope){
		
        
        List<npe03__Recurring_Donation__c> lRecurringDonationsToUpdate = new List<npe03__Recurring_Donation__c>();
        for (npe03__Recurring_Donation__c rC : scope) {
            rC.npe03__Open_Ended_Status__c = 'Closed'; 
            rC.msf_CancelationReason__c = 'Unpaid'; 
            rC.msf_PendingCloseRecurring__c= FALSE; 
            lRecurringDonationsToUpdate.add(rC);
        }
       
        
        // DML statement
        Database.SaveResult[] srList = Database.update(lRecurringDonationsToUpdate, false);
        
        
        //*
        List<msf_AutomatedProcessErrors__c> lAPE = new List<msf_AutomatedProcessErrors__c>(); 
        
        for (Database.SaveResult sr : srList) { // Iterate through each returned result
            if (!sr.isSuccess()) {  // Operation failed, so get all errors                                   
                for(Database.Error err : sr.getErrors()) {
                    msf_AutomatedProcessErrors__c tempAPE = new msf_AutomatedProcessErrors__c(msf_Process__c = 'MSF_CloseRecurringDonations_02_BATCH', msf_RecordId__c = scope.get(srList.indexOf(sr)).Id, msf_StatusCode__c = String.valueOf(err.getStatusCode()), msf_FieldsErrors__c = String.valueOf(err.getFields()), msf_ErrorMessage__c = String.valueOf(err.getMessage()).abbreviate(255));
                    lAPE.add(tempAPE);
                }
            }            
        }  
        
        if(!lAPE.isEmpty()){
            insert lAPE;
        }//*/
    }
    
    global void finish(Database.BatchableContext BC){
        System.debug('END BATCH - MSF_CloseRecurringDonations_02_BATCH');
    }  
}