force-app/main/default/objects/msf_LeadSourceMasterData__c/msf_LeadSourceMasterData__c.object-meta.xml
<CustomObject>
    <label>Maestro de datos de LeadSource</label>
    <nameField>
        <displayFormat>MD_LS_{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maestro de datos de LeadSource</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_LeadSourceMasterData__c/fields/msf_LeadSource3__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource3__c</fullName>
    <label>Canal de entrada 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource3</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_QuotaModification__c/msf_QuotaModification__c.object-meta.xml
<CustomObject>
    <label>Modificación de cuota</label>
    <nameField>
        <label>Nombre de Modificación de cuota</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modificaciones de cuota</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_QuotaModification__c/fields/msf_LeadSource1__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource1__c</fullName>
    <label>Canal de entrada 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_QuotaModification__c/fields/msf_LeadSource2__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource2__c</fullName>
    <label>Canal de entrada 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/npe03__Recurring_Donation__c.object-meta.xml
<CustomObject>
    <description>Recurring Donations track charitable giving where a donor specifies an amount of money to be given on a regular basis.</description>
    <label>Recurring Donation</label>
    <nameField>
        <label>Recurring Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/msf_LeadSource1__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource1__c</fullName>
    <label>Canal de entrada 1 inicial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/msf_LeadSource2__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource2__c</fullName>
    <label>Canal de entrada 2 inicial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/msf_LeadSource3__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource3__c</fullName>
    <label>Canal de entrada 3 inicial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource3</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npsp4hub__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>npsp4hub__Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>CreditCard</fullName>
            </value>
            <value>
                <fullName>PAGARÉS</fullName>
            </value>
            <value>
                <fullName>HERENCIAS Y LEGADOS</fullName>
            </value>
            <value>
                <fullName>FACEBOOK</fullName>
            </value>
            <value>
                <fullName>GIRO POSTAL RECEPCIÓN</fullName>
            </value>
            <value>
                <fullName>EFECTIVO ASOCIATIVO</fullName>
            </value>
            <value>
                <fullName>CUENTA ABOGADO/CUENTA PUENTE</fullName>
            </value>
            <value>
                <fullName>EN ESPECIE-SERVICIOS</fullName>
            </value>
            <value>
                <fullName>TALÓN BANCARIO ESTÁNDAR</fullName>
            </value>
            <value>
                <fullName>INICIATIVA SOLIDARIA ONLINE</fullName>
            </value>
            <value>
                <fullName>GIRO POSTAL</fullName>
            </value>
            <value>
                <fullName>EFECTIVO S.C.</fullName>
            </value>
            <value>
                <fullName>GRANT</fullName>
            </value>
            <value>
                <fullName>TALÓN NO ESTÁNDAR EXTRANJERO</fullName>
            </value>
            <value>
                <fullName>TALÓN NO ESTÁNDAR EN EUROS</fullName>
            </value>
            <value>
                <fullName>TC ONLINE</fullName>
            </value>
            <value>
                <fullName>EFECTIVO RECEPCIÓN</fullName>
            </value>
            <value>
                <fullName>PAYPAL</fullName>
            </value>
            <value>
                <fullName>TRUSTLY - TR ONLINE</fullName>
            </value>
            <value>
                <fullName>ACMA</fullName>
            </value>
            <value>
                <fullName>TRANSFERENCIA BANCARIA</fullName>
            </value>
            <value>
                <fullName>EN ESPECIE-INMOVILIZADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npsp4hub__Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>npsp4hub__Payment_Processor__c</fullName>
    <label>Payment Processor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>npsp4hub__Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PaymentHub-SEPA</fullName>
            </value>
            <value>
                <fullName>PaymentHub-Redsys</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp4hub__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>npsp4hub__Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>CreditCard</fullName>
            </value>
            <value>
                <fullName>PAGARÉS</fullName>
            </value>
            <value>
                <fullName>HERENCIAS Y LEGADOS</fullName>
            </value>
            <value>
                <fullName>FACEBOOK</fullName>
            </value>
            <value>
                <fullName>GIRO POSTAL RECEPCIÓN</fullName>
            </value>
            <value>
                <fullName>EFECTIVO ASOCIATIVO</fullName>
            </value>
            <value>
                <fullName>CUENTA ABOGADO/CUENTA PUENTE</fullName>
            </value>
            <value>
                <fullName>EN ESPECIE-SERVICIOS</fullName>
            </value>
            <value>
                <fullName>TALÓN BANCARIO ESTÁNDAR</fullName>
            </value>
            <value>
                <fullName>INICIATIVA SOLIDARIA ONLINE</fullName>
            </value>
            <value>
                <fullName>GIRO POSTAL</fullName>
            </value>
            <value>
                <fullName>EFECTIVO S.C.</fullName>
            </value>
            <value>
                <fullName>GRANT</fullName>
            </value>
            <value>
                <fullName>TALÓN NO ESTÁNDAR EXTRANJERO</fullName>
            </value>
            <value>
                <fullName>TALÓN NO ESTÁNDAR EN EUROS</fullName>
            </value>
            <value>
                <fullName>TC ONLINE</fullName>
            </value>
            <value>
                <fullName>EFECTIVO RECEPCIÓN</fullName>
            </value>
            <value>
                <fullName>PAYPAL</fullName>
            </value>
            <value>
                <fullName>TRUSTLY - TR ONLINE</fullName>
            </value>
            <value>
                <fullName>ACMA</fullName>
            </value>
            <value>
                <fullName>TRANSFERENCIA BANCARIA</fullName>
            </value>
            <value>
                <fullName>EN ESPECIE-INMOVILIZADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp4hub__Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>npsp4hub__Payment_Processor__c</fullName>
    <label>Payment Processor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>npsp4hub__Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PaymentHub-SEPA</fullName>
            </value>
            <value>
                <fullName>PaymentHub-Redsys</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Donation.recordType-meta.xml
<RecordType>
    <fullName>Donation</fullName>
    <active>true</active>
    <businessProcess>Donation</businessProcess>
    <description>Donation Received</description>
    <label>Donation</label>
</RecordType>

force-app/main/default/globalValueSets/MSF_LeadSource1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cloud page</fullName>
    </customValue>
    <customValue>
        <fullName>Correo postal sin cupón</fullName>
    </customValue>
    <customValue>
        <fullName>Cupón</fullName>
    </customValue>
    <customValue>
        <fullName>Email a Bodas</fullName>
    </customValue>
    <customValue>
        <fullName>Email a Empresas</fullName>
    </customValue>
    <customValue>
        <fullName>Email a Iniciativas Solidarias</fullName>
    </customValue>
    <customValue>
        <fullName>Email a officers Mid Donors</fullName>
    </customValue>
    <customValue>
        <fullName>Email a One to one</fullName>
    </customValue>
    <customValue>
        <fullName>Email a SAS</fullName>
    </customValue>
    <customValue>
        <fullName>Email Director/a General</fullName>
    </customValue>
    <customValue>
        <fullName>Email herencias</fullName>
    </customValue>
    <customValue>
        <fullName>Email Presidente/a MSF</fullName>
    </customValue>
    <customValue>
        <fullName>Entidad financiera</fullName>
    </customValue>
    <customValue>
        <fullName>Eventos</fullName>
    </customValue>
    <customValue>
        <fullName>Mensajería Instantánea</fullName>
    </customValue>
    <customValue>
        <fullName>n/a</fullName>
    </customValue>
    <customValue>
        <fullName>Otro</fullName>
    </customValue>
    <customValue>
        <fullName>Persona a persona</fullName>
    </customValue>
    <customValue>
        <fullName>Personal con tablet</fullName>
    </customValue>
    <customValue>
        <fullName>Plataforma iniciativas</fullName>
    </customValue>
    <customValue>
        <fullName>Redes Sociales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono campaña</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Herencias y Legados</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Officers</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono SAS</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono web</fullName>
    </customValue>
    <customValue>
        <fullName>Telemarketing</fullName>
    </customValue>
    <customValue>
        <fullName>Web campaña</fullName>
    </customValue>
    <customValue>
        <fullName>Web MSF</fullName>
    </customValue>
    <description>LeadSource Master Data</description>
    <masterLabel>LeadSource1</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/MSF_LeadSource2.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Correo postal sin cupón</fullName>
    </customValue>
    <customValue>
        <fullName>Cupón</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Entidad financiera</fullName>
    </customValue>
    <customValue>
        <fullName>Formulario web</fullName>
    </customValue>
    <customValue>
        <fullName>Mensajería Instantánea</fullName>
    </customValue>
    <customValue>
        <fullName>Otro</fullName>
    </customValue>
    <customValue>
        <fullName>Persona a persona</fullName>
    </customValue>
    <customValue>
        <fullName>Redes Sociales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono campaña</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Herencias y Legados</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfonos Officers</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfonos SAS</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono web</fullName>
    </customValue>
    <customValue>
        <fullName>Telemarketing</fullName>
    </customValue>
    <description>LeadSource Master Data</description>
    <masterLabel>LeadSource2</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/MSF_LeadSource3.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Correo postal</fullName>
    </customValue>
    <customValue>
        <fullName>Entidad financiera</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Personal</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono</fullName>
    </customValue>
    <customValue>
        <fullName>Otro</fullName>
    </customValue>
    <description>LeadSource Master Data</description>
    <masterLabel>LeadSource3</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MSF_QuotaModificationFieldsLogic_TEST.cls
/**
* @author 		Deloitte
* @date 		03-2019
* @group 		Recurring donation.
* @description	test class for the MSF_QuotaModificationFieldsLogic_TDTM class.
*/
@isTest
private class MSF_QuotaModificationFieldsLogic_TEST {
    @testSetup static void setup(){
        npsp__Trigger_Handler__c thCon = new npsp__Trigger_Handler__c(
            Name = 'TriggerTestQuotaModificationFieldsLogic',
            npsp__Class__c = 'MSF_QuotaModificationFieldsLogic_TDTM',
            npsp__Object__c = 'msf_QuotaModification__c',
            npsp__Trigger_Action__c = 'BeforeInsert;BeforeUpdate;AfterInsert;AfterUpdate',
            npsp__Active__c = true,
            npsp__Load_Order__c = 3,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );        
        upsert thCon; 
        
        List<msf_LeadSourceMasterData__c> lLeadSourceMD = new List<msf_LeadSourceMasterData__c>();
        List<String> leadSource = leadSource1Desc();
        List<String> leadSource2 = leadSource2Desc();
        List<String> leadSource3 = leadSource3Desc();
        for(Integer x = 0; x < leadSource.size(); x ++){
            msf_LeadSourceMasterData__c data = new msf_LeadSourceMasterData__c(msf_LeadSource1__c = leadSource[x], 
                                                                               msf_LeadSource2__c = LeadSource2[math.mod(x, leadSource2.size())], 
                                                                               msf_LeadSource3__c = LeadSource3[math.mod(x, leadSource3.size())]);
            lLeadSourceMD.add(data);
        }
        insert lLeadSourceMD;
        
        npe03__Recurring_Donation__c RecurringDonation = new npe03__Recurring_Donation__c(Name='MSFOpportunitiesFieldsLogicTESTLastName');
        RecurringDonation.npsp4hub__Payment_Method__c = 'Direct Debit';
        RecurringDonation.npsp4hub__Payment_Processor__c  = 'PaymentHub-SEPA';
        RecurringDonation.npsp4hub__Target__c  = 'LA CAIXA CCC OPERATIVA';
        insert RecurringDonation;
        
        msf_QuotaModification__c quotaMod = new msf_QuotaModification__c(Name='MSFQuotaModificationFieldsLogicTESTName2');
        quotaMod.msf_RecurringDonation__c =  [SELECT Id FROM npe03__Recurring_Donation__c
                                              WHERE Name = 'MSFOpportunitiesFieldsLogicTESTLastName' LIMIT 1].Id;
        insert quotaMod;
        
        Campaign camp = new Campaign(Name='MSFQuotaModificationFieldsLogicTESTName1',msf_FinalCampaign__c = false);
        insert camp;
    }
    @isTest static void insertQuotaModificationFieldsLogic(){
        msf_QuotaModification__c quotaMod = new msf_QuotaModification__c(Name='MSFQuotaModificationFieldsLogicTESTName1',
                                                                         msf_CampaignInfluence__c = [SELECT Id FROM Campaign
                                                                                                     WHERE Name = 'MSFQuotaModificationFieldsLogicTESTName1' LIMIT 1].Id,
                                                                         msf_RecurringDonation__c = [SELECT Id FROM npe03__Recurring_Donation__c
                                                                                                     WHERE Name = 'MSFOpportunitiesFieldsLogicTESTLastName' LIMIT 1].Id,
                                                                         msf_LeadSource1__c = leadSource1Desc()[0]
                                                                        );
        
        insert quotaMod;
        
        npe03__Recurring_Donation__c result = [SELECT Id, msf_CurrentCampaign__c, msf_CurrentQuotaModification__c
                                               FROM npe03__Recurring_Donation__c 
                                               WHERE Id = :quotaMod.msf_RecurringDonation__c ];
        
        
        System.assertEquals(quotaMod.msf_RecurringDonation__c, result.Id);
        System.assertEquals(quotaMod.Id, result.msf_CurrentQuotaModification__c);
        
    }
    
    @isTest static void updateQuotaModificationFieldsLogic(){
        msf_QuotaModification__c quotaMod = [SELECT Id, msf_CampaignInfluence__c, msf_RecurringDonation__c
                                             FROM msf_QuotaModification__c 
                                             WHERE Name = 'MSFQuotaModificationFieldsLogicTESTName2'];
		msf_QuotaModification__c oldQuotaMod = quotaMod;
        quotaMod.msf_CampaignInfluence__c = [SELECT Id FROM Campaign
                                             WHERE Name = 'MSFQuotaModificationFieldsLogicTESTName1' LIMIT 1].Id;
        update quotaMod;
        System.assertEquals(oldQuotaMod,QuotaMOd);
    }
    private static List<String> leadSource1Desc(){
        Schema.DescribeFieldResult fieldResult = Opportunity.LeadSource.getDescribe(); 
        List<Schema.PicklistEntry> pickListValues = fieldResult.getPicklistValues();
        
        List<String> options = new List<String>();
        
        for(Schema.PicklistEntry p : pickListValues){
            options.add(p.getLabel());
        }
        return options;
    }
    private static List<String> leadSource2Desc(){
        Schema.DescribeFieldResult fieldResult = Opportunity.msf_LeadSource2Level__c.getDescribe(); 
        List<Schema.PicklistEntry> pickListValues = fieldResult.getPicklistValues();
        
        List<String> options = new List<String>();
        
        for(Schema.PicklistEntry p : pickListValues){
            options.add(p.getLabel());
        }
        return options;
    }
    private static List<String> leadSource3Desc(){
        Schema.DescribeFieldResult fieldResult = Opportunity.msf_LeadSource3Level__c.getDescribe(); 
        List<Schema.PicklistEntry> pickListValues = fieldResult.getPicklistValues();
        
        List<String> options = new List<String>();
        
        for(Schema.PicklistEntry p : pickListValues){
            options.add(p.getLabel());
        }
        return options;
    }
}