force-app/main/default/objects/msf_LeadSourceMasterData__c/msf_LeadSourceMasterData__c.object-meta.xml
<CustomObject>
    <label>Maestro de datos de LeadSource</label>
    <nameField>
        <displayFormat>MD_LS_{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maestro de datos de LeadSource</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_LeadSourceMasterData__c/fields/msf_LeadSource3__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource3__c</fullName>
    <label>Canal de entrada 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource3</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_QuotaModification__c/msf_QuotaModification__c.object-meta.xml
<CustomObject>
    <label>Modificación de cuota</label>
    <nameField>
        <label>Nombre de Modificación de cuota</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modificaciones de cuota</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_QuotaModification__c/fields/msf_LeadSource1__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource1__c</fullName>
    <label>Canal de entrada 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_QuotaModification__c/fields/msf_LeadSource2__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource2__c</fullName>
    <label>Canal de entrada 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_QuotaModification__c/fields/msf_RecurringDonation__c.field-meta.xml
<CustomField>
    <fullName>msf_RecurringDonation__c</fullName>
    <label>Recurring Donations</label>
    <referenceTo>npe03__Recurring_Donation__c</referenceTo>
    <relationshipLabel>Modificaciones de cuota</relationshipLabel>
    <relationshipName>Modificaciones_de_cuota</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/npe03__Recurring_Donation__c.object-meta.xml
<CustomObject>
    <description>Recurring Donations track charitable giving where a donor specifies an amount of money to be given on a regular basis.</description>
    <label>Recurring Donation</label>
    <nameField>
        <label>Recurring Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/msf_CurrentQuotaModification__c.field-meta.xml
<CustomField>
    <fullName>msf_CurrentQuotaModification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modificación de cuota actual</label>
    <referenceTo>msf_QuotaModification__c</referenceTo>
    <relationshipName>Donaciones_recurrentes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/msf_LeadSource1__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource1__c</fullName>
    <label>Canal de entrada 1 inicial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/msf_LeadSource2__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource2__c</fullName>
    <label>Canal de entrada 2 inicial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/msf_LeadSource3__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource3__c</fullName>
    <label>Canal de entrada 3 inicial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource3</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/MSF_LeadSource1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cloud page</fullName>
    </customValue>
    <customValue>
        <fullName>Correo postal sin cupón</fullName>
    </customValue>
    <customValue>
        <fullName>Cupón</fullName>
    </customValue>
    <customValue>
        <fullName>Email a Bodas</fullName>
    </customValue>
    <customValue>
        <fullName>Email a Empresas</fullName>
    </customValue>
    <customValue>
        <fullName>Email a Iniciativas Solidarias</fullName>
    </customValue>
    <customValue>
        <fullName>Email a officers Mid Donors</fullName>
    </customValue>
    <customValue>
        <fullName>Email a One to one</fullName>
    </customValue>
    <customValue>
        <fullName>Email a SAS</fullName>
    </customValue>
    <customValue>
        <fullName>Email Director/a General</fullName>
    </customValue>
    <customValue>
        <fullName>Email herencias</fullName>
    </customValue>
    <customValue>
        <fullName>Email Presidente/a MSF</fullName>
    </customValue>
    <customValue>
        <fullName>Entidad financiera</fullName>
    </customValue>
    <customValue>
        <fullName>Eventos</fullName>
    </customValue>
    <customValue>
        <fullName>Mensajería Instantánea</fullName>
    </customValue>
    <customValue>
        <fullName>n/a</fullName>
    </customValue>
    <customValue>
        <fullName>Otro</fullName>
    </customValue>
    <customValue>
        <fullName>Persona a persona</fullName>
    </customValue>
    <customValue>
        <fullName>Personal con tablet</fullName>
    </customValue>
    <customValue>
        <fullName>Plataforma iniciativas</fullName>
    </customValue>
    <customValue>
        <fullName>Redes Sociales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono campaña</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Herencias y Legados</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Officers</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono SAS</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono web</fullName>
    </customValue>
    <customValue>
        <fullName>Telemarketing</fullName>
    </customValue>
    <customValue>
        <fullName>Web campaña</fullName>
    </customValue>
    <customValue>
        <fullName>Web MSF</fullName>
    </customValue>
    <description>LeadSource Master Data</description>
    <masterLabel>LeadSource1</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/MSF_LeadSource2.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Correo postal sin cupón</fullName>
    </customValue>
    <customValue>
        <fullName>Cupón</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Entidad financiera</fullName>
    </customValue>
    <customValue>
        <fullName>Formulario web</fullName>
    </customValue>
    <customValue>
        <fullName>Mensajería Instantánea</fullName>
    </customValue>
    <customValue>
        <fullName>Otro</fullName>
    </customValue>
    <customValue>
        <fullName>Persona a persona</fullName>
    </customValue>
    <customValue>
        <fullName>Redes Sociales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono campaña</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Herencias y Legados</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfonos Officers</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfonos SAS</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono web</fullName>
    </customValue>
    <customValue>
        <fullName>Telemarketing</fullName>
    </customValue>
    <description>LeadSource Master Data</description>
    <masterLabel>LeadSource2</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/MSF_LeadSource3.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Correo postal</fullName>
    </customValue>
    <customValue>
        <fullName>Entidad financiera</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Personal</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono</fullName>
    </customValue>
    <customValue>
        <fullName>Otro</fullName>
    </customValue>
    <description>LeadSource Master Data</description>
    <masterLabel>LeadSource3</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MSF_QuotaModificationFieldsLogic_TDTM.cls
/**
* @author 		Deloitte
* @date 		10-2018
* @group 		QuotaModification
* @description	QuotaModification fields management and name.
*/
global without sharing class MSF_QuotaModificationFieldsLogic_TDTM extends npsp.TDTM_Runnable {
    
    /*******************************************************************************************************
    * @description	Trigger Handler on Quota Modifications that handles the logic of some fields and the 
    * 				change of quota. 
    * @param 		listNew the list of Recurring Donations from trigger new. 
    * @param 		listOld the list of Recurring Donations from trigger old. 
    * @param 		triggerAction which trigger event (BeforeInsert, AfterInsert, etc.). 
    * @param 		objResult the describe for Recurring Donations 
    * @return 		dmlWrapper. 
    ********************************************************************************************************/
    global override npsp.TDTM_Runnable.DmlWrapper run(List<SObject> newlist, List<SObject> oldlist, npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {    
    	
        //Attributes
        List<msf_QuotaModification__c> lNewMQ = (List<msf_QuotaModification__c>) newlist;
        List<msf_QuotaModification__c> lOldMQ = (List<msf_QuotaModification__c>) oldlist;
        Map<Id, msf_QuotaModification__c> mOldMQ = new Map<Id, msf_QuotaModification__c>();
        if(lOldMQ != null){            
            mOldMQ.putAll(lOldMQ);
        }

        List<npe03__Recurring_Donation__c> lRDToUpdate = new List<npe03__Recurring_Donation__c>();
        
        //Actions             
        
        if(triggerAction == npsp.TDTM_Runnable.Action.BeforeInsert){	  
       		
            MSF_SharedMethods_UTIL smUtil = new MSF_SharedMethods_UTIL();            
            Map<String, msf_LeadSourceMasterData__c> mLeadSourceValues = smUtil.getLeadSourceDependencies();
            
            for(msf_QuotaModification__c mq : lNewMQ){    
            	setLeadSourceDependencies(mq, mLeadSourceValues);                
            }         
        }
        
        if(triggerAction == npsp.TDTM_Runnable.Action.AfterInsert){	  
       		lRDToUpdate.addAll(updateRD(lNewMQ));          
        }
                        
        //DML Operations
        npsp.TDTM_Runnable.dmlWrapper dmlWrapper = new npsp.TDTM_Runnable.DmlWrapper();
        dmlWrapper.objectsToUpdate.addAll((List<npe03__Recurring_Donation__c>)lRDToUpdate);
        
        if(lRDToUpdate.isEmpty()){
            return null;
        }
        
        return dmlWrapper;
    }
    
    // PRIVATE METHODS
    
	/*******************************************************************************************************
    * @description	Establishes the new quota modification in the related recurring donation.
    * @param 		lMQ is a new quota modification.				
    ********************************************************************************************************/
    private List<npe03__Recurring_Donation__c> updateRD(List<msf_QuotaModification__c> lMQ){
        
        List<npe03__Recurring_Donation__c> lRD = new List<npe03__Recurring_Donation__c>();
        
        for(msf_QuotaModification__c mq : lMQ){
        	lRD.add(
                new npe03__Recurring_Donation__c(
                    Id = mq.msf_RecurringDonation__c, 
                    msf_CurrentQuotaModification__c = mq.Id
                )
            );    
        }
        
        return lRD;
    }   
    
    /*******************************************************************************************************
    * @description	Establishes the values in the 'LeadSource2; LeadSource3' fields in lead depending of the 
    * 				value of the 'LeadSource1' field.
    * @param 		rd is the Recurrent Donation to update its fields. 
    * @param 		mLsValues is a map that contains values for fields 'LeadSource2; LeadSource3'
    ********************************************************************************************************/
    private void setLeadSourceDependencies(msf_QuotaModification__c mq, Map<String, msf_LeadSourceMasterData__c> mLsValues){
        if(mLsValues.containsKey(mq.msf_LeadSource1__c)){
            mq.msf_LeadSource2__c = mLsValues.get(mq.msf_LeadSource1__c).msf_LeadSource2__c;
            mq.msf_LeadSource3__c = mLsValues.get(mq.msf_LeadSource1__c).msf_LeadSource3__c;
        }
    }
}