force-app/main/default/objects/msf_LeadSourceMasterData__c/msf_LeadSourceMasterData__c.object-meta.xml
<CustomObject>
    <label>Maestro de datos de LeadSource</label>
    <nameField>
        <displayFormat>MD_LS_{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maestro de datos de LeadSource</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_LeadSourceMasterData__c/fields/msf_LeadSource3__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource3__c</fullName>
    <label>Canal de entrada 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource3</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/msf_EconomicProcessUser__c.field-meta.xml
<CustomField>
    <fullName>msf_EconomicProcessUser__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check only for economic.process@barcelona.msf.org</inlineHelpText>
    <label>Economic process user</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/MSF_LeadSource3.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Correo postal</fullName>
    </customValue>
    <customValue>
        <fullName>Entidad financiera</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Personal</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono</fullName>
    </customValue>
    <customValue>
        <fullName>Otro</fullName>
    </customValue>
    <description>LeadSource Master Data</description>
    <masterLabel>LeadSource3</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Globals.cls
/**
 * @description       : 
 * @author            : sheredia@omegacrmconsulting.com
 * @group             : 
 * @last modified on  : 04-26-2022
 * @last modified by  : sheredia@omegacrmconsulting.com
**/
public with sharing class Globals {
    
    public static Boolean bEcoUser {get{ 
        if (bEcoUser == null)
        bEcoUser = [SELECT Id, msf_EconomicProcessUser__c FROM User WHERE Id =: UserInfo.getUserId()].msf_EconomicProcessUser__c;        
        return bEcoUser ;
    }set;}

    public static ID adminProfileID {get{ 
        if (adminProfileID == null)
        adminProfileID = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id;        
        return adminProfileID ;
    }set;}

    public static List<msf_LeadSourceMasterData__c> leadSources {get{ 
        if (leadSources == null)
        leadSources = [SELECT msf_LeadSource1__c, msf_LeadSource2__c, msf_LeadSource3__c FROM msf_LeadSourceMasterData__c];        
        return leadSources ;
    }set;}

}