force-app/main/default/objects/Account/recordTypes/Anonymous.recordType-meta.xml
<RecordType>
    <fullName>Anonymous</fullName>
    <active>true</active>
    <label>Anonymous</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Anonymous.recordType-meta.xml
<RecordType>
    <fullName>Anonymous</fullName>
    <active>true</active>
    <label>Anonymous</label>
</RecordType>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/msf_AutomatedProcessErrors__c.object-meta.xml
<CustomObject>
    <label>Automated Process Error</label>
    <nameField>
        <displayFormat>ERROR_{YYYY}-{MM}-{DD}_{0000000000}</displayFormat>
        <label>Identificador de error</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automated Process Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>msf_ErrorMessage__c</fullName>
    <label>Mensaje de error</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_FieldsErrors__c.field-meta.xml
<CustomField>
    <fullName>msf_FieldsErrors__c</fullName>
    <label>Campos con errores</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_Process__c.field-meta.xml
<CustomField>
    <fullName>msf_Process__c</fullName>
    <label>Proceso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_RecordId__c.field-meta.xml
<CustomField>
    <fullName>msf_RecordId__c</fullName>
    <label>Id registro</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_StatusCode__c.field-meta.xml
<CustomField>
    <fullName>msf_StatusCode__c</fullName>
    <label>Código de error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MSF_AnonymousManagement_BATCH.cls
/**
* @author 		Deloitte
* @date 		10-2018
* @group 		Accounts
* @description	Monthly anonymous management. This class creates a monthly account to group all anonymous donations.
*/
global without sharing class MSF_AnonymousManagement_BATCH implements Schedulable {
    
    global void execute(SchedulableContext SC) {

        List<Account> laccNew = new List<Account>();
        List<Contact> lcontNew = new List<Contact>();
        Savepoint sp = Database.setSavepoint();
        
        try{
            Date DateNextMonth = date.today().addMonths(1);
            String nextMonth = String.valueOf(DateNextMonth.month());
            if(nextMonth.length()==1){
                nextMonth = '0'+nextMonth;
            }
            String NameRecord = 'Anónimos_'+DateNextMonth.year()+'_'+nextMonth;
            
            List<Account> aAnonymous = [SELECT Id, Name FROM Account WHERE Name=: NameRecord AND RecordType.DeveloperName = 'Anonymous'];
            
            if(aAnonymous.isEmpty()){
                
                List<Contact> cAnonymous = [SELECT Id, Name FROM Contact WHERE Name=: NameRecord AND RecordType.DeveloperName = 'Anonymous'];
                
                if(cAnonymous.isEmpty()){
                    RecordType accRt =[SELECT Id FROM RecordType WHERE DeveloperName = 'Anonymous' AND SobjectType = 'Account'];
                    RecordType contRt =[SELECT Id FROM RecordType WHERE DeveloperName = 'Anonymous' AND SobjectType = 'Contact'];
                    
                    Account accNew = new Account(
                        Name = NameRecord,
                        RecordTypeId = accRt.Id,
                        Type = 'Anonymous'
                    );

                    laccNew.add(accNew);                      

                    Database.SaveResult[] srList = Database.insert(laccNew, false);            
                    
                    
                    List<msf_AutomatedProcessErrors__c> lAPE = new List<msf_AutomatedProcessErrors__c>(); 
                    
                    for (Database.SaveResult sr : srList) { // Iterate through each returned result
                        if (!sr.isSuccess()) {  // Operation failed, so get all errors                                   
                            for(Database.Error err : sr.getErrors()) {
                                msf_AutomatedProcessErrors__c tempAPE = new msf_AutomatedProcessErrors__c(msf_Process__c = 'MSF_AnonymousManagement_BATCH', msf_RecordId__c = laccNew.get(srList.indexOf(sr)).Id, msf_StatusCode__c = String.valueOf(err.getStatusCode()), msf_FieldsErrors__c = String.valueOf(err.getFields()), msf_ErrorMessage__c = err.getMessage());
                                lAPE.add(tempAPE);
                            }
                        }            
                    }
                    
                    if(lAPE.isEmpty()){
                        Contact contNew = new Contact(
                            LastName = NameRecord+' - Transferencias',
                            RecordTypeId = contRt.Id,
                            AccountId = accNew.Id
                        );
                        lcontNew.add(contNew);
                        
                        Contact contNew2 = new Contact(
                            LastName = NameRecord+' - Otras formas de pago',
                            RecordTypeId = contRt.Id,
                            AccountId = accNew.Id
                        );
                        lcontNew.add(contNew2);

                        Database.SaveResult[] srListaCont = Database.insert(lcontNew, false);                
                        
                        for (Database.SaveResult sr : srList) { // Iterate through each returned result
                            if (!sr.isSuccess()) {  // Operation failed, so get all errors                                   
                                for(Database.Error err : sr.getErrors()) {
                                    msf_AutomatedProcessErrors__c tempAPE = new msf_AutomatedProcessErrors__c(msf_Process__c = 'MSF_AnonymousManagement_BATCH', msf_RecordId__c = lcontNew.get(srList.indexOf(sr)).Id, msf_StatusCode__c = String.valueOf(err.getStatusCode()), msf_FieldsErrors__c = String.valueOf(err.getFields()), msf_ErrorMessage__c = err.getMessage());
                                    lAPE.add(tempAPE);
                                }
                            } 
                        }
                    }
                    
                    if(!lAPE.isEmpty()){
                        insert lAPE;
                    }
                }
                else{
                    msf_AutomatedProcessErrors__c tempAPE = new msf_AutomatedProcessErrors__c(msf_Process__c = 'MSF_AnonymousManagement_BATCH', msf_ErrorMessage__c = 'El contacto '+NameRecord+' ya existe en el sistema.');              
                    insert tempAPE;
                    
                }
            } 
            else{
                msf_AutomatedProcessErrors__c tempAPE = new msf_AutomatedProcessErrors__c(msf_Process__c = 'MSF_AnonymousManagement_BATCH', msf_ErrorMessage__c = 'La cuenta '+NameRecord+' ya existe en el sistema.'); 
                insert tempAPE;
                
            }
        }catch(exception e){
            Database.rollback(sp);
            msf_AutomatedProcessErrors__c tempAPE = new msf_AutomatedProcessErrors__c( msf_Process__c = 'MSF_AnonymousManagement_BATCH', msf_ErrorMessage__c = e.getMessage());
            insert tempAPE;          
        }
    }
}