force-app/main/default/objects/Account/recordTypes/HH_Account.recordType-meta.xml
<RecordType>
    <fullName>HH_Account</fullName>
    <active>true</active>
    <description>An Account representing a Household containing one or more individuals</description>
    <label>Household Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <description>An Account representing an organization</description>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MSF_AccountFieldsLogic_TEST.cls
/**
* @author       Deloitte
* @date         01-2019
* @group        Account
* @description  test class for the MSF_AccountFieldsLogic_TDTM class.
*/
@isTest
private class MSF_AccountFieldsLogic_TEST {
    @testSetup static void setup(){
        //Create Trigger
        npsp__Trigger_Handler__c thCon = new npsp__Trigger_Handler__c(
            Name = 'TriggerTestAccountFieldLogic',
            npsp__Class__c = 'MSF_AccountFieldsLogic_TDTM',
            npsp__Object__c = 'Account',
            npsp__Trigger_Action__c = 'BeforeInsert;BeforeUpdate',
            npsp__Active__c = true,
            npsp__Load_Order__c = 3,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );
        upsert thCon;
        //Initialize values
        Id IdOrgCont = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization').getRecordTypeId();
        Contact cont = new Contact(LastName='MSF_AccountFieldsLogic_TEST_LastName1',RecordTypeId=IdOrgCont);
        insert cont;
        Account acc = new Account(Name='MSF_AccountFieldsLogic_TEST_Name1',
                                  RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Organization').getRecordTypeId());
        insert acc;
    }
    @isTest static void testInsertOrganizationAcc(){
        Id IdOrgRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Organization').getRecordTypeId(); 
        Contact cont = [SELECT Id FROM Contact WHERE LastName='MSF_AccountFieldsLogic_TEST_LastName1' LIMIT 1];
        Account acc = new Account(Name='MSF_AccountFieldsLogic_TEST_InsertOrgAcct1',RecordTypeId=IdOrgRT);
        acc.npe01__One2OneContact__c=cont.Id;
        insert acc;
        acc = [SELECT Id,Name,npe01__One2OneContact__c FROM Account WHERE Name='CUENTA - MSF_AccountFieldsLogic_TEST_LastName1' LIMIT 1];
        System.assertEquals(acc.npe01__One2OneContact__c,cont.Id);
    }
    @isTest static void testInsertOrganizationHHAcc(){
        Id IdHHRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('HH_Account').getRecordTypeId(); 
        Contact cont = [SELECT Id FROM Contact WHERE LastName='MSF_AccountFieldsLogic_TEST_LastName1' LIMIT 1];
        Account acc = new Account(Name='MSF_AccountFieldsLogic_TEST_InsertHHAcc1',
                                  npe01__One2OneContact__c=cont.Id,
                                  RecordTypeId=IdHHRT
                                 );        
        insert acc;
        acc = [SELECT Id, Name FROM Account WHERE npe01__One2OneContact__c=:cont.Id LIMIT 1];
        System.assertEquals('MSF_AccountFieldsLogic_TEST_InsertHHAcc1',acc.Name);
    }
    @isTest static void testUpdateAcc(){
        Id IdHHRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('HH_Account').getRecordTypeId(); 
        Contact cont = [SELECT Id FROM Contact WHERE LastName='MSF_AccountFieldsLogic_TEST_LastName1' LIMIT 1];
        Account acc = [SELECT Id, Name FROM Account WHERE Name='CUENTA - MSF_AccountFieldsLogic_TEST_Name1' LIMIT 1];
        
        acc.RecordTypeId = IdHHRT;
        acc.npe01__One2OneContact__c=cont.Id;
        update acc;
        acc = [SELECT Id,npe01__One2OneContact__c,type FROM Account WHERE Name = 'CUENTA - MSF_AccountFieldsLogic_TEST_LastName1' LIMIT 1];
        System.assertEquals('Company',acc.type);
    }
}