force-app/main/default/objects/Account/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <description>An Account representing an organization</description>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/Contact/fields/msf_EndDate__c.field-meta.xml
<CustomField>
    <fullName>msf_EndDate__c</fullName>
    <label>Fecha final</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_FechaExclusionComunicaciones__c.field-meta.xml
<CustomField>
    <fullName>msf_FechaExclusionComunicaciones__c</fullName>
    <label>E.C. Fecha exclusión comunicaciones</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_IsActive__c.field-meta.xml
<CustomField>
    <fullName>msf_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Es activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_IsPrimary__c.field-meta.xml
<CustomField>
    <fullName>msf_IsPrimary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es contacto principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_Organization__c.field-meta.xml
<CustomField>
    <fullName>msf_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organización</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contactos de organización</relationshipLabel>
    <relationshipName>Organization</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_OrgContactDataUpdated__c.field-meta.xml
<CustomField>
    <fullName>msf_OrgContactDataUpdated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>System field</description>
    <label>Datos de contacto actualizados</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_OrgPrimaryContactUpdated__c.field-meta.xml
<CustomField>
    <fullName>msf_OrgPrimaryContactUpdated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>System field</description>
    <label>Contacto principal actualizado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>msf_PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contacto principal</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No es un contacto de tipo contacto organización</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organization Contact</value>
        </filterItems>
        <filterItems>
            <field>Contact.msf_Organization__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.msf_IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contactos Principales</relationshipLabel>
    <relationshipName>Contactos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_ShippingName__c.field-meta.xml
<CustomField>
    <fullName>msf_ShippingName__c</fullName>
    <label>Nombre envío</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_StartDate__c.field-meta.xml
<CustomField>
    <fullName>msf_StartDate__c</fullName>
    <label>Fecha inicial</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Organization_Contact.recordType-meta.xml
<RecordType>
    <fullName>Organization_Contact</fullName>
    <active>true</active>
    <label>Organization Contact</label>
</RecordType>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MSF_OrganizationContactData_TEST.cls
/**
* @author       Deloitte
* @date         02-2019
* @group        Contacts
* @description  Test class for the MSF_OrganizationContactData_TDTM class.
*/
@isTest
private class MSF_OrganizationContactData_TEST {
    @testSetup static void setup(){
        //Create Trigger
        npsp__Trigger_Handler__c thCon = new npsp__Trigger_Handler__c(
            Name = 'TriggerTestOrganizationContactData',
            npsp__Class__c = 'MSF_OrganizationContactData_TDTM',
            npsp__Object__c = 'Contact',
            npsp__Trigger_Action__c = 'BeforeUpdate;BeforeInsert;AfterInsert;AfterUpdate',
            npsp__Active__c = true,
            npsp__Load_Order__c = 5,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );        
        upsert thCon; 
        //Initialize values
        List<Account> accList = new List<Account>(); 
        Account acc = new Account(Name='MSF_AccountFieldsLogic_TEST_Name1');
       	accList.add(acc);
        
        Account acc2 = new Account(Name='MSF_AccountFieldsLogic_TEST_Name2');
       	accList.add(acc2);
        insert accList;
        
        acc = [SELECT Id FROM Account WHERE Name = 'MSF_AccountFieldsLogic_TEST_Name1'];
        acc2 = [SELECT Id FROM Account WHERE Name = 'MSF_AccountFieldsLogic_TEST_Name2'];
        
        Contact orgCont = new Contact(LastName='MSF_AccountFieldsLogic_TEST_Org_LastName1');
        orgCont.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization').getRecordTypeId();
        insert orgCont;
        orgCont = [SELECT Id FROM Contact WHERE LastName='MSF_AccountFieldsLogic_TEST_Org_LastName1' LIMIT 1];
        
        Contact orgCont2 = new Contact(LastName='MSF_AccountFieldsLogic_TEST_Org_LastName4');
        orgCont2.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization').getRecordTypeId();
        insert orgCont2;
        orgCont2 = [SELECT Id FROM Contact WHERE LastName='MSF_AccountFieldsLogic_TEST_Org_LastName4' LIMIT 1];
        
        Contact orgCont3 = new Contact(LastName='MSF_AccountFieldsLogic_TEST_Org_LastName_WithoutContact');
        orgCont3.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization').getRecordTypeId();
        insert orgCont3;
        
        
        Contact cont = new Contact(LastName='MSF_AccountFieldsLogic_TEST_LastName1');
        cont.AccountId = acc.Id;
        cont.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization_Contact').getRecordTypeId();
        cont.msf_Organization__c = orgCont.Id;
        cont.msf_IsPrimary__c = true;
        
        insert cont;
        
        
        Contact cont2 = new Contact(LastName='MSF_AccountFieldsLogic_TEST_LastName1_isNotPrimary');
        cont2.FirstName = 'MSF_AFL_TEST_LastName1_isNotPrimary';
        cont2.AccountId = acc.Id;
        cont2.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization_Contact').getRecordTypeId();
        cont2.msf_Organization__c = orgCont.Id;
        cont2.msf_IsPrimary__c = cont2.msf_IsActive__c = false;
        cont2.msf_EndDate__c = date.today();
        insert cont2;
        
        cont2 = new Contact(LastName='MSF_AccountFieldsLogic_TEST_LastName1_isPrimary');
        cont2.AccountId = acc2.Id;
        cont2.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization_Contact').getRecordTypeId();
        cont2.msf_Organization__c = orgCont2.Id;
        cont2.msf_IsPrimary__c = cont2.msf_IsActive__c = true;
        
        insert cont2;
        cont2 = [SELECT Id FROM Contact WHERE LastName = 'MSF_AccountFieldsLogic_TEST_LastName1_isPrimary' LIMIT 1];
        
        orgCont2.msf_PrimaryContact__c = cont2.Id;
        orgCont2.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization').getRecordTypeId();
        update orgCont2;
        
        Contact cont3 = new Contact(LastName='MSF_AccountFieldsLogic_TEST_LastName1_isNotActive');
        cont3.AccountId = acc.Id;
        cont3.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization_Contact').getRecordTypeId();
        cont3.msf_Organization__c = orgCont.Id;
        cont3.msf_IsPrimary__c = true;
        cont3.msf_IsActive__c = false;
        
        insert cont3;
        
        Contact cont4 = new Contact(LastName='MSF_AccountFieldsLogic_TEST_LastName1_isNotPrimary');
        cont4.AccountId = acc.Id;
        cont4.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization_Contact').getRecordTypeId();
        cont4.msf_IsActive__c = true;
        
        insert cont4;
        
    }
    
    @isTest static void testInsertOrganizationContactData_Type_Organization_Contact_IsNotPrimary_IsActive(){
        Contact orgCont = [SELECT Id FROM Contact WHERE LastName='MSF_AccountFieldsLogic_TEST_Org_LastName4' LIMIT 1];
        
        Contact cont = new Contact(LastName='MSF_AccountFieldsLogic_TEST_LastNameNew');
        cont.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization_Contact').getRecordTypeId();
        cont.msf_IsPrimary__c = false;
        cont.msf_IsActive__c = true;
        
        cont.msf_Organization__c = orgCont.Id;
        insert cont;
        cont = [SELECT Id FROM Contact WHERE LastName = 'MSF_AccountFieldsLogic_TEST_LastNameNew' LIMIT 1];
        System.assertNotEquals(cont.Id,null);
    }
    
    @isTest static void testInsertOrganizationContactData_Type_Organization_Contact_IsPrimary(){
        
        Contact orgCont = new Contact(LastName='MSF_AccountFieldsLogic_TEST_Org_LastNamenNew');
        orgCont.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization').getRecordTypeId();
        insert orgCont;        
        
        Contact cont = new Contact(LastName='MSF_AccountFieldsLogic_TEST_LastNameNew');
        cont.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization_Contact').getRecordTypeId();
        cont.msf_IsPrimary__c = false;
        cont.msf_IsActive__c = true;
        
        cont.msf_Organization__c = orgCont.Id;
        insert cont;
        cont = [SELECT Id FROM Contact WHERE LastName = 'MSF_AccountFieldsLogic_TEST_LastNameNew' LIMIT 1];
        System.assertNotEquals(cont.Id,null);
    }
    
    @isTest static void testUpdateOrganizationContactData_Type_Organization_Contact(){
        Contact cont = [SELECT Id,LastName FROM Contact WHERE LastName='MSF_AccountFieldsLogic_TEST_LastName1' LIMIT 1];
        cont.LastName = 'MSF_AccountFieldsLogic_TEST_LastName2';
        cont.msf_FechaExclusionComunicaciones__c = date.today();
        cont.msf_PrimaryContact__c = null;
        update cont;
        cont = [SELECT Id,LastName FROM Contact WHERE LastName='MSF_AccountFieldsLogic_TEST_LastName2' LIMIT 1];
        System.assertNotEquals(cont.Id, null);
    }
    
    @isTest static void testUpdateOrganizationContactData_Type_Organization(){
        Contact cont = [SELECT Id,LastName FROM Contact WHERE LastName='MSF_AccountFieldsLogic_TEST_Org_LastName1' LIMIT 1];
        cont.LastName = 'MSF_AccountFieldsLogic_TEST_LastName2';
        cont.msf_FechaExclusionComunicaciones__c = date.today();
        cont.msf_PrimaryContact__c = null;
        update cont;
        cont = [SELECT Id,msf_ShippingName__c FROM Contact WHERE Id= :cont.Id LIMIT 1];
        System.assertEquals(cont.msf_ShippingName__c,null);
    }
    
    @isTest static void testUpdateOrganizationContactData_Error(){
        try{
            Contact cont = [SELECT Id,LastName FROM Contact WHERE LastName='MSF_AccountFieldsLogic_TEST_Org_LastName1' LIMIT 1];
            cont.msf_OrgPrimaryContactUpdated__c = false;
            cont.msf_OrgContactDataUpdated__c = true;
            update cont;
            //If there's no error, the tests fails.
            //System.assert(false);
        }catch(DmlException e){
            System.assert(true);
        }
    }
    
    @isTest static void testUpdateOrganizationContactData_Type_Organization_Contact_CheckLogicIf1(){
        Contact cont = [SELECT Id,LastName FROM Contact WHERE LastName='MSF_AccountFieldsLogic_TEST_LastName1_isNotPrimary' LIMIT 1];
        cont.LastName = 'MSF_AccountFieldsLogic_TEST_LastName2';
        cont.msf_FechaExclusionComunicaciones__c = date.today();
        cont.msf_PrimaryContact__c = null;
        cont.msf_IsPrimary__c = true;
        cont.msf_IsActive__c = false;
        update cont;
        cont = [SELECT Id,msf_StartDate__c,msf_EndDate__c,msf_IsActive__c FROM Contact WHERE Id = :cont.Id LIMIT 1];
        System.assertEquals(cont.msf_StartDate__c, date.today());
        System.assertEquals(cont.msf_EndDate__c, null);
        System.assertEquals(cont.msf_IsActive__c, true);
    }
    @isTest static void testUpdateOrganizationContactData_Type_Organization_Contact_CheckLogicIf2(){
        Contact cont = [SELECT Id,LastName FROM Contact WHERE LastName='MSF_AccountFieldsLogic_TEST_LastName1_isNotPrimary' LIMIT 1];
        cont.LastName = 'MSF_AccountFieldsLogic_TEST_LastName2';
        cont.msf_FechaExclusionComunicaciones__c = date.today();
        cont.msf_PrimaryContact__c = null;
        cont.msf_IsActive__c = true;
        update cont;
        cont = [SELECT Id,msf_StartDate__c,msf_EndDate__c,msf_IsActive__c FROM Contact WHERE Id = :cont.Id LIMIT 1];
        System.assertEquals(cont.msf_StartDate__c, date.today());
        System.assertEquals(cont.msf_EndDate__c, null);
        System.assertEquals(cont.msf_IsActive__c, true);
    }
    @isTest static void testUpdateOrganizationContactData_Type_Organization_Contact_CheckLogicIf3(){
        Contact cont = [SELECT Id,LastName FROM Contact WHERE LastName='MSF_AccountFieldsLogic_TEST_LastName1' LIMIT 1];
        cont.LastName = 'MSF_AccountFieldsLogic_TEST_LastName2';
        cont.msf_FechaExclusionComunicaciones__c = date.today();
        cont.msf_PrimaryContact__c = null;
        cont.msf_IsActive__c = false;
        update cont;
        
        cont = [SELECT Id,msf_EndDate__c,msf_IsPrimary__c FROM Contact WHERE Id = :cont.Id LIMIT 1];
        
        System.assertEquals(cont.msf_EndDate__c, date.today());
        System.assertEquals(cont.msf_IsPrimary__c, false);
    }
    @isTest static void testUpdateOrganizationContactData_Type_Organization_Contact_to_Active(){
        Contact cont = [SELECT Id,LastName FROM Contact WHERE LastName='MSF_AccountFieldsLogic_TEST_LastName1_isNotActive' LIMIT 1];
        cont.LastName = 'MSF_AccountFieldsLogic_TEST_LastName2';
        cont.msf_FechaExclusionComunicaciones__c = date.today();
        cont.msf_PrimaryContact__c = null;
        cont.msf_IsActive__c = true;
        update cont;
        cont = [SELECT Id,LastName FROM Contact WHERE LastName='MSF_AccountFieldsLogic_TEST_LastName2' LIMIT 1];
        System.assertEquals(cont.LastName, 'MSF_AccountFieldsLogic_TEST_LastName2');
    }
    
     @isTest static void testUpdateOrganizationContactData_Type_Organization_Contact_IsPrimary(){
        Contact orgCont = [SELECT Id FROM Contact WHERE LastName='MSF_AccountFieldsLogic_TEST_Org_LastName_WithoutContact' LIMIT 1];
        
        Contact cont = [SELECT Id,RecordTypeId,msf_IsPrimary__c,msf_IsActive__c,msf_Organization__c FROM Contact WHERE LastName='MSF_AccountFieldsLogic_TEST_LastName1_isNotPrimary' LIMIT 1];
        cont.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization_Contact').getRecordTypeId();
        cont.msf_IsPrimary__c = false;
        cont.msf_IsActive__c = true;
        
        cont.msf_Organization__c = orgCont.Id;
        update cont;
        cont = [SELECT Id,msf_IsPrimary__c FROM Contact WHERE LastName = 'MSF_AccountFieldsLogic_TEST_LastName1_isNotPrimary' LIMIT 1];
        System.assertEquals(false, cont.msf_IsPrimary__c);
    }
    
    @isTest static void testUpdateOrganizationContactData_Type_Organization_Contact_DeletePrimaryFromOrganization(){
        Contact cont = [SELECT Id,LastName FROM Contact WHERE LastName='MSF_AccountFieldsLogic_TEST_LastName1_isPrimary' LIMIT 1];
        cont.LastName = 'MSF_AccountFieldsLogic_TEST_LastName2';
        cont.msf_FechaExclusionComunicaciones__c = date.today();
        cont.msf_IsPrimary__c = false;
        cont.msf_IsActive__c = false;
        Contact contOrg = [SELECT Id FROM Contact WHERE msf_PrimaryContact__c = :cont.Id LIMIT 1];
        update cont;
        
        contOrg = [SELECT Id,msf_PrimaryContact__c FROM Contact WHERE Id = :contOrg.Id];
        System.assertEquals(contOrg.msf_PrimaryContact__c, null);
    }
    
}