force-app/main/default/objects/Account/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <description>An Account representing an organization</description>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/Contact/fields/msf_Organization__c.field-meta.xml
<CustomField>
    <fullName>msf_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organización</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contactos de organización</relationshipLabel>
    <relationshipName>Organization</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <description>Indicates if this Contact is designated as the Primary Contact on their Account (read only).</description>
    <formula>Account.npe01__One2OneContact__c = Id</formula>
    <inlineHelpText>Este campo esta seleccionado si es el contacto principal en la cuenta. El contacto principal puede editarse en la cuenta.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Organization_Contact.recordType-meta.xml
<RecordType>
    <fullName>Organization_Contact</fullName>
    <active>true</active>
    <label>Organization Contact</label>
</RecordType>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Contact for this Opportunity. If this is an individual Donation, NPSP attributes the Donation to the Primary Contact. If this is an organizational Donation, NPSP attributes a soft credit to the Primary Contact.</description>
    <inlineHelpText>El contacto principal para esta oportunidad. La función del contacto principal se mantiene sincronizada con este campo. Para donantes individuales, esto significa atribuciones por esta oportunidad.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MSF_CreateOrganizationAccounts_TEST.cls
/**
* @author       Deloitte
* @date         01-2019
* @group        Contact.
* @description  Test class for the MSF_CreateOrganizationAccounts_TDTM class.
*/
@isTest
private class MSF_CreateOrganizationAccounts_TEST {
    @testSetup static void setup(){
        //Create Trigger
        npsp__Trigger_Handler__c thCon = new npsp__Trigger_Handler__c(
            Name = 'TriggerTestCreateOrganizationAccounts',
            npsp__Class__c = 'MSF_CreateOrganizationAccounts_TDTM',
            npsp__Object__c = 'Contact',
            npsp__Trigger_Action__c = 'BeforeUpdate;AfterDelete;AfterUpdate',
            npsp__Active__c = true,
            npsp__Load_Order__c = 4,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );        
        upsert thCon; 
        //Initialize values
        Account acc = new Account(Name='MSF_AccountFieldsLogic_TEST_Name1');
        insert acc;

        Account acc2 = new Account(Name='MSF_AccountFieldsLogic_TEST_Name2');
        insert acc2;
        
        Contact cont = new Contact(LastName='MSF_AccountFieldsLogic_TEST_LastName1');
        cont.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization').getRecordTypeId();
        cont.AccountId = acc.Id;
        
        insert cont;
        
        Contact cont2 = new Contact(LastName='MSF_AccountFieldsLogic_TEST_LastName1OC');
        cont2.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization_Contact').getRecordTypeId();
        cont2.msf_Organization__c = cont.Id;
        insert cont2;
        
        Contact cont3 = new Contact(LastName='MSF_AccountFieldsLogic_TEST_LastName2OC');
        cont3.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization').getRecordTypeId();
        cont3.AccountId = acc2.Id;
        insert cont3;
        
        
        Opportunity opp = new Opportunity(npsp__Primary_Contact__c=cont.Id);
        opp.Name='testUpdateCreateOrganizationAccountsSetAccName1';
        opp.StageName='Propuesta';
        opp.CloseDate = date.today();
        
        insert opp;
                
    }
    @isTest static void testUpdateCreateOrganizationAccounts(){
        List<Contact> cont = [SELECT Id,LastName FROM Contact WHERE LastName = 'MSF_AccountFieldsLogic_TEST_LastName1' LIMIT 1];
        cont[0].LastName='MSF_AccountFieldsLogic_TEST_LastName2';
        update cont;
        cont = [SELECT Id FROM Contact WHERE LastName = 'MSF_AccountFieldsLogic_TEST_LastName2' LIMIT 1];
        System.assertNotEquals(0,cont.size());
    }
    
    @isTest static void testUpdateCreateOrganizationAccountsWithoutAcc(){
        Contact cont = [SELECT Id,LastName FROM Contact WHERE LastName = 'MSF_AccountFieldsLogic_TEST_LastName1' LIMIT 1];
        cont.LastName='MSF_AccountFieldsLogic_TEST_LastName2';
        cont.AccountId = null;
        update cont;
        cont = [SELECT Id, AccountId FROM Contact WHERE LastName = 'MSF_AccountFieldsLogic_TEST_LastName2' LIMIT 1];
        System.assertNotEquals(null,cont.AccountId);
    }
    
    @isTest static void testUpdateCreateOrganizationAccountsSetAcc(){
        Account acc = new Account(Name='MSF_AccountFieldsLogic_TEST_Name141');
        insert acc;
        acc = [SELECT Id FROM Account WHERE Name = 'MSF_AccountFieldsLogic_TEST_Name141'];
        
        Contact cont = [SELECT Id,LastName FROM Contact WHERE LastName = 'MSF_AccountFieldsLogic_TEST_LastName1' LIMIT 1];
        cont.LastName='MSF_AccountFieldsLogic_TEST_LastName2';
        cont.AccountId = acc.Id;
        update cont;
        
        cont = [SELECT Id, AccountId FROM Contact WHERE LastName = 'MSF_AccountFieldsLogic_TEST_LastName2' LIMIT 1];
        System.assertNotEquals(cont.AccountId,null);
    }
    
    @isTest static void testUpdateCreateOrganizationAccountsMoveOpportunities(){
        Account acc = new Account(Name='MSF_AccountFieldsLogic_TEST_Name141');
        insert acc;
        acc = [SELECT Id FROM Account WHERE Name = 'MSF_AccountFieldsLogic_TEST_Name141'];
        
        Contact cont = [SELECT Id,LastName FROM Contact WHERE LastName = 'MSF_AccountFieldsLogic_TEST_LastName1' LIMIT 1];
        cont.LastName='MSF_AccountFieldsLogic_TEST_LastName2';
        cont.AccountId = acc.Id;
                
        update cont;
        
        cont = [SELECT Id, AccountId FROM Contact WHERE LastName = 'MSF_AccountFieldsLogic_TEST_LastName2' LIMIT 1];
        System.assertNotEquals(cont.AccountId,null);
    }
    
    @isTest static void testUpdateCreateOrganizationAccountsMoveContacts(){
        Contact contOrg = new Contact(LastName='MSF_AccountFieldsLogic_TEST_Name141');
        contOrg.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization').getRecordTypeId();
        insert contOrg;
        contOrg = [SELECT Id FROM Contact WHERE LastName = 'MSF_AccountFieldsLogic_TEST_Name141'];

        Account acc = new Account(Name='MSF_AccountFieldsLogic_TEST_Name141');
        insert acc;
        acc = [SELECT Id FROM Account WHERE Name = 'MSF_AccountFieldsLogic_TEST_Name141'];
        
        Contact cont = [SELECT Id,LastName FROM Contact WHERE LastName = 'MSF_AccountFieldsLogic_TEST_LastName2OC' LIMIT 1];
        cont.LastName='MSF_AccountFieldsLogic_TEST_LastName2';
        cont.AccountId = acc.Id;
        cont.msf_Organization__c=contOrg.Id;
        
        Opportunity opp = new Opportunity(npsp__Primary_Contact__c=cont.Id);
        opp.Name='testUpdateCreateOrganizationAccountsSetAccName1';
        opp.StageName='Propuesta';
        opp.CloseDate = date.today();
        
        insert opp;
        
        update cont;
        
        cont = [SELECT Id, AccountId FROM Contact WHERE LastName = 'MSF_AccountFieldsLogic_TEST_LastName2' LIMIT 1];
        System.assertNotEquals(cont.AccountId,null);
    }

    @isTest static void testDeleteCreateOrganizationContacts(){
        Contact cont = [SELECT Id, LastName FROM Contact WHERE LastName = 'MSF_AccountFieldsLogic_TEST_LastName1' LIMIT 1];
        delete cont;
        List<Contact> result = [SELECT Id, LastName FROM Contact WHERE LastName = 'MSF_AccountFieldsLogic_TEST_LastName1' LIMIT 1];
        System.assert(result.isEmpty(), 'Contact still exists');
    }
    
    @isTest static void testDeleteCreateOrganizationAccounts(){
        Contact cont = [SELECT Id,AccountId FROM Contact WHERE LastName = 'MSF_AccountFieldsLogic_TEST_LastName2OC' LIMIT 1];
        delete cont;

        List<Contact> result = [SELECT Id, Name FROM Contact WHERE LastName = 'MSF_AccountFieldsLogic_TEST_LastName2OC' LIMIT 1];
        System.assert(result.isEmpty(), 'Contact still exists');
        
        List<Account> resultAcc = [SELECT Id FROM Account WHERE Name = 'MSF_AccountFieldsLogic_TEST_Name2' LIMIT 1];
        System.assert(resultAcc.isEmpty(), 'Account still exists');
    }
}