force-app/main/default/objects/Account/fields/msf_IsOrganizationGroup__c.field-meta.xml
<CustomField>
    <fullName>msf_IsOrganizationGroup__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es un grupo de Empresas u Organizaciones</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/msf_PromoterIndividual__c.field-meta.xml
<CustomField>
    <fullName>msf_PromoterIndividual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campañas de promotor</relationshipLabel>
    <relationshipName>Campanas_promotor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_ContactInformationSummary__c.field-meta.xml
<CustomField>
    <fullName>msf_ContactInformationSummary__c</fullName>
    <label>Resumen de los datos de contacto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_IsAssosiative__c.field-meta.xml
<CustomField>
    <fullName>msf_IsAssosiative__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es asociado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_IsPrimary__c.field-meta.xml
<CustomField>
    <fullName>msf_IsPrimary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es contacto principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_IsPublicPerson__c.field-meta.xml
<CustomField>
    <fullName>msf_IsPublicPerson__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Implica exclusión programa de prospectos.</inlineHelpText>
    <label>Es persona pública</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_Level__c.field-meta.xml
<CustomField>
    <fullName>msf_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level económico</label>
    <referenceTo>npsp__Level__c</referenceTo>
    <relationshipLabel>Contactos</relationshipLabel>
    <relationshipName>Contactos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_MainEmail__c.field-meta.xml
<CustomField>
    <fullName>msf_MainEmail__c</fullName>
    <label>Email principal</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_MemberType__c.field-meta.xml
<CustomField>
    <fullName>msf_MemberType__c</fullName>
    <defaultValue>&apos;Nada&apos;</defaultValue>
    <label>Tipo de miembro</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_NIF__c.field-meta.xml
<CustomField>
    <fullName>msf_NIF__c</fullName>
    <label>NIF/NIE/CIF</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_Organization__c.field-meta.xml
<CustomField>
    <fullName>msf_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organización</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contactos de organización</relationshipLabel>
    <relationshipName>Organization</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_OrganizationType__c.field-meta.xml
<CustomField>
    <fullName>msf_OrganizationType__c</fullName>
    <label>Tipo de organización</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Company</fullName>
                <default>true</default>
                <label>Company</label>
            </value>
            <value>
                <fullName>Public Entity</fullName>
            </value>
            <value>
                <fullName>Collective</fullName>
            </value>
            <value>
                <fullName>Foundation</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
                <isActive>false</isActive>
                <label>Anonymous</label>
            </value>
            <value>
                <fullName>Channel Partner / Reseller</fullName>
                <isActive>false</isActive>
                <label>Channel Partner / Reseller</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <isActive>false</isActive>
                <label>Corporate</label>
            </value>
            <value>
                <fullName>Customer - Channel</fullName>
                <isActive>false</isActive>
                <label>Customer - Channel</label>
            </value>
            <value>
                <fullName>Customer - Direct</fullName>
                <isActive>false</isActive>
                <label>Customer - Direct</label>
            </value>
            <value>
                <fullName>Government</fullName>
                <isActive>false</isActive>
                <label>Government</label>
            </value>
            <value>
                <fullName>Household</fullName>
                <isActive>false</isActive>
                <label>Household</label>
            </value>
            <value>
                <fullName>Individual</fullName>
                <isActive>false</isActive>
                <label>Individual</label>
            </value>
            <value>
                <fullName>Installation Partner</fullName>
                <isActive>false</isActive>
                <label>Installation Partner</label>
            </value>
            <value>
                <fullName>Nonprofit</fullName>
                <isActive>false</isActive>
                <label>Nonprofit</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
                <isActive>false</isActive>
                <label>Technology Partner</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_OrgContactType__c.field-meta.xml
<CustomField>
    <fullName>msf_OrgContactType__c</fullName>
    <formula>IF(AND(msf_IsActive__c,msf_IsPrimary__c), $Label.MSF_CONTACT_FORMULA_PRIMARY_CONTACT,
    IF(AND(msf_IsActive__c,!msf_IsPrimary__c), $Label.MSF_CONTACT_FORMULA_NOT_PRIMARY_CONTACT_ACTIVE , 
    $Label.MSF_CONTACT_FORMULA_CONTACT_INACTIVE ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de contacto de organización</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_PercomsSummary__c.field-meta.xml
<CustomField>
    <fullName>msf_PercomsSummary__c</fullName>
    <label>Resumen percoms</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>msf_PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contacto principal</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No es un contacto de tipo contacto organización</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organization Contact</value>
        </filterItems>
        <filterItems>
            <field>Contact.msf_Organization__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.msf_IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contactos Principales</relationshipLabel>
    <relationshipName>Contactos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_Program__c.field-meta.xml
<CustomField>
    <fullName>msf_Program__c</fullName>
    <label>Programa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Retención 1r año MASS</fullName>
            </value>
            <value>
                <fullName>Cultivación socios MASS</fullName>
            </value>
            <value>
                <fullName>Cultivación/conversión Donantes MASS</fullName>
            </value>
            <value>
                <fullName>Reactivación bajas MASS</fullName>
            </value>
            <value>
                <fullName>Conversión prospectos</fullName>
            </value>
            <value>
                <fullName>Reactivación/conversión EXDonantes MASS</fullName>
            </value>
            <value>
                <fullName>Otros programas transversales</fullName>
            </value>
            <value>
                <fullName>Retención 1r año MID</fullName>
            </value>
            <value>
                <fullName>Cultivación socios MID</fullName>
            </value>
            <value>
                <fullName>Cultivación/conversión Donantes MID</fullName>
            </value>
            <value>
                <fullName>Reactivación/conversión EXDonantes MID</fullName>
            </value>
            <value>
                <fullName>Reactivación bajas MID</fullName>
            </value>
            <value>
                <fullName>Mid+ Donors</fullName>
            </value>
            <value>
                <fullName>Testamentarios</fullName>
            </value>
            <value>
                <fullName>Otros 12Few+</fullName>
            </value>
            <value>
                <fullName>Major Donors</fullName>
            </value>
            <value>
                <fullName>Potenciales a Major Donors</fullName>
            </value>
            <value>
                <fullName>Públicos Especiales</fullName>
            </value>
            <value>
                <fullName>Otros 121</fullName>
            </value>
            <value>
                <fullName>Vehículo donación de Gran Donante = YES</fullName>
            </value>
            <value>
                <fullName>Prospectos Empresas &amp; Colectivos Mass</fullName>
            </value>
            <value>
                <fullName>Prospectos Fundaciones Mass</fullName>
            </value>
            <value>
                <fullName>Fundaciones Mass</fullName>
            </value>
            <value>
                <fullName>Empresas y Colectivos Mass</fullName>
            </value>
            <value>
                <fullName>Instituciones Públicas Mass</fullName>
            </value>
            <value>
                <fullName>Fundaciones Mid, Mid +</fullName>
            </value>
            <value>
                <fullName>Empresas y Colectivos Mid, Mid +</fullName>
            </value>
            <value>
                <fullName>Instituciones Públicas Mid y Mid +</fullName>
            </value>
            <value>
                <fullName>Fundaciones Estratégicas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_RelationshipLevel__c.field-meta.xml
<CustomField>
    <fullName>msf_RelationshipLevel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level de relación</label>
    <referenceTo>npsp__Level__c</referenceTo>
    <relationshipLabel>Contactos (Level de relación)</relationshipLabel>
    <relationshipName>Contactos2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_Seniority__c.field-meta.xml
<CustomField>
    <fullName>msf_Seniority__c</fullName>
    <formula>IF(ISBLANK(npo02__FirstCloseDate__c),
  0,
  (TODAY() - npo02__FirstCloseDate__c) / 365
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Antigüedad en años colaborador MSF</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <description>Indicates if this Contact is designated as the Primary Contact on their Account (read only).</description>
    <formula>Account.npe01__One2OneContact__c = Id</formula>
    <inlineHelpText>Este campo esta seleccionado si es el contacto principal en la cuenta. El contacto principal puede editarse en la cuenta.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Organization_Contact.recordType-meta.xml
<RecordType>
    <fullName>Organization_Contact</fullName>
    <active>true</active>
    <label>Organization Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/msf_Program__c.field-meta.xml
<CustomField>
    <fullName>msf_Program__c</fullName>
    <label>Programa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Contact for this Opportunity. If this is an individual Donation, NPSP attributes the Donation to the Primary Contact. If this is an organizational Donation, NPSP attributes a soft credit to the Primary Contact.</description>
    <inlineHelpText>El contacto principal para esta oportunidad. La función del contacto principal se mantiene sincronizada con este campo. Para donantes individuales, esto significa atribuciones por esta oportunidad.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MSF_SummarySection_CONTROLLER.cls
public with sharing class MSF_SummarySection_CONTROLLER {
    
    @AuraEnabled
    public static Object getContact(Id idContact){
        Contact c;
        Account acc;
        String lvl;
        String program;
        Map<String,Object> out = new Map<String,Object>();
        try{
    	c = [SELECT RecordType.DeveloperName, toLabel(RecordType.Name),  toLabel(msf_OrganizationType__c), 
             msf_OrgContactType__c, msf_RelationshipLevel__r.Name, msf_Level__r.Name, msf_PrimaryContact__c,
             msf_Program__c, msf_MainEmail__c, msf_NIF__c, msf_IsPrimary__c,  msf_MemberType__c,
             msf_ContactInformationSummary__c, msf_PercomsSummary__c, msf_Seniority__c, msf_IsAssosiative__c, msf_IsPublicPerson__c,             
             msf_Organization__r.Name, msf_Organization__r.msf_RelationshipLevel__r.Name, msf_Organization__r.msf_Program__c,
             AccountId
             FROM Contact 
             WHERE Id =: idContact
             LIMIT 1];

            lvl = c.msf_RelationshipLevel__r.Name;
            program = c.msf_Program__c;
            
            if(c.RecordType.DeveloperName == 'Organization_Contact'){          
                lvl = (c.msf_Organization__r.msf_RelationshipLevel__r.Name != null ? c.msf_Organization__r.msf_RelationshipLevel__r.Name : '') ; 
                program = (c.msf_Organization__r.msf_Program__c != null ? c.msf_Organization__r.msf_Program__c : '');
            }
            
            if(c.AccountId != null){
                acc = [SELECT Name, msf_IsOrganizationGroup__c FROM Account WHERE id=:c.AccountId LIMIT 1];
            }
            out.put('c',c);   
 			out.put('lvl',lvl);
            out.put('program',program);
            out.put('acc',acc);
            
        }catch(exception e){
            System.debug('ERROR');
        }
        return out;
    }

    @AuraEnabled
    public static Boolean getProm(Id idContact, String rtDevName){
        List<Campaign> result = [SELECT Id FROM Campaign  WHERE msf_PromoterIndividual__c =: idContact LIMIT 1];
        if(result.size()>0){
            return true; 
        }else{
            return false;
        }    
    }
    
    @AuraEnabled
    public static Object getCaso(Id idContact){
        Map<String,Object> out = new Map<String,Object>();
        List<Case> cases = [SELECT id FROM Case WHERE ContactId=: idContact AND IsClosed = false];
        out.put('case',cases.size());
        return out;
    }
    
    @AuraEnabled
    public static Object getOpor(Id idContact){
        Map<String,Object> out = new Map<String,Object>();
        out.put('boda',false);
        out.put('apor',false);
        out.put('her',false);
        out.put('herStage','');
        for(Opportunity o : [SELECT Type, StageName FROM Opportunity WHERE npsp__Primary_Contact__c =: idContact  AND ((CreatedDate = LAST_90_DAYS AND isWon = false AND StageName IN ('Impagada','Devuelta') ) OR (Type IN ('Solidarity Wedding','Herencia') AND StageName != 'Cancelada' ))]){  //#31790
            if(o.Type == 'Solidarity Wedding'){ 
                out.put('boda',true);
            }else if(o.Type == 'Herencia'){ 
                out.put('her',true);
                out.put('herStage', o.StageName);
            }else{ 
                out.put('apor',true);
            }
		}
        return out;
    }
    
    @AuraEnabled
    public static Boolean getVD(Id idContact){
        List<Opportunity> result = [SELECT id , name FROM Opportunity WHERE npsp__Primary_Contact__c =: idContact AND msf_IsDonationVehicle__c = true LIMIT 1];
        if(result.isEmpty()){
            return false;    
        }else{
        	return true;    
        }            
    }
    
    @AuraEnabled
    public static Boolean getDuplicate(Id idContact){
        List<npe4__Relationship__c> result = [SELECT id FROM npe4__Relationship__c WHERE npe4__Type__c = 'Duplicate' AND npe4__Contact__c =: idContact LIMIT 1];
        if(result.isEmpty()){
            return false;    
        }else{
        	return true;    
        } 
    }
}