force-app/main/default/objects/Account/fields/msf_IsOrganizationGroup__c.field-meta.xml
<CustomField>
    <fullName>msf_IsOrganizationGroup__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es un grupo de Empresas u Organizaciones</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/msf_IsPrimaryContactOrg__c.field-meta.xml
<CustomField>
    <fullName>msf_IsPrimaryContactOrg__c</fullName>
    <formula>IF(ISBLANK(npe01__One2OneContact__c ),
  FALSE,
  IF( npe01__One2OneContact__r.RecordType.DeveloperName = &apos;Organization&apos;, TRUE, FALSE)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Es organización el contacto principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/npe01__SYSTEM_AccountType__c.field-meta.xml
<CustomField>
    <fullName>npe01__SYSTEM_AccountType__c</fullName>
    <description>Hidden system field: do not change.  Updated by automatic processes.</description>
    <inlineHelpText>Indica el modelo de cuenta: Familia, Uno-a-Uno o Individual.</inlineHelpText>
    <label>_SYSTEM: AccountType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/HH_Account.recordType-meta.xml
<RecordType>
    <fullName>HH_Account</fullName>
    <active>true</active>
    <description>An Account representing a Household containing one or more individuals</description>
    <label>Household Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <description>An Account representing an organization</description>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/Contact/fields/npe01__SystemIsIndividual__c.field-meta.xml
<CustomField>
    <fullName>npe01__SystemIsIndividual__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Deprecated field.  Do not use.</description>
    <inlineHelpText>Este campo ya no se usa. Debe reemplazarse con Tipo de cuenta.</inlineHelpText>
    <label>_SYSTEM: IsIndividual - DEPRECATED</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <label>Organization</label>
</RecordType>

force-app/main/default/classes/MSF_AccountFieldsLogic_TDTM.cls
/**
* @author 		Deloitte
* @date 		10-2018
* @group 		Account
* @description	ContactInformationSummary and PercomsSummary fields management.
*/
global without sharing class MSF_AccountFieldsLogic_TDTM extends npsp.TDTM_Runnable {
    
    /*******************************************************************************************************
    * @description	Trigger Handler on Account that handles ***
    * @param 		listNew the list of Account from trigger new. 
    * @param 		listOld the list of Account from trigger old. 
    * @param 		triggerAction which trigger event (BeforeInsert, AfterInsert, etc.). 
    * @param 		objResult the describe for Account
    * @return 		dmlWrapper. 
    ********************************************************************************************************/
    global override npsp.TDTM_Runnable.DmlWrapper run(List<SObject> newlist, List<SObject> oldlist, npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult){
                
        //Attributes
        List<Account> lNewAcc = (List<Account>) newlist;
        List<Account> lOldAcc = (List<Account>) oldlist;
        Map<Id, Account> mOldAcc = new Map<Id, Account>();
        if(lOldAcc != null){            
            mOldAcc.putAll(lOldAcc);
        }
		
        //BEFORE INSERT && BEFORE UPDATE
        if(triggerAction == npsp.TDTM_Runnable.Action.BeforeInsert || triggerAction == npsp.TDTM_Runnable.Action.BeforeUpdate) {      
 	
            Id IdOrgRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Organization').getRecordTypeId(); 
            Id IdHHRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('HH_Account').getRecordTypeId(); 
            
            Set<Id> sPrimaryContacts = new Set<Id>();
            Map<Id, Contact> mNames = new Map<Id, Contact>();
            for(Account a : lNewAcc){
                if(a.npe01__One2OneContact__c != null) {
                	sPrimaryContacts.add(a.npe01__One2OneContact__c);    
                }                    
            }
            
            mNames.putAll([SELECT Id, LastName FROM Contact WHERE ID IN: sPrimaryContacts AND RecordType.Name = 'Organization']);
            
            for(Account a : lNewAcc){
                if(a.RecordTypeId == IdHHRT && a.npe01__One2OneContact__c != null && a.msf_IsPrimaryContactOrg__c && a.CreatedDate != null && a.CreatedDate.date() == date.today()) {
                    a.RecordTypeId = IdOrgRT;
                    a.Type = 'Company';
                    a.npe01__SYSTEM_AccountType__c = null;
                    a.npe01__SYSTEMIsIndividual__c = false;
                    if(!mNames.isEmpty() && mNames.containskey(a.npe01__One2OneContact__c)){
                    	a.Name = 'CUENTA - '+ mNames.get(a.npe01__One2OneContact__c).LastName;   
                    }                    
                }
                else if(a.RecordTypeId == IdOrgRT) {
                    if(!a.msf_IsOrganizationGroup__c && !mNames.isEmpty() && mNames.containskey(a.npe01__One2OneContact__c)){
                    	a.Name = 'CUENTA - '+ mNames.get(a.npe01__One2OneContact__c).LastName;     
                    }
                    if(!a.Name.startsWith('CUENTA - ')){
                    	a.Name = 'CUENTA - '+ a.Name;     
                    }                                                         
                }
                setAccountCountry(a);
            }
        }
        
        return null; 
    }  
    
	// PRIVATE METHODS
    
    private static void setAccountCountry(Account a) {
        if (a.BillingStreet != null && a.BillingCountry == null) {
            a.BillingCountry = 'España'; 
        }
        
        if (a.ShippingStreet != null && a.ShippingCountry == null) {
            a.ShippingCountry = 'España'; 
        }
    }
}