force-app/main/default/objects/msf_Modelo182__c/msf_Modelo182__c.object-meta.xml
<CustomObject>
    <description>Objeto para la creación y gestión del modelo 182</description>
    <label>Modelo182</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modelo182</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_Modelo182__c/fields/msf_Anterior__c.field-meta.xml
<CustomField>
    <fullName>msf_Anterior__c</fullName>
    <defaultValue>&quot;0000000000000&quot;</defaultValue>
    <description>Número identificativo de la declaración anterior.</description>
    <inlineHelpText>Número identificativo de la declaración anterior.</inlineHelpText>
    <label>Anterior</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_Modelo182__c/fields/msf_Anyo_fiscal__c.field-meta.xml
<CustomField>
    <fullName>msf_Anyo_fiscal__c</fullName>
    <defaultValue>TEXT(YEAR( TODAY())-1)</defaultValue>
    <description>Año fiscal</description>
    <inlineHelpText>Año fiscal</inlineHelpText>
    <label>Año fiscal</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_Modelo182__c/fields/msf_caracter__c.field-meta.xml
<CustomField>
    <fullName>msf_caracter__c</fullName>
    <description>Valores permitidos: C / S / blanco, en el caso excepcional de segunda o posterior presentación de declaraciones.</description>
    <inlineHelpText>Valores permitidos: C / S / blanco, en el caso excepcional de segunda o posterior presentación de declaraciones.</inlineHelpText>
    <label>caracter</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nueva</fullName>
                <default>true</default>
                <label>Nueva</label>
            </value>
            <value>
                <fullName>Complementaria</fullName>
            </value>
            <value>
                <fullName>Sustitutiva</fullName>
            </value>
            <value>
                <fullName>C</fullName>
                <isActive>false</isActive>
                <label>C</label>
            </value>
            <value>
                <fullName>S</fullName>
                <isActive>false</isActive>
                <label>S</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_Modelo182__c/fields/msf_Estado__c.field-meta.xml
<CustomField>
    <fullName>msf_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Iniciando proceso</fullName>
                <default>true</default>
                <label>Iniciando proceso</label>
            </value>
            <value>
                <fullName>Recalculando 4º año</fullName>
            </value>
            <value>
                <fullName>Generando fichero</fullName>
            </value>
            <value>
                <fullName>Enviando al Chatter</fullName>
            </value>
            <value>
                <fullName>Finalizado OK</fullName>
            </value>
            <value>
                <fullName>Finalizado Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_Modelo182__c/fields/msf_Justificante__c.field-meta.xml
<CustomField>
    <fullName>msf_Justificante__c</fullName>
    <defaultValue>&quot;0000000000000&quot;</defaultValue>
    <description>Se consignará el número de justificante correspondiente a la declaración. Campo de contenido numérico de 13 posiciones.</description>
    <inlineHelpText>Se consignará el número de justificante correspondiente a la declaración. Campo de contenido numérico de 13 posiciones.</inlineHelpText>
    <label>Justificante</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_Modelo182__c/fields/msf_Resultado__c.field-meta.xml
<CustomField>
    <fullName>msf_Resultado__c</fullName>
    <description>Pequeño resumen del log.</description>
    <inlineHelpText>Pequeño resumen del log</inlineHelpText>
    <label>Resultado</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Modelo182TriggerTest.cls
@isTest
private class Modelo182TriggerTest {
	@IsTest
    private static void testCalloutOK(){
        msf_Modelo182__c m182new = new msf_Modelo182__c(
        	Name='Test',
            msf_Anterior__c = '0000',
            msf_Anyo_fiscal__c=String.valueOf(Date.today().year()),
            msf_Justificante__c='0000',
            msf_caracter__c='Complementaria',
            msf_Estado__c = 'Iniciando proceso'
        );
        Test.setMock(HttpCalloutMock.class, new Modelo182HttpCalloutsMock_OK());
    	Test.startTest();
        insert m182new;
    	Test.stopTest();
        msf_Modelo182__c m182 = [select Id,msf_Estado__c,msf_Resultado__c from msf_Modelo182__c where Id = :m182new.Id limit 1];
        System.assertNotEquals(null, m182);
        System.assertEquals('OK - Status 200', m182.msf_Resultado__c);
        System.assertNotEquals('Finalizado Error', m182.msf_Estado__c);
    }
    
    @IsTest 
    private static void testCalloutKO(){
        msf_Modelo182__c m182new = new msf_Modelo182__c(
        	Name='Test',
            msf_Anterior__c = '0000',
            msf_Anyo_fiscal__c=String.valueOf(Date.today().year()),
            msf_Justificante__c='0000',
            msf_caracter__c='Complementaria',
            msf_Estado__c = 'Iniciando proceso'
        );
        Test.setMock(HttpCalloutMock.class, new Modelo182HttpCalloutsMock_400());
    	Test.startTest();
        insert m182new;
    	Test.stopTest();
        msf_Modelo182__c m182 = [select Id,msf_Estado__c,msf_Resultado__c from msf_Modelo182__c where Id = :m182new.Id limit 1];
        System.assertNotEquals(null, m182);
        System.assertEquals('Error - Status 400', m182.msf_Resultado__c);
        System.assertEquals('Finalizado Error', m182.msf_Estado__c);
    }
}