force-app/main/default/objects/msf_Modelo182__c/msf_Modelo182__c.object-meta.xml
<CustomObject>
    <description>Objeto para la creación y gestión del modelo 182</description>
    <label>Modelo182</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modelo182</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_Modelo182__c/fields/msf_Estado__c.field-meta.xml
<CustomField>
    <fullName>msf_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Iniciando proceso</fullName>
                <default>true</default>
                <label>Iniciando proceso</label>
            </value>
            <value>
                <fullName>Recalculando 4º año</fullName>
            </value>
            <value>
                <fullName>Generando fichero</fullName>
            </value>
            <value>
                <fullName>Enviando al Chatter</fullName>
            </value>
            <value>
                <fullName>Finalizado OK</fullName>
            </value>
            <value>
                <fullName>Finalizado Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_Modelo182__c/fields/msf_Resultado__c.field-meta.xml
<CustomField>
    <fullName>msf_Resultado__c</fullName>
    <description>Pequeño resumen del log.</description>
    <inlineHelpText>Pequeño resumen del log</inlineHelpText>
    <label>Resultado</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Modelo182Launcher.cls
public class Modelo182Launcher {
    @future (callout=true)
    public static void calloutLauncher(Id idModelo182){
        try{
        msf_Modelo182__c m182 = [select Id,msf_Estado__c,msf_Resultado__c from msf_Modelo182__c where Id = :idModelo182 limit 1];
       	Modelo182Callouts m182Callouts = new Modelo182Callouts();
       	HttpResponse resultado = m182Callouts.sendWebHook(idModelo182);
       	m182.msf_Resultado__c = resultado.getStatus() + ' - Status ' +  resultado.getStatusCode();
       	if (resultado.getStatusCode()!=200){
           	m182.msf_Estado__c = 'Finalizado Error';
           }
        update m182; 
        } catch(CalloutException e){
            ErrorException(idModelo182,e.getMessage());
           }
    }
    
    public static void ErrorException(Id idModelo182, String error){
         msf_Modelo182__c m182 = [select Id,msf_Estado__c,msf_Resultado__c from msf_Modelo182__c where Id = :idModelo182 limit 1];
         m182.msf_Resultado__c = error;
         m182.msf_Estado__c = 'Finalizado Error';
         update m182;
    }
}