force-app/main/default/objects/msf_IntegrationsControl__c/msf_IntegrationsControl__c.object-meta.xml
<CustomObject>
    <label>Importaciones e integraciones</label>
    <nameField>
        <displayFormat>CI-{0}</displayFormat>
        <label>Control Integraciones Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Importaciones e integraciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_IntegrationsControl__c/fields/msf_EndDatePeriod__c.field-meta.xml
<CustomField>
    <fullName>msf_EndDatePeriod__c</fullName>
    <label>Fecha fin periodo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/fields/msf_ProcessType__c.field-meta.xml
<CustomField>
    <fullName>msf_ProcessType__c</fullName>
    <label>Tipo de proceso</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAP Finance</fullName>
            </value>
            <value>
                <fullName>SAP HR</fullName>
            </value>
            <value>
                <fullName>Altiria</fullName>
            </value>
            <value>
                <fullName>Talones</fullName>
            </value>
            <value>
                <fullName>Fichero entrada único</fullName>
            </value>
            <value>
                <fullName>SAP ITR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/fields/msf_StartDatePeriod__c.field-meta.xml
<CustomField>
    <fullName>msf_StartDatePeriod__c</fullName>
    <label>Fecha inicio periodo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/fields/msf_Status__c.field-meta.xml
<CustomField>
    <fullName>msf_Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>En progreso</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Finalización correcta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/fields/msf_TypologyPaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>msf_TypologyPaymentMethod__c</fullName>
    <label>Tipologia forma de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <label>Orden Bancaria</label>
            </value>
            <value>
                <fullName>01</fullName>
                <label>Tarjeta Crédito</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Talones standard</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Transferencias</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Varios</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>TC On line</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Cheques varios</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Devolución OB</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>En especie - Servicio</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>En especie - inmovilizado</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Sellos Correo</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Trustly On line</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>PayPal</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Iniciativa solidaria On line</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Efectivo asociativo</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>ACMA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_IntegrationsControl__c/recordTypes/SAPFinance.recordType-meta.xml
<RecordType>
    <fullName>SAPFinance</fullName>
    <active>true</active>
    <label>SAP Finanzas</label>
</RecordType>

force-app/main/default/classes/MSF_IntegrationsControl_SCHED_02.cls
global without sharing class MSF_IntegrationsControl_SCHED_02 implements Schedulable{
	
    global void execute(SchedulableContext SC) {
        
        List<msf_IntegrationsControl__c> icToInsert = new List<msf_IntegrationsControl__c>();
        
        List<String> codes = new List<String>{'09', '10'};
            
        //Date; 
		Date startDate = Date.today().addYears(-1);
        Integer numberOfDays = Date.daysInMonth(startDate.year(), 12);
        
        Id recordTypeIdSAPFinance = Schema.SObjectType.msf_IntegrationsControl__c.getRecordTypeInfosByDeveloperName().get('SAPFinance').getRecordTypeId();
        
        for (String code : codes) {
            msf_IntegrationsControl__c ic = new msf_IntegrationsControl__c();
            ic.msf_ProcessType__c = 'SAP Finance'; 
            ic.msf_StartDatePeriod__c = Date.newInstance(startDate.year(), 1, 1);
            ic.msf_EndDatePeriod__c   = Date.newInstance(startDate.year(), 12, numberOfDays);
            ic.msf_TypologyPaymentMethod__c = code; 
            ic.msf_Status__c = 'Nuevo'; 
            ic.RecordTypeId = recordTypeIdSAPFinance;
                   
            icToInsert.add(ic);
        }
        
        insert icToInsert; 
        
    }

}