force-app/main/default/objects/Lead/fields/msf_AuxNIF__c.field-meta.xml
<CustomField>
    <fullName>msf_AuxNIF__c</fullName>
    <label>NIF/NIE (Tutor/Representante)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_HolderNIF__c.field-meta.xml
<CustomField>
    <fullName>msf_HolderNIF__c</fullName>
    <label>NIF/NIE (Titular)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANAccountNumber__c</fullName>
    <label>Número de cuenta</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANCode__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANCode__c</fullName>
    <label>Código IBAN</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANDC__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANDC__c</fullName>
    <label>Dígito de control</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANEntity__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANEntity__c</fullName>
    <label>Entidad</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANOffice__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANOffice__c</fullName>
    <label>Oficina</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_LeadSource2Level__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource2Level__c</fullName>
    <label>Canal de entrada 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_LeadSource3Level__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource3Level__c</fullName>
    <label>Canal de entrada 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource3</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_NIF__c.field-meta.xml
<CustomField>
    <fullName>msf_NIF__c</fullName>
    <description>VAT Number</description>
    <label>NIF/NIE/CIF</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>msf_PaymentMethod__c</fullName>
    <label>Método de pago</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>msf_ExemptOfPayment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domiciliación bancaria</fullName>
            </value>
            <value>
                <fullName>Tarjeta de crédito o débito</fullName>
            </value>
            <value>
                <fullName>ACMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_LeadSourceMasterData__c/msf_LeadSourceMasterData__c.object-meta.xml
<CustomObject>
    <label>Maestro de datos de LeadSource</label>
    <nameField>
        <displayFormat>MD_LS_{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maestro de datos de LeadSource</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_LeadSourceMasterData__c/fields/msf_LeadSource3__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource3__c</fullName>
    <label>Canal de entrada 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource3</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/globalValueSets/MSF_LeadSource2.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Correo postal sin cupón</fullName>
    </customValue>
    <customValue>
        <fullName>Cupón</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Entidad financiera</fullName>
    </customValue>
    <customValue>
        <fullName>Formulario web</fullName>
    </customValue>
    <customValue>
        <fullName>Mensajería Instantánea</fullName>
    </customValue>
    <customValue>
        <fullName>Otro</fullName>
    </customValue>
    <customValue>
        <fullName>Persona a persona</fullName>
    </customValue>
    <customValue>
        <fullName>Redes Sociales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono campaña</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Herencias y Legados</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfonos Officers</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfonos SAS</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono web</fullName>
    </customValue>
    <customValue>
        <fullName>Telemarketing</fullName>
    </customValue>
    <description>LeadSource Master Data</description>
    <masterLabel>LeadSource2</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/MSF_LeadSource3.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Correo postal</fullName>
    </customValue>
    <customValue>
        <fullName>Entidad financiera</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Personal</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono</fullName>
    </customValue>
    <customValue>
        <fullName>Otro</fullName>
    </customValue>
    <description>LeadSource Master Data</description>
    <masterLabel>LeadSource3</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MSF_LeadFieldsLogic_TEST.cls
/**
* @author 		Deloitte
* @date 		02-2019
* @group 		Lead
* @description	test class for the MSF_LeadFieldsLogic_TDTM class.
*/
@isTest
private class MSF_LeadFieldsLogic_TEST {
    @testSetup static void setup(){
        //Create Trigger
        npsp__Trigger_Handler__c thCon = new npsp__Trigger_Handler__c(
            Name = 'TriggerTestLeadFieldsLogic',
            npsp__Class__c = 'MSF_LeadFieldsLogic_TDTM',
            npsp__Object__c = 'Lead',
            npsp__Trigger_Action__c = 'BeforeInsert;BeforeUpdate',
            npsp__Active__c = true,
            npsp__Load_Order__c = 3,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );        
        upsert thCon; 
        //Initialize values
        Lead newLead = new Lead(LastName='MSF_LeadFieldsLogic_TEST_Name1',
                                Company='MSF_LeadFieldsLogic_TEST_DummyCompany');
        insert newLead;        
        
        List<msf_LeadSourceMasterData__c> lLeadSourceMD = new List<msf_LeadSourceMasterData__c>();
        List<String> leadSource = leadSource1Desc();
        List<String> leadSource2 = leadSource2Desc();
        List<String> leadSource3 = leadSource3Desc();
        for(Integer x = 0; x < leadSource.size(); x ++){
            msf_LeadSourceMasterData__c data = new msf_LeadSourceMasterData__c(msf_LeadSource1__c = leadSource[x], 
                                                                               msf_LeadSource2__c = LeadSource2[math.mod(x, leadSource2.size())], 
                                                                               msf_LeadSource3__c = LeadSource3[math.mod(x, leadSource3.size())]);
            lLeadSourceMD.add(data);
        }
        insert lLeadSourceMD;        
    }
    
    @isTest static void testInsertNif(){
        Lead l = new Lead(LastName='MSF_LeadFieldsLogic_TEST_LastName',
                          Company='MSF_LeadFieldsLogic_TEST_DummyCompany',
                          Street='Street',
                          msf_NIF__c='62796843N',
                          msf_AuxNIF__c='62796843N',
                          msf_HolderNIF__c='62796843N');
        insert l;
        l = [SELECt Id FROM Lead WHERE msf_NIF__c='62796843N' LIMIT 1];
        System.assertNotEquals(null,l,'Lead has not been created, probably DNI error');
    }
    
    @isTest static void testInsertCif(){
        Lead l = new Lead(LastName='MSF_LeadFieldsLogic_TEST_LastName',
                          Company='MSF_LeadFieldsLogic_TEST_DummyCompany',
                          msf_NIF__c='B52296126',
                          msf_AuxNIF__c='B52296126',
                          msf_HolderNIF__c='B52296126');
        insert l;
        l = [SELECt Id FROM Lead WHERE msf_NIF__c='B52296126' LIMIT 1];
        System.assertNotEquals(null,l,'Lead has not been created, probably DNI error');
    }
    
    @isTest static void testInsertOldCif(){
        Lead l = new Lead(LastName='MSF_LeadFieldsLogic_TEST_LastName',
                          Company='MSF_LeadFieldsLogic_TEST_DummyCompany',
                          msf_NIF__c='K4585653A',
                          msf_AuxNIF__c='K4585653A',
                          msf_HolderNIF__c='K4585653A');
        insert l;
        l = [SELECt Id FROM Lead WHERE msf_NIF__c='K4585653A' LIMIT 1];
        System.assertNotEquals(null,l,'Lead has not been created, probably DNI error');
    }
    
    @isTest static void testInsertNifCifNotValid(){
        try{
            Lead l = new Lead(LastName='MSF_LeadFieldsLogic_TEST_LastName',
                              Company='MSF_LeadFieldsLogic_TEST_DummyCompany',
                              msf_NIF__c='62796143T',
                              msf_AuxNIF__c='62796143T',
                              msf_HolderNIF__c='62796143T');
            insert l;
            System.assert(false, 'Record with an invalid DNI inserted.');
        }catch(DmlException ex){
            System.assert(true);            
        }
    }
    
    @isTest static void testInsertNifCifBadFormated(){
        try{
            Lead l = new Lead(LastName='MSF_LeadFieldsLogic_TEST_LastName',
                              Company='MSF_LeadFieldsLogic_TEST_DummyCompany',
                              msf_NIF__c='62796143*',
                              msf_AuxNIF__c='62796143*',
                              msf_HolderNIF__c='62796143*');
            insert l;
            System.assert(false, 'Record with a DNI with incorrect format inserted.');
        }catch(DmlException ex){
            System.assert(true);            
        }
    }
    
    @isTest static void testInsertIBAN(){
        Lead l = new Lead(LastName='MSF_LeadFieldsLogic_TEST_LastName',
                          Company='MSF_LeadFieldsLogic_TEST_DummyCompany',
                          msf_PaymentMethod__c = 'Domiciliación bancaria',
                          msf_IBANCode__c='ES83',
                          msf_IBANEntity__c='0138', 
                          msf_IBANOffice__c='8772', 
                          msf_IBANDC__c = '71',
                          msf_IBANAccountNumber__c = '8584470812');
        insert l;
        /*l = [SELECt Id FROM Lead WHERE LastName='MSF_LeadFieldsLogic_TEST_LastName' AND msf_IBANDC__c='71' LIMIT 1];
        System.assertNotEquals(null,l,'Lead has not been created, probably DNI error');*/
    }  
    
    @isTest static void testInsertBadIBAN(){
        try{            
            Lead l = new Lead(LastName='MSF_LeadFieldsLogic_TEST_LastName',
                              Company='MSF_LeadFieldsLogic_TEST_DummyCompany',
                              msf_PaymentMethod__c = 'Domiciliación bancaria',
                              msf_IBANCode__c='ES73',
                              msf_IBANEntity__c='0138', 
                              msf_IBANOffice__c='8772',
                              msf_IBANDC__c = '75',
                              msf_IBANAccountNumber__c = '8584478808');
            insert l;
            System.assert(false, 'Record with a IBAN with incorrect format inserted.');
        }catch(DmlException ex){
            System.debug('ex: '+ex);
            System.assert(true);
        }
    }
    
    @isTest static void testLeadsource(){
        List<msf_LeadSourceMasterData__c> values = [SELECT msf_LeadSource1__c, msf_LeadSource2__c, msf_LeadSource3__c 
                                                    FROM msf_LeadSourceMasterData__c 
                                                    WHERE msf_LeadSource1__c = :leadSource1Desc()[0] LIMIT 1];
        Lead l = [SELECT Id,LeadSource FROM Lead WHERE LastName = 'MSF_LeadFieldsLogic_TEST_Name1' LIMIT 1];
        l.LeadSource = values[0].msf_LeadSource1__c;
        update l;
        
        Lead l2 = [SELECT Id,LeadSource,msf_LeadSource2Level__c,msf_LeadSource3Level__c FROM Lead WHERE Id = :l.Id LIMIT 1];
        
        System.assertNotEquals(null, l2.msf_LeadSource2Level__c, 'Result is not null for msf_LeadSource2Level__c');
        System.assertNotEquals(null, l2.msf_LeadSource3Level__c, 'Result is not null for msf_LeadSource3Level__c');
    }
    
    private static List<String> leadSource1Desc(){
        Schema.DescribeFieldResult fieldResult = Lead.LeadSource.getDescribe(); 
        List<Schema.PicklistEntry> pickListValues = fieldResult.getPicklistValues();
        
        List<String> options = new List<String>();
        
        for(Schema.PicklistEntry p : pickListValues){
            options.add(p.getLabel());
        }
        return options;
    }
    
    private static List<String> leadSource2Desc(){
        Schema.DescribeFieldResult fieldResult = Lead.msf_LeadSource2Level__c.getDescribe(); 
        List<Schema.PicklistEntry> pickListValues = fieldResult.getPicklistValues();
        
        List<String> options = new List<String>();
        
        for(Schema.PicklistEntry p : pickListValues){
            options.add(p.getLabel());
        }
        return options;
    }
    
    private static List<String> leadSource3Desc(){
        Schema.DescribeFieldResult fieldResult = Lead.msf_LeadSource3Level__c.getDescribe(); 
        List<Schema.PicklistEntry> pickListValues = fieldResult.getPicklistValues();
        
        List<String> options = new List<String>();
        
        for(Schema.PicklistEntry p : pickListValues){
            options.add(p.getLabel());
        }
        return options;
    }
}