force-app/main/default/objects/Opportunity/fields/msf_IsFromLastMonths__c.field-meta.xml
<CustomField>
    <fullName>msf_IsFromLastMonths__c</fullName>
    <formula>IF(OR((CloseDate &gt;= (TODAY() - 365*2)),
		(msf_TypeFundraisingContribution__c = &apos;D&apos; &amp;&amp; CloseDate &gt;= (TODAY() - 365*5)),
		(CloseDate &lt;= (TODAY() - 365*2) &amp;&amp; CloseDate &gt;= (TODAY() - 365*5) &amp;&amp; NOT(ISPICKVAL(Type, &apos;Recurrent Donation&apos;)) &amp;&amp; NOT(ISPICKVAL(Type, &apos;Historical&apos;)) &amp;&amp; NOT(ISPICKVAL(Type, &apos;Membership&apos;)))
      ),
true,
false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Últimos meses</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_IsFromLastMonthsBool__c.field-meta.xml
<CustomField>
    <fullName>msf_IsFromLastMonthsBool__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Nuevo campo para comprobar si la fecha de cierre esta dentro de los últimos 2 años, o si es del tipo D en los últimos 5 años.</description>
    <label>Últimos meses Boolean</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_TypeFundraisingContribution__c.field-meta.xml
<CustomField>
    <fullName>msf_TypeFundraisingContribution__c</fullName>
    <formula>CASE(RecordType.DeveloperName , 
     
     &quot;Donation&quot;,CASE( Type ,
           &quot;Recurrent Donation&quot;,&quot;S&quot;,
           &quot;SMS Donor&quot;,&quot;D&quot;,
           &quot;One off Donation&quot;,&quot;D&quot;,
           &quot;SMS Operator&quot;,&quot;D&quot;,
           &quot;Employee or client Donation&quot;,&quot;D&quot;,
           &quot;Recovered Quota&quot;,&quot;S&quot;,
           &quot;Solidarity initiative&quot;,&quot;D&quot;,
           &quot;Solidarity Wedding&quot;,&quot;D&quot;,
           &quot;Solidarity Gift&quot;,&quot;D&quot;, null),

     &quot;Grant&quot;,IF(ISPICKVAL(Type, &quot;Grant&quot;), &quot;G&quot;, null),

     &quot;In_Kind_Gift&quot;,IF(ISPICKVAL(Type, &quot;In-Kind Gift&quot;), &quot;I&quot;, null),

     &quot;Matching_Gift&quot;,IF(ISPICKVAL(Type, &quot;Matching Gift&quot;), &quot;D&quot;, null),

     &quot;Membership&quot;,IF(ISPICKVAL(Type, &quot;Membership&quot;), &quot;A&quot;, null),

     &quot;Legacy&quot;,CASE( Type ,
           &quot;Herencia&quot;,&quot;H&quot;,
           &quot;Pago de Herencia&quot;,&quot;H&quot;, null),

      null

)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo aportación Fundraising</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Donation.recordType-meta.xml
<RecordType>
    <fullName>Donation</fullName>
    <active>true</active>
    <businessProcess>Donation</businessProcess>
    <description>Donation Received</description>
    <label>Donation</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Historical.recordType-meta.xml
<RecordType>
    <fullName>Historical</fullName>
    <active>true</active>
    <businessProcess>Donation</businessProcess>
    <label>Historical</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>A membership record type</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/classes/MSF_CheckUtimosMeses_QUEUEABLE.cls
/**
* @author 		Omega
* @date 		01/07/2021
* @group 		Opportunity
* @description	Job to check and update the field msf_IsFromLastMonthsBool__c ZenIT#25762
*/
public class MSF_CheckUtimosMeses_QUEUEABLE implements Queueable {
    
    Boolean process;

    public MSF_CheckUtimosMeses_QUEUEABLE(){
        this.process = true;
    }
    
    public void execute(QueueableContext context) {
		date lastTwoYears = date.today()-365*2;      
        date lastFiveYears = date.today()-365*5;   
        List<Opportunity> listOppToCheck = [ SELECT Id, msf_IsFromLastMonthsBool__c, msf_IsFromLastMonths__c From Opportunity where msf_IsFromLastMonthsBool__c = false and (
                                            (msf_TypeFundraisingContribution__c = 'D' AND CloseDate >=:lastFiveYears) OR
                                            (CloseDate >=:lastFiveYears AND CloseDate <= :lastTwoYears AND Type != 'Recurrent Donation' AND Type != 'Historical' AND Type != 'Membership'))Limit 100];      
        
        integer limite = 0;
        integer errors = 0;
        List<Opportunity> listOppToUpdate = new List<Opportunity>();
        
        for(Opportunity iOpp: listOppToCheck){
            
            limite++;            
           	
            if(iOpp.msf_IsFromLastMonths__c == true && iOpp.msf_IsFromLastMonthsBool__c == false ){
                iOpp.msf_IsFromLastMonthsBool__c = true;            
            	listOppToUpdate.add(iOpp);                
            }
            
            if(listOppToUpdate.size() > 0 && limite >= 10){ 
                limite = 0;
                try{
        			update listOppToUpdate;//Esta operación esta dentro de un bucle lo cual no es lo indicado, pero si lanzamos el update con todos las opp de golpe da CPU time limit, es una manera sencilla de hacerlo por bloques
                }catch(exception exc){
                    errors++;
                    System.debug('Exception: ' + exc);
                }
                listOppToUpdate.clear();
        	}
            
        }//END FOR     
        
        if(errors < 10){//si aún hay opp que no originen error
            List<Opportunity> listCheckIfThereIsMoreOpp = [ SELECT Id, msf_IsFromLastMonthsBool__c, msf_IsFromLastMonths__c From Opportunity where msf_IsFromLastMonthsBool__c = false and (
                                            (msf_TypeFundraisingContribution__c = 'D' AND CloseDate >=:lastFiveYears) OR
                                            (CloseDate >=:lastFiveYears AND CloseDate <= :lastTwoYears AND Type != 'Recurrent Donation' AND Type != 'Historical' AND Type != 'Membership'))Limit 100];   
            if(listCheckIfThereIsMoreOpp.size() >= 100){//si aún quedan opp que comprobar
                System.enqueueJob(new MSF_CheckUtimosMeses_QUEUEABLE());
            }
        }
    }
}