force-app/main/default/objects/Opportunity/fields/msf_LeadId__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidato</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Contact for this Opportunity. If this is an individual Donation, NPSP attributes the Donation to the Primary Contact. If this is an organizational Donation, NPSP attributes a soft credit to the Primary Contact.</description>
    <inlineHelpText>El contacto principal para esta oportunidad. La función del contacto principal se mantiene sincronizada con este campo. Para donantes individuales, esto significa atribuciones por esta oportunidad.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ConvertLeadToContact.cls
/**
 * @description       : 
 * @author            : sheredia@omegacrmconsulting.com
 * @group             : 
 * @last modified on  : 02-23-2022
 * @last modified by  : sheredia@omegacrmconsulting.com
**/
global with sharing class ConvertLeadToContact implements dupcheck.dc3Plugin.InterfaceConvert {

    global static void afterConvert(Database.LeadConvertResult leadConvertResult, Task taskData) {
        ID leadID = leadConvertResult.getLeadId();
        ID contactID = leadConvertResult.getContactId();

        if (contactID != NULL){
            List<Opportunity> oppFromLead = [SELECT ID, npsp__Primary_Contact__c, msf_LeadId__c FROM Opportunity WHERE msf_LeadId__c =: leadID];
            
            for (Opportunity opp : oppFromLead){
                opp.npsp__Primary_Contact__c = contactID;
                opp.msf_LeadId__c = null;
            }

            update oppFromLead;
        }

    }
    
    global static void beforeConvert(Database.LeadConvert leadConvertData) {
        

    }

    global static void convertFailed(Database.LeadConvert leadConvertData, dupcheck.dc3Exception.ConvertException exceptionData) {

    }

}