force-app/main/default/objects/Contact/fields/msf_Forced__c.field-meta.xml
<CustomField>
    <fullName>msf_Forced__c</fullName>
    <inlineHelpText>Implica cambio de level o programa.</inlineHelpText>
    <label>Level de relación o programa forzado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>121</fullName>
            </value>
            <value>
                <fullName>12Few</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelRelationshipScore__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelRelationshipScore__c</fullName>
    <description>Campo a partir del cual se calcula el nivel de relación: (10-None; 20-One to many; 30-One to few; 40-One to few+; 50-One to one )</description>
    <label>(Level) Relationship Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_Program__c.field-meta.xml
<CustomField>
    <fullName>msf_Program__c</fullName>
    <label>Programa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Retención 1r año MASS</fullName>
            </value>
            <value>
                <fullName>Cultivación socios MASS</fullName>
            </value>
            <value>
                <fullName>Cultivación/conversión Donantes MASS</fullName>
            </value>
            <value>
                <fullName>Reactivación bajas MASS</fullName>
            </value>
            <value>
                <fullName>Conversión prospectos</fullName>
            </value>
            <value>
                <fullName>Reactivación/conversión EXDonantes MASS</fullName>
            </value>
            <value>
                <fullName>Otros programas transversales</fullName>
            </value>
            <value>
                <fullName>Retención 1r año MID</fullName>
            </value>
            <value>
                <fullName>Cultivación socios MID</fullName>
            </value>
            <value>
                <fullName>Cultivación/conversión Donantes MID</fullName>
            </value>
            <value>
                <fullName>Reactivación/conversión EXDonantes MID</fullName>
            </value>
            <value>
                <fullName>Reactivación bajas MID</fullName>
            </value>
            <value>
                <fullName>Mid+ Donors</fullName>
            </value>
            <value>
                <fullName>Testamentarios</fullName>
            </value>
            <value>
                <fullName>Otros 12Few+</fullName>
            </value>
            <value>
                <fullName>Major Donors</fullName>
            </value>
            <value>
                <fullName>Potenciales a Major Donors</fullName>
            </value>
            <value>
                <fullName>Públicos Especiales</fullName>
            </value>
            <value>
                <fullName>Otros 121</fullName>
            </value>
            <value>
                <fullName>Vehículo donación de Gran Donante = YES</fullName>
            </value>
            <value>
                <fullName>Prospectos Empresas &amp; Colectivos Mass</fullName>
            </value>
            <value>
                <fullName>Prospectos Fundaciones Mass</fullName>
            </value>
            <value>
                <fullName>Fundaciones Mass</fullName>
            </value>
            <value>
                <fullName>Empresas y Colectivos Mass</fullName>
            </value>
            <value>
                <fullName>Instituciones Públicas Mass</fullName>
            </value>
            <value>
                <fullName>Fundaciones Mid, Mid +</fullName>
            </value>
            <value>
                <fullName>Empresas y Colectivos Mid, Mid +</fullName>
            </value>
            <value>
                <fullName>Instituciones Públicas Mid y Mid +</fullName>
            </value>
            <value>
                <fullName>Fundaciones Estratégicas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_RelationshipLevel__c.field-meta.xml
<CustomField>
    <fullName>msf_RelationshipLevel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level de relación</label>
    <referenceTo>npsp__Level__c</referenceTo>
    <relationshipLabel>Contactos (Level de relación)</relationshipLabel>
    <relationshipName>Contactos2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Individual_Contact.recordType-meta.xml
<RecordType>
    <fullName>Individual_Contact</fullName>
    <active>true</active>
    <label>Individual Contact</label>
</RecordType>

force-app/main/default/objects/npsp__Level__c/npsp__Level__c.object-meta.xml
<CustomObject>
    <description>Tracks the definition of levels, for any object.</description>
    <label>Level</label>
    <nameField>
        <label>Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Level__c/fields/npsp__Minimum_Amount__c.field-meta.xml
<CustomField>
    <fullName>npsp__Minimum_Amount__c</fullName>
    <description>The minimum amount needed for NPSP to assign this Level. If this field is empty, then NPSP will assign this Level to any amount less than this Level&apos;s Maximum Amount.</description>
    <inlineHelpText>La cantidad menor para ser asignado a este nivel. Si esta vacío, cualquier cantidad menor a la cantidad máxima de este nivel será asignado a este nivel.</inlineHelpText>
    <label>Minimum Amount (&gt;=)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MSF_ModifyLevelEconomico_TDTM.cls
/**
* @author 		Omega CRM
* @date 		11-2021
* @group 		Contacts
* @description	ContactInformationSummary and PercomsSummary fields management.
*/
global without sharing class MSF_ModifyLevelEconomico_TDTM extends npsp.TDTM_Runnable {
    
    global override npsp.TDTM_Runnable.DmlWrapper run(List<SObject> newlist, List<SObject> oldlist, npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult){

        //npsp.TDTM_Runnable.dmlWrapper dmlWrapper = new npsp.TDTM_Runnable.DmlWrapper();
        List<Contact> lNewCon = (List<Contact>) newlist;
        system.debug('lNewCon: ' + lNewCon);
        List<Contact> lOldCon = (List<Contact>) oldlist;
        system.debug('lOldCon: ' + lOldCon);
        Map<Id, Contact> mOldCon = new Map<Id, Contact>();
        if(lOldCon != null){            
            mOldCon.putAll(lOldCon);
        }

        //BEFORE UPDATE
        if(triggerAction == npsp.TDTM_Runnable.Action.BeforeUpdate) {
            List<Contact> listOrganizationContact = new List<Contact>();
            Set<Id> setOrganization = new Set<Id>();
            
            List<npsp__Level__c> levels = [SELECT Id, Name, npsp__Minimum_Amount__c FROM npsp__Level__c WHERE name = 'One to few+' OR name = 'One to one'];
            Id idLevelEcoFew = null;
            Id idLevelEcoOnetoOne = null;
            Decimal scoreFew = 0.0;
            Decimal scoreOneToOne = 0.0;

            for (npsp__Level__c level : levels){
                if (level.Name == 'One to few+'){
                    idLevelEcoFew = level.Id;
                    scoreFew = level.npsp__Minimum_Amount__c;
                }else if (level.Name == 'One to one'){
                    idLevelEcoOnetoOne = level.Id;
                    scoreOneToOne = level.npsp__Minimum_Amount__c;
                }
            }

            for(Contact c : lNewCon){
                if(c.RecordTypeId == Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Individual_Contact').getRecordTypeId()){
                    Contact oldContact = new Contact();
                    oldContact = mOldCon.get(c.Id);
                    if (c.msf_Forced__c != oldContact.msf_Forced__c && c.msf_Forced__c == '12Few'){
                        c.msf_RelationshipLevel__c = idLevelEcoFew;
                        c.msf_LevelRelationshipScore__c = scoreFew;
                        c.msf_Program__c = 'Mid+ Donors';
                    } else if (c.msf_Forced__c != oldContact.msf_Forced__c && c.msf_Forced__c == '121'){
                        c.msf_RelationshipLevel__c = idLevelEcoOnetoOne;
                        c.msf_LevelRelationshipScore__c = scoreOneToOne;
                        c.msf_Program__c = 'Major Donors';
                    }
                }
            } 
        }

        if(triggerAction == npsp.TDTM_Runnable.Action.BeforeInsert) {
            List<Contact> listOrganizationContact = new List<Contact>();
            Set<Id> setOrganization = new Set<Id>();
            
            List<npsp__Level__c> levels = [SELECT Id, Name, npsp__Minimum_Amount__c FROM npsp__Level__c WHERE name = 'One to few+' OR name = 'One to one'];
            Id idLevelEcoFew = null;
            Id idLevelEcoOnetoOne = null;
            Decimal scoreFew = 0.0;
            Decimal scoreOneToOne = 0.0;

            for (npsp__Level__c level : levels){
                if (level.Name == 'One to few+'){
                    idLevelEcoFew = level.Id;
                    scoreFew = level.npsp__Minimum_Amount__c;
                }else if (level.Name == 'One to one'){
                    idLevelEcoOnetoOne = level.Id;
                    scoreOneToOne = level.npsp__Minimum_Amount__c;
                }
            }

            for(Contact c : lNewCon){
                if(c.RecordTypeId == Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Individual_Contact').getRecordTypeId()){
                    if (c.msf_Forced__c == '12Few'){
                        c.msf_RelationshipLevel__c = idLevelEcoFew;
                        c.msf_LevelRelationshipScore__c = scoreFew;
                        c.msf_Program__c = 'Mid+ Donors';
                    } else if (c.msf_Forced__c == '121'){
                        c.msf_RelationshipLevel__c = idLevelEcoOnetoOne;
                        c.msf_LevelRelationshipScore__c = scoreOneToOne;
                        c.msf_Program__c = 'Major Donors';
                    }
                }
            } 
        }
        
        return null;
    }
}