force-app/main/default/objects/Contact/fields/msf_BeginDateMSF__c.field-meta.xml
<CustomField>
    <fullName>msf_BeginDateMSF__c</fullName>
    <description>This field is to register the first time in MSF</description>
    <label>Fecha alta MSF</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <description>Indicates if this Contact is designated as the Primary Contact on their Account (read only).</description>
    <formula>Account.npe01__One2OneContact__c = Id</formula>
    <inlineHelpText>Este campo esta seleccionado si es el contacto principal en la cuenta. El contacto principal puede editarse en la cuenta.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/cpm__Installment__c.object-meta.xml
<CustomObject>
    <description>Installments are the result of a Recurring Payment. Installments track the status of a invoice or a direct debit transaction.</description>
    <label>Installment</label>
    <nameField>
        <displayFormat>INST-{00000000}</displayFormat>
        <label>Installment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>cpm__Payment_Processor__c</fullName>
    <label>Payment Processor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>cpm__Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PaymentHub-SEPA</fullName>
            </value>
            <value>
                <fullName>PaymentHub-Redsys</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>cpm__Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Payment_Schedule__c</description>
    <label>Payment Schedule</label>
    <referenceTo>cpm__Payment_Schedule__c</referenceTo>
    <relationshipName>Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Status__c.field-meta.xml
<CustomField>
    <fullName>cpm__Status__c</fullName>
    <description>The status of this Installment.</description>
    <inlineHelpText>El estado de este installment</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Outstanding</fullName>
                <default>true</default>
                <label>Outstanding</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Pending recollection</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Partially paid</fullName>
            </value>
            <value>
                <fullName>Pending Processing</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/cpm__Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>Object is used to schedule Payment Runs in the future</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{000000000}</displayFormat>
        <label>Payment Schedule Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>cpm__Collection_Date__c</fullName>
    <description>Date when the payments should be collected by the bank. This is only used for direct debit methods with FinDock as processor (PaymentHub-BACS, PaymentHub-SEPA, etc.)</description>
    <label>Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>cpm__Payment_Processor__c</fullName>
    <label>Payment Processor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>cpm__PaymentMethod__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PaymentHub-SEPA</fullName>
            </value>
            <value>
                <fullName>PaymentHub-Redsys</fullName>
            </value>
            <value>
                <fullName>PaymentHub-MT940</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>cpm__PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>CreditCard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Run_Date__c.field-meta.xml
<CustomField>
    <fullName>cpm__Run_Date__c</fullName>
    <description>Date when payment schedule is run.</description>
    <inlineHelpText>¿Cuándo debe ejecutarse este pago?</inlineHelpText>
    <label>Run Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Selection_Date__c.field-meta.xml
<CustomField>
    <fullName>cpm__Selection_Date__c</fullName>
    <description>Installments with a due date on or before the selection date are collected if all other processing details match.</description>
    <inlineHelpText>La fecha en que se seleccionan los Pagos recurrentes dentro de esta ejecución del proceso de cobros</inlineHelpText>
    <label>Selection Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Status__c.field-meta.xml
<CustomField>
    <fullName>cpm__Status__c</fullName>
    <description>Set status to &apos;Scheduled&apos; unless otherwise instructed.</description>
    <inlineHelpText>El estado actual de este elemento programado</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Generating</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Contact for this Opportunity. If this is an individual Donation, NPSP attributes the Donation to the Primary Contact. If this is an organizational Donation, NPSP attributes a soft credit to the Primary Contact.</description>
    <inlineHelpText>El contacto principal para esta oportunidad. La función del contacto principal se mantiene sincronizada con este campo. Para donantes individuales, esto significa atribuciones por esta oportunidad.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MSF_Installments_TEST.cls
/**
* @author 		Deloitte
* @date 		05-2019
* @group 		Installment
* @description	test class for the MSF_Installments_TDTM class.
*/
@isTest
public class MSF_Installments_TEST {
    @testSetup static void setup(){
        //Create Trigger
        npsp__Trigger_Handler__c thCon = new npsp__Trigger_Handler__c(
            Name = 'TriggerTestInstallments',
            npsp__Class__c = 'MSF_Installments_TDTM',
            npsp__Object__c = 'cpm__Installment__c',
            npsp__Trigger_Action__c = 'BeforeInsert,AfterInsert,BeforeUpdate,AfterUpdate',
            npsp__Active__c = true,
            npsp__Load_Order__c = 1,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );
        upsert thCon;
        
        Contact c = new Contact(LastName='LastName1', msf_BeginDateMSF__c=date.today());
        insert c;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'testopp';
        opp.StageName = 'Propuesta'; 
        opp.CloseDate = Date.today().addDays(1);
       	opp.Amount = 100;
        opp.npsp__Primary_Contact__c = c.Id;
        //opp.npe03__Recurring_Donation__c = don.Id;
        insert opp;
        
        cpm__Payment_Schedule__c ps = new cpm__Payment_Schedule__c(); 
        ps.cpm__Status__c = 'Verified';
        ps.cpm__PaymentMethod__c = 'CreditCard'; 
        ps.cpm__Run_Date__c = Date.today(); 
        ps.cpm__Selection_Date__c = Date.today(); 
        ps.cpm__Target__c = 'none'; 
        ps.cpm__Collection_Date__c = Date.today();
        ps.cpm__Payment_Processor__c = 'PaymentHub-MT940'; 
        ps.cpm__Source__c = 'PaymentHub'; 
        insert ps; 
        
        cpm__Installment__c inst = new cpm__Installment__c();
       	inst.npsp4hub__Opportunity__c = opp.Id; 
       	inst.cpm__of_times_rejected__c = 0; 
        inst.cpm__Contact__c = c.Id;
        inst.msf_LeadSource__c = 'Telemarketing';
        inst.msf_Description__c = 'Descripcion test';
        //inst.cpm__Payment_Method__c = 'CreditCard';
        inst.cpm__Status__c = 'New';
        insert inst; 
        
    }
    
    @isTest
    private static void test() {
        Profile p = [SELECT Id FROM Profile WHERE Name='Fundraising'];    
        User u1 = new User(Alias = 'standt1',Country='United Kingdom',Email='testPaymentProfile@test.org',EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',LocaleSidKey='en_US',ProfileId = p.Id,TimeZoneSidKey='America/Los_Angeles', UserName='testPaymentProfile@test.org');
        insert u1;
        cpm__Installment__c inst = [SELECT Id, cpm__of_times_rejected__c,cpm__Last_ReasonCode_Received__c, 
                                    cpm__Last_Rejection_Date__c, cpm__Payment_Method__c
                                    FROM cpm__Installment__c  LIMIT 1];
       
        inst.cpm__of_times_rejected__c = 2; 
        inst.cpm__Last_ReasonCode_Received__c = '001'; 
        inst.cpm__Last_Rejection_Date__c = Date.today();
        inst.cpm__Payment_Method__c = 'CreditCard';

        System.runAs(u1){
            test.startTest();
            update inst; 
            test.stopTest();
        }
        system.assertEquals('CreditCard', inst.cpm__Payment_Method__c);
        
    }

    @isTest
    private static void test2() {
        Profile p = [SELECT Id FROM Profile WHERE Name='Fundraising'];    
        User u1 = new User(Alias = 'standt1',Country='United Kingdom',Email='testPaymentProfile@test.org',EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',LocaleSidKey='en_US',ProfileId = p.Id,TimeZoneSidKey='America/Los_Angeles', UserName='testPaymentProfile@test.org');
        insert u1;

        Contact contacto = [SELECT Id FROM Contact LIMIT 1];
        Opportunity opp = [SELECT Id, name, npe03__Recurring_Donation__c FROM Opportunity WHERE Name = 'testopp'];

        npe03__Recurring_Donation__c don = new npe03__Recurring_Donation__c();
        don.npe03__Contact__c = contacto.Id;
        don.npe03__Open_Ended_Status__c = 'Open';
        don.npsp4hub__Payment_Method__c = 'Direct Debit';
        don.npsp4hub__Payment_Processor__c  = 'PaymentHub-SEPA';
        don.npsp4hub__Target__c  = 'LA CAIXA CCC OPERATIVA';
        don.RecordTypeId = Schema.SObjectType.npe03__Recurring_Donation__c.getRecordTypeInfosByDeveloperName().get('Associate').getRecordTypeId();
        insert don;

        opp.npe03__Recurring_Donation__c = don.Id;
        update opp;

        cpm__Installment__c inst = [SELECT Id, cpm__of_times_rejected__c,cpm__Last_ReasonCode_Received__c, 
                                    cpm__Last_Rejection_Date__c, cpm__Payment_Method__c
                                    FROM cpm__Installment__c  LIMIT 1];
       
        inst.cpm__of_times_rejected__c = 2; 
        inst.cpm__Last_ReasonCode_Received__c = '001'; 
        inst.cpm__Last_Rejection_Date__c = Date.today();
        inst.cpm__Payment_Method__c = 'CreditCard';



        System.runAs(u1){
            test.startTest();
            update inst; 
            test.stopTest();
        }
        system.assertEquals('CreditCard', inst.cpm__Payment_Method__c);
    }
}