force-app/main/default/objects/Contact/fields/msf_FiscalFirstName__c.field-meta.xml
<CustomField>
    <fullName>msf_FiscalFirstName__c</fullName>
    <description>First name for generate fiscal documents</description>
    <label>Nombre fiscal</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_FiscalLastName1__c.field-meta.xml
<CustomField>
    <fullName>msf_FiscalLastName1__c</fullName>
    <description>last name for generate fiscal documents</description>
    <label>Apellido fiscal 1</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_FiscalLastName2__c.field-meta.xml
<CustomField>
    <fullName>msf_FiscalLastName2__c</fullName>
    <description>suffix for generate fiscal documents</description>
    <label>Apellido fiscal 2</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_fiscalNif__c.field-meta.xml
<CustomField>
    <fullName>msf_fiscalNif__c</fullName>
    <label>NIF fiscal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_OppFiscalAmountLastYear__c.field-meta.xml
<CustomField>
    <fullName>msf_OppFiscalAmountLastYear__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Importe total último año fiscal</description>
    <inlineHelpText>Importe total último año fiscal</inlineHelpText>
    <label>Importe total último año fiscal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_StartDate__c.field-meta.xml
<CustomField>
    <fullName>msf_StartDate__c</fullName>
    <label>Fecha inicial</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_Status__c.field-meta.xml
<CustomField>
    <fullName>msf_Status__c</fullName>
    <label>Estado candidato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pool Asociativo</fullName>
            </value>
            <value>
                <fullName>Solicita información Asociativo</fullName>
            </value>
            <value>
                <fullName>Formulario incompleto</fullName>
            </value>
            <value>
                <fullName>Pendiente de presentar</fullName>
            </value>
            <value>
                <fullName>Pendiente de aprobar</fullName>
            </value>
            <value>
                <fullName>Asociado Stand-by</fullName>
                <isActive>false</isActive>
                <label>Asociado Stand-by</label>
            </value>
            <value>
                <fullName>Solicitud de alta</fullName>
                <isActive>false</isActive>
                <label>Solicitud de alta</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/msf_InteractionsMasterData__c.object-meta.xml
<CustomObject>
    <label>Maestro de datos de Interacciones</label>
    <nameField>
        <displayFormat>MD_IN_{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maestro de datos de Interacciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_AttributeFive__c.field-meta.xml
<CustomField>
    <fullName>msf_AttributeFive__c</fullName>
    <label>Atributo 5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_AttributeFour__c.field-meta.xml
<CustomField>
    <fullName>msf_AttributeFour__c</fullName>
    <label>Atributo 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_AttributeOne__c.field-meta.xml
<CustomField>
    <fullName>msf_AttributeOne__c</fullName>
    <label>Atributo 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_AttributeSix__c.field-meta.xml
<CustomField>
    <fullName>msf_AttributeSix__c</fullName>
    <label>Atributo 6</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_AttributeThree__c.field-meta.xml
<CustomField>
    <fullName>msf_AttributeThree__c</fullName>
    <label>Atributo 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_AttributeTwo__c.field-meta.xml
<CustomField>
    <fullName>msf_AttributeTwo__c</fullName>
    <label>Atributo 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_Campaign__c.field-meta.xml
<CustomField>
    <fullName>msf_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaña</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Maestro de datos de Interacciones</relationshipLabel>
    <relationshipName>Maestro_de_datos_de_Interacciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_Channel__c.field-meta.xml
<CustomField>
    <fullName>msf_Channel__c</fullName>
    <label>Canal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_Comment__c.field-meta.xml
<CustomField>
    <fullName>msf_Comment__c</fullName>
    <label>Comentario</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_Family__c.field-meta.xml
<CustomField>
    <fullName>msf_Family__c</fullName>
    <label>Familia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_GenerateTask__c.field-meta.xml
<CustomField>
    <fullName>msf_GenerateTask__c</fullName>
    <label>Genera la Tarea</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_InboundOutbound__c.field-meta.xml
<CustomField>
    <fullName>msf_InboundOutbound__c</fullName>
    <label>Sentido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_InboundOutbound</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_LeadSource__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource__c</fullName>
    <label>Canal de entrada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_Objective__c.field-meta.xml
<CustomField>
    <fullName>msf_Objective__c</fullName>
    <label>Objetivo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_Objective</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_ProactiveReactive__c.field-meta.xml
<CustomField>
    <fullName>msf_ProactiveReactive__c</fullName>
    <label>Proactiva / Reactiva</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_ProactiveReactive</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_Status__c.field-meta.xml
<CustomField>
    <fullName>msf_Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Eliminada</fullName>
            </value>
            <value>
                <fullName>En curso</fullName>
            </value>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Realizada</fullName>
            </value>
            <value>
                <fullName>Sin gestión</fullName>
            </value>
            <value>
                <fullName>Inalcanzable</fullName>
            </value>
            <value>
                <fullName>No requerido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_Subject__c.field-meta.xml
<CustomField>
    <fullName>msf_Subject__c</fullName>
    <label>Asunto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abogado, Familiar o un Tercero Reclama sobre una Herencia (Retraso, Pago Pendiente, Comparecencia, etc)</fullName>
            </value>
            <value>
                <fullName>ACMA Envia Justificante Pago Cuota Asociado</fullName>
            </value>
            <value>
                <fullName>ACTUA COMO ALTAVOZ</fullName>
                <isActive>false</isActive>
                <label>ACTUA COMO ALTAVOZ</label>
            </value>
            <value>
                <fullName>Actúa Como Altavoz</fullName>
            </value>
            <value>
                <fullName>Actúa como Aval</fullName>
            </value>
            <value>
                <fullName>ACTUA COMO PORTAVOZ HERENCIAS</fullName>
                <isActive>false</isActive>
                <label>ACTUA COMO PORTAVOZ HERENCIAS</label>
            </value>
            <value>
                <fullName>Actúa Como Portavoz Herencias</fullName>
            </value>
            <value>
                <fullName>ACTUA COMO VOLUNTARIO</fullName>
                <isActive>false</isActive>
                <label>ACTUA COMO VOLUNTARIO</label>
            </value>
            <value>
                <fullName>Actúa Como Voluntario</fullName>
            </value>
            <value>
                <fullName>Actúa como Voluntario Asociativo</fullName>
            </value>
            <value>
                <fullName>AGRADECIMIENTO ANUAL</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO ANUAL</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO ASISTENCIA A ENTREVISTA O REUNION</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO ASISTENCIA A ENTREVISTA O REUNION</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO ASISTENCIA A EVENTO O EXPOSICION</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO ASISTENCIA A EVENTO O EXPOSICION</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO ASISTENCIA A VISITA</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO ASISTENCIA A VISITA</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO AUMEN CUOTA</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO AUMEN CUOTA</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO CELEBRACIONES</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO CELEBRACIONES</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO CUOTA ANUAL</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO CUOTA ANUAL</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO DONATIVO</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO DONATIVO</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO EMPRESA SIN FRONTERAS ESF</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO EMPRESA SIN FRONTERAS ESF</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO FAMILIARES HERENCIAS</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO FAMILIARES HERENCIAS</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO INICIATIVA SOLIDARIA</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO INICIATIVA SOLIDARIA</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO OTROS (EL DONANTE HACE/ENVÍA ALGO)</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO OTROS (EL DONANTE HACE/ENVÍA ALGO)</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO PARTICIPA EN CAMPAÑA</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO PARTICIPA EN CAMPAÑA</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO REGALO SOLIDARIO</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO REGALO SOLIDARIO</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO TESTAMENTO A FAVOR</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO TESTAMENTO A FAVOR</label>
            </value>
            <value>
                <fullName>AGRADECIMINETO ENCUESTA</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMINETO ENCUESTA</label>
            </value>
            <value>
                <fullName>Asiste a Charla PEU</fullName>
            </value>
            <value>
                <fullName>Asiste a Entrevista o Reunión</fullName>
            </value>
            <value>
                <fullName>Asiste a Evento Asociativo</fullName>
            </value>
            <value>
                <fullName>Asiste a Evento o Exposición</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_TaskNumber__c.field-meta.xml
<CustomField>
    <fullName>msf_TaskNumber__c</fullName>
    <label>Número de tarea</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_TypeTemplate__c.field-meta.xml
<CustomField>
    <fullName>msf_TypeTemplate__c</fullName>
    <label>Tipo / Pieza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_TypeTemplate</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/MSF_Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Correo Postal</fullName>
    </customValue>
    <customValue>
        <fullName>E-mail</fullName>
    </customValue>
    <customValue>
        <fullName>Fax</fullName>
    </customValue>
    <customValue>
        <fullName>Fichero Informático</fullName>
    </customValue>
    <customValue>
        <fullName>Formularios Web</fullName>
    </customValue>
    <customValue>
        <fullName>Generación Aplicación</fullName>
    </customValue>
    <customValue>
        <fullName>Interno</fullName>
    </customValue>
    <customValue>
        <fullName>Llamada</fullName>
    </customValue>
    <customValue>
        <fullName>Mensajería Instantánea</fullName>
    </customValue>
    <customValue>
        <fullName>Mi Perfil</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Presencial</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>n/a</fullName>
    </customValue>
    <customValue>
        <fullName>Telemarketing</fullName>
        <isActive>false</isActive>
        <label>Telemarketing</label>
    </customValue>
    <customValue>
        <fullName>Buzón Móvil</fullName>
        <isActive>false</isActive>
        <label>Buzón Móvil</label>
    </customValue>
    <customValue>
        <fullName>Skype</fullName>
        <isActive>false</isActive>
        <label>Skype</label>
    </customValue>
    <customValue>
        <fullName>Whatsapp</fullName>
        <isActive>false</isActive>
        <label>Whatsapp</label>
    </customValue>
    <description>Interactions Master Data</description>
    <masterLabel>Canal</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MSF_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Area socio Web</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio de datos</fullName>
    </customValue>
    <customValue>
        <fullName>Campañas de petición</fullName>
    </customValue>
    <customValue>
        <fullName>Campañas fundraising</fullName>
    </customValue>
    <customValue>
        <fullName>Certificado fiscal</fullName>
    </customValue>
    <customValue>
        <fullName>Colaboraciones especiales</fullName>
    </customValue>
    <customValue>
        <fullName>Devoluciones económicas</fullName>
    </customValue>
    <customValue>
        <fullName>Encuestas</fullName>
    </customValue>
    <customValue>
        <fullName>Eventos</fullName>
    </customValue>
    <customValue>
        <fullName>Gestión administrativa</fullName>
    </customValue>
    <customValue>
        <fullName>Plan de relación</fullName>
    </customValue>
    <customValue>
        <fullName>Presenciales O2O</fullName>
    </customValue>
    <customValue>
        <fullName>Proyectos, operaciones y actividades MSF</fullName>
    </customValue>
    <description>Interactions Master Data</description>
    <masterLabel>Familia</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MSF_InboundOutbound.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Entrante</fullName>
    </customValue>
    <customValue>
        <fullName>Saliente</fullName>
    </customValue>
    <customValue>
        <fullName>Interno</fullName>
    </customValue>
    <customValue>
        <fullName>n/a</fullName>
    </customValue>
    <description>Interactions Master Data</description>
    <masterLabel>Sentido</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MSF_LeadSource1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cloud page</fullName>
    </customValue>
    <customValue>
        <fullName>Correo postal sin cupón</fullName>
    </customValue>
    <customValue>
        <fullName>Cupón</fullName>
    </customValue>
    <customValue>
        <fullName>Email a Bodas</fullName>
    </customValue>
    <customValue>
        <fullName>Email a Empresas</fullName>
    </customValue>
    <customValue>
        <fullName>Email a Iniciativas Solidarias</fullName>
    </customValue>
    <customValue>
        <fullName>Email a officers Mid Donors</fullName>
    </customValue>
    <customValue>
        <fullName>Email a One to one</fullName>
    </customValue>
    <customValue>
        <fullName>Email a SAS</fullName>
    </customValue>
    <customValue>
        <fullName>Email Director/a General</fullName>
    </customValue>
    <customValue>
        <fullName>Email herencias</fullName>
    </customValue>
    <customValue>
        <fullName>Email Presidente/a MSF</fullName>
    </customValue>
    <customValue>
        <fullName>Entidad financiera</fullName>
    </customValue>
    <customValue>
        <fullName>Eventos</fullName>
    </customValue>
    <customValue>
        <fullName>Mensajería Instantánea</fullName>
    </customValue>
    <customValue>
        <fullName>n/a</fullName>
    </customValue>
    <customValue>
        <fullName>Otro</fullName>
    </customValue>
    <customValue>
        <fullName>Persona a persona</fullName>
    </customValue>
    <customValue>
        <fullName>Personal con tablet</fullName>
    </customValue>
    <customValue>
        <fullName>Plataforma iniciativas</fullName>
    </customValue>
    <customValue>
        <fullName>Redes Sociales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono campaña</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Herencias y Legados</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Officers</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono SAS</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono web</fullName>
    </customValue>
    <customValue>
        <fullName>Telemarketing</fullName>
    </customValue>
    <customValue>
        <fullName>Web campaña</fullName>
    </customValue>
    <customValue>
        <fullName>Web MSF</fullName>
    </customValue>
    <description>LeadSource Master Data</description>
    <masterLabel>LeadSource1</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/MSF_Objective.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agradecimiento</fullName>
    </customValue>
    <customValue>
        <fullName>Bienvenida</fullName>
    </customValue>
    <customValue>
        <fullName>Cultivar</fullName>
    </customValue>
    <customValue>
        <fullName>Dar opinión</fullName>
    </customValue>
    <customValue>
        <fullName>Gestión administrativa</fullName>
    </customValue>
    <customValue>
        <fullName>Gestión económica</fullName>
    </customValue>
    <customValue>
        <fullName>Informar</fullName>
    </customValue>
    <customValue>
        <fullName>Informar de modificaciones</fullName>
    </customValue>
    <customValue>
        <fullName>Interno</fullName>
    </customValue>
    <customValue>
        <fullName>Invitación</fullName>
    </customValue>
    <customValue>
        <fullName>Participa en</fullName>
    </customValue>
    <customValue>
        <fullName>Pedir opinión o respuesta</fullName>
    </customValue>
    <customValue>
        <fullName>Petición de documentos o información</fullName>
    </customValue>
    <customValue>
        <fullName>Petición difusión</fullName>
    </customValue>
    <customValue>
        <fullName>Petición económica</fullName>
    </customValue>
    <customValue>
        <fullName>Petición económica-Conversión Prospecto</fullName>
    </customValue>
    <customValue>
        <fullName>Petición económica-Reactivación Donante</fullName>
    </customValue>
    <customValue>
        <fullName>Petición económica-Reactivación Socio</fullName>
    </customValue>
    <customValue>
        <fullName>Petición económica-Resto</fullName>
    </customValue>
    <customValue>
        <fullName>Petición económica-Upgrade Donante</fullName>
    </customValue>
    <customValue>
        <fullName>Petición económica-Upgrade Socio</fullName>
    </customValue>
    <customValue>
        <fullName>Queja</fullName>
    </customValue>
    <customValue>
        <fullName>Recuperación</fullName>
    </customValue>
    <customValue>
        <fullName>Rendir cuentas</fullName>
    </customValue>
    <customValue>
        <fullName>Respuesta a</fullName>
    </customValue>
    <customValue>
        <fullName>Retención</fullName>
    </customValue>
    <customValue>
        <fullName>Repuesta a</fullName>
        <isActive>false</isActive>
        <label>Repuesta a</label>
    </customValue>
    <description>Interactions Master Data</description>
    <masterLabel>Objetivo</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/MSF_ProactiveReactive.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Interna</fullName>
    </customValue>
    <customValue>
        <fullName>Proactiva</fullName>
    </customValue>
    <customValue>
        <fullName>Reactiva</fullName>
    </customValue>
    <customValue>
        <fullName>n/a</fullName>
    </customValue>
    <customValue>
        <fullName>Proactivo</fullName>
        <isActive>false</isActive>
        <label>Proactivo</label>
    </customValue>
    <customValue>
        <fullName>Interno</fullName>
        <isActive>false</isActive>
        <label>Interno</label>
    </customValue>
    <description>Interactions Master Data</description>
    <masterLabel>Proactiva / Reactiva</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MSF_TypeTemplate.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acreditación de Socio</fullName>
    </customValue>
    <customValue>
        <fullName>Calendario</fullName>
    </customValue>
    <customValue>
        <fullName>Carnet de socio</fullName>
    </customValue>
    <customValue>
        <fullName>Cesión de aportaciones</fullName>
    </customValue>
    <customValue>
        <fullName>Charla Temática</fullName>
    </customValue>
    <customValue>
        <fullName>Cupón de Alta</fullName>
    </customValue>
    <customValue>
        <fullName>Documento de Baja</fullName>
    </customValue>
    <customValue>
        <fullName>Dossier Herencias y Legados</fullName>
    </customValue>
    <customValue>
        <fullName>Evento Genérico Masivo</fullName>
    </customValue>
    <customValue>
        <fullName>Evento Grandes Colaboradores</fullName>
    </customValue>
    <customValue>
        <fullName>Evento Legal Herencias</fullName>
    </customValue>
    <customValue>
        <fullName>Evento OneToFew+</fullName>
    </customValue>
    <customValue>
        <fullName>Evento PEU</fullName>
    </customValue>
    <customValue>
        <fullName>Exposición</fullName>
    </customValue>
    <customValue>
        <fullName>Mandato</fullName>
    </customValue>
    <customValue>
        <fullName>Memoria</fullName>
    </customValue>
    <customValue>
        <fullName>Recibo donativo Persona Física</fullName>
    </customValue>
    <customValue>
        <fullName>Recibo donativo Persona Jurídica</fullName>
    </customValue>
    <customValue>
        <fullName>Revista</fullName>
    </customValue>
    <customValue>
        <fullName>Visita Base Logística</fullName>
    </customValue>
    <customValue>
        <fullName>Visita Sede/Oficina delegada</fullName>
    </customValue>
    <customValue>
        <fullName>Visita Terreno</fullName>
    </customValue>
    <customValue>
        <fullName>Pieza 12Few (libros, fotos, otros)</fullName>
    </customValue>
    <customValue>
        <fullName>Pieza 121 (libros, fotos, otros)</fullName>
    </customValue>
    <masterLabel>Tipo / Pieza</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/MSF_TaskFieldsLogic_TDTM.cls
/**
* @author 		Deloitte
* @date 		02-2019
* @group 		Task
* @description	Contains the logic that is applied to some fields based on other fields or related objects.
*/
global without sharing class MSF_TaskFieldsLogic_TDTM extends npsp.TDTM_Runnable {
    
    /*******************************************************************************************************
    * @description  Trigger Handler on Tasks that contains the logic that is applied to some fields based 
    * 				on other fields or related objects.
    * @param        listNew the list of Tasks from trigger new. 
    * @param        listOld the list of Tasks from trigger old. 
    * @param        triggerAction which trigger event (BeforeInsert, AfterInsert, etc.). 
    * @param        objResult the describe for Tasks.
    * @return       dmlWrapper. 
    ********************************************************************************************************/
    global override npsp.TDTM_Runnable.DmlWrapper run(List<SObject> newlist, List<SObject> oldlist, npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult){
        
        //Attributes
        List<Task> lNewTasks = (List<Task>) newlist;
        List<Task> lOldTasks = (List<Task>) oldlist;
        Map<Id, Task> mOldTasks = new Map<Id, Task>();
        if(lOldTasks != null){            
            mOldTasks.putAll(lOldTasks);
        }
        
        Set<String> sSubjectAllowedValues = new Set<String>();
        Map<String,msf_InteractionsMasterData__c> mIntMD = new Map<String,msf_InteractionsMasterData__c>();
        mIntMD = getInteractionDependences();
        
        List<RecordType> rTLeads = [SELECT Id FROM RecordType WHERE SobjectType = 'Lead'];
        List<Id> idsRTLeads = new List<Id>(); 
        for (RecordType rt : rTLeads) {
            idsRTLeads.add(rt.Id);
        }
        System.debug('Hello there');
        
        //DML WRAPPER
        npsp.TDTM_Runnable.dmlWrapper dmlWrapper = new npsp.TDTM_Runnable.DmlWrapper();
   
        //BEFORE INSERT && BEFORE UPDATE
        if(triggerAction == npsp.TDTM_Runnable.Action.BeforeInsert || triggerAction == npsp.TDTM_Runnable.Action.BeforeUpdate ) {
            sSubjectAllowedValues = getStatusAllowedValues();
			System.debug('Values: '+sSubjectAllowedValues);
            System.debug('Hello there 2');
			List<Id> tasksContactsIds = new List<Id>();             
            for (Task t : lNewTasks) {
                tasksContactsIds.add(t.WhoId);
            }
            Map<Id, Contact> tasksContacts = new Map<Id, Contact>();  
            for (Contact c : [SELECT Id, msf_OppFiscalAmountLastYear__c, msf_FiscalFirstName__c,
                              msf_FiscalLastName1__c, msf_FiscalLastName2__c, msf_fiscalNif__c
                              FROM Contact WHERE Id IN :tasksContactsIds]) {
				tasksContacts.put(c.Id, c);                
            }
            
            for(Task t : lNewTasks){
                if(t.msf_Channel__c != null && !sSubjectAllowedValues.isEmpty() && !sSubjectAllowedValues.contains(t.Subject)){
                    t.Subject.addError(System.label.MSF_INTERACTIONS_SUBJECT_ERROR);    
                }

                if(!mOldTasks.isEmpty() && !mIntMD.isEmpty() && mIntMD.containsKey(t.Subject)){
                    Task oldTask = mOldTasks.get(t.Id);
                    if (oldTask.Subject != t.Subject || oldTask.msf_TaskNumber__c != t.msf_TaskNumber__c){
                        msf_InteractionsMasterData__c intMD = mIntMD.get(t.Subject);
                        t.msf_TaskNumber__c = intMD.msf_TaskNumber__c;
                    }
                }
                
                if(mOldTasks.isEmpty() && !mIntMD.isEmpty() && mIntMD.containsKey(t.Subject)){
                    setDefaultValues(t, mIntMD.get(t.Subject));
                }
                              
                
                if (t.msf_TaskNumber__c == 224 || t.msf_TaskNumber__c == 225 || t.msf_TaskNumber__c == 226 || t.msf_TaskNumber__c == 227) {
                    Contact c = tasksContacts.get(t.WhoId);
                    if (c != null) {
						t.msf_AttributeOne__c = String.valueOf(c.msf_OppFiscalAmountLastYear__c); 
                        t.msf_AttributeTwo__c = String.valueOf(System.today().year() - 1); 
                        t.msf_AttributeThree__c = c.msf_FiscalFirstName__c; 
                        t.msf_AttributeFour__c = c.msf_FiscalLastName1__c; 
                        t.msf_AttributeFive__c = c.msf_FiscalLastName2__c; 
                        t.msf_AttributeSix__c = c.msf_fiscalNif__c;
                    }
                }
            }  
        }
        
        //AFTER INSERT
        if (triggerAction == npsp.TDTM_Runnable.Action.AfterInsert) {
            List<Task> subtasksToAdd = new List<Task>();
            for(Task t : lNewTasks){
               	msf_InteractionsMasterData__c mInt = mIntMD.get(t.Subject);
                 if (mInt != null && mInt.msf_GenerateTask__c != null && t.msf_ParentTaskId__c == null) {
                     Task subTask = new Task();
                     subTask.msf_ParentTaskId__c = String.valueOf(t.Id);
                     subTask.Subject = getTaskSubjectByTaskNumber(String.valueOf(mInt.msf_GenerateTask__c), mIntMD.values());
                     subTask.OwnerId = t.OwnerId;
                     subTask.msf_StartDate__c = t.msf_StartDate__c;
                     subTask.msf_RelatedContact__c = t.msf_RelatedContact__c; 
                     subTask.WhatId = t.WhatId;
                     subTask.WhoId = t.WhoId;
                     subTask.msf_Campaign__c = t.msf_Campaign__c; 
                     subTask.msf_LeadSource__c = t.msf_LeadSource__c; 
                     subTask.ActivityDate = t.ActivityDate;
                     subTask.msf_TypeTemplate__c = t.msf_TypeTemplate__c;
                     subTask.msf_ProactiveReactive__c = 'n/a';
                     subTask.msf_Channel__c = 'n/a';
                     subtasksToAdd.add(subTask);
                 }
            }
            dmlWrapper.objectsToInsert.addAll(subtasksToAdd);
            return dmlWrapper;
        }
       
        //AFTER DELETE
        if (triggerAction == npsp.TDTM_Runnable.Action.AfterDelete) {
            List<Task> childTasksToUpdate = new List<Task>();
            
            childTasksToUpdate.addAll(removeParentFromChildTasks(lOldTasks));
            
            dmlWrapper.objectsToUpdate.addAll(childTasksToUpdate);
            return dmlWrapper;
        }
                
        return null;        
    }
    
    
    // PRIVATE METHODS    
    private static List<Task> removeParentFromChildTasks(List<Task> tasks) {
        List<String> taskIds = new List<String>();
        for (Task t : tasks) {
            String ids = String.valueOf(t.Id);
            taskIds.add(ids);
        }
        
        List<Task> childTasks = [SELECT msf_ParentTaskId__c FROM Task WHERE msf_ParentTaskId__c IN :taskIds];
        for (Task tt : childTasks) {
            tt.msf_ParentTaskId__c = null; 
        }
        return childTasks; 
    }
    
    /*******************************************************************************************************
    * @description  Obtain the values of the Subject picklist field in Task object.
    * @return       Set<String>
    ********************************************************************************************************/ 
    private Set<String> getStatusAllowedValues (){        
        Set<String> sValues = new Set<String>();
        
        Schema.DescribeFieldResult fieldResult = Task.Subject.getDescribe(); 
        List<Schema.PicklistEntry> pickListValues = fieldResult.getPicklistValues();
        
        for(Schema.PicklistEntry pe : pickListValues){            
            sValues.add(pe.getValue());            
        }
        
        return sValues;
    }
    
    /*******************************************************************************************************
    * @description 	Returns a map that contains all the records of the msf_InteractionsMasterData__c object 
    * 				with the value of the msf_Subject__c field as the key.     
    * @return	 	Map<String, String> has the values recovered.        
    ********************************************************************************************************/
    private Map<String, msf_InteractionsMasterData__c> getInteractionDependences(){        
        Map<String, msf_InteractionsMasterData__c> mReturnValues = new Map<String, msf_InteractionsMasterData__c>();        
        
        for(msf_InteractionsMasterData__c imd : [SELECT msf_Subject__c, msf_Campaign__c, msf_Channel__c, msf_LeadSource__c, msf_Comment__c, msf_TaskNumber__c,
                                                 msf_Status__c, msf_Family__c, msf_Objective__c, msf_ProactiveReactive__c, msf_InboundOutbound__c, msf_Thematic__c,
                                                 msf_Owner__c, msf_AttributeOne__c, msf_AttributeTwo__c, msf_AttributeThree__c, msf_AttributeFour__c, msf_AttributeFive__c, 
                                                 msf_AttributeSix__c, msf_Commitment__c, msf_GenerateTask__c,msf_Thematic2__c,msf_ProductProgram__c, MSF_ServiceOwner__c, msf_TypeTemplate__c
                                                 FROM msf_InteractionsMasterData__c ])
        {              
            mReturnValues.put(imd.msf_Subject__c, imd);                      
        }
        
        return mReturnValues;
    }
    
    
    private String getTaskSubjectByTaskNumber(String taskNumber, List<msf_InteractionsMasterData__c> interactionDependences) {
        String subject = null;
        Integer i = 0; 
        while (subject == null && i < interactionDependences.size()) {
          	msf_InteractionsMasterData__c iM = interactionDependences.get(i);
            if (String.valueOf(iM.msf_TaskNumber__c).equals(taskNumber)) {
                subject = iM.msf_Subject__c;
            }
            i++;
        }
        return subject; 
    }
    
    /*******************************************************************************************************
    * @description 	Returns a map that contains all the records of the msf_InteractionsMasterData__c object 
    * 				with the value of the msf_Subject__c field as the key. 
    * @param        t is the task to which your information is updated.
    * @param        intMD contains the default values for the task.             
    ********************************************************************************************************/
    private void setDefaultValues (Task t, msf_InteractionsMasterData__c intMD){
        
		t.msf_TaskNumber__c = intMD.msf_TaskNumber__c;
        t.msf_StartDate__c = date.today();
        
        if(t.Status == null){
        	t.Status = intMD.msf_Status__c;
        }
        if(t.msf_InboundOutbound__c == null){
        	t.msf_InboundOutbound__c = intMD.msf_InboundOutbound__c;
        }
        if(t.msf_Channel__c == null){
        	t.msf_Channel__c = intMD.msf_Channel__c;
        }
        if(t.msf_ProactiveReactive__c == null){
        	t.msf_ProactiveReactive__c = intMD.msf_ProactiveReactive__c;
        }
        if(t.msf_Campaign__c == null){
        	t.msf_Campaign__c = intMD.msf_Campaign__c;
        }
        if(t.msf_LeadSource__c == null){
            t.msf_LeadSource__c = intMD.msf_LeadSource__c;
        }
        if(t.Description == null){
        	t.Description = intMD.msf_Comment__c;
        }
        if(t.msf_Family__c == null){
        	t.msf_Family__c = intMD.msf_Family__c;
        }
        if(t.msf_Objective__c == null){
        	t.msf_Objective__c = intMD.msf_Objective__c;
        } 
        if (t.msf_Thematic__c == null) {
            t.msf_Thematic__c = intMD.msf_Thematic__c; 
        }
        if (t.msf_Thematic2__c == null) {
            t.msf_Thematic2__c = intMD.msf_Thematic2__c; 
        }
        if (t.msf_Commitment__c == null) {
            t.msf_Commitment__c= intMD.msf_Commitment__c;
        }
        if (t.msf_AttributeOne__c == null) {
            t.msf_AttributeOne__c = intMD.msf_AttributeOne__c;
        }
        if (t.msf_AttributeTwo__c == null) {
            t.msf_AttributeTwo__c = intMD.msf_AttributeTwo__c;
        }
        if (t.msf_AttributeThree__c == null) {
            t.msf_AttributeThree__c = intMD.msf_AttributeThree__c;
        }
        if (t.msf_AttributeFour__c == null) {
            t.msf_AttributeFour__c = intMD.msf_AttributeFour__c;
        }
        if (t.msf_AttributeFive__c == null) {
            t.msf_AttributeFive__c = intMD.msf_AttributeFive__c;
        }
        if (t.msf_AttributeSix__c == null) {
            t.msf_AttributeSix__c = intMD.msf_AttributeSix__c;
        }
        if (t.msf_ProductProgram__c == null) {
            t.msf_ProductProgram__c = intMD.msf_ProductProgram__c;
        }
        if (t.msf_Owner__c == null) {
            t.msf_Owner__c = intMD.MSF_ServiceOwner__c;
        }
        if (t.msf_TypeTemplate__c == null) {
            t.msf_TypeTemplate__c = intMD.msf_TypeTemplate__c; 
        }
        if (t.ActivityDate == null && t.RecurrenceActivityId == null && t.IsRecurrence != true ) {  // Zenit #19563
            t.ActivityDate = date.today();
        }
        
    }   

}