force-app/main/default/objects/Contact/fields/msf_BeginDateMSF__c.field-meta.xml
<CustomField>
    <fullName>msf_BeginDateMSF__c</fullName>
    <description>This field is to register the first time in MSF</description>
    <label>Fecha alta MSF</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_DateFirstRecurringDonorQuota__c.field-meta.xml
<CustomField>
    <fullName>msf_DateFirstRecurringDonorQuota__c</fullName>
    <label>Fecha de cobro de primera cuota de socio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_DateLastRecurringDonorQuota__c.field-meta.xml
<CustomField>
    <fullName>msf_DateLastRecurringDonorQuota__c</fullName>
    <label>Fecha de cobro de última cuota de socio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_EntryDateCurrentRecurringDonor__c.field-meta.xml
<CustomField>
    <fullName>msf_EntryDateCurrentRecurringDonor__c</fullName>
    <label>Fecha de la última alta de socio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_FirstAnnualizedQuota__c.field-meta.xml
<CustomField>
    <fullName>msf_FirstAnnualizedQuota__c</fullName>
    <label>Primera Cuota anualizada</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_FirstCampaignEntryRecurringDonor__c.field-meta.xml
<CustomField>
    <fullName>msf_FirstCampaignEntryRecurringDonor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primera campaña alta socio</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Contactos (Primera campaña alta socio)</relationshipLabel>
    <relationshipName>FirstCampaignEntryRecurringDonor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_FirstCampaignRecurringDonorChannel__c.field-meta.xml
<CustomField>
    <fullName>msf_FirstCampaignRecurringDonorChannel__c</fullName>
    <label>Canal campaña de primera alta de socio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_FirstEntryDateRecurringDonor__c.field-meta.xml
<CustomField>
    <fullName>msf_FirstEntryDateRecurringDonor__c</fullName>
    <label>Fecha de primera alta de socio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_isActiveDonor__c.field-meta.xml
<CustomField>
    <fullName>msf_isActiveDonor__c</fullName>
    <description>One Off Donor is active or no</description>
    <label>Es donante</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_IsActiveRecurringDonor__c.field-meta.xml
<CustomField>
    <fullName>msf_IsActiveRecurringDonor__c</fullName>
    <description>Recurrent Donor is active or no</description>
    <label>Es socio</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LastAnnualizedQuota__c.field-meta.xml
<CustomField>
    <fullName>msf_LastAnnualizedQuota__c</fullName>
    <label>Última cuota anualizada</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LastRecurringDonationDate__c.field-meta.xml
<CustomField>
    <fullName>msf_LastRecurringDonationDate__c</fullName>
    <label>Fecha de última baja</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_MemberType__c.field-meta.xml
<CustomField>
    <fullName>msf_MemberType__c</fullName>
    <defaultValue>&apos;Nada&apos;</defaultValue>
    <label>Tipo de miembro</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_RecalculateMemberType__c.field-meta.xml
<CustomField>
    <fullName>msf_RecalculateMemberType__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Recalcular tipo de miembro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_ValueRecurringDonorCont__c.field-meta.xml
<CustomField>
    <fullName>msf_ValueRecurringDonorCont__c</fullName>
    <label>Valor de compromiso de socio (cont)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/npsp__Deceased__c.field-meta.xml
<CustomField>
    <fullName>npsp__Deceased__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates the Contact is deceased. When selected, NPSP excludes this Contact from Household Naming (unless this Contact is the only one in the Household) and from standard email and phone lists.</description>
    <inlineHelpText>Cuando se encuentra seleccionado, se excluye al contacto de el nombre y saludos de la familia, correos electrónicos y llamados.</inlineHelpText>
    <label>Deceased</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/msf_LeadSourceMasterData__c/msf_LeadSourceMasterData__c.object-meta.xml
<CustomObject>
    <label>Maestro de datos de LeadSource</label>
    <nameField>
        <displayFormat>MD_LS_{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maestro de datos de LeadSource</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_LeadSourceMasterData__c/fields/msf_LeadSource3__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource3__c</fullName>
    <label>Canal de entrada 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource3</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_QuotaModification__c/msf_QuotaModification__c.object-meta.xml
<CustomObject>
    <label>Modificación de cuota</label>
    <nameField>
        <label>Nombre de Modificación de cuota</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modificaciones de cuota</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_QuotaModification__c/fields/msf_LeadSource1__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource1__c</fullName>
    <label>Canal de entrada 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_QuotaModification__c/fields/msf_LeadSource2__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource2__c</fullName>
    <label>Canal de entrada 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/npe03__Recurring_Donation__c.object-meta.xml
<CustomObject>
    <description>Recurring Donations track charitable giving where a donor specifies an amount of money to be given on a regular basis.</description>
    <label>Recurring Donation</label>
    <nameField>
        <label>Recurring Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/msf_AnnualizedQuota__c.field-meta.xml
<CustomField>
    <fullName>msf_AnnualizedQuota__c</fullName>
    <formula>CASE(npe03__Installment_Period__c, 
&apos;Monthly&apos;, npe03__Amount__c * 12, 
&apos;Quarterly&apos;, npe03__Amount__c * 4, 
&apos;Yearly&apos;, npe03__Amount__c, 
&apos;Bimensual&apos;, npe03__Amount__c * 6, 
&apos;Semestral&apos;, npe03__Amount__c * 2, 
npe03__Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cuota anualizada</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/msf_CancelationDate__c.field-meta.xml
<CustomField>
    <fullName>msf_CancelationDate__c</fullName>
    <label>Fecha de cancelación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/msf_CancelationReason__c.field-meta.xml
<CustomField>
    <fullName>msf_CancelationReason__c</fullName>
    <label>Motivo de cancelación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1 OBS/TCS devueltas con otras aportaciones impagadas en los últimos 2 años</fullName>
            </value>
            <value>
                <fullName>2 OBS devueltas es la primera de su historia</fullName>
            </value>
            <value>
                <fullName>2 TCS devueltas</fullName>
            </value>
            <value>
                <fullName>3 Obs/Tcs Devueltas</fullName>
            </value>
            <value>
                <fullName>Baja argumentada</fullName>
            </value>
            <value>
                <fullName>Baja asociativo</fullName>
                <isActive>false</isActive>
                <label>Baja asociativo</label>
            </value>
            <value>
                <fullName>Baja económica argumentada</fullName>
            </value>
            <value>
                <fullName>Baja e llamada de Bienvenida</fullName>
            </value>
            <value>
                <fullName>Baja en llamada de aumentos</fullName>
            </value>
            <value>
                <fullName>Baja en llamada de gestión de devoluciones</fullName>
            </value>
            <value>
                <fullName>Baja por cambio de titular</fullName>
            </value>
            <value>
                <fullName>Baja por impago orden Socio</fullName>
            </value>
            <value>
                <fullName>Baja proactiva Coronavirus</fullName>
            </value>
            <value>
                <fullName>Baja reactiva Coronavirus</fullName>
            </value>
            <value>
                <fullName>Baja socio temporal</fullName>
            </value>
            <value>
                <fullName>Voluntary withdrawal</fullName>
                <label>Baja voluntaria</label>
            </value>
            <value>
                <fullName>Cambio de domicilio</fullName>
            </value>
            <value>
                <fullName>Captador F2F-TLMK me informó mal</fullName>
            </value>
            <value>
                <fullName>Cierre/Cambio cuenta bancaria</fullName>
            </value>
            <value>
                <fullName>Colabora con otra ONG</fullName>
            </value>
            <value>
                <fullName>Decepcionado</fullName>
            </value>
            <value>
                <fullName>Desacuerdo aborto</fullName>
            </value>
            <value>
                <fullName>Desacuerdo colaboración  con Empresas</fullName>
            </value>
            <value>
                <fullName>Desacuerdo destino ayuda</fullName>
            </value>
            <value>
                <fullName>Desacuerdo gestión financiera</fullName>
            </value>
            <value>
                <fullName>Desacuerdo operaciones mediterraneo</fullName>
            </value>
            <value>
                <fullName>Desacuerdo política captacion de fondos</fullName>
            </value>
            <value>
                <fullName>Desacuerdo política intervención</fullName>
            </value>
            <value>
                <fullName>Duplicado</fullName>
            </value>
            <value>
                <fullName>Económico</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
                <label>Fallecido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/msf_CurrentCampaign__c.field-meta.xml
<CustomField>
    <fullName>msf_CurrentCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaña actual</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipName>Donaciones_recurrentes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/msf_LeadSource1__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource1__c</fullName>
    <label>Canal de entrada 1 inicial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/msf_LeadSource2__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource2__c</fullName>
    <label>Canal de entrada 2 inicial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/msf_LeadSource3__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource3__c</fullName>
    <label>Canal de entrada 3 inicial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource3</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npe03__Contact__c.field-meta.xml
<CustomField>
    <fullName>npe03__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>R00N80000002bOmREAU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npe03__Date_Established__c.field-meta.xml
<CustomField>
    <fullName>npe03__Date_Established__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>The initial inception date for this Recurring Donation. The default is the current date.</description>
    <label>Date Established</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npe03__Open_Ended_Status__c.field-meta.xml
<CustomField>
    <fullName>npe03__Open_Ended_Status__c</fullName>
    <label>Open Ended Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npe03__Recurring_Donation_Campaign__c.field-meta.xml
<CustomField>
    <fullName>npe03__Recurring_Donation_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Recurring Donations</relationshipLabel>
    <relationshipName>Recurring_Donations_Pledges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/recordTypes/Associate.recordType-meta.xml
<RecordType>
    <fullName>Associate</fullName>
    <active>true</active>
    <label>Associate</label>
</RecordType>

force-app/main/default/objects/npe03__Recurring_Donation__c/recordTypes/Recurring_donation.recordType-meta.xml
<RecordType>
    <fullName>Recurring_donation</fullName>
    <active>true</active>
    <label>Recurring donation</label>
</RecordType>

force-app/main/default/globalValueSets/MSF_LeadSource1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cloud page</fullName>
    </customValue>
    <customValue>
        <fullName>Correo postal sin cupón</fullName>
    </customValue>
    <customValue>
        <fullName>Cupón</fullName>
    </customValue>
    <customValue>
        <fullName>Email a Bodas</fullName>
    </customValue>
    <customValue>
        <fullName>Email a Empresas</fullName>
    </customValue>
    <customValue>
        <fullName>Email a Iniciativas Solidarias</fullName>
    </customValue>
    <customValue>
        <fullName>Email a officers Mid Donors</fullName>
    </customValue>
    <customValue>
        <fullName>Email a One to one</fullName>
    </customValue>
    <customValue>
        <fullName>Email a SAS</fullName>
    </customValue>
    <customValue>
        <fullName>Email Director/a General</fullName>
    </customValue>
    <customValue>
        <fullName>Email herencias</fullName>
    </customValue>
    <customValue>
        <fullName>Email Presidente/a MSF</fullName>
    </customValue>
    <customValue>
        <fullName>Entidad financiera</fullName>
    </customValue>
    <customValue>
        <fullName>Eventos</fullName>
    </customValue>
    <customValue>
        <fullName>Mensajería Instantánea</fullName>
    </customValue>
    <customValue>
        <fullName>n/a</fullName>
    </customValue>
    <customValue>
        <fullName>Otro</fullName>
    </customValue>
    <customValue>
        <fullName>Persona a persona</fullName>
    </customValue>
    <customValue>
        <fullName>Personal con tablet</fullName>
    </customValue>
    <customValue>
        <fullName>Plataforma iniciativas</fullName>
    </customValue>
    <customValue>
        <fullName>Redes Sociales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono campaña</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Herencias y Legados</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Officers</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono SAS</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono web</fullName>
    </customValue>
    <customValue>
        <fullName>Telemarketing</fullName>
    </customValue>
    <customValue>
        <fullName>Web campaña</fullName>
    </customValue>
    <customValue>
        <fullName>Web MSF</fullName>
    </customValue>
    <description>LeadSource Master Data</description>
    <masterLabel>LeadSource1</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/MSF_LeadSource2.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Correo postal sin cupón</fullName>
    </customValue>
    <customValue>
        <fullName>Cupón</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Entidad financiera</fullName>
    </customValue>
    <customValue>
        <fullName>Formulario web</fullName>
    </customValue>
    <customValue>
        <fullName>Mensajería Instantánea</fullName>
    </customValue>
    <customValue>
        <fullName>Otro</fullName>
    </customValue>
    <customValue>
        <fullName>Persona a persona</fullName>
    </customValue>
    <customValue>
        <fullName>Redes Sociales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono campaña</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Herencias y Legados</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfonos Officers</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfonos SAS</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono web</fullName>
    </customValue>
    <customValue>
        <fullName>Telemarketing</fullName>
    </customValue>
    <description>LeadSource Master Data</description>
    <masterLabel>LeadSource2</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/MSF_LeadSource3.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Correo postal</fullName>
    </customValue>
    <customValue>
        <fullName>Entidad financiera</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Personal</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono</fullName>
    </customValue>
    <customValue>
        <fullName>Otro</fullName>
    </customValue>
    <description>LeadSource Master Data</description>
    <masterLabel>LeadSource3</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MSF_RecurringDonation_TDTM.cls
/**
* @author 		Deloitte
* @date 		11-2018
* @group 		Recurring donation.
* @description	Logic of some fields and the change of quota.
*/
global without sharing class MSF_RecurringDonation_TDTM extends npsp.TDTM_Runnable {
    
    /*******************************************************************************************************
    * @description	Trigger Handler on Recurring Donations that handles the logic of some fields and the 
    * 				change of quota. 
    * @param 		listNew the list of Recurring Donations from trigger new. 
    * @param 		listOld the list of Recurring Donations from trigger old. 
    * @param 		triggerAction which trigger event (BeforeInsert, AfterInsert, etc.). 
    * @param 		objResult the describe for Recurring Donations 
    * @return 		dmlWrapper. 
    ********************************************************************************************************/
    global override npsp.TDTM_Runnable.DmlWrapper run(List<SObject> newlist, List<SObject> oldlist, npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {    
    	
        //Attributes
        List<npe03__Recurring_Donation__c> lNewRD = (List<npe03__Recurring_Donation__c>) newlist;
        List<npe03__Recurring_Donation__c> lOldRD = (List<npe03__Recurring_Donation__c>) oldlist;
        Map<Id, npe03__Recurring_Donation__c> mOldRD = new Map<Id, npe03__Recurring_Donation__c>();
        if(lOldRD != null){            
            mOldRD.putAll(lOldRD);
        }

        List<Contact> lContactsToUpdate = new List<Contact>();
        List<msf_QuotaModification__c> lModificationQuotasToInsert = new List<msf_QuotaModification__c>();
        
        Map<String,Schema.RecordTypeInfo> mRdRtInfo = Schema.SObjectType.npe03__Recurring_Donation__c.getRecordTypeInfosByDeveloperName(); 
        ID rtRD = mRdRtInfo.get('Recurring_donation').getRecordTypeId();
        
        Set<ID> sContactIds = new Set<ID>();   
        
        //Actions
        if(triggerAction != npsp.TDTM_Runnable.Action.AfterDelete){
            for(npe03__Recurring_Donation__c rd : lNewRD){
                if(rd.npe03__Contact__c != null){
                    sContactIds.add(rd.npe03__Contact__c);    
                }
            }
        }
                  
        if(triggerAction == npsp.TDTM_Runnable.Action.BeforeInsert){
        	//allowNewRD(lNewRD, sContactIds, rtRD);	  
        }       
        
        if(triggerAction == npsp.TDTM_Runnable.Action.BeforeInsert || triggerAction == npsp.TDTM_Runnable.Action.BeforeUpdate) {	            
            
            MSF_SharedMethods_UTIL smUtil = new MSF_SharedMethods_UTIL();            
            Map<String, msf_LeadSourceMasterData__c> mLeadSourceValues = smUtil.getLeadSourceDependencies();
            
            for(npe03__Recurring_Donation__c rd : lNewRD){                
                setCurrentCampaign(rd);
                setCurrentLeadSource(rd);
            	setLeadSourceDependencies(rd, mLeadSourceValues);          
            }
        }
        
        if(triggerAction == npsp.TDTM_Runnable.Action.BeforeUpdate){            
            for(npe03__Recurring_Donation__c rd : lNewRD){
                if(rd.npe03__Open_Ended_Status__c != mOldRD.get(rd.Id).npe03__Open_Ended_Status__c){
                    if(rd.npe03__Open_Ended_Status__c == 'Closed'){
                        rd.msf_CancelationDate__c = Date.today();     
                    }else{
                        rd.msf_CancelationDate__c = null;
                        rd.msf_CancelationReason__c = null;
                    }                    
                }                
                setRdName(rd, mRdRtInfo, mOldRD.isEmpty());
            }            
        }
                 
        if(triggerAction == npsp.TDTM_Runnable.Action.AfterInsert || triggerAction == npsp.TDTM_Runnable.Action.AfterUpdate) {	  
            List<Contact> lc = new List<Contact>();  
            
            if(!sContactIds.isEmpty()){
                lc = setContactFields(lNewRD, sContactIds);
                //if(triggerAction == npsp.TDTM_Runnable.Action.AfterInsert) {
                List<Contact> tempContacts = new List<Contact>();
                tempContacts = MSF_SharedMethods_UTIL.contactMemberType(lc);
                
                Map<Id,Contact> tempMap = new Map<Id,Contact>(tempContacts);
                
                for(Contact c : lc){
                    if(tempMap.containsKey(c.Id)){
                        c.msf_MemberType__c = tempMap.get(c.Id).msf_MemberType__c ;
                        c.msf_IsActiveDonor__c = tempMap.get(c.Id).msf_IsActiveDonor__c ;
                        c.msf_IsActiveRecurringDonor__c = tempMap.get(c.Id).msf_IsActiveRecurringDonor__c ;
                    }
                }                
                //}
                
                if(lc != null && !lc.isEmpty()){
                    lContactsToUpdate.addAll(lc);
                } 
            }

            List<msf_QuotaModification__c> lqm = createQuotaModification(lNewRD, mOldRD);
            if(lqm != null && !lqm.isEmpty()){
            	lModificationQuotasToInsert.addAll(lqm);             
            } 
        }
                
        if(triggerAction == npsp.TDTM_Runnable.Action.AfterDelete){
            for(npe03__Recurring_Donation__c rd : lOldRD){
                if(rd.npe03__Contact__c != null){
                    lContactsToUpdate.add(new Contact(Id=rd.npe03__Contact__c,msf_RecalculateMemberType__c=TRUE));
                }
            }   
        }
        
        //DML Operations
        npsp.TDTM_Runnable.dmlWrapper dmlWrapper = new npsp.TDTM_Runnable.DmlWrapper();
        dmlWrapper.objectsToUpdate.addAll((List<Contact>)lContactsToUpdate);
        dmlWrapper.objectsToInsert.addAll((List<msf_QuotaModification__c>)lModificationQuotasToInsert);
        
        if(lContactsToUpdate.isEmpty() && lModificationQuotasToInsert.isEmpty()){
            return null;
        }
        
        return dmlWrapper;
    }
    
    // PRIVATE METHODS
    
    /*******************************************************************************************************
    * @description	Set the values in the 'LeadSource2; LeadSource3' fields in lead depending of the value 
    * 				of the 'LeadSource1' field.
    * @param 		rd is the Recurrent Donation to update the Name. 
    * @param 		mRdRtInfo is a map that contains information of recurrent donations record types.
    ********************************************************************************************************/
    private void setRdName(npe03__Recurring_Donation__c rd, Map<String,Schema.RecordTypeInfo> mRdRtInfo, Boolean isNew){
        String sDate = '';
        Integer day = Date.today().day(); 
        Integer month = Date.today().month();
        Integer year = Date.today().year(); 
                
        if(!isNew) {
            day = rd.createdDate.day();
            month = rd.createdDate.month();
            year = rd.createdDate.year();
        }
        
        String sDay = String.valueOf(day);
		String sMonth = String.valueOf(month); 
        
        if (day < 10) { sDay = '0' + sDay; }
        if (month < 10) { sMonth = '0' + sMonth; }
        
        sDate = '_' + sDay + '-' + sMonth + '-' + String.valueOf(year);
        
        if(rd.RecordTypeId == mRdRtInfo.get('Recurring_donation').getRecordTypeId()){
        	rd.Name = 'Cuota'+sDate;   
        }else if(rd.RecordTypeId == mRdRtInfo.get('Associate').getRecordTypeId()){
          	rd.Name = 'Cuota de asociado'+sDate;    
        }        
    }
    
	/*******************************************************************************************************
    * @description	Set the values in the 'LeadSource2; LeadSource3' fields in lead depending of the value 
    * 				of the 'LeadSource1' field.
    * @param 		rd is the Recurrent Donation to update its fields. 
    * @param 		mLsValues is a map that contains values for fields 'LeadSource2; LeadSource3'
    ********************************************************************************************************/
    private void setLeadSourceDependencies(npe03__Recurring_Donation__c rd, Map<String, msf_LeadSourceMasterData__c> mLsValues){
        if(mLsValues.containsKey(rd.msf_LeadSource1__c)){
            rd.msf_LeadSource2__c = mLsValues.get(rd.msf_LeadSource1__c).msf_LeadSource2__c;
            rd.msf_LeadSource3__c = mLsValues.get(rd.msf_LeadSource1__c).msf_LeadSource3__c;
        }
        if(mLsValues.containsKey(rd.msf_CurrentLeadSource1__c)){
            rd.msf_CurrentLeadSource2__c = mLsValues.get(rd.msf_CurrentLeadSource1__c).msf_LeadSource2__c;
            rd.msf_CurrentLeadSource3__c = mLsValues.get(rd.msf_CurrentLeadSource1__c).msf_LeadSource3__c;
        }
    }
    
    /*******************************************************************************************************
    * @description	
    * @param 		 
    ********************************************************************************************************/
    private void setCurrentCampaign(npe03__Recurring_Donation__c rd){
        if(rd.npe03__Recurring_Donation_Campaign__c != null && rd.msf_CurrentCampaign__c == null){
        	rd.msf_CurrentCampaign__c = rd.npe03__Recurring_Donation_Campaign__c;   
        }
    }
    
    /*******************************************************************************************************
    * @description	
    * @param 		 
    ********************************************************************************************************/
    private void setCurrentLeadSource(npe03__Recurring_Donation__c rd){
        if(rd.msf_LeadSource1__c != null && rd.msf_CurrentLeadSource1__c == null){
        	rd.msf_CurrentLeadSource1__c = rd.msf_LeadSource1__c;   
        }
    }
    
	/*******************************************************************************************************
    * @description	
    * @param 		
    * @param 	
    * @return	
    ********************************************************************************************************/
    private List<Contact> setContactFields(List<npe03__Recurring_Donation__c> lRD, Set<ID> sCon){

        List<Contact> lReturnContacts = new List<Contact>();
        Map<ID,Contact> mCon = new Map<ID,Contact>();
        mCon.putAll( [SELECT Id, 
                      msf_BeginDateMSF__c,
                      msf_FirstEntryDateRecurringDonor__c,
                      msf_EntryDateCurrentRecurringDonor__c,
                      msf_LastRecurringDonationDate__c,
                      msf_DateFirstRecurringDonorQuota__c,
                      msf_DateLastRecurringDonorQuota__c,
                      msf_LastAnnualizedQuota__c,
                      msf_FirstAnnualizedQuota__c, 
                      msf_FirstCampaignEntryRecurringDonor__c,
                      msf_FirstCampaignRecurringDonorChannel__c,
                      msf_ValueRecurringDonorCont__c, 
                      npsp__Deceased__c,
                      (SELECT id, msf_AnnualizedQuota__c FROM R00N80000002bOmREAU__r WHERE npe03__Open_Ended_Status__c = 'Open' AND RecordType.DeveloperName = 'Recurring_donation')
                      FROM Contact WHERE ID IN: sCon]);
        
        if(!mCon.isEmpty()){            
            for(npe03__Recurring_Donation__c rd : lRD){
                if(mCon.containskey(rd.npe03__Contact__c)){
                	Contact tempC = mCon.get(rd.npe03__Contact__c);  
                    Decimal iAnnualizedQuota = 0;

                    if(!tempC.R00N80000002bOmREAU__r.isEmpty()){
                        for(npe03__Recurring_Donation__c cRD : tempC.R00N80000002bOmREAU__r){
                        	iAnnualizedQuota += cRD.msf_AnnualizedQuota__c;    
                        }   
                    }
         
                    if(rd.npe03__Open_Ended_Status__c == 'Open'){
                        if(tempC.msf_BeginDateMSF__c == null || tempC.msf_BeginDateMSF__c > rd.npe03__Date_Established__c){
                            tempC.msf_BeginDateMSF__c = rd.npe03__Date_Established__c; 
                            tempC.msf_EntryCampaign__c = rd.npe03__Recurring_Donation_Campaign__c;
                        } 
                        if(tempC.msf_FirstEntryDateRecurringDonor__c == null || tempC.msf_FirstEntryDateRecurringDonor__c > rd.npe03__Date_Established__c){
                            tempC.msf_FirstEntryDateRecurringDonor__c = rd.npe03__Date_Established__c;
                            tempC.msf_FirstAnnualizedQuota__c = iAnnualizedQuota;
                            tempC.msf_FirstCampaignEntryRecurringDonor__c = rd.npe03__Recurring_Donation_Campaign__c;
                            tempC.msf_FirstCampaignRecurringDonorChannel__c = rd.msf_LeadSource1__c;
                        }  
                        if(tempC.msf_EntryDateCurrentRecurringDonor__c == null || tempC.msf_EntryDateCurrentRecurringDonor__c < rd.npe03__Date_Established__c){
                            tempC.msf_EntryDateCurrentRecurringDonor__c = rd.npe03__Date_Established__c;
                        }
                        if(tempC.msf_DateFirstRecurringDonorQuota__c == null || tempC.msf_DateFirstRecurringDonorQuota__c > rd.npe03__Last_Payment_Date__c){
                            tempC.msf_DateFirstRecurringDonorQuota__c = rd.npe03__Last_Payment_Date__c;
                        }
                        if(tempC.msf_DateLastRecurringDonorQuota__c == null || tempC.msf_DateLastRecurringDonorQuota__c < rd.npe03__Last_Payment_Date__c){
                            tempC.msf_DateLastRecurringDonorQuota__c = rd.npe03__Last_Payment_Date__c;
                        }
                        tempC.msf_LastAnnualizedQuota__c = iAnnualizedQuota;
                        tempC.msf_ValueRecurringDonorCont__c = iAnnualizedQuota;
                    }else if(rd.npe03__Open_Ended_Status__c == 'Closed' ){
                        if(tempC.msf_LastRecurringDonationDate__c == null || tempC.msf_LastRecurringDonationDate__c < rd.msf_CancelationDate__c){
                            tempC.msf_LastRecurringDonationDate__c = rd.msf_CancelationDate__c;
                        }  
                        tempC.msf_ValueRecurringDonorCont__c = iAnnualizedQuota;
                        if(iAnnualizedQuota !=0){
                            tempC.msf_LastAnnualizedQuota__c = iAnnualizedQuota;
                        }
                    }
                    
                    if(tempC.msf_FirstAnnualizedQuota__c == null){
                        tempC.msf_FirstAnnualizedQuota__c = iAnnualizedQuota;
                    } 
                    
                    if(tempC.msf_FirstCampaignEntryRecurringDonor__c == null){
                        tempC.msf_FirstCampaignEntryRecurringDonor__c = rd.npe03__Recurring_Donation_Campaign__c;
                        tempC.msf_FirstCampaignRecurringDonorChannel__c = rd.msf_LeadSource1__c;
                    }        
                    
                    if(rd.msf_CancelationReason__c == 'Deceased' && !tempC.npsp__Deceased__c){
                        tempC.npsp__Deceased__c = true;
                        tempC.msf_ContactDeleteReason__c = rd.MSF_CancelationReason__c;
                    }
                    
                    lReturnContacts.add(tempC);
                }
            }        
            
            if(!lReturnContacts.isEmpty()){
            	return lReturnContacts;    
            }            
        }
        
        return null;        
    }
    
    /*******************************************************************************************************
    * @description	
    * @param 		
    * @param 
    * @param
    * @return		
    ********************************************************************************************************/
    private List<msf_QuotaModification__c> createQuotaModification(List<npe03__Recurring_Donation__c> lNewRD, Map<Id,npe03__Recurring_Donation__c> mOldRD){
        
        Boolean isInsert = mOldRD.isEmpty();
        
        List<msf_QuotaModification__c> lNewQM = new List<msf_QuotaModification__c>();
        
        for(npe03__Recurring_Donation__c rd : lNewRD){
            
            if(rd.npe03__Open_Ended_Status__c != 'Closed'){
                
                Datetime dt = Datetime.now();
                Long l = dt.getTime();                
                
                msf_QuotaModification__c tempQM = new msf_QuotaModification__c();
                tempQM.msf_RecurringDonation__c = rd.Id;
                tempQM.msf_CampaignInfluence__c = rd.msf_CurrentCampaign__c;
                tempQM.msf_NewAmount__c = rd.npe03__Amount__c;	
                tempQM.msf_NewRecurringPeriod__c = rd.npe03__Installment_Period__c;	
                tempQM.msf_NewAnnualizedQuota__c = rd.msf_AnnualizedQuota__c;  
                tempQM.msf_LeadSource1__c = rd.msf_CurrentLeadSource1__c;
                tempQM.msf_Canvasser__c = rd.msf_Canvasser__c;
                tempQM.msf_CityCanvasser__c = rd.msf_CityCanvasser__c;
                tempQM.msf_PlaceCanvasser__c = rd.msf_PlaceCanvasser__c;
                tempQM.msf_ContactId__c = rd.npe03__Contact__c;
                
                if(isInsert){
                    tempQM.Name = ('I - '+l);
                    tempQM.msf_ChangeType__c = 'Initial';                    
                    tempQM.msf_ChangeAmount__c = rd.npe03__Amount__c;
                    tempQM.msf_ChangeAnnualizedQuota__c = rd.msf_AnnualizedQuota__c;                    
                    
                    lNewQM.add(tempQM);
                }else{
                    npe03__Recurring_Donation__c oldRD = mOldRD.get(rd.Id);      
                    
                    if(rd.msf_AnnualizedQuota__c != oldRD.msf_AnnualizedQuota__c){                        
                        
                        if(rd.msf_AnnualizedQuota__c > oldRD.msf_AnnualizedQuota__c){
                            tempQM.Name = ('A - '+l);
                            tempQM.msf_ChangeType__c = 'Increase';
                            tempQM.msf_ChangeAnnualizedQuota__c = rd.msf_AnnualizedQuota__c - oldRD.msf_AnnualizedQuota__c;  
                        }else{
                            tempQM.Name = ('D - '+l);
                            tempQM.msf_ChangeType__c = 'Decrease'; 
                            tempQM.msf_ChangeAnnualizedQuota__c = oldRD.msf_AnnualizedQuota__c - rd.msf_AnnualizedQuota__c;  
                        }
                        
                        if(rd.npe03__Amount__c > oldRD.npe03__Amount__c){
                        	tempQM.msf_ChangeAmount__c = rd.npe03__Amount__c - oldRD.npe03__Amount__c;    
                        }else{
                        	tempQM.msf_ChangeAmount__c = oldRD.npe03__Amount__c - rd.npe03__Amount__c;    
                        }
                        
                        lNewQM.add(tempQM);
                    }              
                }                 
            }              
        }       
        
        return lNewQM;        
    }
    
    /*******************************************************************************************************
    * @description	
    * @param 		
    * @param
    * @param 		
    ********************************************************************************************************/
    /*private void allowNewRD (List<npe03__Recurring_Donation__c> lNewRD, Set<ID> sCon, Id idRTQuota){
    	Set<ID> sConWithRD = new Set<ID>();
        
        for(npe03__Recurring_Donation__c rd : [SELECT npe03__Contact__c 
                                               FROM npe03__Recurring_Donation__c 
                                               WHERE npe03__Contact__c IN: sCon 
                                               AND npe03__Open_Ended_Status__c = 'Open' 
                                               AND RecordTypeId =: idRTQuota])
        {
            sConWithRD.add(rd.npe03__Contact__c);
        }
        
        for(npe03__Recurring_Donation__c rd : lNewRD){
            if(sConWithRD.contains(rd.npe03__Contact__c)){
            	rd.addError(System.Label.MSF_RD_ERROR_NEW_OPEN);    
            }
        }
    }*/

}