force-app/main/default/objects/Contact/fields/msf_LevelRelationshipScore__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelRelationshipScore__c</fullName>
    <description>Campo a partir del cual se calcula el nivel de relación: (10-None; 20-One to many; 30-One to few; 40-One to few+; 50-One to one )</description>
    <label>(Level) Relationship Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_Organization__c.field-meta.xml
<CustomField>
    <fullName>msf_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organización</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contactos de organización</relationshipLabel>
    <relationshipName>Organization</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_Program__c.field-meta.xml
<CustomField>
    <fullName>msf_Program__c</fullName>
    <label>Programa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Retención 1r año MASS</fullName>
            </value>
            <value>
                <fullName>Cultivación socios MASS</fullName>
            </value>
            <value>
                <fullName>Cultivación/conversión Donantes MASS</fullName>
            </value>
            <value>
                <fullName>Reactivación bajas MASS</fullName>
            </value>
            <value>
                <fullName>Conversión prospectos</fullName>
            </value>
            <value>
                <fullName>Reactivación/conversión EXDonantes MASS</fullName>
            </value>
            <value>
                <fullName>Otros programas transversales</fullName>
            </value>
            <value>
                <fullName>Retención 1r año MID</fullName>
            </value>
            <value>
                <fullName>Cultivación socios MID</fullName>
            </value>
            <value>
                <fullName>Cultivación/conversión Donantes MID</fullName>
            </value>
            <value>
                <fullName>Reactivación/conversión EXDonantes MID</fullName>
            </value>
            <value>
                <fullName>Reactivación bajas MID</fullName>
            </value>
            <value>
                <fullName>Mid+ Donors</fullName>
            </value>
            <value>
                <fullName>Testamentarios</fullName>
            </value>
            <value>
                <fullName>Otros 12Few+</fullName>
            </value>
            <value>
                <fullName>Major Donors</fullName>
            </value>
            <value>
                <fullName>Potenciales a Major Donors</fullName>
            </value>
            <value>
                <fullName>Públicos Especiales</fullName>
            </value>
            <value>
                <fullName>Otros 121</fullName>
            </value>
            <value>
                <fullName>Vehículo donación de Gran Donante = YES</fullName>
            </value>
            <value>
                <fullName>Prospectos Empresas &amp; Colectivos Mass</fullName>
            </value>
            <value>
                <fullName>Prospectos Fundaciones Mass</fullName>
            </value>
            <value>
                <fullName>Fundaciones Mass</fullName>
            </value>
            <value>
                <fullName>Empresas y Colectivos Mass</fullName>
            </value>
            <value>
                <fullName>Instituciones Públicas Mass</fullName>
            </value>
            <value>
                <fullName>Fundaciones Mid, Mid +</fullName>
            </value>
            <value>
                <fullName>Empresas y Colectivos Mid, Mid +</fullName>
            </value>
            <value>
                <fullName>Instituciones Públicas Mid y Mid +</fullName>
            </value>
            <value>
                <fullName>Fundaciones Estratégicas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_RelationshipLevel__c.field-meta.xml
<CustomField>
    <fullName>msf_RelationshipLevel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level de relación</label>
    <referenceTo>npsp__Level__c</referenceTo>
    <relationshipLabel>Contactos (Level de relación)</relationshipLabel>
    <relationshipName>Contactos2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Organization_Contact.recordType-meta.xml
<RecordType>
    <fullName>Organization_Contact</fullName>
    <active>true</active>
    <label>Organization Contact</label>
</RecordType>

force-app/main/default/classes/MSF_CopyLevelAndProgramContact_TDTM.cls
/**
* @author 		Omega CRM
* @date 		11-2021
* @group 		Contacts
* @description	ContactInformationSummary and PercomsSummary fields management.
*/
global without sharing class MSF_CopyLevelAndProgramContact_TDTM extends npsp.TDTM_Runnable {
    
    global override npsp.TDTM_Runnable.DmlWrapper run(List<SObject> newlist, List<SObject> oldlist, npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult){
        //Attributes
        npsp.TDTM_Runnable.dmlWrapper dmlWrapper = new npsp.TDTM_Runnable.DmlWrapper();
        List<Contact> lNewCon = (List<Contact>) newlist;
        system.debug('lNewCon: ' + lNewCon);
        List<Contact> lOldCon = (List<Contact>) oldlist;
        system.debug('lOldCon: ' + lOldCon);
        Map<Id, Contact> mOldCon = new Map<Id, Contact>();
        if(lOldCon != null){            
            mOldCon.putAll(lOldCon);
        }

        //BEFORE INSERT
        if(triggerAction == npsp.TDTM_Runnable.Action.BeforeInsert) {
            //Map<Id, Contact> mapOrganizationContact = new Map<Id, Contact>();
            List<Contact> listOrganizationContact = new List<Contact>();
            Set<Id> setOrganization = new Set<Id>();
            for(Contact c : lNewCon){
                if(c.RecordTypeId == Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization_Contact').getRecordTypeId()){
                    //mapOrganizationContact.put(c.Id, c);
                    listOrganizationContact.add(c);
                    setOrganization.add(c.msf_Organization__c);
                }
            }
            Map<Id, Contact> mapOrganization = new Map<Id, Contact>();
            mapOrganization = organization(setOrganization);
        
            List<Contact> listOrganizationContactInsert = new List<Contact>();
            updateOrganizationContact(listOrganizationContact, mapOrganization);
        }

        //BEFORE UPDATE
        if(triggerAction == npsp.TDTM_Runnable.Action.BeforeUpdate) {
            List<Contact> listOrganizationContact = new List<Contact>();
            Set<Id> setOrganization = new Set<Id>();
            for(Contact c : lNewCon){
                if(c.RecordTypeId == Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization_Contact').getRecordTypeId()){
                    Contact oldContact = new Contact();
                    oldContact = mOldCon.get(c.Id);
                    if (c.msf_Organization__c != oldContact.msf_Organization__c){
                        listOrganizationContact.add(c);
                        setOrganization.add(c.msf_Organization__c);
                    }
                }
            }

            Map<Id, Contact> mapOrganization = new Map<Id, Contact>();
            mapOrganization = organization(setOrganization);

            List<Contact> listOrganizationContactInsert = new List<Contact>();
            updateOrganizationContact(listOrganizationContact, mapOrganization);
        }

         //AFTER UPDATE
         if(triggerAction == npsp.TDTM_Runnable.Action.AfterUpdate) {
            Map<Id,Contact> mapOrganization = new Map<Id,Contact>();
            Set<Id> setOrganization = new Set<Id>();
            system.debug('lNewCon: ' + lNewCon);
            for(Contact c : lNewCon){
                if(c.RecordTypeId == Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization').getRecordTypeId()){
                    Contact oldContact = new Contact();
                    oldContact = mOldCon.get(c.Id);
                    if (c.msf_RelationshipLevel__c != oldContact.msf_RelationshipLevel__c || c.msf_Program__c != oldContact.msf_Program__c 
                        || c.msf_LevelRelationshipScore__c != oldContact.msf_LevelRelationshipScore__c){
                        mapOrganization.put(c.Id, c);
                        setOrganization.add(c.Id);
                    }
                }
            }

            system.debug('setOrganization:' + setOrganization);
            List<Contact> listOrganizationContact = [SELECT Id, msf_Organization__c, msf_RelationshipLevel__c, msf_Program__c,msf_LevelRelationshipScore__c
                                                    FROM Contact WHERE msf_Organization__c = :setOrganization];
            system.debug('listOrganizationContact: ' + listOrganizationContact);

            List<Contact> listOrganizationContactUpdate = new List<Contact>();
            for (Contact c: listOrganizationContact){
               Contact organization = new Contact();
               Contact organizationContact = new Contact();
               organization = mapOrganization.get(c.msf_Organization__c);
               organizationContact = c;
               organizationContact.msf_RelationshipLevel__c = organization.msf_RelationshipLevel__c;
               organizationContact.msf_Program__c = organization.msf_Program__c;
               organizationContact.msf_LevelRelationshipScore__c = organization.msf_LevelRelationshipScore__c;
               listOrganizationContactUpdate.add(organizationContact);
            } 
            system.debug('listOrganizationContactUpdate: ' + listOrganizationContactUpdate);
            dmlWrapper.objectsToUpdate.addAll(listOrganizationContactUpdate);
            
         }
         system.debug('dmlWrapper: ' + dmlWrapper);
         if (dmlWrapper != null){
            return dmlWrapper;
         } else {
             return null;
         }
    }

    // PRIVATE METHODS

    private Map<Id, Contact> organization (Set<Id> setOrganization){
        Map<Id, Contact> mapOrganization = new Map<Id, Contact>();
        for (Contact c : [SELECT Id, msf_RelationshipLevel__c, msf_Program__c, msf_LevelRelationshipScore__c FROM Contact WHERE Id = :setOrganization]){
            mapOrganization.put(c.Id, c);
        }
        return mapOrganization;   
    }


    private void updateOrganizationContact (List<Contact> listOrganizationContact, Map<Id, Contact> mapOrganization){
        List<Contact> listOrganizationContactInsert = new List<Contact>();
        for (Contact c: listOrganizationContact){
            Contact organizationContact = new contact();
            Contact organization = new contact();
            organization = mapOrganization.get(c.msf_Organization__c);
            c.msf_RelationshipLevel__c = organization.msf_RelationshipLevel__c;
            c.msf_Program__c = organization.msf_Program__c;
            c.msf_LevelRelationshipScore__c = organization.msf_LevelRelationshipScore__c;
        }
    }
}