force-app/main/default/objects/Contact/fields/msf_IsAssosiative__c.field-meta.xml
<CustomField>
    <fullName>msf_IsAssosiative__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es asociado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Individual_Contact.recordType-meta.xml
<RecordType>
    <fullName>Individual_Contact</fullName>
    <active>true</active>
    <label>Individual Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/Lead/fields/msf_IsAssosiative__c.field-meta.xml
<CustomField>
    <fullName>msf_IsAssosiative__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es de asociativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_Status__c.field-meta.xml
<CustomField>
    <fullName>msf_Status__c</fullName>
    <label>Estado candidato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pool Asociativo</fullName>
            </value>
            <value>
                <fullName>Solicita información Asociativo</fullName>
            </value>
            <value>
                <fullName>Formulario incompleto</fullName>
            </value>
            <value>
                <fullName>Pendiente de presentar</fullName>
            </value>
            <value>
                <fullName>Pendiente de aprobar</fullName>
            </value>
            <value>
                <fullName>Asociado Stand-by</fullName>
                <isActive>false</isActive>
                <label>Asociado Stand-by</label>
            </value>
            <value>
                <fullName>Solicitud de alta</fullName>
                <isActive>false</isActive>
                <label>Solicitud de alta</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Associative.recordType-meta.xml
<RecordType>
    <fullName>Associative</fullName>
    <active>true</active>
    <businessProcess>Associative Lead</businessProcess>
    <label>Associative</label>
</RecordType>

force-app/main/default/objects/msf_Associative__c/msf_Associative__c.object-meta.xml
<CustomObject>
    <label>Asociativo</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Número asociado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asociativos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_Associative__c/fields/msf_ContactId__c.field-meta.xml
<CustomField>
    <fullName>msf_ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre del contacto</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Asociativos</relationshipLabel>
    <relationshipName>Asociativos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_Status__c.field-meta.xml
<CustomField>
    <fullName>msf_Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Baja</fullName>
            </value>
            <value>
                <fullName>Baja en proceso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MSF_SummarySectionAssociative_TEST.cls
@isTest
private class MSF_SummarySectionAssociative_TEST {
    @testSetup static void setup(){
        Id IdRTContact = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Individual_Contact').getRecordTypeId();  
        Contact cont = new Contact(LastName='MSF_SummarySectionAssociative_TEST_LastName1', RecordTypeId=IdRTContact);
        insert cont;
        msf_Associative__c assoc = new msf_Associative__c(msf_Status__c='Activo', msf_contactId__c=cont.Id);
        insert assoc; 
        Lead lead = new Lead(LastName='MSF_SummarySectionAssociative_TEST_LastName1',Company='MSF_SummarySectionAssociative_TEST_Company1');
        insert lead;        
    }
    
    @isTest static void getObjectTypeTestTrue(){
        Contact cont = [SELECT Id, LastName FROM Contact WHERE LastName = 'MSF_SummarySectionAssociative_TEST_LastName1' LIMIT 1];
        Object obj = MSF_SummarySectionAssociative_CTRL.getObjectType(cont.Id);        
        Map<String, Object> msfa = (Map<String, Object>)obj;
        System.assert((Boolean)msfa.get('isContact'));
    }
    
    @isTest static void getObjectTypeTestFalse(){
        Lead lead = [SELECT Id FROM Lead WHERE LastName = 'MSF_SummarySectionAssociative_TEST_LastName1' LIMIT 1];
        Object obj = MSF_SummarySectionAssociative_CTRL.getObjectType(lead.Id);  
        Map<String, Object> msfa = (Map<String, Object>)obj;
        System.assert(!(Boolean)msfa.get('isContact'));
    }
    @isTest static void getContactInformationTest(){
        Id IdOrgRTContact = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization').getRecordTypeId();  
        
        Contact cont = [SELECT Id, msf_IsAssosiative__c,RecordTypeId FROM Contact WHERE LastName = 'MSF_SummarySectionAssociative_TEST_LastName1' LIMIT 1];

        Map<String,Object> contactInfo = (Map<String,Object>) MSF_SummarySectionAssociative_CTRL.getContactInformation(cont.Id);
        Contact returnData = (Contact)contactInfo.get('contact');
        System.assertEquals(returnData, cont);
        System.assertEquals(contactInfo.get('numEndorsements'),0);
    }
    
    
    @isTest static void getAssociativeInformationTestTrue(){
        Contact cont = [SELECT Id, LastName FROM Contact WHERE LastName = 'MSF_SummarySectionAssociative_TEST_LastName1' LIMIT 1];
        Map<String,Object> Associatives = (Map<String,Object>)MSF_SummarySectionAssociative_CTRL.getAssociativeInformation(cont.Id);
        System.assertNotEquals(Associatives.get('associative'),null);
    }
    @isTest static void getAssociativeInformationTestFalse(){
        Contact cont = new Contact(LastName='MSF_AssociativeSectionInContact_TEST_LastName2');
        Map<String,Object> Associatives = (Map<String,Object>)MSF_SummarySectionAssociative_CTRL.getAssociativeInformation(cont.Id);
        System.assertEquals(Associatives.get('associative'),null);
    }
    @isTest static void getLeadInformationTest(){
        Lead ld = [SELECT Id FROM LEAD WHERE LastName = 'MSF_SummarySectionAssociative_TEST_LastName1' LIMIT 1];
        Map<String,Object> leadFound = (Map<String,Object>)MSF_SummarySectionAssociative_CTRL.getLeadInformation(ld.Id);        
        System.assertNotEquals(leadFound.get('ld'),null);
    }    
    
}