force-app/main/default/objects/Contact/fields/msf_RecalculateMemberType__c.field-meta.xml
<CustomField>
    <fullName>msf_RecalculateMemberType__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Recalcular tipo de miembro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <description>Indicates if this Contact is designated as the Primary Contact on their Account (read only).</description>
    <formula>Account.npe01__One2OneContact__c = Id</formula>
    <inlineHelpText>Este campo esta seleccionado si es el contacto principal en la cuenta. El contacto principal puede editarse en la cuenta.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Individual_Contact.recordType-meta.xml
<RecordType>
    <fullName>Individual_Contact</fullName>
    <active>true</active>
    <label>Individual Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/msf_AutomatedProcessErrors__c.object-meta.xml
<CustomObject>
    <label>Automated Process Error</label>
    <nameField>
        <displayFormat>ERROR_{YYYY}-{MM}-{DD}_{0000000000}</displayFormat>
        <label>Identificador de error</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automated Process Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>msf_ErrorMessage__c</fullName>
    <label>Mensaje de error</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_FieldsErrors__c.field-meta.xml
<CustomField>
    <fullName>msf_FieldsErrors__c</fullName>
    <label>Campos con errores</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_Process__c.field-meta.xml
<CustomField>
    <fullName>msf_Process__c</fullName>
    <label>Proceso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_RecordId__c.field-meta.xml
<CustomField>
    <fullName>msf_RecordId__c</fullName>
    <label>Id registro</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_StatusCode__c.field-meta.xml
<CustomField>
    <fullName>msf_StatusCode__c</fullName>
    <label>Código de error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_TypeFundraisingContribution__c.field-meta.xml
<CustomField>
    <fullName>msf_TypeFundraisingContribution__c</fullName>
    <formula>CASE(RecordType.DeveloperName , 
     
     &quot;Donation&quot;,CASE( Type ,
           &quot;Recurrent Donation&quot;,&quot;S&quot;,
           &quot;SMS Donor&quot;,&quot;D&quot;,
           &quot;One off Donation&quot;,&quot;D&quot;,
           &quot;SMS Operator&quot;,&quot;D&quot;,
           &quot;Employee or client Donation&quot;,&quot;D&quot;,
           &quot;Recovered Quota&quot;,&quot;S&quot;,
           &quot;Solidarity initiative&quot;,&quot;D&quot;,
           &quot;Solidarity Wedding&quot;,&quot;D&quot;,
           &quot;Solidarity Gift&quot;,&quot;D&quot;, null),

     &quot;Grant&quot;,IF(ISPICKVAL(Type, &quot;Grant&quot;), &quot;G&quot;, null),

     &quot;In_Kind_Gift&quot;,IF(ISPICKVAL(Type, &quot;In-Kind Gift&quot;), &quot;I&quot;, null),

     &quot;Matching_Gift&quot;,IF(ISPICKVAL(Type, &quot;Matching Gift&quot;), &quot;D&quot;, null),

     &quot;Membership&quot;,IF(ISPICKVAL(Type, &quot;Membership&quot;), &quot;A&quot;, null),

     &quot;Legacy&quot;,CASE( Type ,
           &quot;Herencia&quot;,&quot;H&quot;,
           &quot;Pago de Herencia&quot;,&quot;H&quot;, null),

      null

)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo aportación Fundraising</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Contact for this Opportunity. If this is an individual Donation, NPSP attributes the Donation to the Primary Contact. If this is an organizational Donation, NPSP attributes a soft credit to the Primary Contact.</description>
    <inlineHelpText>El contacto principal para esta oportunidad. La función del contacto principal se mantiene sincronizada con este campo. Para donantes individuales, esto significa atribuciones por esta oportunidad.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MSF_MemberType_02_BATCH.cls
/**
* @author       Deloitte
* @date         01-2019
* @group        Contacts
* @description  Calculation of member type.
*/
global without sharing class MSF_MemberType_02_BATCH implements Database.Batchable<sObject>{
    
    global final String query;
    global static final Integer BATCH_SIZE = 1000;
    
    global MSF_MemberType_02_BATCH (){
        String queryStep = '';
        queryStep = 'SELECT Id ';
        queryStep += 'FROM Contact ';
        queryStep += 'WHERE RecordType.DeveloperName IN (\'Individual_Contact\',\'Organization\') AND msf_RecalculateMemberType__c = FALSE ';
        queryStep += 'AND Id IN (SELECT npsp__Primary_Contact__c FROM Opportunity WHERE npsp__Primary_Contact__c != null AND LastModifiedDate >= YESTERDAY AND msf_TypeFundraisingContribution__c IN (\'D\',\'G\',\'I\')) ';
        query = queryStep; 
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Contact> scope){
        
        for(Contact s : scope){
            s.msf_RecalculateMemberType__c = true;            
        }
        
        // DML statements         
        Database.SaveResult[] srList = Database.update(scope, false);            
        //*
        List<msf_AutomatedProcessErrors__c> lAPE = new List<msf_AutomatedProcessErrors__c>(); 
        
        for (Database.SaveResult sr : srList) { // Iterate through each returned result
            if (!sr.isSuccess()) {  // Operation failed, so get all errors                                   
                for(Database.Error err : sr.getErrors()) {
                    msf_AutomatedProcessErrors__c tempAPE = new msf_AutomatedProcessErrors__c(msf_Process__c = 'MSF_MemberType_02', msf_RecordId__c = scope.get(srList.indexOf(sr)).Id, msf_StatusCode__c = String.valueOf(err.getStatusCode()), msf_FieldsErrors__c = String.valueOf(err.getFields()), msf_ErrorMessage__c = String.valueOf(err.getMessage()).abbreviate(255));
                    lAPE.add(tempAPE);
                }
            } 
        }
        
        if(!lAPE.isEmpty()){
            insert lAPE;
        }//*/ 
    }
    
    global void finish(Database.BatchableContext BC){
        System.debug('END BATCH - MSF_MemberType_02_BATCH');
        Id batchJobId = Database.executeBatch(new MSF_MemberType_03_BATCH(), BATCH_SIZE);
    } 
}