force-app/main/default/objects/Contact/fields/msf_IsAssosiative__c.field-meta.xml
<CustomField>
    <fullName>msf_IsAssosiative__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es asociado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/msf_Associative__c.object-meta.xml
<CustomObject>
    <label>Asociativo</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Número asociado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asociativos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_Associative__c/fields/msf_CancellationReason__c.field-meta.xml
<CustomField>
    <fullName>msf_CancellationReason__c</fullName>
    <label>Motivo de baja</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>msf_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Desconectado de la asociación</fullName>
            </value>
            <value>
                <fullName>Desacuerdo con las posiciones / decisiones adoptadas por la asociación</fullName>
            </value>
            <value>
                <fullName>Fallecido</fullName>
            </value>
            <value>
                <fullName>Enlace a otra asociación de MSF</fullName>
            </value>
            <value>
                <fullName>Incumplimiento de los estatutos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_ContactId__c.field-meta.xml
<CustomField>
    <fullName>msf_ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre del contacto</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Asociativos</relationshipLabel>
    <relationshipName>Asociativos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_ReceiveEmailCommunications__c.field-meta.xml
<CustomField>
    <fullName>msf_ReceiveEmailCommunications__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Recibir comunicaciones por email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_Status__c.field-meta.xml
<CustomField>
    <fullName>msf_Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Baja</fullName>
            </value>
            <value>
                <fullName>Baja en proceso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/npe03__Recurring_Donation__c.object-meta.xml
<CustomObject>
    <description>Recurring Donations track charitable giving where a donor specifies an amount of money to be given on a regular basis.</description>
    <label>Recurring Donation</label>
    <nameField>
        <label>Recurring Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npe03__Contact__c.field-meta.xml
<CustomField>
    <fullName>npe03__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>R00N80000002bOmREAU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npe03__Open_Ended_Status__c.field-meta.xml
<CustomField>
    <fullName>npe03__Open_Ended_Status__c</fullName>
    <label>Open Ended Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npsp4hub__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>npsp4hub__Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>CreditCard</fullName>
            </value>
            <value>
                <fullName>PAGARÉS</fullName>
            </value>
            <value>
                <fullName>HERENCIAS Y LEGADOS</fullName>
            </value>
            <value>
                <fullName>FACEBOOK</fullName>
            </value>
            <value>
                <fullName>GIRO POSTAL RECEPCIÓN</fullName>
            </value>
            <value>
                <fullName>EFECTIVO ASOCIATIVO</fullName>
            </value>
            <value>
                <fullName>CUENTA ABOGADO/CUENTA PUENTE</fullName>
            </value>
            <value>
                <fullName>EN ESPECIE-SERVICIOS</fullName>
            </value>
            <value>
                <fullName>TALÓN BANCARIO ESTÁNDAR</fullName>
            </value>
            <value>
                <fullName>INICIATIVA SOLIDARIA ONLINE</fullName>
            </value>
            <value>
                <fullName>GIRO POSTAL</fullName>
            </value>
            <value>
                <fullName>EFECTIVO S.C.</fullName>
            </value>
            <value>
                <fullName>GRANT</fullName>
            </value>
            <value>
                <fullName>TALÓN NO ESTÁNDAR EXTRANJERO</fullName>
            </value>
            <value>
                <fullName>TALÓN NO ESTÁNDAR EN EUROS</fullName>
            </value>
            <value>
                <fullName>TC ONLINE</fullName>
            </value>
            <value>
                <fullName>EFECTIVO RECEPCIÓN</fullName>
            </value>
            <value>
                <fullName>PAYPAL</fullName>
            </value>
            <value>
                <fullName>TRUSTLY - TR ONLINE</fullName>
            </value>
            <value>
                <fullName>ACMA</fullName>
            </value>
            <value>
                <fullName>TRANSFERENCIA BANCARIA</fullName>
            </value>
            <value>
                <fullName>EN ESPECIE-INMOVILIZADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npsp4hub__Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>npsp4hub__Payment_Processor__c</fullName>
    <label>Payment Processor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>npsp4hub__Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PaymentHub-SEPA</fullName>
            </value>
            <value>
                <fullName>PaymentHub-Redsys</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npsp4hub__Target__c.field-meta.xml
<CustomField>
    <fullName>npsp4hub__Target__c</fullName>
    <label>Target</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>npsp4hub__Payment_Processor__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>LIBERBANK (CAJASTUR)</fullName>
            </value>
            <value>
                <fullName>TRIODOS BANK</fullName>
            </value>
            <value>
                <fullName>CAIXABANK DONATIVOS</fullName>
            </value>
            <value>
                <fullName>BANKIA</fullName>
            </value>
            <value>
                <fullName>CAIXABANK INTERNA</fullName>
            </value>
            <value>
                <fullName>BANC SABADELL</fullName>
            </value>
            <value>
                <fullName>BANCO SANTANDER BIZUM</fullName>
            </value>
            <value>
                <fullName>CUENTA DOLARES</fullName>
            </value>
            <value>
                <fullName>CUENTA CUADRE-PROVISIONES</fullName>
            </value>
            <value>
                <fullName>LA CAIXA CCC OPERATIVA</fullName>
            </value>
            <value>
                <fullName>KUTXABANK</fullName>
            </value>
            <value>
                <fullName>ABANCA</fullName>
            </value>
            <value>
                <fullName>CAIXABANK FUSION BANKIA</fullName>
            </value>
            <value>
                <fullName>UNICAJA</fullName>
            </value>
            <value>
                <fullName>BBVA BCN GENERAL</fullName>
            </value>
            <value>
                <fullName>BANCO SANTANDER EMERGENCIAS</fullName>
            </value>
            <value>
                <fullName>BANCO SANTANDER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/recordTypes/Associate.recordType-meta.xml
<RecordType>
    <fullName>Associate</fullName>
    <active>true</active>
    <label>Associate</label>
</RecordType>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MSF_AssociativeLogic_TEST.cls
/**
* @author       Deloitte
* @date         02-2019
* @group        Associative
* @description  test class for the MSF_AssociativeLogic_TDTM class.
*/
@isTest
private class MSF_AssociativeLogic_TEST {
    
    @testSetup static void setup(){
        
        //Create Trigger
        npsp__Trigger_Handler__c thCon = new npsp__Trigger_Handler__c(
            Name = 'TriggerTestAssociativeLogic',
            npsp__Class__c = 'MSF_AssociativeLogic_TDTM',
            npsp__Object__c = 'msf_Associative__c',
            npsp__Trigger_Action__c = 'BeforeInsert;BeforeUpdate;AfterInsert;AfterUpdate',
            npsp__Active__c = true, 
            npsp__Load_Order__c = 1,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );
        upsert thCon;
        
        //Initialize values
        //Contact
        Contact cont = new Contact(LastName='MSF_AssociativeLogic_TEST_LastName1');
        insert cont;
        
        //Donation
        npe03__Recurring_Donation__c don = new npe03__Recurring_Donation__c();
        don.npe03__Contact__c = cont.Id;
        don.npe03__Open_Ended_Status__c = 'Open';
        don.npsp4hub__Payment_Method__c = 'Direct Debit';
        don.npsp4hub__Payment_Processor__c  = 'PaymentHub-SEPA';
        don.npsp4hub__Target__c  = 'LA CAIXA CCC OPERATIVA';
        don.RecordTypeId = Schema.SObjectType.npe03__Recurring_Donation__c.getRecordTypeInfosByDeveloperName().get('Associate').getRecordTypeId();
        insert don;
        
        //Associative
        msf_Associative__c assoLogic = new msf_Associative__c();
        assoLogic.msf_Status__c = 'Activo';
        assoLogic.msf_ContactId__c = cont.Id;
        insert assoLogic;
    }
    
    @isTest static void testUpdateStatusBaja(){
        msf_Associative__c assoLogic = [SELECT Id FROM msf_Associative__c  LIMIT 1];
        assoLogic.msf_Status__c = 'Baja';
        assoLogic.msf_CancellationReason__c = 'Fallecido';
        update assoLogic;
     
        assoLogic = [SELECT msf_receiveEmailCommunications__c FROM msf_Associative__c LIMIT 1];
        System.assert(!assoLogic.msf_receiveEmailCommunications__c);
    }
    
    @isTest static void testInsertStatusAlta(){
        Contact cont = new Contact(LastName='MSF_AssociativeLogic_TEST_LastName2');
        insert cont;
        
        //Donation
        npe03__Recurring_Donation__c don = new npe03__Recurring_Donation__c();
        don.npe03__Contact__c = cont.Id;
        don.npe03__Open_Ended_Status__c = 'Open';
         don.npsp4hub__Payment_Method__c = 'Direct Debit';
        don.npsp4hub__Payment_Processor__c  = 'PaymentHub-SEPA';
        don.npsp4hub__Target__c  = 'LA CAIXA CCC OPERATIVA';
        don.RecordTypeId = Schema.SObjectType.npe03__Recurring_Donation__c.getRecordTypeInfosByDeveloperName().get('Associate').getRecordTypeId();
        insert don;
        
        //Associative
        msf_Associative__c assoLogic = new msf_Associative__c();
        assoLogic.msf_Status__c = 'Activo';
        assoLogic.msf_ContactId__c = cont.Id;
        insert assoLogic;
                
        cont = [SELECT Id,msf_IsAssosiative__c FROM Contact WHERE LastName='MSF_AssociativeLogic_TEST_LastName2'];    
        System.assert(cont.msf_IsAssosiative__c);
    }

}