force-app/main/default/objects/Contact/fields/msf_CRMExternalId__c.field-meta.xml
<CustomField>
    <fullName>msf_CRMExternalId__c</fullName>
    <description>WebSAS Member ID</description>
    <displayFormat>{0}</displayFormat>
    <externalId>true</externalId>
    <label>ID Miembro</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Contact/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <description>Indicates if this Contact is designated as the Primary Contact on their Account (read only).</description>
    <formula>Account.npe01__One2OneContact__c = Id</formula>
    <inlineHelpText>Este campo esta seleccionado si es el contacto principal en la cuenta. El contacto principal puede editarse en la cuenta.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/msf_opportunity_h__x/msf_opportunity_h__x.object-meta.xml
<CustomObject>
    <description>msf_opportunity_h</description>
    <externalDataSource>AWS</externalDataSource>
    <externalName>msf_opportunity_h</externalName>
    <label>Oportunidad histórica</label>
    <pluralLabel>Oportunidades históricas</pluralLabel>
</CustomObject>

force-app/main/default/objects/msf_opportunity_h__x/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <description>amount</description>
    <externalDeveloperName>amount</externalDeveloperName>
    <label>Importe</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/msf_opportunity_h__x/fields/closedate__c.field-meta.xml
<CustomField>
    <fullName>closedate__c</fullName>
    <description>closedate</description>
    <externalDeveloperName>closedate</externalDeveloperName>
    <label>Fecha de cierre</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/msf_opportunity_h__x/fields/npsp_primary_contact_c__c.field-meta.xml
<CustomField>
    <fullName>npsp_primary_contact_c__c</fullName>
    <description>npsp__primary_contact__c</description>
    <externalDeveloperName>npsp__primary_contact__c</externalDeveloperName>
    <label>Contacto principal</label>
    <length>18</length>
    <referenceTargetField>Contact.msf_CustomExternalId__c</referenceTargetField>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades históricas</relationshipLabel>
    <relationshipName>msf_opportunity_h</relationshipName>
    <type>IndirectLookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_CRMExternalId__c.field-meta.xml
<CustomField>
    <fullName>msf_CRMExternalId__c</fullName>
    <displayFormat>{0}</displayFormat>
    <externalId>true</externalId>
    <label>Id aportación</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Contact for this Opportunity. If this is an individual Donation, NPSP attributes the Donation to the Primary Contact. If this is an organizational Donation, NPSP attributes a soft credit to the Primary Contact.</description>
    <inlineHelpText>El contacto principal para esta oportunidad. La función del contacto principal se mantiene sincronizada con este campo. Para donantes individuales, esto significa atribuciones por esta oportunidad.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Historical.recordType-meta.xml
<RecordType>
    <fullName>Historical</fullName>
    <active>true</active>
    <businessProcess>Donation</businessProcess>
    <label>Historical</label>
</RecordType>

force-app/main/default/classes/MSF_ReassignOpportunity_CTRL_TEST.cls
/**
 * @description       : 
 * @author            : sheredia@omegacrmconsulting.com
 * @group             : 
 * @last modified on  : 04-04-2022
 * @last modified by  : sheredia@omegacrmconsulting.com
**/
@isTest
public with sharing class MSF_ReassignOpportunity_CTRL_TEST {

    @TestSetup
    static void makeData(){
    }

    @isTest static void testGetInformationNoContact() {
        try {
            MSF_ReassignOpportunity_CTRL.getInformation(null);   
        } catch (Exception e) {
            System.assert(false, 'Error: ' + e);
        }
    }

    @isTest static void testGetInformationContactTry() { 
        //TODO Hacer que con.msf_CRMExternalId__c = msf_opportunity_h__x.npsp_primary_contact_c__c 
        try {
            Contact con = new Contact(LastName='Test');
            insert con;
    
            MSF_ReassignOpportunity_CTRL.getInformation(null); 
        } catch (Exception e) {
            System.assert(false, 'Error: ' + e);
        }
    }

    @isTest static void testGetInformationContactCatch() {
        try {
            Contact con = new Contact(LastName='Test');
            insert con;
    
            MSF_ReassignOpportunity_CTRL.getInformation(null); 
        } catch (Exception e) {
            System.assert(false, 'Error: ' + e);
        }
    }

    @isTest static void testGetTargetInformation() {
        try {
            Contact con = new Contact(LastName='Test');
            insert con;

            Opportunity opp = new Opportunity(Name = 'Test', StageName = 'Prospecting' , npsp__primary_contact__c = con.Id, CloseDate = System.today(), RecordTypeId = [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND DeveloperName = 'Historical'].ID );
            insert opp;

            con = [SELECT ID, msf_CRMExternalId__c FROM Contact LIMIT 1];

            MSF_ReassignOpportunity_CTRL.getTargetInformation(con.msf_CRMExternalId__c, System.today());
        } catch (Exception e) {
            System.assert(false, 'Error: ' + e);
        }
    }

    @isTest static void testGetTargetInformationCatch() {
        try {
            Contact con = new Contact(LastName='Test');
            insert con;

            MSF_ReassignOpportunity_CTRL.getTargetInformation(null, System.today());
            
            MSF_ReassignOpportunity_CTRL.getTargetInformation('1234', System.today());
        } catch (Exception e) {
            System.assert(false, 'Error: ' + e);
        }
    }

    @isTest static void testReassignProcess() {
        try {
            Contact con = new Contact(LastName='Test');
            insert con;

            Opportunity opp = new Opportunity(Name = 'Test', StageName = 'Prospecting' , npsp__primary_contact__c = con.Id, CloseDate = System.today(), RecordTypeId = [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND DeveloperName = 'Historical'].ID );
            insert opp;

            msf_opportunity_h__x exOppHis = new msf_opportunity_h__x(closedate__c = System.today(), amount__c = 0);

            MSF_ReassignOpportunity_CTRL.mockedListRequests.add(exOppHis);
            MSF_ReassignOpportunity_CTRL.reassignProcess (con, con, exOppHis, opp, opp);
            
        } catch (Exception e) {
            System.assert(false, 'Error: ' + e);
        }
    }

    @isTest static void testReassignProcessTargetNull() {
        try {
            Contact con = new Contact(LastName='Test');
            insert con;

            Opportunity opp = new Opportunity(Name = 'Test', StageName = 'Prospecting' , npsp__primary_contact__c = con.Id, CloseDate = System.today(), RecordTypeId = [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND DeveloperName = 'Historical'].ID );
            insert opp;

            msf_opportunity_h__x exOppHis = new msf_opportunity_h__x(closedate__c = System.today(), amount__c = 0);

            MSF_ReassignOpportunity_CTRL.mockedListRequests.add(exOppHis);
            MSF_ReassignOpportunity_CTRL.reassignProcess (con, con, exOppHis, opp, null);
            
        } catch (Exception e) {
            System.assert(false, 'Error: ' + e);
        }
    }

}