force-app/main/default/objects/Contact/fields/msf_CRMExternalId__c.field-meta.xml
<CustomField>
    <fullName>msf_CRMExternalId__c</fullName>
    <description>WebSAS Member ID</description>
    <displayFormat>{0}</displayFormat>
    <externalId>true</externalId>
    <label>ID Miembro</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_CRMHistoryIds__c.field-meta.xml
<CustomField>
    <fullName>msf_CRMHistoryIds__c</fullName>
    <label>Histórico de Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_opportunity_h__x/msf_opportunity_h__x.object-meta.xml
<CustomObject>
    <description>msf_opportunity_h</description>
    <externalDataSource>AWS</externalDataSource>
    <externalName>msf_opportunity_h</externalName>
    <label>Oportunidad histórica</label>
    <pluralLabel>Oportunidades históricas</pluralLabel>
</CustomObject>

force-app/main/default/objects/msf_opportunity_h__x/fields/npsp_primary_contact_c__c.field-meta.xml
<CustomField>
    <fullName>npsp_primary_contact_c__c</fullName>
    <description>npsp__primary_contact__c</description>
    <externalDeveloperName>npsp__primary_contact__c</externalDeveloperName>
    <label>Contacto principal</label>
    <length>18</length>
    <referenceTargetField>Contact.msf_CustomExternalId__c</referenceTargetField>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades históricas</relationshipLabel>
    <relationshipName>msf_opportunity_h</relationshipName>
    <type>IndirectLookup</type>
</CustomField>

force-app/main/default/classes/MSF_FutureDuplicateCheckAws_CTRL.cls
public class MSF_FutureDuplicateCheckAws_CTRL {

    @future
    public static void processRecords(Set<Id> mergedRecordIds, Id master_id) {

        Contact master_contact = [SELECT Id, msf_CRMExternalId__c, msf_CRMHistoryIds__c FROM Contact WHERE Id = :master_id];
        String id_miembro_master = (String) master_contact.get('msf_CRMExternalId__c');
        
        String history_ids = (String) master_contact.get('msf_CRMHistoryIds__c');
        List<String> history_id_list = history_ids.split(',');

        for (String history_id: history_id_list) {

            List<msf_opportunity_h__x> opportunities = [SELECT Id, npsp_primary_contact_c__c FROM msf_opportunity_h__x WHERE npsp_primary_contact_c__c = :history_id];

            for (msf_opportunity_h__x opp: opportunities) {
                opp.npsp_primary_contact_c__c = id_miembro_master;
            }

            database.updateAsync(opportunities);
        }
    }
}