force-app/main/default/objects/Contact/fields/msf_MemberType__c.field-meta.xml
<CustomField>
    <fullName>msf_MemberType__c</fullName>
    <defaultValue>&apos;Nada&apos;</defaultValue>
    <label>Tipo de miembro</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_NextMemberTypeCheck__c.field-meta.xml
<CustomField>
    <fullName>msf_NextMemberTypeCheck__c</fullName>
    <label>Próxima comprobación tipo de miembro</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_RecalculateMemberType__c.field-meta.xml
<CustomField>
    <fullName>msf_RecalculateMemberType__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Recalcular tipo de miembro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Individual_Contact.recordType-meta.xml
<RecordType>
    <fullName>Individual_Contact</fullName>
    <active>true</active>
    <label>Individual Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/msf_AutomatedProcessErrors__c.object-meta.xml
<CustomObject>
    <label>Automated Process Error</label>
    <nameField>
        <displayFormat>ERROR_{YYYY}-{MM}-{DD}_{0000000000}</displayFormat>
        <label>Identificador de error</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automated Process Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>msf_ErrorMessage__c</fullName>
    <label>Mensaje de error</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_FieldsErrors__c.field-meta.xml
<CustomField>
    <fullName>msf_FieldsErrors__c</fullName>
    <label>Campos con errores</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_Process__c.field-meta.xml
<CustomField>
    <fullName>msf_Process__c</fullName>
    <label>Proceso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_RecordId__c.field-meta.xml
<CustomField>
    <fullName>msf_RecordId__c</fullName>
    <label>Id registro</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_StatusCode__c.field-meta.xml
<CustomField>
    <fullName>msf_StatusCode__c</fullName>
    <label>Código de error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MSF_MemberType_03_BATCH.cls
/**
* @author       Deloitte
* @date         01-2019
* @group        Contacts
* @description  Calculation of member type.
*/
global without sharing class MSF_MemberType_03_BATCH implements Database.Batchable<sObject>{
    
    global final String query; 
    
    global MSF_MemberType_03_BATCH (){
        String queryStep = '';
        queryStep = 'SELECT Id, msf_NextMemberTypeCheck__c ';
        queryStep += 'FROM Contact ';
        queryStep += 'WHERE RecordType.DeveloperName IN (\'Individual_Contact\',\'Organization\') ';
        queryStep += 'AND (msf_RecalculateMemberType__c = TRUE ';
        queryStep += 'OR msf_MemberType__c = null ';
        queryStep += 'OR msf_NextMemberTypeCheck__c = null ';
        queryStep += 'OR msf_NextMemberTypeCheck__c < TOMORROW)';
        query = queryStep; 
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contact> scope){

        List<Contact> lConToUpdate = new List<Contact>();
        lConToUpdate.addAll(MSF_SharedMethods_UTIL.contactMemberType(scope));
        
        // DML statements
        if(!lConToUpdate.isEmpty()){            
            Database.SaveResult[] srList = Database.update(lConToUpdate, false);            
            //*
            List<msf_AutomatedProcessErrors__c> lAPE = new List<msf_AutomatedProcessErrors__c>(); 

            for (Database.SaveResult sr : srList) { // Iterate through each returned result
                if (!sr.isSuccess()) {  // Operation failed, so get all errors                                   
                    for(Database.Error err : sr.getErrors()) {
                        msf_AutomatedProcessErrors__c tempAPE = new msf_AutomatedProcessErrors__c(msf_Process__c = 'MSF_MemberType_03', msf_RecordId__c = scope.get(srList.indexOf(sr)).Id, msf_StatusCode__c = String.valueOf(err.getStatusCode()), msf_FieldsErrors__c = String.valueOf(err.getFields()), msf_ErrorMessage__c = String.valueOf(err.getMessage()).abbreviate(255));
                        lAPE.add(tempAPE);
                    }
                }
            }
            
            if(!lAPE.isEmpty()){
                insert lAPE;
            }//*/ 
        }
    }
    
    global void finish(Database.BatchableContext BC){
        System.debug('END BATCH - MSF_MemberType_03_BATCH');
    }    
}