force-app/main/default/objects/Contact/fields/msf_ContactDeleteReason__c.field-meta.xml
<CustomField>
    <fullName>msf_ContactDeleteReason__c</fullName>
    <label>Motivo fin de relación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ethical code</fullName>
                <label>Código ético</label>
            </value>
            <value>
                <fullName>Deceased</fullName>
                <label>Fallecido</label>
            </value>
            <value>
                <fullName>Tests</fullName>
                <label>Pruebas</label>
            </value>
            <value>
                <fullName>Complaints</fullName>
                <label>Quejas</label>
            </value>
            <value>
                <fullName>Country change</fullName>
                <label>Cambio de país</label>
            </value>
            <value>
                <fullName>Disolución</fullName>
            </value>
            <value>
                <fullName>Miembro eliminado</fullName>
            </value>
            <value>
                <fullName>By ethical code</fullName>
                <isActive>false</isActive>
                <label>By ethical code</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_IsAssosiative__c.field-meta.xml
<CustomField>
    <fullName>msf_IsAssosiative__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es asociado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/npsp__Deceased__c.field-meta.xml
<CustomField>
    <fullName>npsp__Deceased__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates the Contact is deceased. When selected, NPSP excludes this Contact from Household Naming (unless this Contact is the only one in the Household) and from standard email and phone lists.</description>
    <inlineHelpText>Cuando se encuentra seleccionado, se excluye al contacto de el nombre y saludos de la familia, correos electrónicos y llamados.</inlineHelpText>
    <label>Deceased</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/msf_Associative__c.object-meta.xml
<CustomObject>
    <label>Asociativo</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Número asociado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asociativos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_Associative__c/fields/msf_CancellationReason__c.field-meta.xml
<CustomField>
    <fullName>msf_CancellationReason__c</fullName>
    <label>Motivo de baja</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>msf_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Desconectado de la asociación</fullName>
            </value>
            <value>
                <fullName>Desacuerdo con las posiciones / decisiones adoptadas por la asociación</fullName>
            </value>
            <value>
                <fullName>Fallecido</fullName>
            </value>
            <value>
                <fullName>Enlace a otra asociación de MSF</fullName>
            </value>
            <value>
                <fullName>Incumplimiento de los estatutos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_ContactId__c.field-meta.xml
<CustomField>
    <fullName>msf_ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre del contacto</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Asociativos</relationshipLabel>
    <relationshipName>Asociativos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_ReceiveEmailCommunications__c.field-meta.xml
<CustomField>
    <fullName>msf_ReceiveEmailCommunications__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Recibir comunicaciones por email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_Status__c.field-meta.xml
<CustomField>
    <fullName>msf_Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Baja</fullName>
            </value>
            <value>
                <fullName>Baja en proceso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/npe03__Recurring_Donation__c.object-meta.xml
<CustomObject>
    <description>Recurring Donations track charitable giving where a donor specifies an amount of money to be given on a regular basis.</description>
    <label>Recurring Donation</label>
    <nameField>
        <label>Recurring Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npe03__Contact__c.field-meta.xml
<CustomField>
    <fullName>npe03__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>R00N80000002bOmREAU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/npe03__Open_Ended_Status__c.field-meta.xml
<CustomField>
    <fullName>npe03__Open_Ended_Status__c</fullName>
    <label>Open Ended Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/recordTypes/Associate.recordType-meta.xml
<RecordType>
    <fullName>Associate</fullName>
    <active>true</active>
    <label>Associate</label>
</RecordType>

force-app/main/default/classes/MSF_AssociativeLogic_TDTM.cls
/**
* @author 		Deloitte
* @date 		12-2018
* @group 		Associative
* @description	Trigger Handler that controls the associative logic
*/

global without sharing class MSF_AssociativeLogic_TDTM extends npsp.TDTM_Runnable {

	/*******************************************************************************************************
    * @description	Trigger Handler on Associative that controls the communication permissions, the associative 
    * 				check of the related contact and the cancellation of the recurring donations 
    * @param 		listNew the list of Associative from trigger new. 
    * @param 		listOld the list of Associative from trigger old. 
    * @param 		triggerAction which trigger event (BeforeInsert, AfterInsert, etc.). 
    * @param 		objResult the describe for Associative.
    * @return 		dmlWrapper. 
    ********************************************************************************************************/
    global override npsp.TDTM_Runnable.DmlWrapper run(List<SObject> newlist, List<SObject> oldlist, npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {    
    	
        //Attributes
        List<msf_Associative__c> lNewAs = (List<msf_Associative__c>) newlist;      
		List<msf_Associative__c> lOldAs = (List<msf_Associative__c>) oldlist;
        Map<Id, msf_Associative__c> mOldAs = new Map<Id, msf_Associative__c>();
        if(lOldAs != null){            
            mOldAs.putAll(lOldAs);
        }    
        
        List<Contact> lConToUpdate = new List<Contact>();
        List<npe03__Recurring_Donation__c> lRDToUpdate = new List<npe03__Recurring_Donation__c>();
        Set<ID> sCon = new Set<ID>();
        
        Set<ID> lDisableContactRD = new Set<ID>();
   

        //Actions
        
        /*** BEFORE INSERT & BEFORE UPDATE ***/        
        if(triggerAction == npsp.TDTM_Runnable.Action.BeforeInsert || triggerAction == npsp.TDTM_Runnable.Action.BeforeUpdate) {	
            
            for(msf_Associative__c asso : lNewAs){
                if(asso.msf_Status__c == 'Baja'){
                    asso.msf_receiveEmailCommunications__c = false;
                }else if(asso.msf_Status__c == 'Activo'){
                	asso.msf_receiveEmailCommunications__c = true;    
                }  
                
                sCon.add(asso.msf_ContactId__c);
            } 

            allowNewAsso(lNewAs, sCon);    
                       
        } 
        
        /*** AFTER INSERT & AFTER UPDATE ***/
        if(triggerAction == npsp.TDTM_Runnable.Action.AfterInsert || triggerAction == npsp.TDTM_Runnable.Action.AfterUpdate) {	
            
            for(msf_Associative__c asso : lNewAs){  
                
                if(lOldAs == null || 
                   asso.msf_Status__c != mOldAs.get(asso.Id).msf_Status__c || 
                   asso.msf_CancellationReason__c != mOldAs.get(asso.Id).msf_CancellationReason__c)
                {
                    Contact tempCon = new Contact();
                    tempCon.Id = asso.msf_ContactId__c;
                    
                    if(asso.msf_Status__c == 'Baja'){
                        tempCon.msf_IsAssosiative__c = false;
                        if(asso.msf_CancellationReason__c == 'Fallecido'){
                            tempCon.npsp__Deceased__c = true;
                            tempCon.msf_ContactDeleteReason__c = 'Deceased';
                        }                        
                        lDisableContactRD.add(asso.msf_ContactId__c);
                    }else if(asso.msf_Status__c == 'Activo'){
                        tempCon.msf_IsAssosiative__c = true;   
                    }
   
                    lConToUpdate.add(tempCon);
                }
            } 
            
            if(!lDisableContactRD.isEmpty()){                
                List<npe03__Recurring_Donation__c> tempRD = closeMembershipQuota(lDisableContactRD);
                if(!tempRD.isEmpty()){
                	lRDToUpdate.addAll(tempRD);    
                }    
            }             
        }  
        
        /*** DML OPERATIONS ***/
        npsp.TDTM_Runnable.dmlWrapper dmlWrapper = new npsp.TDTM_Runnable.DmlWrapper();
        dmlWrapper.objectsToUpdate.addAll((List<Contact>) lConToUpdate);
        dmlWrapper.objectsToUpdate.addAll((List<npe03__Recurring_Donation__c>) lRDToUpdate);

        if(lConToUpdate.isEmpty() && lRDToUpdate.isEmpty()){
            return null;
        }
        
        return dmlWrapper; 
    } 
    
    
    /*******************************************************************************************************
    * @description	Close recurring donations of the membership type for related contacts.
    * @param 		sConIDs is a set with contacts ids of the related associative records.
    * @return		List<npe03__Recurring_Donation__c> Recurring donatios to close.
    ********************************************************************************************************/
    private List<npe03__Recurring_Donation__c> closeMembershipQuota (Set<ID> sConIds){
        List<npe03__Recurring_Donation__c> lRDToUpdate = new List<npe03__Recurring_Donation__c>();
        
        for(npe03__Recurring_Donation__c rd : [SELECT Id FROM npe03__Recurring_Donation__c 
                                               WHERE npe03__Contact__c IN: sConIds 
                                               AND npe03__Open_Ended_Status__c = 'Open' 
                                               AND RecordType.DeveloperName = 'Associate'])
        {
            rd.npe03__Open_Ended_Status__c = 'Closed';
            /* Set a cancellation reason ? */
            lRDToUpdate.add(rd);
        }
        
        return lRDToUpdate;
    }
    
    /*******************************************************************************************************
    * @description	Avoid creating an associative record for a contact that already has one.
    * @param		lNewAs is the list of the new or updated associative records.			
    * @param		sConIDs is a set with contacts ids of the related associative records.
    ********************************************************************************************************/
    private void allowNewAsso (List<msf_Associative__c> lNewAs, Set<ID> sConIDs){
        Set<ID> sConWithAsso = new Set<ID>(); 
        Set<ID> sAssoId = new Set<ID>();
        
        for(msf_Associative__c asso : lNewAs){
        	sAssoId.add(asso.Id);  
        }
        
        for(msf_Associative__c asso : [SELECT id, msf_ContactId__c 
                                       FROM msf_Associative__c 
                                       WHERE msf_ContactId__c IN: sConIDs
                                       AND ID NOT IN : sAssoId
                                       AND msf_Status__c = 'Activo'] )
        {
            sConWithAsso.add(asso.msf_ContactId__c);
        }
        
        for(msf_Associative__c asso : lNewAs){
            if(sConWithAsso.contains(asso.msf_ContactId__c) && asso.msf_Status__c == 'Activo' ){
            	asso.addError(System.Label.MSF_TWO_ASSOCIATED_RECORD_ERROR);    
            }
        }
    }
    
}