force-app/main/default/objects/Contact/fields/msf_BigDonorContact__c.field-meta.xml
<CustomField>
    <fullName>msf_BigDonorContact__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Implica exclusión programa de prospectos.</inlineHelpText>
    <label>Contacto de gran donante</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_ContactInformationSummary__c.field-meta.xml
<CustomField>
    <fullName>msf_ContactInformationSummary__c</fullName>
    <label>Resumen de los datos de contacto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_FechaCambioLevelEconomico__c.field-meta.xml
<CustomField>
    <fullName>msf_FechaCambioLevelEconomico__c</fullName>
    <label>Fecha cambio de Level económico</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_FechaCambioLevelRelacion__c.field-meta.xml
<CustomField>
    <fullName>msf_FechaCambioLevelRelacion__c</fullName>
    <label>Fecha cambio de Level relación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_Forced__c.field-meta.xml
<CustomField>
    <fullName>msf_Forced__c</fullName>
    <inlineHelpText>Implica cambio de level o programa.</inlineHelpText>
    <label>Level de relación o programa forzado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>121</fullName>
            </value>
            <value>
                <fullName>12Few</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_IsAssosiative__c.field-meta.xml
<CustomField>
    <fullName>msf_IsAssosiative__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es asociado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_IsInfluencer__c.field-meta.xml
<CustomField>
    <fullName>msf_IsInfluencer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es influencer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_IsPublicPerson__c.field-meta.xml
<CustomField>
    <fullName>msf_IsPublicPerson__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Implica exclusión programa de prospectos.</inlineHelpText>
    <label>Es persona pública</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_IsStrategic__c.field-meta.xml
<CustomField>
    <fullName>msf_IsStrategic__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Implica cambio de level o programa.</inlineHelpText>
    <label>Es estratégico</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_Level__c.field-meta.xml
<CustomField>
    <fullName>msf_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level económico</label>
    <referenceTo>npsp__Level__c</referenceTo>
    <relationshipLabel>Contactos</relationshipLabel>
    <relationshipName>Contactos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelHCCurrentFiscalYear__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelHCCurrentFiscalYear__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) H.Credit año fiscal en curso</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelHCLifetime__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelHCLifetime__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) H.Credit Lifetime</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelHCLifetimeVD__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelHCLifetimeVD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) H.Credit Lifetime VD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelHCNextFiscalYear__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelHCNextFiscalYear__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) H.Credit próximo año fiscal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelHCOneFiscalYearAgo__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelHCOneFiscalYearAgo__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) H.Credit año fiscal anterior</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelHCTwoFiscalYearsAgo__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelHCTwoFiscalYearsAgo__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) H.Credit hace dos años fiscales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelSCCurrentFiscalYear__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelSCCurrentFiscalYear__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) S.Credit año fiscal en curso</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelSCNextFiscalYear__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelSCNextFiscalYear__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) S.Credit próximo año fiscal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelSCOneFiscalYearAgo__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelSCOneFiscalYearAgo__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) S.Credit año fiscal anterior</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelSCTwoFiscalYearsAgo__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelSCTwoFiscalYearsAgo__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) S.Credit hace dos años fiscales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_PercomsSummary__c.field-meta.xml
<CustomField>
    <fullName>msf_PercomsSummary__c</fullName>
    <label>Resumen percoms</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_PotentialAccordingOfficer__c.field-meta.xml
<CustomField>
    <fullName>msf_PotentialAccordingOfficer__c</fullName>
    <inlineHelpText>Implica cambio de level o programa.</inlineHelpText>
    <label>Potencial según 121 Officer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>121</fullName>
            </value>
            <value>
                <fullName>12Few</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_RecalculateLevel__c.field-meta.xml
<CustomField>
    <fullName>msf_RecalculateLevel__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Recalcular level</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_RelationshipLevel__c.field-meta.xml
<CustomField>
    <fullName>msf_RelationshipLevel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level de relación</label>
    <referenceTo>npsp__Level__c</referenceTo>
    <relationshipLabel>Contactos (Level de relación)</relationshipLabel>
    <relationshipName>Contactos2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_RelationshipMajorDonorsProgram__c.field-meta.xml
<CustomField>
    <fullName>msf_RelationshipMajorDonorsProgram__c</fullName>
    <label>Nivel relación programa Major Donors</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mantenimiento</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Sin Mantenimiento</fullName>
            </value>
            <value>
                <fullName>IS Sin Mantenimiento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_RelationshipMidDonorsProgram__c.field-meta.xml
<CustomField>
    <fullName>msf_RelationshipMidDonorsProgram__c</fullName>
    <label>Nivel relación programa Mid Donors</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mantenimiento</fullName>
            </value>
            <value>
                <fullName>Upgrade cuota</fullName>
            </value>
            <value>
                <fullName>Upgrade donación</fullName>
            </value>
            <value>
                <fullName>Sin mantenimiento</fullName>
            </value>
            <value>
                <fullName>IS Sin Mantenimiento</fullName>
            </value>
            <value>
                <fullName>Alto desarrollo</fullName>
            </value>
            <value>
                <fullName>Recuperación baja</fullName>
            </value>
            <value>
                <fullName>Recuperación donante</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MSF_LevelFieldsChanges_TDTM.cls
/**
* @author       Deloitte
* @date         01-2019
* @group        Contact
* @description  Calculation of member level.
*/
global without sharing class MSF_LevelFieldsChanges_TDTM extends npsp.TDTM_Runnable {
    
    /*******************************************************************************************************
    * @description  Trigger Handler on Contact that handles the changes in the fields involved in the 
    *               calculation of levels
    * @param        listNew the list of Contacts from trigger new. 
    * @param        listOld the list of Contacts from trigger old. 
    * @param        triggerAction which trigger event (BeforeInsert, AfterInsert, etc.). 
    * @param        objResult the describe for Contacts.
    * @return       dmlWrapper. 
    ********************************************************************************************************/
    global override npsp.TDTM_Runnable.DmlWrapper run(List<SObject> newlist, List<SObject> oldlist, npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult){
        //Attributes
        List<Contact> lNewCon = (List<Contact>) newlist;
        List<Contact> lOldCon = (List<Contact>) oldlist;
        Map<Id, Contact> mOldCon = new Map<Id, Contact>();
        if(lOldCon != null){            
            mOldCon.putAll(lOldCon);
        }
        
        if(triggerAction == npsp.TDTM_Runnable.Action.BeforeUpdate) {            
            for(Contact c : lNewCon){
                if(!c.msf_RecalculateLevel__c){
                	c.msf_RecalculateLevel__c = recalculateLevel(c, mOldCon.get(c.Id));     
                } 
                setLevelDates(c, mOldCon.get(c.Id));
            }
        }
        
        return null;        
    }
    
    
    //PRIVATE METHODS
    
    /*******************************************************************************************************
    * @description  The helper method for Trigger Handler that compare if there is a difference in certain 
    * 				fields between two contacts and set a flag if have some difference.
    * @param        newC is the new Contact to be saved.
    * @param        oldC is the old Contact to compare.
    ********************************************************************************************************/ 
    private boolean recalculateLevel(Contact newC, Contact oldC){
        boolean bRecalculate = false;
        if(newC.msf_Forced__c != oldC.msf_Forced__c ||
           newC.msf_PotentialAccordingOfficer__c != oldC.msf_PotentialAccordingOfficer__c ||
           newC.msf_IsStrategic__c != oldC.msf_IsStrategic__c ||
           newC.msf_ContactInformationSummary__c != oldC.msf_ContactInformationSummary__c ||
           newC.msf_PercomsSummary__c != oldC.msf_PercomsSummary__c ||
           newC.msf_RelationshipMidDonorsProgram__c != oldC.msf_RelationshipMidDonorsProgram__c ||
           newC.msf_RelationshipMajorDonorsProgram__c != oldC.msf_RelationshipMajorDonorsProgram__c ||
           newC.msf_IsAssosiative__c != oldC.msf_IsAssosiative__c ||
           newC.msf_IsPublicPerson__c != oldC.msf_IsPublicPerson__c ||
           newC.msf_IsInfluencer__c != oldC.msf_IsInfluencer__c ||
           newC.msf_BigDonorContact__c != oldC.msf_BigDonorContact__c ||
           // Economic level fields
           newC.msf_LevelHCLifetime__c != oldC.msf_LevelHCLifetime__c ||
           newC.msf_LevelHCLifetimeVD__c != oldC.msf_LevelHCLifetimeVD__c ||                    
           newC.msf_LevelHCNextFiscalYear__c != oldC.msf_LevelHCNextFiscalYear__c ||
           newC.msf_LevelSCNextFiscalYear__c != oldC.msf_LevelSCNextFiscalYear__c ||
           newC.msf_LevelHCCurrentFiscalYear__c != oldC.msf_LevelHCCurrentFiscalYear__c ||
           newC.msf_LevelSCCurrentFiscalYear__c != oldC.msf_LevelSCCurrentFiscalYear__c ||
           newC.msf_LevelHCOneFiscalYearAgo__c != oldC.msf_LevelHCOneFiscalYearAgo__c ||
           newC.msf_LevelSCOneFiscalYearAgo__c != oldC.msf_LevelSCOneFiscalYearAgo__c ||
           newC.msf_LevelHCTwoFiscalYearsAgo__c != oldC.msf_LevelHCTwoFiscalYearsAgo__c ||  
           newC.msf_LevelSCTwoFiscalYearsAgo__c != oldC.msf_LevelSCTwoFiscalYearsAgo__c
          )
        {
            bRecalculate = true;    
        } 
        
        return bRecalculate;
    }  
    
    /*******************************************************************************************************
    * @description  The helper method for Trigger Handler that compare if there is a difference in levels fields 
    *               between two contacts and set a date of change.
    * @param        c is the new Contact to be saved.
    * @param        cOld is the old Contact to compare.
    ********************************************************************************************************/ 
    private void setLevelDates (Contact c, Contact cOld){
        if(c.msf_Level__c != cOld.msf_Level__c){
            c.msf_FechaCambioLevelEconomico__c = date.today();
        }
        if(c.msf_RelationshipLevel__c != cOld.msf_RelationshipLevel__c){
            c.msf_FechaCambioLevelRelacion__c = date.today();
        }
    }
}