force-app/main/default/objects/Contact/fields/msf_BeginDateMSF__c.field-meta.xml
<CustomField>
    <fullName>msf_BeginDateMSF__c</fullName>
    <description>This field is to register the first time in MSF</description>
    <label>Fecha alta MSF</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_CRMExternalId__c.field-meta.xml
<CustomField>
    <fullName>msf_CRMExternalId__c</fullName>
    <description>WebSAS Member ID</description>
    <displayFormat>{0}</displayFormat>
    <externalId>true</externalId>
    <label>ID Miembro</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LastModificationChannel__c.field-meta.xml
<CustomField>
    <fullName>msf_LastModificationChannel__c</fullName>
    <label>Último canal de modificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_ModificationChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_LeadSourceMasterData__c/msf_LeadSourceMasterData__c.object-meta.xml
<CustomObject>
    <label>Maestro de datos de LeadSource</label>
    <nameField>
        <displayFormat>MD_LS_{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maestro de datos de LeadSource</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_LeadSourceMasterData__c/fields/msf_LeadSource3__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource3__c</fullName>
    <label>Canal de entrada 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource3</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/MSF_LeadSource3.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Correo postal</fullName>
    </customValue>
    <customValue>
        <fullName>Entidad financiera</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Personal</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono</fullName>
    </customValue>
    <customValue>
        <fullName>Otro</fullName>
    </customValue>
    <description>LeadSource Master Data</description>
    <masterLabel>LeadSource3</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MSF_ModificationChannel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Teléfonos At. Socio</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Asociativo</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono One-to-One</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Telemarketing</fullName>
    </customValue>
    <customValue>
        <fullName>Centro de Preferencias</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud Page</fullName>
    </customValue>
    <customValue>
        <fullName>Correo Postal</fullName>
    </customValue>
    <customValue>
        <fullName>E-mail Asociativo</fullName>
    </customValue>
    <customValue>
        <fullName>E-mails At. Socio</fullName>
    </customValue>
    <customValue>
        <fullName>E-mails One-to-One</fullName>
    </customValue>
    <customValue>
        <fullName>F2F</fullName>
        <label>F2F Tablet</label>
    </customValue>
    <customValue>
        <fullName>Fax</fullName>
    </customValue>
    <customValue>
        <fullName>Fichero Bancario</fullName>
    </customValue>
    <customValue>
        <fullName>Single entry file</fullName>
        <label>Fichero de importación</label>
    </customValue>
    <customValue>
        <fullName>Formularios Web</fullName>
    </customValue>
    <customValue>
        <fullName>Generación Aplicación</fullName>
    </customValue>
    <customValue>
        <fullName>Mensajería Instantánea</fullName>
    </customValue>
    <customValue>
        <fullName>Mi Perfil</fullName>
    </customValue>
    <customValue>
        <fullName>n/a</fullName>
    </customValue>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>Nuevo</label>
    </customValue>
    <customValue>
        <fullName>Presencial</fullName>
    </customValue>
    <customValue>
        <fullName>RRHH</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
        <isActive>false</isActive>
        <label>Email</label>
    </customValue>
    <customValue>
        <fullName>Teléfono SAS</fullName>
        <isActive>false</isActive>
        <label>Teléfono SAS</label>
    </customValue>
    <masterLabel>Canal de modificación</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MSF_SharedMethods_TEST.cls
/**
* @author       Deloitte
* @date         03-2019
* @group        SObjects
* @description  test class for the MSF_SharedMethods_UTIL class.
*/
@isTest
private class MSF_SharedMethods_TEST {
    @testSetup static void setup(){
        msf_LeadSourceMasterData__c data = new msf_LeadSourceMasterData__c(msf_LeadSource1__c = leadSource1Desc()[0],
                                                                           msf_LeadSource2__c = leadSource2Desc()[0], 
                                                                           msf_LeadSource3__c = leadSource3Desc()[0]);
        insert data;   
        
        Contact c = new Contact(LastName='Testin', msf_BeginDateMSF__c=date.today());
        insert c; 
    }
        
    @isTest static void testCreateLog() {
        Contact con = [SELECT Id, FirstName, LastName, Suffix, msf_LastModificationChannel__c, msf_CRMExternalId__c FROM Contact WHERE LastName = 'Testin' LIMIT 1];
        MSF_SharedMethods_UTIL shared = new MSF_SharedMethods_UTIL();
        Set<String> sfields = new Set<String>{'FirstName','LastName'};
        Map<String,Schema.sObjectField> mObjectFields = Contact.sObjectType.getDescribe().fields.getMap();
        shared.createLog(con, null, UserInfo.getUserId(), con.Id, null, true, false, sfields, mObjectFields); 
        shared.createLog(con, null, UserInfo.getUserId(), con.Id, null, false, true, sfields, mObjectFields);
        
        Contact con2 = con; 
        con2.FirstName = 'Test';
        upsert con2; 
        
        shared.createLog(con2, con , UserInfo.getUserId(), con.Id, null, false, false, sfields, mObjectFields); 
    }
    
    @isTest static void testGetLeadSourceDependence(){
        MSF_SharedMethods_UTIL shared = new MSF_SharedMethods_UTIL();
        Map<String,String> stringReturned = shared.getLeadSourceDependence(leadSource1Desc()[0]);
        System.assertEquals(leadSource2Desc()[0],stringReturned.get('LS2'), 'Dependence not found');
        System.assertEquals(leadSource3Desc()[0],stringReturned.get('LS3'), 'Dependence not found');
    }
    
    @isTest static void testGetLeadSourceDependencies(){
        MSF_SharedMethods_UTIL shared = new MSF_SharedMethods_UTIL();
        Map<String,msf_LeadSourceMasterData__c> mapReturned = shared.getLeadSourceDependencies();
        msf_LeadSourceMasterData__c leadSource = mapReturned.get(leadSource1Desc()[0]);
        msf_LeadSourceMasterData__c leadSourceExpected = [SELECT msf_LeadSource1__c,
                                                          msf_LeadSource2__c, 
                                                          msf_LeadSource3__c 
                                                          FROM msf_LeadSourceMasterData__c
                                                          WHERE msf_LeadSource1__c = :leadSource1Desc()[0] LIMIT 1];
        System.assertEquals(leadSourceExpected, leadSource);
        
    }
    
    private static List<String> leadSource1Desc(){
        Schema.DescribeFieldResult fieldResult = msf_LeadSourceMasterData__c.msf_LeadSource1__c.getDescribe(); 
        List<Schema.PicklistEntry> pickListValues = fieldResult.getPicklistValues();
        
        List<String> options = new List<String>();
        
        for(Schema.PicklistEntry p : pickListValues){
            options.add(p.getLabel());
        }
        return options;
    }
    
    private static List<String> leadSource2Desc(){
        Schema.DescribeFieldResult fieldResult = msf_LeadSourceMasterData__c.msf_LeadSource2__c.getDescribe(); 
        List<Schema.PicklistEntry> pickListValues = fieldResult.getPicklistValues();
        
        List<String> options = new List<String>();
        
        for(Schema.PicklistEntry p : pickListValues){
            options.add(p.getLabel());
        }
        return options;
    }
    
    private static List<String> leadSource3Desc(){
        Schema.DescribeFieldResult fieldResult = msf_LeadSourceMasterData__c.msf_LeadSource3__c.getDescribe(); 
        List<Schema.PicklistEntry> pickListValues = fieldResult.getPicklistValues();
        
        List<String> options = new List<String>();
        
        for(Schema.PicklistEntry p : pickListValues){
            options.add(p.getLabel());
        }
        return options;
    }
}