force-app/main/default/objects/Contact/fields/msf_IsAssosiative__c.field-meta.xml
<CustomField>
    <fullName>msf_IsAssosiative__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es asociado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Individual_Contact.recordType-meta.xml
<RecordType>
    <fullName>Individual_Contact</fullName>
    <active>true</active>
    <label>Individual Contact</label>
</RecordType>

force-app/main/default/objects/Lead/fields/msf_IsAssosiative__c.field-meta.xml
<CustomField>
    <fullName>msf_IsAssosiative__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es de asociativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_isSanitary__c.field-meta.xml
<CustomField>
    <fullName>msf_isSanitary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Personal sanitario</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_StaffType__c.field-meta.xml
<CustomField>
    <fullName>msf_StaffType__c</fullName>
    <label>Tipo de personal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internacional</fullName>
            </value>
            <value>
                <fullName>Sede o delegaciones</fullName>
            </value>
            <value>
                <fullName>Nacional</fullName>
            </value>
            <value>
                <fullName>Otros MSF</fullName>
            </value>
            <value>
                <fullName>Voluntario</fullName>
                <isActive>false</isActive>
                <label>Voluntario</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Associative.recordType-meta.xml
<RecordType>
    <fullName>Associative</fullName>
    <active>true</active>
    <businessProcess>Associative Lead</businessProcess>
    <label>Associative</label>
</RecordType>

force-app/main/default/objects/msf_Associative__c/msf_Associative__c.object-meta.xml
<CustomObject>
    <label>Asociativo</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Número asociado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asociativos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_Associative__c/fields/msf_ContactId__c.field-meta.xml
<CustomField>
    <fullName>msf_ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre del contacto</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Asociativos</relationshipLabel>
    <relationshipName>Asociativos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_FieldExperienceSAP__c.field-meta.xml
<CustomField>
    <fullName>msf_FieldExperienceSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Experiencia en el terreno con OCBA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_IsFieldSAP__c.field-meta.xml
<CustomField>
    <fullName>msf_IsFieldSAP__c</fullName>
    <formula>BEGINS(msf_JobSAP__c , &apos;F -&apos;) 
||
BEGINS(msf_CostCenterSAP__c , &apos;ES&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actualmente en terreno</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_IsSanitary__c.field-meta.xml
<CustomField>
    <fullName>msf_IsSanitary__c</fullName>
    <formula>ISPICKVAL(msf_ProfessionAreas__c, &apos;Ciencias de la Salud y Servicios Sociales&apos;) &amp;&amp;
(
  ISPICKVAL(msf_ProfessionSubAreas__c, &apos;Medicina&apos;) ||
  ISPICKVAL(msf_ProfessionSubAreas__c, &apos;Farmacia&apos;) ||
  ISPICKVAL(msf_ProfessionSubAreas__c, &apos;Psicología&apos;) ||
  ISPICKVAL(msf_ProfessionSubAreas__c, &apos;Enfermería&apos;) ||
  ISPICKVAL(msf_ProfessionSubAreas__c, &apos;Matronas&apos;) ||
  ISPICKVAL(msf_ProfessionSubAreas__c, &apos;Odontología&apos;) ||
  ISPICKVAL(msf_ProfessionSubAreas__c, &apos;Fisioterapia&apos;) ||
  ISPICKVAL(msf_ProfessionSubAreas__c, &apos;Nutrición&apos;) ||
  ISPICKVAL(msf_ProfessionSubAreas__c, &apos;Técnicos Superiores en Laboratorio de diagnóstico Clínico&apos;)    
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Es sanitario</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_MemberMeetingStartDate__c.field-meta.xml
<CustomField>
    <fullName>msf_MemberMeetingStartDate__c</fullName>
    <label>Fecha inicio miembro en junta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_SalariedSAP__c.field-meta.xml
<CustomField>
    <fullName>msf_SalariedSAP__c</fullName>
    <formula>!ISBLANK(msf_CostCenterSAP__c) &amp;&amp; !BEGINS(msf_CostCenterSAP__c , &apos;ES&apos;) &amp;&amp; !BEGINS(msf_CostCenterSAP__c , &apos;90&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asalariado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_StaffType__c.field-meta.xml
<CustomField>
    <fullName>msf_StaffType__c</fullName>
    <label>Tipo de personal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internacional</fullName>
            </value>
            <value>
                <fullName>Sede o delegaciones</fullName>
            </value>
            <value>
                <fullName>Nacional</fullName>
            </value>
            <value>
                <fullName>Otros MSF</fullName>
            </value>
            <value>
                <fullName>Voluntario</fullName>
                <isActive>false</isActive>
                <label>Voluntario</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_Endorsement__c/msf_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Aval</label>
    <nameField>
        <displayFormat>AV-{000000}</displayFormat>
        <label>Código aval</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_Endorsement__c/fields/msf_isEndorsing__c.field-meta.xml
<CustomField>
    <fullName>msf_isEndorsing__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Aval</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Aval de</relationshipLabel>
    <relationshipName>Avales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MSF_SummarySectionAssociative_CTRL.cls
/**
* @author       Deloitte
* @date         12-2018
* @group        Associative.
* @description  Controller for the lightning component MSF_SummarySectionAssociative
*/
public without sharing class MSF_SummarySectionAssociative_CTRL {
   	
    @AuraEnabled
    public static Object getObjectType(ID objectId){
        
        Map<String,Object> outputMap = new Map<String,Object>();   
        
        if(Schema.Contact.SObjectType == objectId.getSobjectType()){
        	outputMap.put('isContact',true);    
        }
        else if (Schema.Lead.SObjectType == objectId.getSobjectType()){
        	outputMap.put('isContact',false);    
        }
        
        return outputMap;     
    }    
    
    @AuraEnabled
    public static Object getContactInformation(ID contactId){
        
        Map<String,Object> outputMap = new Map<String,Object>();        
		
        List<Contact> c = new List<Contact>();
        
        c = [SELECT Id, msf_IsAssosiative__c,
             (SELECT Id FROM Avales__r)
             FROM Contact 
             WHERE RecordType.DeveloperName = 'Individual_Contact'
             AND Id =: contactId
             LIMIT 1
            ];
 
        if(!c.IsEmpty()){
            outputMap.put('contact',c[0]);
            outputMap.put('numEndorsements',c[0].Avales__r.size()); 
        }else{
        	outputMap.put('contact',new Contact());
            outputMap.put('numEndorsements',0);     
        }
        
        return outputMap;        
    }
    
    @AuraEnabled
    public static Object getAssociativeInformation(ID contactId){
        
        Map<String,Object> outputMap = new Map<String,Object>();        
		
        List<msf_Associative__c> asso = new List<msf_Associative__c>();
        
        asso = [SELECT Id, msf_IsSanitary__c, msf_FieldExperienceSAP__c, msf_MemberMeetingStartDate__c, msf_IsFieldSAP__c, msf_SalariedSAP__c, msf_StaffType__c
                FROM msf_Associative__c 
                WHERE msf_ContactId__c =: contactId
                ORDER BY CreatedDate DESC
                LIMIT 1
               ];
        
        if(!asso.isEmpty()){
        	outputMap.put('associative',asso[0]);     
        }else{
            outputMap.put('associative',null);    
        }             
        
        return outputMap;        
    }
    
    @AuraEnabled
    public static Object getLeadInformation(ID leadId){
        
        Map<String,Object> outputMap = new Map<String,Object>();        
		
        Lead ld = new Lead();
        
        ld = [SELECT Id, Name, msf_isSanitary__c, msf_StaffType__c, RecordType.DeveloperName
              FROM Lead 
              WHERE Id =: leadId
              LIMIT 1
             ];
        
        outputMap.put('ld',ld);      
        
        return outputMap;        
    }
}