force-app/main/default/objects/Contact/fields/msf_EntryCampaign__c.field-meta.xml
<CustomField>
    <fullName>msf_EntryCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaña de entrada inicial</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Contactos (Campaña de entrada)</relationshipLabel>
    <relationshipName>Contactos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <description>Indicates if this Contact is designated as the Primary Contact on their Account (read only).</description>
    <formula>Account.npe01__One2OneContact__c = Id</formula>
    <inlineHelpText>Este campo esta seleccionado si es el contacto principal en la cuenta. El contacto principal puede editarse en la cuenta.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_EntryCampaign__c.field-meta.xml
<CustomField>
    <fullName>msf_EntryCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaña de entrada inicial</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_LeadId__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidato</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Contact for this Opportunity. If this is an individual Donation, NPSP attributes the Donation to the Primary Contact. If this is an organizational Donation, NPSP attributes a soft credit to the Primary Contact.</description>
    <inlineHelpText>El contacto principal para esta oportunidad. La función del contacto principal se mantiene sincronizada con este campo. Para donantes individuales, esto significa atribuciones por esta oportunidad.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Donation.recordType-meta.xml
<RecordType>
    <fullName>Donation</fullName>
    <active>true</active>
    <businessProcess>Donation</businessProcess>
    <description>Donation Received</description>
    <label>Donation</label>
</RecordType>

force-app/main/default/classes/ConvertLeadToContactTest.cls
/**
 * @description       : 
 * @author            : sheredia@omegacrmconsulting.com
 * @group             : 
 * @last modified on  : 02-23-2022
 * @last modified by  : sheredia@omegacrmconsulting.com
**/
@istest
public with sharing class ConvertLeadToContactTest {
   
    @TestSetup
    static void makeData(){
        Lead lead = new Lead(LastName = 'Lead Test', Company = 'Company Test', msf_EntryCampaign__c = (new Campaign(Name = 'Campaña Test')).Id ) ;
        insert lead;
        
        Contact con = new Contact(LastName = 'Contact Test');
        insert con;

        Opportunity opp = new Opportunity(Name = 'Opportunity Test', 
            RecordTypeId = [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND Name = 'Donation'].Id,
            msf_LeadId__c = lead.Id,
            StageName = 'Propuesta',
            CloseDate = System.today() + 7,
            npsp__Primary_Contact__c = null
            );

        insert opp;
    }
    
    @istest static void testConvertLeadAfterConvert(){
        Database.LeadConvert convertData = new database.LeadConvert();
        convertData.setLeadId([SELECT ID FROM Lead WHERE LastName = 'Lead Test'].Id);

        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted = true LIMIT 1];
        convertData.setConvertedStatus(convertStatus.MasterLabel);

        Database.LeadConvertResult convertDataResult = Database.convertLead(convertData);
        
        Test.startTest();
        ConvertLeadToContact.afterConvert(convertDataResult, NULL);
        Test.stopTest();
        
        Opportunity opp = [SELECT ID, npsp__Primary_Contact__c, msf_LeadId__c FROM Opportunity WHERE NAME = 'Opportunity Test' LIMIT 1];

        System.assert( convertDataResult.getContactId() != null, 'Debe crearse un contact a partir de un lead');
        System.assert( opp.npsp__Primary_Contact__c == convertDataResult.getContactId(), 'La opportunidad debe de asociarse al contacto, pero no se ha hecho');
        System.assert( opp.msf_LeadId__c == null, 'La opportunidad no debe estar al lead, pero lo está');

    }
    
}