force-app/main/default/objects/Contact/fields/msf_ContactInformationSummary__c.field-meta.xml
<CustomField>
    <fullName>msf_ContactInformationSummary__c</fullName>
    <label>Resumen de los datos de contacto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_Forced__c.field-meta.xml
<CustomField>
    <fullName>msf_Forced__c</fullName>
    <inlineHelpText>Implica cambio de level o programa.</inlineHelpText>
    <label>Level de relación o programa forzado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>121</fullName>
            </value>
            <value>
                <fullName>12Few</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_IsAssosiative__c.field-meta.xml
<CustomField>
    <fullName>msf_IsAssosiative__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es asociado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_IsPublicPerson__c.field-meta.xml
<CustomField>
    <fullName>msf_IsPublicPerson__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Implica exclusión programa de prospectos.</inlineHelpText>
    <label>Es persona pública</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_IsStrategic__c.field-meta.xml
<CustomField>
    <fullName>msf_IsStrategic__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Implica cambio de level o programa.</inlineHelpText>
    <label>Es estratégico</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelHCCurrentFiscalYear__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelHCCurrentFiscalYear__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) H.Credit año fiscal en curso</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelHCLifetime__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelHCLifetime__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) H.Credit Lifetime</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelHCLifetimeVD__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelHCLifetimeVD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) H.Credit Lifetime VD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelHCNextFiscalYear__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelHCNextFiscalYear__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) H.Credit próximo año fiscal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelHCOneFiscalYearAgo__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelHCOneFiscalYearAgo__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) H.Credit año fiscal anterior</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelHCTwoFiscalYearsAgo__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelHCTwoFiscalYearsAgo__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) H.Credit hace dos años fiscales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelSCCurrentFiscalYear__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelSCCurrentFiscalYear__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) S.Credit año fiscal en curso</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelSCNextFiscalYear__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelSCNextFiscalYear__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) S.Credit próximo año fiscal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelSCOneFiscalYearAgo__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelSCOneFiscalYearAgo__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) S.Credit año fiscal anterior</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelSCTwoFiscalYearsAgo__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelSCTwoFiscalYearsAgo__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) S.Credit hace dos años fiscales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_PercomsSummary__c.field-meta.xml
<CustomField>
    <fullName>msf_PercomsSummary__c</fullName>
    <label>Resumen percoms</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_PotentialAccordingOfficer__c.field-meta.xml
<CustomField>
    <fullName>msf_PotentialAccordingOfficer__c</fullName>
    <inlineHelpText>Implica cambio de level o programa.</inlineHelpText>
    <label>Potencial según 121 Officer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>121</fullName>
            </value>
            <value>
                <fullName>12Few</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_RecalculateLevel__c.field-meta.xml
<CustomField>
    <fullName>msf_RecalculateLevel__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Recalcular level</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_RelationshipMajorDonorsProgram__c.field-meta.xml
<CustomField>
    <fullName>msf_RelationshipMajorDonorsProgram__c</fullName>
    <label>Nivel relación programa Major Donors</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mantenimiento</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Sin Mantenimiento</fullName>
            </value>
            <value>
                <fullName>IS Sin Mantenimiento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_RelationshipMidDonorsProgram__c.field-meta.xml
<CustomField>
    <fullName>msf_RelationshipMidDonorsProgram__c</fullName>
    <label>Nivel relación programa Mid Donors</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mantenimiento</fullName>
            </value>
            <value>
                <fullName>Upgrade cuota</fullName>
            </value>
            <value>
                <fullName>Upgrade donación</fullName>
            </value>
            <value>
                <fullName>Sin mantenimiento</fullName>
            </value>
            <value>
                <fullName>IS Sin Mantenimiento</fullName>
            </value>
            <value>
                <fullName>Alto desarrollo</fullName>
            </value>
            <value>
                <fullName>Recuperación baja</fullName>
            </value>
            <value>
                <fullName>Recuperación donante</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Level__c/npsp__Level__c.object-meta.xml
<CustomObject>
    <description>Tracks the definition of levels, for any object.</description>
    <label>Level</label>
    <nameField>
        <label>Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Level__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Level is currently in use.</description>
    <inlineHelpText>Si este nivel esta en uso actualmente.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Level__c/fields/npsp__Level_Field__c.field-meta.xml
<CustomField>
    <fullName>npsp__Level_Field__c</fullName>
    <description>Indicates which field to use on the target object to store the current Level.</description>
    <inlineHelpText>El campo (nombre de la Api) en el objecto destino donde se guarda la búsqueda al nivel actual. Tenga en cuenta que este campo implícitamente define la &quot;escalera&quot; de la que este nivel es parte.</inlineHelpText>
    <label>Level Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Level__c/fields/npsp__Target__c.field-meta.xml
<CustomField>
    <fullName>npsp__Target__c</fullName>
    <description>The object that this Level applies to.</description>
    <inlineHelpText>El objeto al que se le aplica este nivel.</inlineHelpText>
    <label>Target</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MSF_LevelFieldsChanges_TEST.cls
/**
* @author       Deloitte
* @date         01-2019
* @group        Contact
* @description  test class for the MSF_LevelFieldsChanges_TDTM class.
*/
@isTest
public class MSF_LevelFieldsChanges_TEST {
    
    @testSetup static void setup(){
        //Create Trigger
        npsp__Trigger_Handler__c thCon = new npsp__Trigger_Handler__c(
            Name = 'TriggerTestLevelFieldChanges',
            npsp__Class__c = 'MSF_LevelFieldsChanges_TDTM',
            npsp__Object__c = 'Contact',
            npsp__Trigger_Action__c = 'BeforeUpdate',
            npsp__Active__c = true,
            npsp__Load_Order__c = 3,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );        
        upsert thCon; 
        //Initialize values
        List<Contact> listContactTest = new List<Contact>();
        Contact cont = new Contact(LastName = 'MSF_LevelFIelds_Changes_Test_LastName1');
        cont.msf_Forced__c = '121'; 
        cont.msf_PotentialAccordingOfficer__c = '121'; 
        cont.msf_IsStrategic__c = false; 
        cont.msf_ContactInformationSummary__c = 'ResumenDatos'; 
        cont.msf_PercomsSummary__c = 'ResumenDatos'; 
        cont.msf_RelationshipMidDonorsProgram__c = cont.msf_RelationshipMajorDonorsProgram__c = 'Mantenimiento'; 
        cont.msf_IsAssosiative__c = cont.msf_IsPublicPerson__c  = false;
        cont.msf_LevelHCLifetime__c = cont.msf_LevelHCLifetimeVD__c  = 0.01; 
        cont.msf_LevelHCNextFiscalYear__c = 0.01; 
        cont.msf_LevelHCCurrentFiscalYear__c = 0.01; 
        cont.msf_LevelHCOneFiscalYearAgo__c = 0.01;
        cont.msf_LevelHCTwoFiscalYearsAgo__c = 0.01; 
        cont.msf_LevelSCNextFiscalYear__c = 0.01; 
        cont.msf_LevelsCCurrentFiscalYear__c = 0.01; 
        cont.msf_LevelSCOneFiscalYearAgo__c = 0.01;
        cont.msf_LevelsCTwoFiscalYearsAgo__c = 0.01; 
        cont.msf_RecalculateLevel__c = false;
        listContactTest.add(cont);
        insert listContactTest;
        List<npsp__Level__c> listLevel = new List<npsp__Level__c>();
        listLevel.add(new npsp__Level__c(
        	Name='MSF_LevelFieldsChanges_TEST_Contact_Level_Name',
            npsp__Target__c	= 'Contact',
            npsp__Level_Field__c='MSF_LevelFieldsChanges_TEST_Contact_Level_Field',
            npsp__Source_Field__c='MSF_LevelFieldsChanges_TEST_Contact_Level_Source_Field'
        ));
        insert listLevel;
    }
    
    @isTest static void test_no_change(){
        Contact cont = [SELECT Id, FirstName FROM Contact Where LastName = 'MSF_LevelFIelds_Changes_Test_LastName1' LIMIT 1];
        cont.FirstName = 'Hello';
        update cont;
        cont = [SELECT Id, FirstName, msf_RecalculateLevel__c FROM Contact Where LastName = 'MSF_LevelFIelds_Changes_Test_LastName1' LIMIT 1];
        System.assert(!cont.msf_RecalculateLevel__c);
    }
    
    @isTest static void test_msf_Forced_c(){
        Contact cont = [SELECT Id, msf_Forced__c,msf_RecalculateLevel__c FROM Contact Where LastName = 'MSF_LevelFIelds_Changes_Test_LastName1' LIMIT 1];
        cont.msf_Forced__c = '12Few';
        update cont;
        cont = [SELECT Id, msf_Forced__c,msf_RecalculateLevel__c FROM Contact Where LastName = 'MSF_LevelFIelds_Changes_Test_LastName1' LIMIT 1];
        System.assert(cont.msf_RecalculateLevel__c);
    }
    
    @isTest static void test_LevelChange(){
        Contact cont = [SELECT Id, FirstName FROM Contact Where LastName = 'MSF_LevelFIelds_Changes_Test_LastName1' LIMIT 1];
        cont.msf_Level__c = [SELECT Id FROM npsp__Level__c 
                             WHERE Name='MSF_LevelFieldsChanges_TEST_Contact_Level_Name' LIMIT 1].Id;
        cont.msf_RelationshipLevel__c = [SELECT Id FROM npsp__Level__c 
                                         WHERE Name='MSF_LevelFieldsChanges_TEST_Contact_Level_Name' LIMIT 1].Id;
        update cont;
        cont = [SELECT msf_FechaCambioLevelEconomico__c FROM Contact Where Id = :cont.Id LIMIT 1];
        System.assertEquals(date.today(), cont.msf_FechaCambioLevelEconomico__c);
    }
    
    @isTest static void test_msf_LevelHCTwoFiscalYearsAgo_c(){
        Contact cont = [SELECT Id, msf_LevelHCTwoFiscalYearsAgo__c,msf_RecalculateLevel__c FROM Contact Where LastName = 'MSF_LevelFIelds_Changes_Test_LastName1' LIMIT 1];
        cont.msf_LevelHCTwoFiscalYearsAgo__c = 0.02;
        update cont;
        cont = [SELECT Id, msf_LevelHCTwoFiscalYearsAgo__c,msf_RecalculateLevel__c FROM Contact Where LastName = 'MSF_LevelFIelds_Changes_Test_LastName1' LIMIT 1];
        System.assert(cont.msf_RecalculateLevel__c);
    }
}