force-app/main/default/objects/Contact/fields/msf_ContactDeleteReason__c.field-meta.xml
<CustomField>
    <fullName>msf_ContactDeleteReason__c</fullName>
    <label>Motivo fin de relación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ethical code</fullName>
                <label>Código ético</label>
            </value>
            <value>
                <fullName>Deceased</fullName>
                <label>Fallecido</label>
            </value>
            <value>
                <fullName>Tests</fullName>
                <label>Pruebas</label>
            </value>
            <value>
                <fullName>Complaints</fullName>
                <label>Quejas</label>
            </value>
            <value>
                <fullName>Country change</fullName>
                <label>Cambio de país</label>
            </value>
            <value>
                <fullName>Disolución</fullName>
            </value>
            <value>
                <fullName>Miembro eliminado</fullName>
            </value>
            <value>
                <fullName>By ethical code</fullName>
                <isActive>false</isActive>
                <label>By ethical code</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_Forced__c.field-meta.xml
<CustomField>
    <fullName>msf_Forced__c</fullName>
    <inlineHelpText>Implica cambio de level o programa.</inlineHelpText>
    <label>Level de relación o programa forzado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>121</fullName>
            </value>
            <value>
                <fullName>12Few</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_IsStrategic__c.field-meta.xml
<CustomField>
    <fullName>msf_IsStrategic__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Implica cambio de level o programa.</inlineHelpText>
    <label>Es estratégico</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_Level__c.field-meta.xml
<CustomField>
    <fullName>msf_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level económico</label>
    <referenceTo>npsp__Level__c</referenceTo>
    <relationshipLabel>Contactos</relationshipLabel>
    <relationshipName>Contactos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelAmountCurrentFiscalYear__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelAmountCurrentFiscalYear__c</fullName>
    <formula>msf_LevelHCCurrentFiscalYear__c + msf_LevelSCCurrentFiscalYear__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>(Level) Importe año fiscal en curso</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelAmountLifetime__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelAmountLifetime__c</fullName>
    <formula>msf_LevelHCLifetime__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>(Level) Importe lifetime</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelAmountNextFiscalYear__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelAmountNextFiscalYear__c</fullName>
    <formula>msf_LevelHCNextFiscalYear__c + msf_LevelSCNextFiscalYear__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>(Level) Importe próximo año fiscal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelAmountOneFiscalYearAgo__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelAmountOneFiscalYearAgo__c</fullName>
    <formula>msf_LevelHCOneFiscalYearAgo__c + msf_LevelSCOneFiscalYearAgo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>(Level) Importe año fiscal anterior</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelAmountTwoFiscalYearsAgo__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelAmountTwoFiscalYearsAgo__c</fullName>
    <formula>msf_LevelHCTwoFiscalYearsAgo__c + msf_LevelSCTwoFiscalYearsAgo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>(Level) Importe hace dos años fiscales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelHCLifetimeVD__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelHCLifetimeVD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>(Level) H.Credit Lifetime VD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelRelationshipScore__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelRelationshipScore__c</fullName>
    <description>Campo a partir del cual se calcula el nivel de relación: (10-None; 20-One to many; 30-One to few; 40-One to few+; 50-One to one )</description>
    <label>(Level) Relationship Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LevelScore__c.field-meta.xml
<CustomField>
    <fullName>msf_LevelScore__c</fullName>
    <description>Campo a partir del cual se calcula el level: (1-NADA; 40-MASS; 60-MID; 80-MID+; 100-BIG)</description>
    <label>(Level) Economic Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_OrganizationType__c.field-meta.xml
<CustomField>
    <fullName>msf_OrganizationType__c</fullName>
    <label>Tipo de organización</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Company</fullName>
                <default>true</default>
                <label>Company</label>
            </value>
            <value>
                <fullName>Public Entity</fullName>
            </value>
            <value>
                <fullName>Collective</fullName>
            </value>
            <value>
                <fullName>Foundation</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
                <isActive>false</isActive>
                <label>Anonymous</label>
            </value>
            <value>
                <fullName>Channel Partner / Reseller</fullName>
                <isActive>false</isActive>
                <label>Channel Partner / Reseller</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <isActive>false</isActive>
                <label>Corporate</label>
            </value>
            <value>
                <fullName>Customer - Channel</fullName>
                <isActive>false</isActive>
                <label>Customer - Channel</label>
            </value>
            <value>
                <fullName>Customer - Direct</fullName>
                <isActive>false</isActive>
                <label>Customer - Direct</label>
            </value>
            <value>
                <fullName>Government</fullName>
                <isActive>false</isActive>
                <label>Government</label>
            </value>
            <value>
                <fullName>Household</fullName>
                <isActive>false</isActive>
                <label>Household</label>
            </value>
            <value>
                <fullName>Individual</fullName>
                <isActive>false</isActive>
                <label>Individual</label>
            </value>
            <value>
                <fullName>Installation Partner</fullName>
                <isActive>false</isActive>
                <label>Installation Partner</label>
            </value>
            <value>
                <fullName>Nonprofit</fullName>
                <isActive>false</isActive>
                <label>Nonprofit</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
                <isActive>false</isActive>
                <label>Technology Partner</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_PotentialAccordingOfficer__c.field-meta.xml
<CustomField>
    <fullName>msf_PotentialAccordingOfficer__c</fullName>
    <inlineHelpText>Implica cambio de level o programa.</inlineHelpText>
    <label>Potencial según 121 Officer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>121</fullName>
            </value>
            <value>
                <fullName>12Few</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_Program__c.field-meta.xml
<CustomField>
    <fullName>msf_Program__c</fullName>
    <label>Programa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Retención 1r año MASS</fullName>
            </value>
            <value>
                <fullName>Cultivación socios MASS</fullName>
            </value>
            <value>
                <fullName>Cultivación/conversión Donantes MASS</fullName>
            </value>
            <value>
                <fullName>Reactivación bajas MASS</fullName>
            </value>
            <value>
                <fullName>Conversión prospectos</fullName>
            </value>
            <value>
                <fullName>Reactivación/conversión EXDonantes MASS</fullName>
            </value>
            <value>
                <fullName>Otros programas transversales</fullName>
            </value>
            <value>
                <fullName>Retención 1r año MID</fullName>
            </value>
            <value>
                <fullName>Cultivación socios MID</fullName>
            </value>
            <value>
                <fullName>Cultivación/conversión Donantes MID</fullName>
            </value>
            <value>
                <fullName>Reactivación/conversión EXDonantes MID</fullName>
            </value>
            <value>
                <fullName>Reactivación bajas MID</fullName>
            </value>
            <value>
                <fullName>Mid+ Donors</fullName>
            </value>
            <value>
                <fullName>Testamentarios</fullName>
            </value>
            <value>
                <fullName>Otros 12Few+</fullName>
            </value>
            <value>
                <fullName>Major Donors</fullName>
            </value>
            <value>
                <fullName>Potenciales a Major Donors</fullName>
            </value>
            <value>
                <fullName>Públicos Especiales</fullName>
            </value>
            <value>
                <fullName>Otros 121</fullName>
            </value>
            <value>
                <fullName>Vehículo donación de Gran Donante = YES</fullName>
            </value>
            <value>
                <fullName>Prospectos Empresas &amp; Colectivos Mass</fullName>
            </value>
            <value>
                <fullName>Prospectos Fundaciones Mass</fullName>
            </value>
            <value>
                <fullName>Fundaciones Mass</fullName>
            </value>
            <value>
                <fullName>Empresas y Colectivos Mass</fullName>
            </value>
            <value>
                <fullName>Instituciones Públicas Mass</fullName>
            </value>
            <value>
                <fullName>Fundaciones Mid, Mid +</fullName>
            </value>
            <value>
                <fullName>Empresas y Colectivos Mid, Mid +</fullName>
            </value>
            <value>
                <fullName>Instituciones Públicas Mid y Mid +</fullName>
            </value>
            <value>
                <fullName>Fundaciones Estratégicas</fullName>
            </value>
            <value>
                <fullName>Instituciones Públicas Estratégicas</fullName>
            </value>
            <value>
                <fullName>Empresas y Colectivos Estratégicas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_RecalculateLevel__c.field-meta.xml
<CustomField>
    <fullName>msf_RecalculateLevel__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Recalcular level</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_RelationshipLevel__c.field-meta.xml
<CustomField>
    <fullName>msf_RelationshipLevel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level de relación</label>
    <referenceTo>npsp__Level__c</referenceTo>
    <relationshipLabel>Contactos (Level de relación)</relationshipLabel>
    <relationshipName>Contactos2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/msf_AutomatedProcessErrors__c.object-meta.xml
<CustomObject>
    <label>Automated Process Error</label>
    <nameField>
        <displayFormat>ERROR_{YYYY}-{MM}-{DD}_{0000000000}</displayFormat>
        <label>Identificador de error</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automated Process Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>msf_ErrorMessage__c</fullName>
    <label>Mensaje de error</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_FieldsErrors__c.field-meta.xml
<CustomField>
    <fullName>msf_FieldsErrors__c</fullName>
    <label>Campos con errores</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_Process__c.field-meta.xml
<CustomField>
    <fullName>msf_Process__c</fullName>
    <label>Proceso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_RecordId__c.field-meta.xml
<CustomField>
    <fullName>msf_RecordId__c</fullName>
    <label>Id registro</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_StatusCode__c.field-meta.xml
<CustomField>
    <fullName>msf_StatusCode__c</fullName>
    <label>Código de error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MSF_LevelCalculation_04A_BATCH.cls
/**
* @author       Deloitte
* @date         01-2019
* @group        Contact
* @description  Calculation of member level for organizations.
*/
global without sharing class MSF_LevelCalculation_04A_BATCH implements Database.Batchable<sObject>{
    
    global final String query;  
    
    global MSF_LevelCalculation_04A_BATCH (){
        String queryStep = '';
        queryStep  = 'SELECT Id, msf_OrganizationType__c, msf_ContactDeleteReason__c, ';        
        queryStep += 'msf_LevelScore__c, msf_LevelRelationshipScore__c, msf_Program__c, ';																					// Level & Programs fields 
        queryStep += 'msf_Forced__c, msf_PotentialAccordingOfficer__c, msf_IsStrategic__c, ';																				// Estrategic fields
        queryStep += 'msf_LevelAmountNextFiscalYear__c, msf_LevelAmountCurrentFiscalYear__c, msf_LevelAmountOneFiscalYearAgo__c, msf_LevelAmountTwoFiscalYearsAgo__c, ';	// Amount fields
        queryStep += 'msf_LevelAmountLifetime__c, msf_LevelHCLifetimeVD__c ';																								// Amount lifetime fields
        queryStep += 'FROM Contact ';
        queryStep += 'WHERE RecordType.DeveloperName = \'Organization\' ';
        queryStep += 'AND (msf_RecalculateLevel__c = TRUE ';
        queryStep += 'OR msf_Level__c = null ';
        queryStep += 'OR msf_RelationshipLevel__c = null) ';
        query = queryStep; 
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Contact> scope){

        List<Contact> lConToUpdate = new List<Contact>();
        
        //Define level of member
        for(Contact c : scope){
            
            if(levelCondition(c,10000))
            {   
                c.msf_LevelScore__c = 100; //BIG
                c.msf_LevelRelationshipScore__c = setRelationshipLevel(c,50); //One to one               
            }
            else if(levelCondition(c,8000))
            {   
                c.msf_LevelScore__c = 80; //MID+
                c.msf_LevelRelationshipScore__c = setRelationshipLevel(c,30); //One to few
            }
            else if(levelCondition(c,1500))
            {   
                c.msf_LevelScore__c = 60; //MID
                c.msf_LevelRelationshipScore__c = setRelationshipLevel(c,30); //One to few     
            }
            else if(levelCondition(c,0) || c.msf_LevelAmountLifetime__c > 0)
            {                 
                c.msf_LevelScore__c = 40; //MASS
                c.msf_LevelRelationshipScore__c = setRelationshipLevel(c,20); //One to many
            }
            else if(c.msf_LevelAmountLifetime__c == 0 && c.msf_LevelHCLifetimeVD__c != null && c.msf_LevelHCLifetimeVD__c > 0) 
            {                 
                c.msf_LevelScore__c = 1; //NONE 
                c.msf_LevelRelationshipScore__c = setRelationshipLevel(c,10); //None
            }
            else if(c.msf_LevelAmountLifetime__c == 0)
            {       
                c.msf_LevelScore__c = 20; //PROSPECTOS
                c.msf_LevelRelationshipScore__c = setRelationshipLevel(c,20); //One to many
            }

            if(String.isNotBlank(c.msf_ContactDeleteReason__c)){
            	c.msf_LevelRelationshipScore__c = 10; //None    
            }            
            
            c.msf_Program__c = setOrganizationProgram(c);
            
            c.msf_RecalculateLevel__c = FALSE;
            
            lConToUpdate.add(c);                        
        }

        if(!lConToUpdate.isEmpty()){
            // DML statement
            Database.SaveResult[] srList = Database.update(lConToUpdate, false);
            
            //*
            List<msf_AutomatedProcessErrors__c> lAPE = new List<msf_AutomatedProcessErrors__c>(); 
            
            for (Database.SaveResult sr : srList) { // Iterate through each returned result
                if (!sr.isSuccess()) {  // Operation failed, so get all errors                                   
                    for(Database.Error err : sr.getErrors()) {
                        msf_AutomatedProcessErrors__c tempAPE = new msf_AutomatedProcessErrors__c(msf_Process__c = 'MSF_LevelCalculation_04A', msf_RecordId__c = scope.get(srList.indexOf(sr)).Id, msf_StatusCode__c = String.valueOf(err.getStatusCode()), msf_FieldsErrors__c = String.valueOf(err.getFields()), msf_ErrorMessage__c = String.valueOf(err.getMessage()).abbreviate(255));
                        lAPE.add(tempAPE);
                    }
                }            
            }  
            
            if(!lAPE.isEmpty()){
                insert lAPE;
            }//*/
        }
    }
    
    global void finish(Database.BatchableContext BC){
        System.debug('END BATCH - MSF_LevelCalculation_04A_BATCH');
    } 
    
    
    //PRIVATE METHODS
    
    private boolean levelCondition (Contact c, Integer iLimit){        
        
        if(iLimit == 0){
            return (c.msf_LevelAmountNextFiscalYear__c > iLimit || 
                    c.msf_LevelAmountCurrentFiscalYear__c > iLimit || 
                    c.msf_LevelAmountOneFiscalYearAgo__c > iLimit);              
        }
        
        return (c.msf_LevelAmountNextFiscalYear__c >= iLimit || 
                c.msf_LevelAmountCurrentFiscalYear__c >= iLimit || 
                c.msf_LevelAmountOneFiscalYearAgo__c >= iLimit);       
    }
    
    private Integer setRelationshipLevel (Contact c, Integer iDefault){
        
        if(c.msf_Forced__c == '121' || c.msf_PotentialAccordingOfficer__c == '121' || c.msf_IsStrategic__c){
            return 50; //One to one
        }
        
        return iDefault;
    }
          
    private String setOrganizationProgram (Contact c){
        
        String sProgram = '';    
         
        if(c.msf_LevelRelationshipScore__c == 50){
            if(c.msf_OrganizationType__c == 'Foundation'){
                sProgram = 'Fundaciones Estratégicas';    
            }else if(c.msf_OrganizationType__c == 'Public Entity'){
                sProgram = 'Instituciones Públicas Estratégicas';                    
            }else if(c.msf_OrganizationType__c == 'Company' || c.msf_OrganizationType__c == 'Collective'){
                sProgram = 'Empresas y Colectivos Estratégicas';    
            }              
        } 
        else if(c.msf_LevelRelationshipScore__c == 30){
            if(c.msf_OrganizationType__c == 'Foundation'){
                sProgram = 'Fundaciones Mid, Mid +';    
            }else if(c.msf_OrganizationType__c == 'Public Entity'){
                sProgram = 'Instituciones Públicas Mid y Mid +';      
            }else if(c.msf_OrganizationType__c == 'Company' || c.msf_OrganizationType__c == 'Collective'){
                sProgram = 'Empresas y Colectivos Mid, Mid +';    
            }          
        } 
        else if(c.msf_LevelRelationshipScore__c == 20){
            if(c.msf_OrganizationType__c == 'Foundation'){
                if(c.msf_LevelScore__c == 40){
                    sProgram = 'Fundaciones Mass';
                }else if(c.msf_LevelScore__c == 20){
                    sProgram = 'Prospectos Fundaciones Mass';    
                }                    
            }else if(c.msf_OrganizationType__c == 'Public Entity'){
                if(c.msf_LevelScore__c == 40){
                    sProgram = 'Instituciones Públicas Mass';
                }else if(c.msf_LevelScore__c == 20){
                    sProgram = null;  
                }       
            }else if(c.msf_OrganizationType__c == 'Company' || c.msf_OrganizationType__c == 'Collective'){
                if(c.msf_LevelScore__c == 40){
                    sProgram = 'Empresas y Colectivos Mass';
                }else if(c.msf_LevelScore__c == 20){
                    sProgram = 'Prospectos Empresas & Colectivos Mass';    
                }    
            }      
        } 
        else if(c.msf_LevelRelationshipScore__c == 10){
            sProgram = 'Vehículo donación de Gran Donante = YES';    
        }
        
        return sProgram;
    }    
}