force-app/main/default/objects/Contact/fields/msf_Canvasser__c.field-meta.xml
<CustomField>
    <fullName>msf_Canvasser__c</fullName>
    <label>Captado por</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_CityCanvasser__c.field-meta.xml
<CustomField>
    <fullName>msf_CityCanvasser__c</fullName>
    <label>Captado en</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_LanguagePreferer__c.field-meta.xml
<CustomField>
    <fullName>msf_LanguagePreferer__c</fullName>
    <inlineHelpText>Al modificar el idioma, asegura que está marcado el check en el campo ‘Idioma confirmado’, de lo contrario no se guardará correctamente.</inlineHelpText>
    <label>Idioma de preferencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ESP</fullName>
                <default>true</default>
                <label>ESP</label>
            </value>
            <value>
                <fullName>CAT</fullName>
            </value>
            <value>
                <fullName>GAL</fullName>
            </value>
            <value>
                <fullName>EUS</fullName>
            </value>
            <value>
                <fullName>ING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_NIF__c.field-meta.xml
<CustomField>
    <fullName>msf_NIF__c</fullName>
    <label>NIF/NIE/CIF</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_PlaceCanvasser__c.field-meta.xml
<CustomField>
    <fullName>msf_PlaceCanvasser__c</fullName>
    <label>Localización del captador</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/Lead/fields/msf_AccountHolderOption__c.field-meta.xml
<CustomField>
    <fullName>msf_AccountHolderOption__c</fullName>
    <label>Opción titular cuenta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_AuxFirstName__c.field-meta.xml
<CustomField>
    <fullName>msf_AuxFirstName__c</fullName>
    <label>Nombre (Tutor/Representante)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_AuxLastName__c.field-meta.xml
<CustomField>
    <fullName>msf_AuxLastName__c</fullName>
    <label>Apellido 1 (Tutor/Representante)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_AuxMobilePhone__c.field-meta.xml
<CustomField>
    <fullName>msf_AuxMobilePhone__c</fullName>
    <label>Teléfono móvil (Representante)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_AuxNIF__c.field-meta.xml
<CustomField>
    <fullName>msf_AuxNIF__c</fullName>
    <label>NIF/NIE (Tutor/Representante)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_AuxRole__c.field-meta.xml
<CustomField>
    <fullName>msf_AuxRole__c</fullName>
    <label>Rol (Representante)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_AuxSuffix__c.field-meta.xml
<CustomField>
    <fullName>msf_AuxSuffix__c</fullName>
    <label>Apellido 2 (Tutor/Representante)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_Birthdate__c.field-meta.xml
<CustomField>
    <fullName>msf_Birthdate__c</fullName>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_Canvasser__c.field-meta.xml
<CustomField>
    <fullName>msf_Canvasser__c</fullName>
    <label>Captado por</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_CanvasserCampaign__c.field-meta.xml
<CustomField>
    <fullName>msf_CanvasserCampaign__c</fullName>
    <label>Campaña captador</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_CityCanvasser__c.field-meta.xml
<CustomField>
    <fullName>msf_CityCanvasser__c</fullName>
    <label>Captado en</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_ContactDate__c.field-meta.xml
<CustomField>
    <fullName>msf_ContactDate__c</fullName>
    <label>Fecha a contactar</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_DoorNumber__c.field-meta.xml
<CustomField>
    <fullName>msf_DoorNumber__c</fullName>
    <label>Puerta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_esOrganizacion__c.field-meta.xml
<CustomField>
    <fullName>msf_esOrganizacion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es organización</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_FirmaDonante__c.field-meta.xml
<CustomField>
    <fullName>msf_FirmaDonante__c</fullName>
    <defaultValue>false</defaultValue>
    <label>msf_FirmaDonante</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_FirmaRepresentante__c.field-meta.xml
<CustomField>
    <fullName>msf_FirmaRepresentante__c</fullName>
    <defaultValue>false</defaultValue>
    <label>msf_FirmaRepresentante</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_FirmaTitular__c.field-meta.xml
<CustomField>
    <fullName>msf_FirmaTitular__c</fullName>
    <defaultValue>false</defaultValue>
    <label>msf_FirmaTitular</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_Floor__c.field-meta.xml
<CustomField>
    <fullName>msf_Floor__c</fullName>
    <label>Piso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_Gender__c.field-meta.xml
<CustomField>
    <fullName>msf_Gender__c</fullName>
    <label>Género</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_HolderFirstName__c.field-meta.xml
<CustomField>
    <fullName>msf_HolderFirstName__c</fullName>
    <label>Nombre (Titular)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_HolderLastName__c.field-meta.xml
<CustomField>
    <fullName>msf_HolderLastName__c</fullName>
    <label>Apellido 1 (Titular)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_HolderNIF__c.field-meta.xml
<CustomField>
    <fullName>msf_HolderNIF__c</fullName>
    <label>NIF/NIE (Titular)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_HolderSuffixName__c.field-meta.xml
<CustomField>
    <fullName>msf_HolderSuffixName__c</fullName>
    <label>Apellido 2 (Titular)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANAccountNumber__c</fullName>
    <label>Número de cuenta</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANCode__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANCode__c</fullName>
    <label>Código IBAN</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANDC__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANDC__c</fullName>
    <label>Dígito de control</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANEntity__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANEntity__c</fullName>
    <label>Entidad</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_IBANOffice__c.field-meta.xml
<CustomField>
    <fullName>msf_IBANOffice__c</fullName>
    <label>Oficina</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_LanguagePreferer__c.field-meta.xml
<CustomField>
    <fullName>msf_LanguagePreferer__c</fullName>
    <label>Idioma de Preferencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAT</fullName>
            </value>
            <value>
                <fullName>ESP</fullName>
            </value>
            <value>
                <fullName>GAL</fullName>
            </value>
            <value>
                <fullName>EUS</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>EN</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_NIF__c.field-meta.xml
<CustomField>
    <fullName>msf_NIF__c</fullName>
    <description>VAT Number</description>
    <label>NIF/NIE/CIF</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_NotInformedAmount__c.field-meta.xml
<CustomField>
    <fullName>msf_NotInformedAmount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Monto no informado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_Opp_npe03_Amount__c.field-meta.xml
<CustomField>
    <fullName>msf_Opp_npe03_Amount__c</fullName>
    <description>amount sms</description>
    <label>Importe</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_PlaceCanvasser__c.field-meta.xml
<CustomField>
    <fullName>msf_PlaceCanvasser__c</fullName>
    <label>Ubicación del captador</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_RecDon_npe03_Installment_Period__c.field-meta.xml
<CustomField>
    <fullName>msf_RecDon_npe03_Installment_Period__c</fullName>
    <description>How often you’ll receive the donations. NOTE: Changing the installment period for an existing Fixed-Length Recurring Donation may result in the loss and re-creation of open opportunities. Any data associated with those opportunities may be lost.</description>
    <label>Periodicidad</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Bimensual</fullName>
            </value>
            <value>
                <fullName>Semestral</fullName>
            </value>
            <value>
                <fullName>Unique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_RecDona_npe03_Next_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>msf_RecDona_npe03_Next_Payment_Date__c</fullName>
    <defaultValue>DATE(YEAR(ADDMONTHS(TODAY(),1)),MONTH(ADDMONTHS(TODAY(),1)),1)</defaultValue>
    <description>next donation date</description>
    <label>Próxima fecha de pago</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/msf_StreetNumber__c.field-meta.xml
<CustomField>
    <fullName>msf_StreetNumber__c</fullName>
    <label>Número</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Associative.recordType-meta.xml
<RecordType>
    <fullName>Associative</fullName>
    <active>true</active>
    <businessProcess>Associative Lead</businessProcess>
    <label>Associative</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <businessProcess>Individual Lead</businessProcess>
    <label>Individual</label>
</RecordType>

force-app/main/default/classes/MSF_IncompleteManagement_CTRL.cls
/**
* @author       Deloitte
* @date         12-2018
* @group        Associative.
* @description  Controller for the lightning component MSF_IncompleteManagement
*/
public with sharing class MSF_IncompleteManagement_CTRL {
	
    @AuraEnabled
    public static Object getMyIncompletes(){
    	
        Map<String,Object> mOutValues = new Map<String,Object>();
        mOutValues.put('lIncompletes',null);
        
        List<Lead> lIncompleteIndividuals = new List<Lead>();        
        lIncompleteIndividuals = [SELECT Id, msf_esOrganizacion__c, OwnerId, createdDate,
                                  msf_Canvasser__c, msf_CityCanvasser__c, msf_CanvasserCampaign__c, msf_PlaceCanvasser__c,								// Canvasser information
                                  Name, FirstName, LastName, Suffix, msf_NIF__c, msf_Birthdate__c, msf_Gender__c, MobilePhone,								// Specific individual information
                                  Company,			 																									// Specific organization information
                                  Description, Email, Phone, msf_LanguagePreferer__c, 																	// General information shared (infividual/organization)
                                  Country, State, PostalCode, City, Street, msf_StreetNumber__c	, msf_Floor__c, msf_DoorNumber__c,						// General information shared (infividual/organization)	
                                  msf_AuxFirstName__c, msf_AuxLastName__c, msf_AuxSuffix__c, msf_AuxNIF__c,												// Information of (tutor/representative)
                                  msf_AuxMobilePhone__c, msf_AuxRole__c, 																				// Specific representative information
                                  msf_IBANCode__c, msf_IBANEntity__c, msf_IBANOffice__c, msf_IBANDC__c, msf_IBANAccountNumber__c,						// Payment profile information
                                  msf_HolderFirstName__c, msf_HolderLastName__c, msf_HolderSuffixName__c, msf_HolderNIF__c,	msf_AccountHolderOption__c,	// Payment profile holder's information
                                  msf_Opp_npe03_Amount__c, msf_RecDon_npe03_Installment_Period__c, msf_RecDona_npe03_Next_Payment_Date__c,				// Payment details
                                  msf_FirmaDonante__c, msf_FirmaRepresentante__c, msf_FirmaTitular__c,													// Signatures
                                  msf_ContactDate__c, msf_NotInformedAmount__c																		// Contact date and NotInformedAmount
                                  FROM Lead 
                                  WHERE RecordType.DeveloperName = 'Individual' 
                                  AND LeadSource = 'Persona a Persona'
                                  ORDER BY msf_ContactDate__c];
        
        if(!lIncompleteIndividuals.isEmpty()){
        	mOutValues.put('lIncompleteIndividuals',lIncompleteIndividuals);    
        }
        
    	return mOutValues; 
    }
    
    @AuraEnabled
    public static Object removeIncomplete(Id incompleteId){

        List<Lead> lIncompletos = new List<Lead>();
        
        Map<String,Object> mResult = new Map<String,Object>();
        mResult.put('title',System.Label.MSF_FORM_F2F_INCOMPLETE_DELETE_INCOMPLETE);
        mResult.put('type','warning');
        mResult.put('eliminado',false);        
        
        if(incompleteId != null){            
            lIncompletos.add(new Lead(ID=incompleteId));

            try{
                delete lIncompletos;   
                mResult.put('type','success');
                mResult.put('msg',System.Label.MSF_FORM_F2F_INCOMPLETE_DELETE_INCOMPLETE_CORRECTLY);
                mResult.put('eliminado',true);
            }catch(Exception ex){
                System.debug('ERROR: '+ex.getMessage());
                mResult.put('type','error');
            	mResult.put('msg',ex.getMessage());
            }
        }
        
    	return mResult;
    }    
}