force-app/main/default/objects/Contact/fields/msf_CRMExternalId__c.field-meta.xml
<CustomField>
    <fullName>msf_CRMExternalId__c</fullName>
    <description>WebSAS Member ID</description>
    <displayFormat>{0}</displayFormat>
    <externalId>true</externalId>
    <label>ID Miembro</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Contact/fields/msf_CRMHistoryIds__c.field-meta.xml
<CustomField>
    <fullName>msf_CRMHistoryIds__c</fullName>
    <label>Histórico de Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <label>Organization</label>
</RecordType>

force-app/main/default/classes/MSF_DefaultMerge_TEST.cls
@isTest
public class MSF_DefaultMerge_TEST {
	@testSetup static void setup(){
        Id IdOrgCont = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Organization').getRecordTypeId();
        Contact cont = new Contact(LastName='MasterRecord',RecordTypeId=IdOrgCont, msf_CRMHistoryIds__c = '3');
        insert cont;
        
        Contact cont2 = new Contact(LastName='MergeRecord', RecordTypeId=IdOrgCont, msf_CRMHistoryIds__c = '6');
        insert cont2;
    }
    
    @isTest static void test() {
        MSF_DefaultMerge_CTRL t = new MSF_DefaultMerge_CTRL();
        Contact masterRecord = [SELECT Id, msf_CRMExternalId__c, msf_CRMHistoryIds__c  FROM Contact WHERE LastName = 'MasterRecord'];
        Contact mergeRecord = [SELECT ID, msf_CRMExternalId__c, msf_CRMHistoryIds__c FROM Contact WHERE LastName = 'MergeRecord'];
        
        List<Contact> lConts = new List<Contact>(); 
        lConts.add(mergeRecord);
        Set<Id> sConts = new Set<Id>(); 
        sConts.add(mergeRecord.Id);
        
        t.beforeMerge('003', masterRecord, lConts);    
        t.afterMerge('003', masterRecord, sConts);
        t.mergeFailed('003', masterRecord, sConts, null);
    }
    
}