force-app/main/default/objects/Contact/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <description>Indicates if this Contact is designated as the Primary Contact on their Account (read only).</description>
    <formula>Account.npe01__One2OneContact__c = Id</formula>
    <inlineHelpText>Este campo esta seleccionado si es el contacto principal en la cuenta. El contacto principal puede editarse en la cuenta.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Anonymous.recordType-meta.xml
<RecordType>
    <fullName>Anonymous</fullName>
    <active>true</active>
    <label>Anonymous</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Individual_Contact.recordType-meta.xml
<RecordType>
    <fullName>Individual_Contact</fullName>
    <active>true</active>
    <label>Individual Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/msf_AutomatedProcessErrors__c.object-meta.xml
<CustomObject>
    <label>Automated Process Error</label>
    <nameField>
        <displayFormat>ERROR_{YYYY}-{MM}-{DD}_{0000000000}</displayFormat>
        <label>Identificador de error</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automated Process Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>msf_ErrorMessage__c</fullName>
    <label>Mensaje de error</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_FieldsErrors__c.field-meta.xml
<CustomField>
    <fullName>msf_FieldsErrors__c</fullName>
    <label>Campos con errores</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_Process__c.field-meta.xml
<CustomField>
    <fullName>msf_Process__c</fullName>
    <label>Proceso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_RecordId__c.field-meta.xml
<CustomField>
    <fullName>msf_RecordId__c</fullName>
    <label>Id registro</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_AutomatedProcessErrors__c/fields/msf_StatusCode__c.field-meta.xml
<CustomField>
    <fullName>msf_StatusCode__c</fullName>
    <label>Código de error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Contact for this Opportunity. If this is an individual Donation, NPSP attributes the Donation to the Primary Contact. If this is an organizational Donation, NPSP attributes a soft credit to the Primary Contact.</description>
    <inlineHelpText>El contacto principal para esta oportunidad. La función del contacto principal se mantiene sincronizada con este campo. Para donantes individuales, esto significa atribuciones por esta oportunidad.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Donation.recordType-meta.xml
<RecordType>
    <fullName>Donation</fullName>
    <active>true</active>
    <businessProcess>Donation</businessProcess>
    <description>Donation Received</description>
    <label>Donation</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <businessProcess>Grant</businessProcess>
    <description>Grant Received</description>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Historical.recordType-meta.xml
<RecordType>
    <fullName>Historical</fullName>
    <active>true</active>
    <businessProcess>Donation</businessProcess>
    <label>Historical</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/In_Kind_Gift.recordType-meta.xml
<RecordType>
    <fullName>In_Kind_Gift</fullName>
    <active>true</active>
    <businessProcess>In-Kind Gift</businessProcess>
    <description>Goods or Services received as In-Kind</description>
    <label>In-Kind Gift</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Legacy.recordType-meta.xml
<RecordType>
    <fullName>Legacy</fullName>
    <active>true</active>
    <businessProcess>Testamentos%26Herencias</businessProcess>
    <description>Opportunity committed without Payment</description>
    <label>Legacy</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Matching_Gift.recordType-meta.xml
<RecordType>
    <fullName>Matching_Gift</fullName>
    <active>true</active>
    <businessProcess>Matching Gift</businessProcess>
    <description>Matching Donation from an Donor&apos;s Employer or other Organization</description>
    <label>Matching Gift</label>
</RecordType>

force-app/main/default/classes/MSF_UpdateRollUpsContact_BATCH.cls
global without sharing class MSF_UpdateRollUpsContact_BATCH implements Database.Batchable<sObject>{

    global final String query; 
    
    global MSF_UpdateRollUpsContact_BATCH (){
         
        String queryStep = '';
        queryStep  = 'SELECT Id ';
        queryStep += 'FROM Contact ';
        queryStep += 'WHERE RecordType.DeveloperName in(\'Individual_Contact\',\'Organization\',\'Anonymous\')';

        query = queryStep;         
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
	
    
    global void execute(Database.BatchableContext BC, List<Contact> scope){
		
        
        List<Contact> lUpdateContacts = new List<Contact>();
        Set<ID> sContIds = new Map<ID,Contact>(scope).keyset();
        
        List<Id> idsRT = new List<Id>(); 
        List<String> rNames = new List<String>{'Donation','Grant','Historical','In_Kind_Gift','Legacy','Matching_Gift'};
        for (String n : rNames) {
             idsRT.add(Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(n).getRecordTypeId());
        }
        
        for(AggregateResult ar : [SELECT npsp__Primary_Contact__c contact, COUNT(Id) NumberOfClosedOpps 
                                  FROM Opportunity 
                                  WHERE npsp__Primary_Contact__c IN: sContIds
                                  AND RecordTypeId IN :idsRT 
                                  AND IsWon = TRUE 
                                  AND Amount > 0 
                                  GROUP BY npsp__Primary_Contact__c])
        {
        	Contact tempCon = new Contact(
                Id = (Id)ar.get('contact'),
                npo02__NumberOfClosedOpps__c = (Double)ar.get('NumberOfClosedOpps')
            );	
            lUpdateContacts.add(tempCon);  
        }
        
        // DML statement
        Database.SaveResult[] srList = Database.update(lUpdateContacts, false);
        
        
        //*
        List<msf_AutomatedProcessErrors__c> lAPE = new List<msf_AutomatedProcessErrors__c>(); 
        
        for (Database.SaveResult sr : srList) { // Iterate through each returned result
            if (!sr.isSuccess()) {  // Operation failed, so get all errors                                   
                for(Database.Error err : sr.getErrors()) {
                    msf_AutomatedProcessErrors__c tempAPE = new msf_AutomatedProcessErrors__c(msf_Process__c = 'MSF_UpdateRollUpsContact_BATCH', msf_RecordId__c = scope.get(srList.indexOf(sr)).Id, msf_StatusCode__c = String.valueOf(err.getStatusCode()), msf_FieldsErrors__c = String.valueOf(err.getFields()), msf_ErrorMessage__c = String.valueOf(err.getMessage()).abbreviate(255));
                    lAPE.add(tempAPE);
                }
            }            
        }  
        
        if(!lAPE.isEmpty()){
            insert lAPE;
        }//*/
    }
    
    global void finish(Database.BatchableContext BC){
        System.debug('END BATCH - MSF_UpdateRollUpsContact_BATCH');
    }  
}