force-app/main/default/objects/Contact/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <description>Indicates if this Contact is designated as the Primary Contact on their Account (read only).</description>
    <formula>Account.npe01__One2OneContact__c = Id</formula>
    <inlineHelpText>Este campo esta seleccionado si es el contacto principal en la cuenta. El contacto principal puede editarse en la cuenta.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Individual_Contact.recordType-meta.xml
<RecordType>
    <fullName>Individual_Contact</fullName>
    <active>true</active>
    <label>Individual Contact</label>
</RecordType>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_DonationVehicleContact__c.field-meta.xml
<CustomField>
    <fullName>msf_DonationVehicleContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Donante por vehículo de donación</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El valor no existe o no coinciden los criterios de filtro. Contacto VD</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Individual Contact, Organization, Anonymous</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades vehículo de donación</relationshipLabel>
    <relationshipName>DonationVehicleContact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Contact for this Opportunity. If this is an individual Donation, NPSP attributes the Donation to the Primary Contact. If this is an organizational Donation, NPSP attributes a soft credit to the Primary Contact.</description>
    <inlineHelpText>El contacto principal para esta oportunidad. La función del contacto principal se mantiene sincronizada con este campo. Para donantes individuales, esto significa atribuciones por esta oportunidad.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Donation.recordType-meta.xml
<RecordType>
    <fullName>Donation</fullName>
    <active>true</active>
    <businessProcess>Donation</businessProcess>
    <description>Donation Received</description>
    <label>Donation</label>
</RecordType>

force-app/main/default/classes/MSF_DonationVehicleManagement_TEST.cls
/**
* @author       Deloitte
* @date         11-2018
* @group        Opportunity
* @description  test class for the MSF_DonationVehicleManagement_TDTM class.
*/
@isTest
private class MSF_DonationVehicleManagement_TEST {

    @testSetup static void setup(){
        
        List<Contact> lConInsert = new List<Contact>();

        Id RTIdIndividuals = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Individual_Contact').getRecordTypeId();
        
        List<npsp__Trigger_Handler__c> triggerHandlers = npsp.TDTM_Config_API.getCachedRecords();

        //Add our Trigger Handler to cached Trigger Handlers
        npsp__Trigger_Handler__c thAff = new npsp__Trigger_Handler__c(
            Name = 'TriggerTestDonationVehicleManagement',
            npsp__Class__c = 'MSF_DonationVehicleManagement_TDTM',
            npsp__Object__c = 'Opportunity',
            npsp__Trigger_Action__c = 'BeforeInsert;BeforeUpdate;AfterInsert;AfterUpdate',
            npsp__Active__c = true,
            npsp__Load_Order__c = 6,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );        
        triggerHandlers.add(thAff);        
        upsert triggerHandlers;
        
        //Create contacts
        Contact c1 = new Contact(
            FirstName = 'FNX',
            LastName = 'LNX',
            RecordTypeId = RTIdIndividuals
        );
        lConInsert.add(c1);
        
        Contact c2 = new Contact(            
            FirstName = 'FNY',
            LastName = 'LNY',
            RecordTypeId = RTIdIndividuals
        );
        lConInsert.add(c2);
        
        insert lConInsert;
    }
    
    @isTest static void DonationVehicleManagement_Individual(){
        String roleString = 'Donor by donation vehicle';
        Id RTDonation = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Donation').getRecordTypeId(); 
        Id RTIdIndividuals = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Individual_Contact').getRecordTypeId();   
        
        List<Contact> lCon = [SELECT Id, Name, AccountId FROM Contact WHERE RecordTypeId =: RTIdIndividuals ORDER BY Name];

        Opportunity o = new Opportunity(
            Name = 'Opportunity X',
            npsp__Primary_Contact__c = lCon[0].Id,
            AccountId = lCon[0].AccountId,
            Amount = 200,
            CloseDate = Date.today(),
            StageName = 'Propuesta'
        );   
        Opportunity o2 = new Opportunity(
            Name = 'Opportunity X',
            npsp__Primary_Contact__c = null,
            AccountId = lCon[1].AccountId,
            Amount = 201,
            CloseDate = Date.today(),
            StageName = 'Propuesta',
            msf_DonationVehicleContact__c = lCon[0].Id
        );   
        
        Test.startTest();        
            insert o;
            o = [SELECT Id, Name, AccountId, npsp__Primary_Contact__c, msf_DonationVehicleContact__c FROM Opportunity WHERE Id =: o.Id LIMIT 1];
            System.assertEquals(o.npsp__Primary_Contact__c, o.msf_DonationVehicleContact__c);       
        
            o.msf_DonationVehicleContact__c = lCon[1].Id;
            update o;
            o = [SELECT Id, Name, AccountId, npsp__Primary_Contact__c, msf_DonationVehicleContact__c FROM Opportunity WHERE Id =: o.Id LIMIT 1];
            List<OpportunityContactRole> lOcr = [SELECT Id FROM OpportunityContactRole WHERE OpportunityId =: o.Id AND Role = :roleString];
            System.assertEquals(lOcr.size(), 1, 'The number of the opportunity contact role records is: '+lOcr.size());
        
            o.msf_DonationVehicleContact__c = lCon[0].Id;
            update o;
            o = [SELECT Id, Name, AccountId, npsp__Primary_Contact__c, msf_DonationVehicleContact__c FROM Opportunity WHERE Id =: o.Id LIMIT 1];
            lOcr = new List<OpportunityContactRole>([SELECT Id FROM OpportunityContactRole WHERE OpportunityId =: o.Id AND Role = :roleString]);
            System.assertEquals(lOcr.size(), 0, 'The number of the opportunity contact role records is: '+lOcr.size());
        
            o.npsp__Primary_Contact__c = null;
            update o;
            o = [SELECT Id, Name, AccountId, npsp__Primary_Contact__c, msf_DonationVehicleContact__c FROM Opportunity WHERE Id =: o.Id LIMIT 1];
            System.assertEquals(o.msf_DonationVehicleContact__c, null, 'The number of the opportunity contact role records is: '+lOcr.size());
        
            insert o2;
            lOcr = new List<OpportunityContactRole>([SELECT Id FROM OpportunityContactRole WHERE OpportunityId =: o2.Id AND Role = :roleString]);
            System.assertEquals(lOcr.size(), 1, 'The number of the opportunity contact role records is: '+lOcr.size());
        Test.stopTest();
    }
}