force-app/main/default/objects/msf_InteractionsMasterData__c/msf_InteractionsMasterData__c.object-meta.xml
<CustomObject>
    <label>Maestro de datos de Interacciones</label>
    <nameField>
        <displayFormat>MD_IN_{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maestro de datos de Interacciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_Campaign__c.field-meta.xml
<CustomField>
    <fullName>msf_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaña</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Maestro de datos de Interacciones</relationshipLabel>
    <relationshipName>Maestro_de_datos_de_Interacciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_Channel__c.field-meta.xml
<CustomField>
    <fullName>msf_Channel__c</fullName>
    <label>Canal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_Comment__c.field-meta.xml
<CustomField>
    <fullName>msf_Comment__c</fullName>
    <label>Comentario</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_Family__c.field-meta.xml
<CustomField>
    <fullName>msf_Family__c</fullName>
    <label>Familia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_InboundOutbound__c.field-meta.xml
<CustomField>
    <fullName>msf_InboundOutbound__c</fullName>
    <label>Sentido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_InboundOutbound</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_LeadSource__c.field-meta.xml
<CustomField>
    <fullName>msf_LeadSource__c</fullName>
    <label>Canal de entrada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_LeadSource1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_ProactiveReactive__c.field-meta.xml
<CustomField>
    <fullName>msf_ProactiveReactive__c</fullName>
    <label>Proactiva / Reactiva</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_ProactiveReactive</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_Status__c.field-meta.xml
<CustomField>
    <fullName>msf_Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Eliminada</fullName>
            </value>
            <value>
                <fullName>En curso</fullName>
            </value>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Realizada</fullName>
            </value>
            <value>
                <fullName>Sin gestión</fullName>
            </value>
            <value>
                <fullName>Inalcanzable</fullName>
            </value>
            <value>
                <fullName>No requerido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_Subject__c.field-meta.xml
<CustomField>
    <fullName>msf_Subject__c</fullName>
    <label>Asunto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abogado, Familiar o un Tercero Reclama sobre una Herencia (Retraso, Pago Pendiente, Comparecencia, etc)</fullName>
            </value>
            <value>
                <fullName>ACMA Envia Justificante Pago Cuota Asociado</fullName>
            </value>
            <value>
                <fullName>ACTUA COMO ALTAVOZ</fullName>
                <isActive>false</isActive>
                <label>ACTUA COMO ALTAVOZ</label>
            </value>
            <value>
                <fullName>Actúa Como Altavoz</fullName>
            </value>
            <value>
                <fullName>Actúa como Aval</fullName>
            </value>
            <value>
                <fullName>ACTUA COMO PORTAVOZ HERENCIAS</fullName>
                <isActive>false</isActive>
                <label>ACTUA COMO PORTAVOZ HERENCIAS</label>
            </value>
            <value>
                <fullName>Actúa Como Portavoz Herencias</fullName>
            </value>
            <value>
                <fullName>ACTUA COMO VOLUNTARIO</fullName>
                <isActive>false</isActive>
                <label>ACTUA COMO VOLUNTARIO</label>
            </value>
            <value>
                <fullName>Actúa Como Voluntario</fullName>
            </value>
            <value>
                <fullName>Actúa como Voluntario Asociativo</fullName>
            </value>
            <value>
                <fullName>AGRADECIMIENTO ANUAL</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO ANUAL</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO ASISTENCIA A ENTREVISTA O REUNION</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO ASISTENCIA A ENTREVISTA O REUNION</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO ASISTENCIA A EVENTO O EXPOSICION</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO ASISTENCIA A EVENTO O EXPOSICION</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO ASISTENCIA A VISITA</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO ASISTENCIA A VISITA</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO AUMEN CUOTA</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO AUMEN CUOTA</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO CELEBRACIONES</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO CELEBRACIONES</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO CUOTA ANUAL</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO CUOTA ANUAL</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO DONATIVO</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO DONATIVO</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO EMPRESA SIN FRONTERAS ESF</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO EMPRESA SIN FRONTERAS ESF</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO FAMILIARES HERENCIAS</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO FAMILIARES HERENCIAS</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO INICIATIVA SOLIDARIA</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO INICIATIVA SOLIDARIA</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO OTROS (EL DONANTE HACE/ENVÍA ALGO)</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO OTROS (EL DONANTE HACE/ENVÍA ALGO)</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO PARTICIPA EN CAMPAÑA</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO PARTICIPA EN CAMPAÑA</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO REGALO SOLIDARIO</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO REGALO SOLIDARIO</label>
            </value>
            <value>
                <fullName>AGRADECIMIENTO TESTAMENTO A FAVOR</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMIENTO TESTAMENTO A FAVOR</label>
            </value>
            <value>
                <fullName>AGRADECIMINETO ENCUESTA</fullName>
                <isActive>false</isActive>
                <label>AGRADECIMINETO ENCUESTA</label>
            </value>
            <value>
                <fullName>Asiste a Charla PEU</fullName>
            </value>
            <value>
                <fullName>Asiste a Entrevista o Reunión</fullName>
            </value>
            <value>
                <fullName>Asiste a Evento Asociativo</fullName>
            </value>
            <value>
                <fullName>Asiste a Evento o Exposición</fullName>
            </value>
            <value>
                <fullName>MSF Responde a: Solicita Envío Documentos, Kits o Publicaciones Varios</fullName>
            </value>
            <value>
                <fullName>Solicita Envío Documentos, Kits o Publicaciones Varios</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_InteractionsMasterData__c/fields/msf_TaskNumber__c.field-meta.xml
<CustomField>
    <fullName>msf_TaskNumber__c</fullName>
    <label>Número de tarea</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/npsp__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Active__c.field-meta.xml
<CustomField>
    <fullName>npsp__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Trigger Handler is in use.</description>
    <inlineHelpText>Indica que este módulo esta activo</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>npsp__Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this class should run asynchronously in this transaction, for any of its After events.</description>
    <inlineHelpText>Indica que este módulo debe correr de forma asincrónica en esta transacción, para cualquiera de estos After Events</inlineHelpText>
    <label>Asynchronous After Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Class__c.field-meta.xml
<CustomField>
    <fullName>npsp__Class__c</fullName>
    <description>The name of the class to run.</description>
    <inlineHelpText>Nombre de la clase que debe correr</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>npsp__Load_Order__c</fullName>
    <description>The order in which this class should run. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>Orden en el cual este módulo debe correr, ayudando a mantener dependencia en los módulos y los datos.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Object__c.field-meta.xml
<CustomField>
    <fullName>npsp__Object__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, or Opportunity.</description>
    <inlineHelpText>Nombre del objeto en el que este handler debe correr</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>npsp__Trigger_Action__c</fullName>
    <description>The context in which this class should run, for example, before a record is inserted, after a record is deleted, etc.</description>
    <inlineHelpText>Acción desencadenada (Trigger Action) en el que este módulo debe disparar</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__User_Managed__c.field-meta.xml
<CustomField>
    <fullName>npsp__User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, NPSP will no longer push updates to this Trigger Handler. Select this option if you have made changes that you do not want NPSP to overwrite.</description>
    <inlineHelpText>Seleccionar si tiene la intención de gestionar el registro usted mismo. Tenga en cuenta que las actualizaciones del paquete no actualizará este registro.</inlineHelpText>
    <label>User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/npsp__Trigger_Handler__c/fields/npsp__Usernames_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>npsp__Usernames_to_Exclude__c</fullName>
    <description>A semicolon-separated list of Usernames that this Trigger Handler will not run for. Leave blank to run for all Users.</description>
    <inlineHelpText>Una lista de separada por punto y coma de nombres de usuario en los que no se ejecutará este controlador de desencadenador. Déjela en blanco para la ejecución para todos los usuarios.</inlineHelpText>
    <label>Usernames to Exclude</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/globalValueSets/MSF_Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Correo Postal</fullName>
    </customValue>
    <customValue>
        <fullName>E-mail</fullName>
    </customValue>
    <customValue>
        <fullName>Fax</fullName>
    </customValue>
    <customValue>
        <fullName>Fichero Informático</fullName>
    </customValue>
    <customValue>
        <fullName>Formularios Web</fullName>
    </customValue>
    <customValue>
        <fullName>Generación Aplicación</fullName>
    </customValue>
    <customValue>
        <fullName>Interno</fullName>
    </customValue>
    <customValue>
        <fullName>Llamada</fullName>
    </customValue>
    <customValue>
        <fullName>Mensajería Instantánea</fullName>
    </customValue>
    <customValue>
        <fullName>Mi Perfil</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Presencial</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>n/a</fullName>
    </customValue>
    <customValue>
        <fullName>Telemarketing</fullName>
        <isActive>false</isActive>
        <label>Telemarketing</label>
    </customValue>
    <customValue>
        <fullName>Buzón Móvil</fullName>
        <isActive>false</isActive>
        <label>Buzón Móvil</label>
    </customValue>
    <customValue>
        <fullName>Skype</fullName>
        <isActive>false</isActive>
        <label>Skype</label>
    </customValue>
    <customValue>
        <fullName>Whatsapp</fullName>
        <isActive>false</isActive>
        <label>Whatsapp</label>
    </customValue>
    <description>Interactions Master Data</description>
    <masterLabel>Canal</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MSF_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Area socio Web</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio de datos</fullName>
    </customValue>
    <customValue>
        <fullName>Campañas de petición</fullName>
    </customValue>
    <customValue>
        <fullName>Campañas fundraising</fullName>
    </customValue>
    <customValue>
        <fullName>Certificado fiscal</fullName>
    </customValue>
    <customValue>
        <fullName>Colaboraciones especiales</fullName>
    </customValue>
    <customValue>
        <fullName>Devoluciones económicas</fullName>
    </customValue>
    <customValue>
        <fullName>Encuestas</fullName>
    </customValue>
    <customValue>
        <fullName>Eventos</fullName>
    </customValue>
    <customValue>
        <fullName>Gestión administrativa</fullName>
    </customValue>
    <customValue>
        <fullName>Plan de relación</fullName>
    </customValue>
    <customValue>
        <fullName>Presenciales O2O</fullName>
    </customValue>
    <customValue>
        <fullName>Proyectos, operaciones y actividades MSF</fullName>
    </customValue>
    <description>Interactions Master Data</description>
    <masterLabel>Familia</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MSF_InboundOutbound.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Entrante</fullName>
    </customValue>
    <customValue>
        <fullName>Saliente</fullName>
    </customValue>
    <customValue>
        <fullName>Interno</fullName>
    </customValue>
    <customValue>
        <fullName>n/a</fullName>
    </customValue>
    <description>Interactions Master Data</description>
    <masterLabel>Sentido</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MSF_LeadSource1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cloud page</fullName>
    </customValue>
    <customValue>
        <fullName>Correo postal sin cupón</fullName>
    </customValue>
    <customValue>
        <fullName>Cupón</fullName>
    </customValue>
    <customValue>
        <fullName>Email a Bodas</fullName>
    </customValue>
    <customValue>
        <fullName>Email a Empresas</fullName>
    </customValue>
    <customValue>
        <fullName>Email a Iniciativas Solidarias</fullName>
    </customValue>
    <customValue>
        <fullName>Email a officers Mid Donors</fullName>
    </customValue>
    <customValue>
        <fullName>Email a One to one</fullName>
    </customValue>
    <customValue>
        <fullName>Email a SAS</fullName>
    </customValue>
    <customValue>
        <fullName>Email Director/a General</fullName>
    </customValue>
    <customValue>
        <fullName>Email herencias</fullName>
    </customValue>
    <customValue>
        <fullName>Email Presidente/a MSF</fullName>
    </customValue>
    <customValue>
        <fullName>Entidad financiera</fullName>
    </customValue>
    <customValue>
        <fullName>Eventos</fullName>
    </customValue>
    <customValue>
        <fullName>Mensajería Instantánea</fullName>
    </customValue>
    <customValue>
        <fullName>n/a</fullName>
    </customValue>
    <customValue>
        <fullName>Otro</fullName>
    </customValue>
    <customValue>
        <fullName>Persona a persona</fullName>
    </customValue>
    <customValue>
        <fullName>Personal con tablet</fullName>
    </customValue>
    <customValue>
        <fullName>Plataforma iniciativas</fullName>
    </customValue>
    <customValue>
        <fullName>Redes Sociales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono campaña</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Herencias y Legados</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Officers</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono SAS</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono web</fullName>
    </customValue>
    <customValue>
        <fullName>Telemarketing</fullName>
    </customValue>
    <customValue>
        <fullName>Web campaña</fullName>
    </customValue>
    <customValue>
        <fullName>Web MSF</fullName>
    </customValue>
    <customValue>
        <fullName>Llamada</fullName>
        <isActive>false</isActive>
        <label>Llamada</label>
    </customValue>
    <description>LeadSource Master Data</description>
    <masterLabel>LeadSource1</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/MSF_ProactiveReactive.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Interna</fullName>
    </customValue>
    <customValue>
        <fullName>Proactiva</fullName>
    </customValue>
    <customValue>
        <fullName>Reactiva</fullName>
    </customValue>
    <customValue>
        <fullName>n/a</fullName>
    </customValue>
    <customValue>
        <fullName>Proactivo</fullName>
        <isActive>false</isActive>
        <label>Proactivo</label>
    </customValue>
    <customValue>
        <fullName>Interno</fullName>
        <isActive>false</isActive>
        <label>Interno</label>
    </customValue>
    <description>Interactions Master Data</description>
    <masterLabel>Proactiva / Reactiva</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MSF_TaskFieldsLogic_TEST.cls
/**
* @author 		Deloitte
* @date 		03-2019
* @group 		Task
* @description	test class for the MSF_TaskFieldsLogic_TDTM class.
*/
@isTest
private class MSF_TaskFieldsLogic_TEST {
    
    @testSetup static void setup(){
        //Create Trigger
        npsp__Trigger_Handler__c thCon = new npsp__Trigger_Handler__c(
            Name = 'TriggerTestTaskFieldsLogic',
            npsp__Class__c = 'MSF_TaskFieldsLogic_TDTM',
            npsp__Object__c = 'Task',
            npsp__Trigger_Action__c = 'BeforeUpdate;BeforeInsert;AfterInsert;AfterDelete',
            npsp__Active__c = true,
            npsp__Load_Order__c = 2,
            npsp__User_Managed__c = true,
            npsp__Asynchronous__c = false,
            npsp__Usernames_to_Exclude__c = ''
        );        
        upsert thCon; 
        
        List<msf_InteractionsMasterData__c> iMDList = new List<msf_InteractionsMasterData__c>();
        msf_InteractionsMasterData__c imd = new msf_InteractionsMasterData__c(
            msf_Subject__c = 'Actúa Como Altavoz',
            msf_Status__c = 'Pendiente',
            msf_TaskNumber__c = 1001,
            msf_InboundOutbound__c = 'Entrante',
            msf_Channel__c = 'Llamada',
            msf_ProactiveReactive__c = 'Reactiva',
            msf_Campaign__c = null,
            msf_LeadSource__c = null,
            msf_Comment__c = 'Comment',
            msf_Family__c = null,
            msf_Objective__c = null          
        );
        iMDList.add(imd);
        
        msf_InteractionsMasterData__c imd2 = new msf_InteractionsMasterData__c(
            msf_Subject__c = 'Solicita Envío Documentos, Kits o Publicaciones Varios',
            msf_Status__c = 'Realizada',
            msf_TaskNumber__c = 118,
            msf_GenerateTask__c = 211,
            msf_InboundOutbound__c = 'Entrante',
            msf_Channel__c = 'Llamada',
            msf_ProactiveReactive__c = 'Reactiva',
            msf_Campaign__c = null,
            msf_LeadSource__c = null,
            msf_Comment__c = 'Comment',
            msf_Family__c = null,
            msf_Objective__c = 'Petición de documentos o información'         
        );
        iMDList.add(imd2);
        
        msf_InteractionsMasterData__c imd3 = new msf_InteractionsMasterData__c(
            msf_Subject__c = 'MSF Responde a: Solicita Envío Documentos, Kits o Publicaciones Varios',
            msf_Status__c = 'Pendiente',
            msf_TaskNumber__c = 211,
            msf_InboundOutbound__c = 'Entrante',
            msf_Channel__c = 'Llamada',
            msf_ProactiveReactive__c = 'Reactiva',
            msf_Campaign__c = null,
            msf_LeadSource__c = null,
            msf_Comment__c = 'Comment',
            msf_Family__c = null,
            msf_Objective__c = null          
        );
        iMDList.add(imd3);
        
        insert iMDList;
        
        Schema.DescribeFieldResult fieldResult = Task.Subject.getDescribe(); 
        List<Schema.PicklistEntry> pickListValues = fieldResult.getPicklistValues();
        
        Task t = new Task(Subject=pickListValues[0].getValue(), msf_Channel__c = 'Llamada');
        insert t;
    }
    
    @isTest static void testGeneratedTask() {
        Task t = new Task(msf_TaskNumber__c=118, Subject='Solicita Envío Documentos, Kits o Publicaciones Varios');
        insert t; 
    }
    
    @isTest static void testSetDefaultValues(){
        Task t = new Task(Subject='Actúa Como Altavoz');
        insert t;
        
        t = [SELECT Id, msf_TaskNumber__c FROM Task WHERE Id =: t.Id LIMIT 1];
        System.assertEquals(1001, t.msf_TaskNumber__c,'ERROR: The default values have not been configured');
    }
    
    @isTest static void testDeleteTask(){
        Task t = new Task(Subject='Actúa Como Altavoz');
        insert t;
        
        delete t;
    }
    
    @isTest static void testSendError_Insert(){
        try{
            Task t = new Task(msf_Channel__c ='Llamada', Subject=null);
            insert t;
            System.assert(false,'ERROR: Error message was not send');
        }catch(DmlException ex){
            System.assert(true);
        }
    }
    
    @isTest static void testSendError_Update(){
        try{
            Schema.DescribeFieldResult fieldResult = Task.Subject.getDescribe(); 
            List<Schema.PicklistEntry> pickListValues = fieldResult.getPicklistValues();
            
			Task t = [SELECT Id, Subject FROM Task WHERE Subject = :pickListValues[0].getValue()];            
            t.Subject = null;
            update t;

            System.assert(false,'ERROR: Error message was not send.');
        }catch(DmlException ex){
            System.assert(true);
        }
    }
}