force-app/main/default/objects/msf_Associative__c/msf_Associative__c.object-meta.xml
<CustomObject>
    <label>Asociativo</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Número asociado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asociativos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_Associative__c/fields/msf_ContactId__c.field-meta.xml
<CustomField>
    <fullName>msf_ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre del contacto</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Asociativos</relationshipLabel>
    <relationshipName>Asociativos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_Status__c.field-meta.xml
<CustomField>
    <fullName>msf_Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Baja</fullName>
            </value>
            <value>
                <fullName>Baja en proceso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MSF_AssociativeSectionInContact_TEST.cls
@isTest
private class MSF_AssociativeSectionInContact_TEST {
    @testSetup static void setup(){
        //Initialize values
        Contact cont = new Contact(LastName='MSF_AssociativeSectionInContact_TEST_LastName1');
        insert cont;
        msf_Associative__c obj = new msf_Associative__c(msf_Status__c='Activo', msf_contactId__c=cont.Id);
        insert obj; 
    }
    
    @isTest static void getMsf_Associative_c(){
        Contact cont = [SELECT Id,LastName FROM Contact Where LastName = 'MSF_AssociativeSectionInContact_TEST_LastName1' LIMIT 1];
        Object obj = MSF_AssociativeSectionInContact_CTRL.getAssociativeInformation(cont.Id);        
        Map<String, Object> msfa = (Map<String, Object>)obj;
        System.assertNotEquals(null,msfa.get('associative'));
    }
    @isTest static void getNull(){
        Contact cont = new Contact(LastName='MSF_AssociativeSectionInContact_TEST_LastName2');
        Object obj = MSF_AssociativeSectionInContact_CTRL.getAssociativeInformation(cont.Id);        
        Map<String, Object> msfa = (Map<String, Object>)obj;
        System.assertEquals(null,msfa.get('associative'));
    }

}