force-app/main/default/objects/msf_Associative__c/msf_Associative__c.object-meta.xml
<CustomObject>
    <label>Asociativo</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Número asociado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asociativos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_Associative__c/fields/msf_AssociativePhone__c.field-meta.xml
<CustomField>
    <fullName>msf_AssociativePhone__c</fullName>
    <label>Teléfono de asociativo</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_CancellationReason__c.field-meta.xml
<CustomField>
    <fullName>msf_CancellationReason__c</fullName>
    <label>Motivo de baja</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>msf_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Desconectado de la asociación</fullName>
            </value>
            <value>
                <fullName>Desacuerdo con las posiciones / decisiones adoptadas por la asociación</fullName>
            </value>
            <value>
                <fullName>Fallecido</fullName>
            </value>
            <value>
                <fullName>Enlace a otra asociación de MSF</fullName>
            </value>
            <value>
                <fullName>Incumplimiento de los estatutos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_ContactId__c.field-meta.xml
<CustomField>
    <fullName>msf_ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre del contacto</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Asociativos</relationshipLabel>
    <relationshipName>Asociativos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_ExemptOfPayment__c.field-meta.xml
<CustomField>
    <fullName>msf_ExemptOfPayment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exento de pago</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_FirstAssociativeEmail__c.field-meta.xml
<CustomField>
    <fullName>msf_FirstAssociativeEmail__c</fullName>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_FirstNameSAP__c.field-meta.xml
<CustomField>
    <fullName>msf_FirstNameSAP__c</fullName>
    <label>Nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_IsFieldSAP__c.field-meta.xml
<CustomField>
    <fullName>msf_IsFieldSAP__c</fullName>
    <formula>BEGINS(msf_JobSAP__c , &apos;F -&apos;) 
||
BEGINS(msf_CostCenterSAP__c , &apos;ES&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actualmente en terreno</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_IsSanitary__c.field-meta.xml
<CustomField>
    <fullName>msf_IsSanitary__c</fullName>
    <formula>ISPICKVAL(msf_ProfessionAreas__c, &apos;Ciencias de la Salud y Servicios Sociales&apos;) &amp;&amp;
(
  ISPICKVAL(msf_ProfessionSubAreas__c, &apos;Medicina&apos;) ||
  ISPICKVAL(msf_ProfessionSubAreas__c, &apos;Farmacia&apos;) ||
  ISPICKVAL(msf_ProfessionSubAreas__c, &apos;Psicología&apos;) ||
  ISPICKVAL(msf_ProfessionSubAreas__c, &apos;Enfermería&apos;) ||
  ISPICKVAL(msf_ProfessionSubAreas__c, &apos;Matronas&apos;) ||
  ISPICKVAL(msf_ProfessionSubAreas__c, &apos;Odontología&apos;) ||
  ISPICKVAL(msf_ProfessionSubAreas__c, &apos;Fisioterapia&apos;) ||
  ISPICKVAL(msf_ProfessionSubAreas__c, &apos;Nutrición&apos;) ||
  ISPICKVAL(msf_ProfessionSubAreas__c, &apos;Técnicos Superiores en Laboratorio de diagnóstico Clínico&apos;)    
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Es sanitario</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_LanguagePreferer__c.field-meta.xml
<CustomField>
    <fullName>msf_LanguagePreferer__c</fullName>
    <label>Lenguaje de preferencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>EN</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_LastNameSAP__c.field-meta.xml
<CustomField>
    <fullName>msf_LastNameSAP__c</fullName>
    <label>Apellido 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_NationalitySAP__c.field-meta.xml
<CustomField>
    <fullName>msf_NationalitySAP__c</fullName>
    <label>Nacionalidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>msf_PaymentMethod__c</fullName>
    <label>Método de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domiciliación bancaria</fullName>
            </value>
            <value>
                <fullName>Tarjeta de crédito o débito</fullName>
            </value>
            <value>
                <fullName>ACMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_SalariedSAP__c.field-meta.xml
<CustomField>
    <fullName>msf_SalariedSAP__c</fullName>
    <formula>!ISBLANK(msf_CostCenterSAP__c) &amp;&amp; !BEGINS(msf_CostCenterSAP__c , &apos;ES&apos;) &amp;&amp; !BEGINS(msf_CostCenterSAP__c , &apos;90&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asalariado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_SecondAssociativeEmail__c.field-meta.xml
<CustomField>
    <fullName>msf_SecondAssociativeEmail__c</fullName>
    <label>Correo electrónico secundario</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_SecondNameSAP__c.field-meta.xml
<CustomField>
    <fullName>msf_SecondNameSAP__c</fullName>
    <label>Apellido 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_StaffType__c.field-meta.xml
<CustomField>
    <fullName>msf_StaffType__c</fullName>
    <label>Tipo de personal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internacional</fullName>
            </value>
            <value>
                <fullName>Sede o delegaciones</fullName>
            </value>
            <value>
                <fullName>Nacional</fullName>
            </value>
            <value>
                <fullName>Otros MSF</fullName>
            </value>
            <value>
                <fullName>Voluntario</fullName>
                <isActive>false</isActive>
                <label>Voluntario</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_StartDateAssociativeSAP__c.field-meta.xml
<CustomField>
    <fullName>msf_StartDateAssociativeSAP__c</fullName>
    <label>Fecha inicio asociativo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/msf_Associative__c/fields/msf_Status__c.field-meta.xml
<CustomField>
    <fullName>msf_Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Baja</fullName>
            </value>
            <value>
                <fullName>Baja en proceso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MSF_AssociativeSectionInContact_CTRL.cls
/**
* @author       Deloitte
* @date         12-2018
* @group        Associative.
* @description  Controller for the lightning component MSF_AssociativeSectionInContact
*/
public without sharing class MSF_AssociativeSectionInContact_CTRL {
    
    @AuraEnabled
    public static Object getAssociativeInformation(ID contactId){
        
        Map<String,Object> outputMap = new Map<String,Object>();        
        
        List<msf_Associative__c> lAsso = new List<msf_Associative__c>();
        
        lAsso = [SELECT Id, Name, msf_ExemptOfPayment__c, msf_Status__c, msf_CancellationReason__c, 
                 msf_FirstNameSAP__c, msf_LastNameSAP__c, msf_SecondNameSAP__c, msf_AssociativePhone__c,
                 msf_FirstAssociativeEmail__c, msf_SecondAssociativeEmail__c,
                 msf_NationalitySAP__c, msf_LanguagePreferer__c, 
                 msf_IsSanitary__c, msf_SalariedSAP__c, msf_IsFieldSAP__c, msf_PaymentMethod__c,
                 msf_StaffType__c, msf_StartDateAssociativeSAP__c
                 FROM msf_Associative__c 
                 WHERE msf_contactId__c =: contactId
                 LIMIT 1
                ];
        
        if(lAsso.isEmpty()){
        	outputMap.put('associative',null);     
        }else{
        	outputMap.put('associative',lAsso[0]);      
        }           
        
        return outputMap;        
    }    
}