force-app/main/default/objects/cpm__Installment__c/cpm__Installment__c.object-meta.xml
<CustomObject>
    <description>Installments are the result of a Recurring Payment. Installments track the status of a invoice or a direct debit transaction.</description>
    <label>Installment</label>
    <nameField>
        <displayFormat>INST-{00000000}</displayFormat>
        <label>Installment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Contact__c.field-meta.xml
<CustomField>
    <fullName>cpm__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The debitor</description>
    <inlineHelpText>El deudor</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>cpm__Due_Date__c</fullName>
    <description>The Due date for this installment</description>
    <inlineHelpText>Fecha de vencimiento para este installment</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__IBAN__c.field-meta.xml
<CustomField>
    <fullName>cpm__IBAN__c</fullName>
    <description>The IBAN as stated on the payment profile.</description>
    <formula>IF ( NOT ( ISBLANK ( cpm__Custom_IBAN__c ) ) , cpm__Custom_IBAN__c , 
  IF ( cpm__Payment_Profile__r.RecordType.DeveloperName == &apos;IBAN&apos; , cpm__Payment_Profile__r.cpm__IBAN__c , 
    IF ( cpm__Payment_Profile__r.RecordType.DeveloperName == &apos;Credit_Card&apos;,  cpm__Mandate__r.cpm__Reference__c, cpm__Payment_Profile__r.cpm__Bank_Account__c )
  )
)</formula>
    <inlineHelpText>El IBAN como se indica en el Perfil de Pago</inlineHelpText>
    <label>Account Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Payment_Profile__c.field-meta.xml
<CustomField>
    <fullName>cpm__Payment_Profile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The associated Payment Profile for this installment.</description>
    <inlineHelpText>El Perfil de Pago asociado para este installment</inlineHelpText>
    <label>Payment Profile</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5))</booleanFilter>
        <filterItems>
            <field>cpm__Payment_Profile__c.cpm__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>cpm__Payment_Profile__c.cpm__Contact__c</field>
            <operation>equals</operation>
            <valueField>$Source.cpm__Contact__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.cpm__Contact__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>cpm__Payment_Profile__c.cpm__Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.cpm__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.cpm__Account__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <infoMessage>By default only active records are shown.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>cpm__Payment_Profile__c</referenceTo>
    <relationshipLabel>Installments</relationshipLabel>
    <relationshipName>Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>cpm__Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Payment_Schedule__c</description>
    <label>Payment Schedule</label>
    <referenceTo>cpm__Payment_Schedule__c</referenceTo>
    <relationshipName>Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Status__c.field-meta.xml
<CustomField>
    <fullName>cpm__Status__c</fullName>
    <description>The status of this Installment.</description>
    <inlineHelpText>El estado de este installment</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Outstanding</fullName>
                <default>true</default>
                <label>Outstanding</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Pending recollection</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Partially paid</fullName>
            </value>
            <value>
                <fullName>Pending Processing</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/cpm__Payment_Profile__c.object-meta.xml
<CustomObject>
    <description>captures the payment profiles per contact/account.
such as IBAN, legacy bank account, Credit Card etc.</description>
    <label>Payment Profile</label>
    <nameField>
        <displayFormat>PP-{0}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/cpm__Contact__c.field-meta.xml
<CustomField>
    <fullName>cpm__Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The debitor.</description>
    <inlineHelpText>El deudor</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Payment_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/cpm__Holder_Name__c.field-meta.xml
<CustomField>
    <fullName>cpm__Holder_Name__c</fullName>
    <description>Name of the account/credit card holder.</description>
    <inlineHelpText>Nombre del titular de la cuenta / tarjeta de crédito.</inlineHelpText>
    <label>Holder Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/cpm__IBAN__c.field-meta.xml
<CustomField>
    <fullName>cpm__IBAN__c</fullName>
    <description>The bank account number in IBAN format.</description>
    <inlineHelpText>El número de cuenta bancaria en formato IBAN.</inlineHelpText>
    <label>IBAN</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/msf_LastModificationChannel__c.field-meta.xml
<CustomField>
    <fullName>msf_LastModificationChannel__c</fullName>
    <label>Último canal de modificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_ModificationChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Payment_Profile__c/fields/msf_ModificationChannel__c.field-meta.xml
<CustomField>
    <fullName>msf_ModificationChannel__c</fullName>
    <inlineHelpText>Es obligatorio informar este campo cada vez que modifique el registro. Tras guardar los cambios el campo queda vacío para la próxima modificación.</inlineHelpText>
    <label>Canal de modificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_ModificationChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/cpm__Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>Object is used to schedule Payment Runs in the future</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{000000000}</displayFormat>
        <label>Payment Schedule Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>cpm__PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>CreditCard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Selection_Date__c.field-meta.xml
<CustomField>
    <fullName>cpm__Selection_Date__c</fullName>
    <description>Installments with a due date on or before the selection date are collected if all other processing details match.</description>
    <inlineHelpText>La fecha en que se seleccionan los Pagos recurrentes dentro de esta ejecución del proceso de cobros</inlineHelpText>
    <label>Selection Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Status__c.field-meta.xml
<CustomField>
    <fullName>cpm__Status__c</fullName>
    <description>Set status to &apos;Scheduled&apos; unless otherwise instructed.</description>
    <inlineHelpText>El estado actual de este elemento programado</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Generating</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/msf_GDPRLog__c/msf_GDPRLog__c.object-meta.xml
<CustomObject>
    <label>Registro RGPD</label>
    <nameField>
        <displayFormat>RGPD_LOG_{0000000000}</displayFormat>
        <label>Nombre de Registro RGPD</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registros RGPD</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_GDPRLog__c/fields/msf_ModificationChannel__c.field-meta.xml
<CustomField>
    <fullName>msf_ModificationChannel__c</fullName>
    <label>Canal de modificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSF_ModificationChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/msf_EconomicProcessUser__c.field-meta.xml
<CustomField>
    <fullName>msf_EconomicProcessUser__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check only for economic.process@barcelona.msf.org</inlineHelpText>
    <label>Economic process user</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/MSF_ModificationChannel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Teléfonos At. Socio</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Asociativo</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono One-to-One</fullName>
    </customValue>
    <customValue>
        <fullName>Teléfono Telemarketing</fullName>
    </customValue>
    <customValue>
        <fullName>Centro de Preferencias</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud Page</fullName>
    </customValue>
    <customValue>
        <fullName>Correo Postal</fullName>
    </customValue>
    <customValue>
        <fullName>E-mail Asociativo</fullName>
    </customValue>
    <customValue>
        <fullName>E-mails At. Socio</fullName>
    </customValue>
    <customValue>
        <fullName>E-mails One-to-One</fullName>
    </customValue>
    <customValue>
        <fullName>F2F</fullName>
        <label>F2F Tablet</label>
    </customValue>
    <customValue>
        <fullName>Fax</fullName>
    </customValue>
    <customValue>
        <fullName>Fichero Bancario</fullName>
    </customValue>
    <customValue>
        <fullName>Single entry file</fullName>
        <label>Fichero de importación</label>
    </customValue>
    <customValue>
        <fullName>Formularios Web</fullName>
    </customValue>
    <customValue>
        <fullName>Generación Aplicación</fullName>
    </customValue>
    <customValue>
        <fullName>Mensajería Instantánea</fullName>
    </customValue>
    <customValue>
        <fullName>Mi Perfil</fullName>
    </customValue>
    <customValue>
        <fullName>n/a</fullName>
    </customValue>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>Nuevo</label>
    </customValue>
    <customValue>
        <fullName>Presencial</fullName>
    </customValue>
    <customValue>
        <fullName>RRHH</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
        <isActive>false</isActive>
        <label>Email</label>
    </customValue>
    <customValue>
        <fullName>Teléfono SAS</fullName>
        <isActive>false</isActive>
        <label>Teléfono SAS</label>
    </customValue>
    <masterLabel>Canal de modificación</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MSF_PaymentProfile_TDTM.cls
/**
* @author 		Deloitte
* @date 		05-2019
* @group 		Payment Profile
* @description	Trigger Handler that create GDPR logs
*/
global without sharing class MSF_PaymentProfile_TDTM extends npsp.TDTM_Runnable{

    /*******************************************************************************************************
    * @description	Trigger Handler on Payment profile that manage the changes that must be registered by the GDPR rules.
    * @param 		listNew the list of Payment Profiles from trigger new.  
    * @param 		listOld the list of Payment Profiles from trigger old. 
    * @param 		triggerAction which trigger event (BeforeInsert, AfterInsert, etc.). 
    * @param 		objResult the describe for Payment Profiles.
    * @return 		dmlWrapper. 
    ********************************************************************************************************/
    global override npsp.TDTM_Runnable.DmlWrapper run(List<SObject> newlist, List<SObject> oldlist, npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {    
    	
        //Current User
        Boolean bEcoUser = [SELECT Id, msf_EconomicProcessUser__c FROM User WHERE Id =: UserInfo.getUserId()].msf_EconomicProcessUser__c;
        
        //Attributes
        List<cpm__Payment_Profile__c> lNewPP = (List<cpm__Payment_Profile__c>) newlist;      
		List<cpm__Payment_Profile__c> lOldPP = (List<cpm__Payment_Profile__c>) oldlist;
        Map<Id, cpm__Payment_Profile__c> mOldPP = new Map<Id, cpm__Payment_Profile__c>();
        if(lOldPP != null){            
            mOldPP.putAll(lOldPP);
        }    
        
        MSF_SharedMethods_UTIL sm = new MSF_SharedMethods_UTIL();
   		
        List<msf_GDPRLog__c> lLogsToInsert = new List<msf_GDPRLog__c>();
        
        Map<String,Schema.sObjectField> mObjectFields = cpm__Payment_Profile__c.sObjectType.getDescribe().fields.getMap();
        
        Set<String> sfields = new Set<String>{'cpm__Holder_Name__c','cpm__IBAN__c','cpm__Token__c'};

        //Comprobar si se pueden modificar los PP;  
        Boolean canUpdate = true;
        if (triggerAction == npsp.TDTM_Runnable.Action.BeforeUpdate || triggerAction == npsp.TDTM_Runnable.Action.AfterUpdate) {
            canUpdate = checkCanUpdate(lNewPP, mOldPP, bEcoUser);
        }
        if (canUpdate == false) {
            return null;
        }
            
        //Actions
                        
        /*** BEFORE INSERT & BEFORE UPDATE ***/
        if(triggerAction == npsp.TDTM_Runnable.Action.BeforeInsert || triggerAction == npsp.TDTM_Runnable.Action.BeforeUpdate) {	
            for(cpm__Payment_Profile__c pp : lNewPP){       
                if(pp.msf_ModificationChannel__c != null){
                    if(bEcoUser){
                        pp.msf_ModificationChannel__c = 'Fichero Bancario';
                    }
                    pp.msf_LastModificationChannel__c = pp.msf_ModificationChannel__c;
                    pp.msf_ModificationChannel__c = null;    
                }				
            }   
        }    
        
        /*** AFTER INSERT ***/
        if(triggerAction == npsp.TDTM_Runnable.Action.AfterInsert) {	
            for(cpm__Payment_Profile__c pp : lNewPP){            	 
            	msf_GDPRLog__c l = sm.createLog(pp, null, UserInfo.getUserId(), pp.cpm__Contact__c, pp.Id, true, false, sfields, mObjectFields);  
                if (l != null){
                	lLogsToInsert.add(l);     
                }
            }   
        }
        /*** AFTER UPDATE ***/
        if(triggerAction == npsp.TDTM_Runnable.Action.AfterUpdate) {	
        	for(cpm__Payment_Profile__c pp : lNewPP){
            	msf_GDPRLog__c l = sm.createLog(pp, mOldPP.get(pp.Id), UserInfo.getUserId(), pp.cpm__Contact__c, pp.Id, false, false, sfields, mObjectFields);  
                if (l != null){
                	lLogsToInsert.add(l);     
                }
            } 	   
        } 
        /*** AFTER DELETE ***/
        if(triggerAction == npsp.TDTM_Runnable.Action.AfterDelete) {	
        	for(cpm__Payment_Profile__c pp : lOldPP){
            	msf_GDPRLog__c l = sm.createLog(pp, null, UserInfo.getUserId(), pp.cpm__Contact__c, pp.Id, false, true, null, null);  
                if (l != null){
                	lLogsToInsert.add(l);     
                }
            } 
        }
        
        /*** DML OPERATIONS ***/
        if(lLogsToInsert.isEmpty()){
            return null;
        }
        
        npsp.TDTM_Runnable.dmlWrapper dmlWrapper = new npsp.TDTM_Runnable.DmlWrapper();
        dmlWrapper.objectsToInsert.addAll((List<msf_GDPRLog__c>) lLogsToInsert);        
        
        return dmlWrapper; 
    } 
    
    
    private static Boolean checkCanUpdate(List<cpm__Payment_Profile__c> lNewPP, Map<Id, cpm__Payment_Profile__c> mOldPP, Boolean isEconomic) {
        Boolean canUpdate = true; 
        
        Id profileId = UserInfo.getProfileId();
        
        Boolean isAdmin = [SELECT PermissionsModifyAllData FROM Profile WHERE Id =: profileId].PermissionsModifyAllData;
        
        if (isAdmin == false && isEconomic == false) {
            
            List<String> paymentSchedulesStatus = new List<String>{'Done'}; 
            List<cpm__Payment_Schedule__c> paymentSchedulesList = [SELECT Id, cpm__Status__c, cpm__PaymentMethod__c, cpm__Selection_Date__c FROM cpm__Payment_Schedule__c WHERE cpm__Status__c NOT IN :paymentSchedulesStatus]; 

            if (!paymentSchedulesList.isEmpty()){               
                Map<Id, List<cpm__Installment__c>> mInstallmentsByPP = new Map<id, List<cpm__Installment__c>>(); 
                for (cpm__Installment__c inst : [SELECT ID, cpm__Payment_Profile__c, cpm__Due_Date__c, cpm__Payment_Method__c, cpm__Status__c FROM cpm__Installment__c WHERE cpm__Payment_Profile__c IN :mOldPP.keyset()]) {
                    List<cpm__Installment__c> l = mInstallmentsByPP.get(inst.cpm__Payment_Profile__c);
                    if (l == null) {
                        l = new List<cpm__Installment__c>(); 
                    }
                    l.add(inst);
                    mInstallmentsByPP.put(inst.cpm__Payment_Profile__c, l);
                }
                
                for (cpm__Payment_Profile__c pp : lNewPP) {
                    cpm__Payment_Profile__c oldPP = mOldPP.get(pp.Id);
                    if (oldPP == null) { oldPP = pp; }
                    List<cpm__Installment__c> installments = mInstallmentsByPP.get(pp.Id);
                    
                    for (cpm__Installment__c inst : installments) {
                        if (inst != null) {
                            if (inst.cpm__Status__c.equals('New') || inst.cpm__Status__c.equals('Pending recollection')) {  
                                for (cpm__Payment_Schedule__c ps : paymentSchedulesList) {
                                    if (inst.cpm__Due_Date__c <= ps.cpm__Selection_Date__c && inst.cpm__Payment_Method__c == ps.cpm__PaymentMethod__c) {
                                        canUpdate = false; 
                                        pp.addError(System.Label.MSF_PAYMENTPROFILE_BLOCKED);    
                                    }
                                }
                            }
                        }   
                    }
                } 
            }
        }
        
        return canUpdate; 
    }

}