force-app/main/default/objects/cpm__Installment__c/cpm__Installment__c.object-meta.xml
<CustomObject>
    <description>Installments are the result of a Recurring Payment. Installments track the status of a invoice or a direct debit transaction.</description>
    <label>Installment</label>
    <nameField>
        <displayFormat>INST-{00000000}</displayFormat>
        <label>Installment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>cpm__Due_Date__c</fullName>
    <description>The Due date for this installment</description>
    <inlineHelpText>Fecha de vencimiento para este installment</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Last_Failed_Date__c.field-meta.xml
<CustomField>
    <fullName>cpm__Last_Failed_Date__c</fullName>
    <label>Last Failed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Last_ReasonCode_Received__c.field-meta.xml
<CustomField>
    <fullName>cpm__Last_ReasonCode_Received__c</fullName>
    <description>This field is only used in Finance integration</description>
    <inlineHelpText>Contiene el último código de motivo recibido</inlineHelpText>
    <label>Last ReasonCode Received</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Last_Refunded_Date__c.field-meta.xml
<CustomField>
    <fullName>cpm__Last_Refunded_Date__c</fullName>
    <label>Last Refunded Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Last_Rejection_Date__c.field-meta.xml
<CustomField>
    <fullName>cpm__Last_Rejection_Date__c</fullName>
    <label>Last Rejection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Last_Reversal_Date__c.field-meta.xml
<CustomField>
    <fullName>cpm__Last_Reversal_Date__c</fullName>
    <label>Last Reversal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__of_times_reversed__c.field-meta.xml
<CustomField>
    <fullName>cpm__of_times_reversed__c</fullName>
    <description>The number of times this transaction was reversed.</description>
    <inlineHelpText>El número de veces que se devolvio esta transacción.</inlineHelpText>
    <label># of times reversed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>cpm__Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Payment_Schedule__c</description>
    <label>Payment Schedule</label>
    <referenceTo>cpm__Payment_Schedule__c</referenceTo>
    <relationshipName>Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Status__c.field-meta.xml
<CustomField>
    <fullName>cpm__Status__c</fullName>
    <description>The status of this Installment.</description>
    <inlineHelpText>El estado de este installment</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Outstanding</fullName>
                <default>true</default>
                <label>Outstanding</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Pending recollection</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Partially paid</fullName>
            </value>
            <value>
                <fullName>Pending Processing</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/msf_Description__c.field-meta.xml
<CustomField>
    <fullName>msf_Description__c</fullName>
    <label>Descripción</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/msf_GAU__c.field-meta.xml
<CustomField>
    <fullName>msf_GAU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Descripción de destino aportación</label>
    <referenceTo>npsp__General_Accounting_Unit__c</referenceTo>
    <relationshipLabel>Installments</relationshipLabel>
    <relationshipName>Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/npsp4hub__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>npsp4hub__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Installments</relationshipLabel>
    <relationshipName>Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/cpm__Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>Object is used to schedule Payment Runs in the future</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{000000000}</displayFormat>
        <label>Payment Schedule Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Last_Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>cpm__Last_Status_Reason__c</fullName>
    <description>Optional additional information added in Last Status Reason field if the payment schedule fails.</description>
    <label>Last Status Reason</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>cpm__PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>CreditCard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Selection_Date__c.field-meta.xml
<CustomField>
    <fullName>cpm__Selection_Date__c</fullName>
    <description>Installments with a due date on or before the selection date are collected if all other processing details match.</description>
    <inlineHelpText>La fecha en que se seleccionan los Pagos recurrentes dentro de esta ejecución del proceso de cobros</inlineHelpText>
    <label>Selection Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cpm__Payment_Schedule__c/fields/cpm__Status__c.field-meta.xml
<CustomField>
    <fullName>cpm__Status__c</fullName>
    <description>Set status to &apos;Scheduled&apos; unless otherwise instructed.</description>
    <inlineHelpText>El estado actual de este elemento programado</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Generating</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/npe03__Recurring_Donation__c.object-meta.xml
<CustomObject>
    <description>Recurring Donations track charitable giving where a donor specifies an amount of money to be given on a regular basis.</description>
    <label>Recurring Donation</label>
    <nameField>
        <label>Recurring Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Allocation__c/npsp__Allocation__c.object-meta.xml
<CustomObject>
    <label>GAU Allocation</label>
    <nameField>
        <displayFormat>ALL-{0}</displayFormat>
        <label>GAU Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GAU Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npsp__Allocation__c/fields/npsp__Amount__c.field-meta.xml
<CustomField>
    <fullName>npsp__Amount__c</fullName>
    <description>The amount of the Opportunity allocated to this General Accounting Unit. Leave blank for percent-based Allocations.</description>
    <inlineHelpText>Monto de la oportunidad a asignar a esta cuenta contable general. Dejar en blanco para asignaciones basadas en porcentaje.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/npsp__Allocation__c/fields/npsp__General_Accounting_Unit__c.field-meta.xml
<CustomField>
    <fullName>npsp__General_Accounting_Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The General Accounting Unit this Allocation is attributed to. Only General Accounting Units marked as active are available for new Allocations.</description>
    <inlineHelpText>La cuenta contable general a atribuir la asignación. Solo cuentas contables generales activas están disponibles para nuevas asignaciones.</inlineHelpText>
    <label>General Accounting Unit</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <errorMessage>Choose an active General Accounting Unit for this Allocation. You cannot modify an Allocation assigned to an inactive General Accounting Unit.</errorMessage>
        <filterItems>
            <field>npsp__General_Accounting_Unit__c.npsp__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.npsp__Payment__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>$Source.npsp__Payment__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <infoMessage>You must select an active General Accounting Unit for this Allocation.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>npsp__General_Accounting_Unit__c</referenceTo>
    <relationshipLabel>GAU Allocations</relationshipLabel>
    <relationshipName>Allocations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/npsp__Allocation__c/fields/npsp__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>npsp__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Opportunity you want this Allocation attributed to. NPSP rolls up all Opportunities in a Closed/Won stage to this Allocation&apos;s General Accounting Unit.</description>
    <inlineHelpText>Oportunidad relacionada. Todas las oportunidades cerradas ganadas van a ser consideradas para los campos de resumen en el registro de la cuenta contable general.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>GAU Allocations</relationshipLabel>
    <relationshipName>Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/npsp__General_Accounting_Unit__c/npsp__General_Accounting_Unit__c.object-meta.xml
<CustomObject>
    <description>Accounting units used for allocating Opportunities.</description>
    <label>General Accounting Unit</label>
    <nameField>
        <label>General Accounting Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Accounting Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/msf_LastReasonCodeReceived__c.field-meta.xml
<CustomField>
    <fullName>msf_LastReasonCodeReceived__c</fullName>
    <label>Último código de devolución</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_LastReversalDate__c.field-meta.xml
<CustomField>
    <fullName>msf_LastReversalDate__c</fullName>
    <label>Fecha de impago</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_NTimesReversed__c.field-meta.xml
<CustomField>
    <fullName>msf_NTimesReversed__c</fullName>
    <label>Número de Devoluciones</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/msf_EconomicProcessUser__c.field-meta.xml
<CustomField>
    <fullName>msf_EconomicProcessUser__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check only for economic.process@barcelona.msf.org</inlineHelpText>
    <label>Economic process user</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MSF_Installments_TDTM.cls
/**
* @author 		Deloitte
* @date 		05-2019
* @group 		Payment Profile
* @description	Trigger Handler that create GDPR logs
*/
global without sharing class MSF_Installments_TDTM extends npsp.TDTM_Runnable{
    
    global override npsp.TDTM_Runnable.DmlWrapper run(List<SObject> newlist, List<SObject> oldlist, npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {    
        
        List<cpm__Installment__c> lNewInstallments = (List<cpm__Installment__c>) newlist;      
        List<cpm__Installment__c> lOldInstallments = (List<cpm__Installment__c>) oldlist;
        Map<Id, cpm__Installment__c> mOldInstallments = new Map<Id, cpm__Installment__c>();
        if(lOldInstallments != null){            
            mOldInstallments.putAll(lOldInstallments);
        }   
        List<Opportunity> lOppsToUpdate = new List<Opportunity>();
        List<npsp__Allocation__c> gauAllocationsToInsert = new List<npsp__Allocation__c>(); 
        
        //Comprobar si se pueden modificar los installments;  
        Boolean canUpdate = true;
        if (triggerAction == npsp.TDTM_Runnable.Action.BeforeUpdate || triggerAction == npsp.TDTM_Runnable.Action.BeforeInsert) {
            canUpdate = checkCanUpdate(lNewInstallments, mOldInstallments);
        }
        if (canUpdate == false) {
            return null;
        }
        
        List<Id> instOppsIds = new List<Id>();
        for (cpm__Installment__c installment : lNewInstallments) {
            if (installment.npsp4hub__Opportunity__c != null) {
                instOppsIds.add(installment.npsp4hub__Opportunity__c);
            }
        }
        
        Map<Id, Opportunity> mOpps = new Map<Id, Opportunity>();
        mOpps.putAll([SELECT Id, Amount, npe03__Recurring_Donation__c, StageName, isClosed, msf_LastReasonCodeReceived__c, msf_LastReversalDate__c, msf_NTimesReversed__c 
                      FROM Opportunity WHERE Id IN :instOppsIds]);   
        
        
        /*** BEFORE UPDATE ***/
        if(triggerAction == npsp.TDTM_Runnable.Action.BeforeUpdate || triggerAction == npsp.TDTM_Runnable.Action.BeforeInsert) {
            for (cpm__Installment__c installment : lNewInstallments) {         
                cpm__Installment__c oldInst = mOldInstallments.get(installment.id);
                Opportunity opp = mOpps.get(installment.npsp4hub__Opportunity__c);
                Boolean updateInstallment = false; 
                if (opp != null) {
                    Double nTimesReversed = 0; 
                    if (installment.cpm__Payment_Method__c == 'CreditCard'){
                        nTimesReversed = getNtimesReversed(installment);
                    }
                    else{
                        nTimesReversed = installment.cpm__of_times_rejected__c;
                    }
                    
                    if (opp.npe03__Recurring_Donation__c != null) {
                        if (nTimesReversed < 3) {
                            updateInstallment = true; 
                        }
                    }
                    else {
                        if (nTimesReversed < 2) {
                            updateInstallment = true;  
                        }
                    }
                    
                    if (installment.cpm__Payment_Method__c == 'CreditCard' && opp.IsClosed == false && updateInstallment == true) {
                        if (oldInst!=null &&
                            (  oldInst.cpm__of_times_failed__c   != installment.cpm__of_times_failed__c
                            || oldInst.cpm__of_times_refunded__c != installment.cpm__of_times_refunded__c
                            || oldInst.cpm__of_times_reversed__c != installment.cpm__of_times_reversed__c)) {
                                installment.cpm__Status__c = 'New';
                            }
                    }
                    
                    if (installment.cpm__Payment_Method__c == 'Direct Debit' && installment.cpm__Last_ReasonCode_Received__c != null && updateInstallment == true) {
                        if (installment.cpm__Last_ReasonCode_Received__c == 'AM04' && installment.cpm__Status__c == 'Rejected') {
                            installment.cpm__Status__c = 'Pending recollection'; 
                        }
                    } 
                }  
            }
        }
        
        
        //AFTER INSERT && AFTER UPDATE; 
        if(triggerAction == npsp.TDTM_Runnable.Action.AfterUpdate || triggerAction == npsp.TDTM_Runnable.Action.AfterInsert) {
            
            List<npsp__Allocation__c> allocations = [SELECT Id, npsp__Opportunity__c FROM npsp__Allocation__c
                                                           WHERE npsp__Opportunity__c IN :mOpps.keyset()];
            Map<Id, npsp__Allocation__c> allocationsByOpp = new Map<Id, npsp__Allocation__c>(); 
            for (npsp__Allocation__c allocation : allocations) {
                Id oppId = allocation.npsp__Opportunity__c;
                allocationsByOpp.put(oppId , allocation);
            }
                       
            for (cpm__Installment__c installment : lNewInstallments) {
                cpm__Installment__c oldInst = mOldInstallments.get(installment.id);
                Opportunity opp = mOpps.get(installment.npsp4hub__Opportunity__c);
                Boolean updateOpp = false;               
                
                 
                if (opp != null) {     
                    if (installment.msf_LeadSource__c != null) {
                        opp.LeadSource = installment.msf_LeadSource__c; 
                        updateOpp = true; 
                    }
                    
                    if (installment.msf_Description__c != null) {
                        opp.Description = installment.msf_Description__c; 
                        updateOpp = true; 
                    }
                    
                    if (installment.msf_GAU__c != null && allocationsByOpp.get(opp.Id) == null) {
                        Id gau = installment.msf_GAU__c; 
                        npsp__Allocation__c gauAll = new npsp__Allocation__c();
                        gauAll.npsp__Amount__c = opp.Amount;
                        gauAll.npsp__General_Accounting_Unit__c = gau;
                        gauAll.npsp__Opportunity__c = opp.Id;
                        gauAllocationsToInsert.add(gauAll);
                    }
                    
                    if (oldInst != null) {
                        
                        Date t = getMaxLastReversalDate(installment);
                        if (t != opp.msf_LastReversalDate__c) {
                            opp.msf_LastReversalDate__c = t; 
                            updateOpp = true; 
                        }
                        
                        if (installment.cpm__Payment_Method__c == 'CreditCard') {
                            if (opp.IsClosed == false) {
                                if (  oldInst.cpm__of_times_failed__c   != installment.cpm__of_times_failed__c
                                    || oldInst.cpm__of_times_refunded__c != installment.cpm__of_times_refunded__c
                                    || oldInst.cpm__of_times_reversed__c != installment.cpm__of_times_reversed__c) {
                                        opp.StageName = 'Devuelta'; 
                                    }
                            }
                            opp.msf_LastReasonCodeReceived__c = installment.cpm__Last_Status_Reason__c;
                            opp.msf_NTimesReversed__c = getNTimesReversed(installment);
                            updateOpp = true; 
                        }
                        else {
                            
                            if (oldInst.cpm__of_times_rejected__c != installment.cpm__of_times_rejected__c || opp.msf_NTimesReversed__c!=installment.cpm__of_times_rejected__c) {
                                opp.msf_LastReasonCodeReceived__c = installment.cpm__Last_ReasonCode_Received__c;
                                opp.msf_NTimesReversed__c = installment.cpm__of_times_rejected__c;
                                updateOpp = true;  
                            }
                            
                            if (installment.cpm__Last_ReasonCode_Received__c != null) {
                                if (installment.cpm__Last_ReasonCode_Received__c != 'AM04' && 
                                    (installment.cpm__Status__c != 'New' && installment.cpm__Status__c != 'Pending recollection' && installment.cpm__Status__c != 'Collected')) {
                                        opp.StageName = 'Impagada'; 
                                        updateOpp = true; 
                                    }
                            }
                            
                        }                        
                    }
                    //System.debug('old'+oldInst.cpm__of_times_rejected__c);
                    //System.debug('new'+installment.cpm__of_times_rejected__c);
                    if (opp.npe03__Recurring_Donation__c != null) {
                        if ((oldInst == null || oldInst.cpm__of_times_rejected__c != installment.cpm__of_times_rejected__c 
                                    ||   oldInst.cpm__of_times_failed__c   != installment.cpm__of_times_failed__c
                                    || oldInst.cpm__of_times_refunded__c != installment.cpm__of_times_refunded__c
                                    || oldInst.cpm__of_times_reversed__c != installment.cpm__of_times_reversed__c) &&
                            opp.msf_NTimesReversed__c >= 3 && installment.cpm__Status__c != 'Collected') {
                            opp.StageName = 'Impagada'; 
                            updateOpp = true;
                        }
                    }
                    else {
                        if ((oldInst == null || oldInst.cpm__of_times_rejected__c != installment.cpm__of_times_rejected__c
                                    ||   oldInst.cpm__of_times_failed__c   != installment.cpm__of_times_failed__c
                                    || oldInst.cpm__of_times_refunded__c != installment.cpm__of_times_refunded__c
                                    || oldInst.cpm__of_times_reversed__c != installment.cpm__of_times_reversed__c) &&
                            opp.msf_NTimesReversed__c >= 2 && installment.cpm__Status__c != 'Collected') {
                            opp.StageName = 'Impagada';
                            updateOpp = true;
                        }
                    }
                    
                    
                    if (updateOpp == true && opp != null) {
                        lOppsToUpdate.add(opp);
                    }
                    
                }
            }
        }   
        
        npsp.TDTM_Runnable.dmlWrapper dmlWrapper = new npsp.TDTM_Runnable.DmlWrapper();
        
        if (lOppsToUpdate.isEmpty() == false) {
            dmlWrapper.objectsToUpdate.addAll((List<Opportunity>) lOppsToUpdate);
        }
        if (gauAllocationsToInsert.isEmpty() == false) {
            dmlWrapper.objectsToInsert.addAll((List<npsp__Allocation__c>) gauAllocationsToInsert);
        }
        
        return dmlWrapper;
        
        //return null; 
    }
    
    
    private static Boolean checkCanUpdate(List<cpm__Installment__c> lNewInstallments, Map<Id, cpm__Installment__c> mOldInstallments) {
        Boolean canUpdate = true; 
        
        Id profileId = UserInfo.getProfileId();
        
        Boolean isAdmin = [SELECT PermissionsModifyAllData FROM Profile WHERE Id =: profileId].PermissionsModifyAllData;
        Boolean bEcoUser = [SELECT Id, msf_EconomicProcessUser__c FROM User WHERE Id =: UserInfo.getUserId()].msf_EconomicProcessUser__c;
        
        if (isAdmin == false && bEcoUser == false) {
            
            //PaymentSchedules;
            List<String> paymentSchedulesStatus = new List<String>{'Done'}; 
                List<cpm__Payment_Schedule__c> paymentSchedulesList = [SELECT Id, cpm__Status__c, cpm__PaymentMethod__c, cpm__Selection_Date__c FROM cpm__Payment_Schedule__c WHERE cpm__Status__c NOT IN :paymentSchedulesStatus]; 
            
            if (paymentSchedulesList.isEmpty() == false) {
                for (cpm__Installment__c installment : lNewInstallments) {
                    cpm__Installment__c oldInstallment = mOldInstallments.get(installment.id);
                    if (oldInstallment == null) { oldInstallment = installment; }
                    
                    if (oldInstallment.cpm__Status__c.equals('New') || oldInstallment.cpm__Status__c.equals('Pending recollection') ||
                        installment.cpm__Status__c.equals('New')    || installment.cpm__Status__c.equals('Pending recollection')) {  
                        for (cpm__Payment_Schedule__c ps : paymentSchedulesList) {
                            if ((oldInstallment.cpm__Due_Date__c <= ps.cpm__Selection_Date__c && oldInstallment.cpm__Payment_Method__c == ps.cpm__PaymentMethod__c) ||
                                (installment.cpm__Due_Date__c <= ps.cpm__Selection_Date__c && installment.cpm__Payment_Method__c == ps.cpm__PaymentMethod__c)) {
                                canUpdate = false; 
                                installment.addError(System.Label.MSF_INSTALLMENT_BLOCKED);    
                            }
                        }
                    }
                }
            }
        }
        
        return canUpdate; 
    }
    
    
    
    private static double getNtimesReversed(cpm__Installment__c installment) {
        Double ret = 0; 
        List<Double> toSum = new List<Double>();
        toSum.add(installment.cpm__of_times_failed__c);
        toSum.add(installment.cpm__of_times_refunded__c);
        toSum.add(installment.cpm__of_times_reversed__c);
        
        for (Double n : toSum) {
            if (n != null) {
                ret += n; 
            }
        }
        
        return ret; 
    } 
    
    private static Date getMaxLastReversalDate(cpm__Installment__c installment) {
        Date ret = null; 
        List<Date> dates = new List<Date>(); 
        dates.add(installment.cpm__Last_Failed_Date__c);
        dates.add(installment.cpm__Last_Refunded_Date__c);
        dates.add(installment.cpm__Last_Reversal_Date__c);
        dates.add(installment.cpm__Last_Rejection_Date__c);
        
        dates.sort();
        ret = dates[dates.size() - 1];
        
        return ret; 
    }
    
}