force-app/main/default/objects/msf_QuotaModification__c/msf_QuotaModification__c.object-meta.xml
<CustomObject>
    <label>Modificación de cuota</label>
    <nameField>
        <label>Nombre de Modificación de cuota</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modificaciones de cuota</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/msf_QuotaModification__c/fields/msf_NewAmount__c.field-meta.xml
<CustomField>
    <fullName>msf_NewAmount__c</fullName>
    <label>Nuevo importe</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/msf_QuotaModification__c/fields/msf_NewRecurringPeriod__c.field-meta.xml
<CustomField>
    <fullName>msf_NewRecurringPeriod__c</fullName>
    <label>Nueva frecuencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Bimensual</fullName>
            </value>
            <value>
                <fullName>Semestral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_CurrentQuotaModification__c.field-meta.xml
<CustomField>
    <fullName>msf_CurrentQuotaModification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modificación de cuota actual</label>
    <referenceTo>msf_QuotaModification__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_OldQuotaModification__c.field-meta.xml
<CustomField>
    <fullName>msf_OldQuotaModification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modificación de cuota antiguo</label>
    <referenceTo>msf_QuotaModification__c</referenceTo>
    <relationshipLabel>Opportunities (Modificación de cuota antiguo)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/msf_RecurringPeriod__c.field-meta.xml
<CustomField>
    <fullName>msf_RecurringPeriod__c</fullName>
    <label>Periodicidad donación recurrente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Bimensual</fullName>
            </value>
            <value>
                <fullName>Semestral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Donation.recordType-meta.xml
<RecordType>
    <fullName>Donation</fullName>
    <active>true</active>
    <businessProcess>Donation</businessProcess>
    <description>Donation Received</description>
    <label>Donation</label>
</RecordType>

force-app/main/default/classes/MSF_OpportunityTriggerHelper.cls
/**
 * @description       :
 * @author            : avargas@omegacrmconsulting.com
 * @group             :
 * @last modified on  : 26-10-2021
 * @last modified by  : avargas@omegacrmconsulting.com
 * Modifications Log
 * Ver   Date         Author                            Modification
 * 1.0   26-10-2021   avargas@omegacrmconsulting.com   Initial Version
 **/
public without sharing class MSF_OpportunityTriggerHelper {
    public static void saveOldQuota(List<Opportunity> oldOpp, List<Opportunity> newOpp, Map<Id, Opportunity> oldMapOpp, map<Id, Opportunity> newMapOpp){
        List<Opportunity> oppToUpdate = New List<Opportunity>();
        List<Id> quotaIdToSearch = New List<Id>();
        

        for(Integer i = 0; i < newOpp.size(); i++){
            Id RTIDDonation = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Donation').getRecordTypeId();
            if(newOpp[i].RecordTypeId == RTIDDonation && newOpp[i].StageName == 'Devuelta'){
                if(newOpp[i].msf_CurrentQuotaModification__c != oldOpp[i].msf_CurrentQuotaModification__c && newOpp[i].msf_CurrentQuotaModification__c != null){
                    newOpp[i].msf_OldQuotaModification__c = oldOpp[i].msf_CurrentQuotaModification__c;
                    System.debug('Guardado de Quota');

                    System.debug('Cambio de Current to Old');
                    newOpp[i].msf_CurrentQuotaModification__c = newOpp[i].msf_OldQuotaModification__c;
                    oppToUpdate.add(newOpp[i]);
                    quotaIdToSearch.add(newOpp[i].msf_OldQuotaModification__c);
                    
                }

                System.debug('Amount: ' + newOpp[i].Amount + ' Viejo: ' + oldOpp[i].Amount);
                if( ((newOpp[i].Amount != oldOpp[i].Amount && newOpp[i].Amount != null) || (newOpp[i].msf_RecurringPeriod__c != oldOpp[i].msf_RecurringPeriod__c) ) && newOpp[i].msf_OldQuotaModification__c != null){
                    System.debug('Cambio de Current to Old');
                    newOpp[i].msf_CurrentQuotaModification__c = newOpp[i].msf_OldQuotaModification__c;
                    
                    
                    oppToUpdate.add(newOpp[i]);
                    quotaIdToSearch.add(newOpp[i].msf_OldQuotaModification__c);

                }

            }
        }

        Map<Id, msf_QuotaModification__c> quotaToSearch = new Map<Id, msf_QuotaModification__c>([select Id,  msf_NewAmount__c, msf_NewRecurringPeriod__c
                                                                                                from msf_QuotaModification__c
                                                                                                where Id in :quotaIdToSearch]);

        for(Opportunity opp: oppToUpdate){
            System.debug('Remodificación de Amount. Nuevo Amount: ' + quotaToSearch.get(opp.msf_OldQuotaModification__c).msf_NewAmount__c );
            newMapOpp.get(opp.Id).Amount                 = quotaToSearch.get(opp.msf_OldQuotaModification__c).msf_NewAmount__c;
            newMapOpp.get(opp.Id).msf_RecurringPeriod__c = quotaToSearch.get(opp.msf_OldQuotaModification__c).msf_NewRecurringPeriod__c;
        }
        
    }
}